let state=loadState();const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setView(v){location.hash=v;render()}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');$('#modalBody').querySelector('input,select,textarea,button')?.focus()}
function closeModal(){ $('#modal').classList.add('hidden') }

function metaLine(item){return `<span class="meta">作成：${esc(item.createdAt||'未記録')} / 更新：${esc(item.updatedAt||'未記録')} / 状態：${esc(item.status||'仮設定')}</span>`}
function tagText(item){return (item.tags||[]).join(', ')}
function tagInputValue(item){return (item.tags||[]).join(',')}
function parseTags(value){return String(value||'').split(',').map(x=>x.trim()).filter((x,i,a)=>x&&a.indexOf(x)===i)}
function touch(item){if(!item.createdAt)item.createdAt=now();item.updatedAt=now();return item}
function typeLabel(type){return TYPE_LABELS[type]||type||'項目'}
function itemTagsHtml(item){return (item.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')||'<span class="meta">タグなし</span>'}
const TYPE_LABELS={project:'作品',episode:'話数',character:'キャラクター',world:'世界観',term:'用語',image:'画像',video:'動画',idea:'アイデア',scene:'シーン',timeline:'年表',history:'変更履歴',app:'アプリ'};
function continueTitle(collection,item){if(collection==='apps')return item.name||item.title||'';if(collection==='episodes')return `${item.numberLabel||item.title||''} ${item.subtitle||''}`.trim();return item.title||item.name||item.numberLabel||item.id||''}
function continueItems(){return [...COMMON_COLLECTIONS,'apps'].flatMap(collection=>(state[collection]||[]).filter(item=>item&&!item.isArchived).map(item=>({collection,item,type:item.type||COLLECTION_TYPE_MAP[collection],title:continueTitle(collection,item),updatedAt:item.updatedAt||''}))).filter(x=>x.updatedAt).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,state.settings.recentLimit||10)}
function openContinue(collection,id){const item=(state[collection]||[]).find(x=>x.id===id);if(!item)return;if(collection==='projects'){selectContext(id,'');setView('projects')}else if(collection==='episodes'){selectContext(item.projectId,id);setView('episodes')}else if(collection==='apps')openApp(id);else{if(item.projectId)selectContext(item.projectId,item.episodeId||'');setView('search')}}
function addRecentItem(type,item){if(!state.settings.saveHistory)return;const p=type==='project'?item:state.projects.find(x=>x.id===item.projectId);const key=[type,item.id].join('|');let r=state.recentItems.find(x=>x.key===key);if(!r){r={id:uid('recent'),key,type,targetId:item.id,projectId:p?.id||'',episodeId:type==='episode'?item.id:'',appId:'',title:'',url:'',openedAt:''};state.recentItems.unshift(r)}Object.assign(r,{title:type==='project'?item.title:`${item.numberLabel} ${item.subtitle||''}`.trim(),projectName:p?.title||'',episodeLabel:type==='episode'?item.numberLabel:'作品',updatedAt:item.updatedAt||now(),openedAt:item.updatedAt||now()});state.recentItems.sort((a,b)=>(b.updatedAt||b.openedAt||'').localeCompare(a.updatedAt||a.openedAt||''));state.recentItems=state.recentItems.slice(0,50)}
$('#modalClose').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function shell(main){const p=currentProject(),e=currentEpisode();$('#app').innerHTML=`<header><button class="brand" onclick="setView('home')"><b>Nova Studio</b><small>創る、繋がる、育っていく。</small></button><button onclick="showContext()">作品：${esc(p?.title)}</button><button onclick="showContext()">話数：${esc(e?.numberLabel)}</button><input id="globalSearch" aria-label="全体検索" placeholder="全体検索" oninput="searchAll(this.value)"><button onclick="setView('consult')">💬 ノヴァに相談</button><button onclick="setView('backup')">💾 バックアップ</button><button onclick="setView('settings')">⚙ 設定</button><span id="saveStatus">保存しました</span></header><div class="layout"><nav><button onclick="setView('home')">🏠 ホーム</button><button onclick="setView('apps')">🧰 アプリ</button><button onclick="setView('cards')">🗂 カード</button><details open><summary>制作</summary><button onclick="setView('projects')">📚 作品</button><button onclick="setView('episodes')">🎬 話数</button><button onclick="setView('scenes')">🎞 シーン</button></details><details open><summary>設定</summary><button onclick="setView('characters')">👤 キャラクター</button><button onclick="setView('worlds')">🌍 世界観</button><button onclick="setView('terms')">📖 用語</button><button onclick="setView('timelines')">🕰 年表</button></details><details open><summary>管理</summary><button onclick="setView('ideas')">💡 アイデア</button><button onclick="setView('search')">🔎 検索</button><button onclick="setView('history')">📝 変更履歴</button></details><button onclick="setView('consult')">💬 ノヴァ</button></nav><main>${main}</main><aside>${side()}</aside></div><div class="bottom"><button onclick="setView('home')">ホーム</button><button onclick="setView('apps')">アプリ</button><button onclick="setView('cards')">カード</button><button onclick="setView('search')">検索</button><button onclick="setView('consult')">ノヴァ</button></div><div id="toast"></div>`}
function side(){const p=currentProject(),e=currentEpisode();return `<section class="card"><h3>現在の制作</h3><p>${esc(p?.title)}<br>${esc(e?.numberLabel)}<br>状態：${esc(p?.productionStatus)}</p>${['storyArchive','productionDashboard','promptStudio','musicStudio'].map(id=>`<button onclick="openApp('${id}')">${esc(state.apps.find(a=>a.id===id)?.subtitle)}を開く</button>`).join('')}</section><section class="card"><h3>バックアップ状況</h3><p>最後の書き出し：${esc(state.backupStatus.lastExportedAt)||'なし'}<br>最後の読み込み：${esc(state.backupStatus.lastImportedAt)||'なし'}<br>保存データ件数：${state.projects.length+state.episodes.length+state.apps.length}</p></section>`}
function render(){const v=(location.hash||'#home').slice(1); if(v==='apps')return shell(appsView()); if(v==='cards')return shell(cardsView()); if(v==='projects')return shell(projectsView()); if(v==='episodes')return shell(episodesView()); if(v==='scenes')return shell(storyCollectionView('scenes')); if(v==='characters')return shell(storyCollectionView('characters')); if(v==='worlds')return shell(storyCollectionView('worlds')); if(v==='terms')return shell(storyCollectionView('terms')); if(v==='timelines')return shell(storyCollectionView('timelines')); if(v==='ideas')return shell(storyCollectionView('ideas')); if(v==='history')return shell(historyView()); if(v==='settings')return shell(settingsView()); if(v==='backup')return shell(backupView()); if(v==='consult')return shell(consultView()); if(v==='search')return shell(searchView()); shell(homeView())}
function homeView(){const p=currentProject(),e=currentEpisode(),recent=continueItems(),fav=state.favorites.slice(0,state.settings.favoriteLimit||10);return `<section class="hero"><h1>Nova Studio</h1><p>創る、繋がる、育っていく。</p><h2>ようこそ、物語の記憶へ。</h2><p>現在：${esc(p?.title)} / ${esc(e?.numberLabel)} <span class="ver">Version ${NOVA_VERSION}</span></p></section><section><h2>続きから</h2>${recent.length?recent.map(r=>`<div class="row"><span>${esc(r.title)} / ${esc(TYPE_LABELS[r.type]||r.type)} / 更新：${esc(r.updatedAt)}</span><button onclick="openContinue('${r.collection}','${r.item.id}')">開く/選択</button></div>`).join(''):'<p>まだ更新された項目はありません</p>'}</section><section><h2>カードシステム</h2><p>作品・話数・キャラクター・世界観・用語・アイデアを統一カードで管理できます。</p><button onclick="setView('cards')">カード一覧を開く</button></section><section><h2>お気に入り</h2>${fav.length?fav.map(f=>`<div class="row"><span>★ ${esc(f.title)} <small>${esc(f.createdAt||'')}</small></span><button onclick="openFavorite('${f.id}')">開く/選択</button><button onclick="toggleFavorite('${f.type}','${f.targetId}','${f.projectId}','${f.episodeId}')">解除</button></div>`).join(''):'<p>お気に入りはまだありません。</p>'}</section><h2>制作アプリ</h2><div class="grid">${appCards()}</div><section class="card"><h2>今後追加予定</h2><p>Asset Library、Voice Studio、Planner、全体検索、Nova Core</p></section>`}
function appCards(){return state.apps.sort((a,b)=>a.sortOrder-b.sortOrder).map(a=>`<article class="card"><h3>${esc(a.name)}</h3><p class="sub">${esc(a.subtitle)}</p><p>${esc(a.description)}</p><p><b>状態：</b>${a.available?'利用可能':'今後追加予定'} / <b>URL：</b>${a.url?esc(a.url):'未登録'}<br><b>最終閲覧：</b>${esc(a.lastOpenedAt)||'なし'}<br><b>お気に入り：</b>${isFav('app',a.id)?'登録済み':'未登録'}</p><button ${!a.available?'disabled':''} onclick="openApp('${a.id}')">開く</button><button onclick="editApp('${a.id}')">設定</button><button class="favorite ${isFav('app',a.id)?'active':''}" onclick="toggleFavorite('app','${a.id}','','')">${isFav('app',a.id)?'★ 解除':'☆ お気に入り'}</button></article>`).join('')}
function appsView(){return `<h1>制作アプリ</h1><div class="grid">${appCards()}</div>`}

const CARD_COLLECTIONS=['projects','episodes','scenes','characters','worlds','terms','timelines','ideas'];
function cardCollectionsOptions(){return CARD_COLLECTIONS.map(k=>`<option value="${k}">${esc(typeLabel(COLLECTION_TYPE_MAP[k]))}</option>`).join('')}
function allCards(){return CARD_COLLECTIONS.flatMap(collection=>(state[collection]||[]).map(item=>({collection,item,type:item.type||COLLECTION_TYPE_MAP[collection],title:continueTitle(collection,item)}))).sort((a,b)=>(b.item.updatedAt||'').localeCompare(a.item.updatedAt||''))}
function cardStatus(item){return item.productionStatus||item.status||'仮設定'}
function cardHtml(collection,item){const type=item.type||COLLECTION_TYPE_MAP[collection],title=continueTitle(collection,item)||'無題';return `<article class="unified-card ${item.isArchived?'archived':''}" role="button" tabindex="0" onclick="openCardDetail('${collection}','${item.id}')" onkeydown="if(event.key==='Enter'||event.key===' ')openCardDetail('${collection}','${item.id}')"><div class="card-top"><span class="type-pill">${esc(typeLabel(type))}</span><button class="favorite mini ${isFav(type,item.id)?'active':''}" onclick="event.stopPropagation();toggleFavorite('${type}','${item.id}','${item.projectId||item.id||''}','${collection==='episodes'?item.id:(item.episodeId||'')}')" aria-label="お気に入り切替">${isFav(type,item.id)?'★':'☆'}</button></div><h3>${esc(title)}</h3><p class="card-status">状態：${esc(cardStatus(item))}</p><div class="tags">${itemTagsHtml(item)}</div><p class="meta">更新：${esc(item.updatedAt||'未記録')}</p></article>`}
function cardsView(){const cards=allCards();return `<h1>カードシステム</h1><p class="meta">作品・話数・キャラクター・世界観・用語・アイデアを同じ形式で表示します。カードをクリックすると詳細を開きます。</p><div class="card-toolbar"><label>追加する種類<select id="newCardCollection">${cardCollectionsOptions()}</select></label><button onclick="editGenericCard($('#newCardCollection').value)">＋カード追加</button></div><div class="unified-grid">${cards.map(({collection,item})=>cardHtml(collection,item)).join('')||'<p>カードはまだありません。</p>'}</div>`}
function openCardDetail(collection,id){const item=(state[collection]||[]).find(x=>x.id===id);if(!item)return;const type=item.type||COLLECTION_TYPE_MAP[collection],title=continueTitle(collection,item)||'無題';modal(`<h2>${esc(title)}</h2><p><span class="type-pill">${esc(typeLabel(type))}</span> <b>状態：</b>${esc(cardStatus(item))} <b>お気に入り：</b>${isFav(type,item.id)?'★':'☆'}</p><p><b>タグ：</b>${itemTagsHtml(item)}</p><p class="meta">作成：${esc(item.createdAt||'未記録')} / 更新：${esc(item.updatedAt||'未記録')}</p><p>${esc(item.summary||item.description||item.memo||'詳細メモは未入力です。')}</p><button onclick="openCardTarget('${collection}','${item.id}')">関連画面を開く</button><button onclick="editGenericCard('${collection}','${item.id}')">編集</button><button class="favorite ${isFav(type,item.id)?'active':''}" onclick="toggleFavorite('${type}','${item.id}','${item.projectId||item.id||''}','${collection==='episodes'?item.id:(item.episodeId||'')}')">${isFav(type,item.id)?'★ 解除':'☆ お気に入り'}</button>`) }
function openCardTarget(collection,id){closeModal();const item=(state[collection]||[]).find(x=>x.id===id);if(collection==='projects'){selectContext(id,'');setView('projects')}else if(collection==='episodes'){selectContext(item.projectId,id);setView('episodes')}else{if(item?.projectId)selectContext(item.projectId,item.episodeId||'');setView('cards')}}
function editGenericCard(collection,id=''){if(collection==='projects')return editProject(id);if(collection==='episodes')return editEpisode(id);const type=COLLECTION_TYPE_MAP[collection],item=id?state[collection].find(x=>x.id===id):normalizeCommonItem({id:uid(type),projectId:currentProject()?.id||'',episodeId:currentEpisode()?.id||'',title:'新しい'+typeLabel(type)},type);modal(`<h2>${esc(typeLabel(type))}${id?'編集':'追加'}</h2><label>タイトル<input id="g_title" value="${esc(item.title||'')}"></label><label>状態<select id="g_status">${ITEM_STATUSES.map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>タグ（カンマ区切り）<input id="g_tags" value="${esc(tagInputValue(item))}"></label><label>メモ<textarea id="g_memo" rows="7">${esc(item.memo||item.summary||item.description||'')}</textarea></label><p class="meta">作成日時：${esc(item.createdAt||'自動保存')} / 更新日時：${esc(item.updatedAt||'自動更新')}</p><button onclick="saveGenericCard('${collection}','${id}')">保存</button>`) }
function saveGenericCard(collection,id=''){const type=COLLECTION_TYPE_MAP[collection];let item=id?state[collection].find(x=>x.id===id):normalizeCommonItem({id:uid(type),projectId:currentProject()?.id||'',episodeId:currentEpisode()?.id||''},type);item.title=$('#g_title').value;item.status=$('#g_status').value;item.tags=parseTags($('#g_tags').value);item.memo=$('#g_memo').value;touch(item);if(!id)state[collection].push(item);saveState();closeModal();render()}

function projectsView(){return `<h1>作品管理</h1><button onclick="editProject()">＋作品追加</button><div>${state.projects.sort((a,b)=>a.sortOrder-b.sortOrder).map(p=>`<div class="card ${p.isArchived?'archived':''}"><h3>${esc(p.title)}</h3><p>ID:${p.id}<br>${esc(p.summary)}<br>制作状態:${esc(p.productionStatus)} / 状態:${esc(p.status||'仮設定')}<br>タグ:${itemTagsHtml(p)}<br>${metaLine(p)}</p><button onclick="selectContext('${p.id}','')">選択</button><button onclick="openProjectDetail('${p.id}')">詳細</button><button onclick="editProject('${p.id}')">編集</button><button onclick="duplicateProject('${p.id}')">複製</button><button onclick="archiveProject('${p.id}')">${p.isArchived?'復元':'アーカイブ'}</button><button onclick="moveProject('${p.id}',-1)">↑</button><button onclick="moveProject('${p.id}',1)">↓</button><button class="danger" onclick="archiveProject('${p.id}')">削除</button><button class="favorite ${isFav('project',p.id)?'active':''}" onclick="toggleFavorite('project','${p.id}','${p.id}','')">${isFav('project',p.id)?'★':'☆'}</button></div>`).join('')}</div>`}
function episodesView(){const p=currentProject();return `<h1>エピソード管理：${esc(p?.title)}</h1><button onclick="editEpisode()">＋話数追加</button>${state.episodes.filter(e=>e.projectId===p?.id).sort((a,b)=>a.sortOrder-b.sortOrder).map(e=>`<div class="card ${e.isArchived?'archived':''}"><h3>${esc(e.numberLabel)} ${esc(e.subtitle)}</h3><p>ID:${e.id}<br>${esc(e.summary)}<br>制作状態:${esc(e.productionStatus)} / 状態:${esc(e.status||'仮設定')}<br>タグ:${itemTagsHtml(e)}<br>${metaLine(e)}</p><button onclick="selectContext('${p.id}','${e.id}')">選択</button><button onclick="editEpisode('${e.id}')">編集</button><button onclick="duplicateEpisode('${e.id}')">複製</button><button onclick="archiveEpisode('${e.id}')">${e.isArchived?'復元':'アーカイブ'}</button><button onclick="moveEpisode('${e.id}',-1)">↑</button><button onclick="moveEpisode('${e.id}',1)">↓</button><button class="danger" onclick="archiveEpisode('${e.id}')">削除</button><button class="favorite ${isFav('episode',e.id)?'active':''}" onclick="toggleFavorite('episode','${e.id}','${p.id}','${e.id}')">${isFav('episode',e.id)?'★':'☆'}</button></div>`).join('')}`}
function settingsView(){return `<h1>設定</h1><h2>表示・動作</h2><label>最近件数<input type="number" value="${state.settings.recentLimit}" onchange="state.settings.recentLimit=+this.value;saveState()"></label><label>お気に入り件数<input type="number" value="${state.settings.favoriteLimit}" onchange="state.settings.favoriteLimit=+this.value;saveState()"></label><label><input type="checkbox" ${state.settings.defaultOpenInNewTab?'checked':''} onchange="state.settings.defaultOpenInNewTab=this.checked;saveState()">新しいタブで開く</label><label><input type="checkbox" ${state.settings.confirmBeforeOpen?'checked':''} onchange="state.settings.confirmBeforeOpen=this.checked;saveState()">開く前に確認</label><label><input type="checkbox" ${state.settings.saveHistory?'checked':''} onchange="state.settings.saveHistory=this.checked;saveState()">履歴を保存</label><label><input type="checkbox" ${state.settings.autoSave?'checked':''} onchange="state.settings.autoSave=this.checked;saveState(true)">自動保存</label><h2>アプリURL</h2><div class="grid">${appCards()}</div><h2>バックアップ</h2>${backupView()}<button class="danger" onclick="resetAll()">初期化</button>`}
function backupView(){return `<h1>バックアップ / JSON</h1><button onclick="exportBackup()">完全バックアップJSONを書き出す</button><button onclick="exportCore('all')">共通JSONを書き出す</button><button onclick="exportCore('projects')">作品だけ</button><button onclick="exportCore('episodes')">エピソードだけ</button><button onclick="exportCore('apps')">アプリ設定だけ</button><button onclick="exportCore('favorites')">お気に入りと履歴</button><label class="file">JSONを読み込む<input type="file" accept="application/json,.json" onchange="this.files[0]&&importFile(this.files[0])"></label><button onclick="state=mergeDefaults(state);saveState(true);render()">サンプルデータを再作成</button>`}
function searchView(){return `<h1>全体検索</h1><input id="searchPage" placeholder="検索語" oninput="searchAll(this.value,true)"><div id="searchResults"></div>`}
function searchableItems(){return [...COMMON_COLLECTIONS,'apps'].flatMap(collection=>(state[collection]||[]).map(item=>({collection,item,type:item.type||COLLECTION_TYPE_MAP[collection],title:continueTitle(collection,item)})))}
function openSearchResult(collection,id){const item=(state[collection]||[]).find(x=>x.id===id);if(!item)return;if(collection==='apps')openApp(id);else if(collection==='projects'){selectContext(id,'');setView('projects')}else if(collection==='episodes'){selectContext(item.projectId,id);setView('episodes')}else{if(item.projectId)selectContext(item.projectId,item.episodeId||'');toast('対象項目を選択しました')}}
function searchAll(q,show=false){const box=show?$('#searchResults'):null;if(!q){if(box)box.innerHTML='';return}q=q.toLowerCase().trim();let res=searchableItems().filter(({collection,item,type,title})=>[title,item.memo,item.summary,item.description,typeLabel(type),type,item.subtitle,item.chapter,(item.tags||[]).join(' ')].join(' ').toLowerCase().includes(q));const html=res.map(({collection,item,type,title})=>`<div class="row"><span><b>${esc(typeLabel(type))}</b>：${esc(title)}<br><small>${itemTagsHtml(item)} ${metaLine(item)}</small></span><button onclick="openSearchResult('${collection}','${item.id}')">開く/選択</button></div>`).join('')||'<p>見つかりません。</p>';if(box)box.innerHTML=html;else modal(`<h2>検索結果</h2>${html}`)}
function consultView(){return `<h1>ノヴァに相談</h1><label>相談の種類<select id="ctype">${['現在の作品について相談','現在の話数について相談','制作の続きを相談','設定整理を相談','今日やることを相談','Nova Studioの改善を相談'].map(x=>`<option>${x}</option>`)}</select></label><label>相談内容<textarea id="cbody" rows="7"></textarea></label><button onclick="genConsult()">相談用文章を作成</button><button onclick="$('#cbody').value=''">入力内容を消す</button><textarea id="cout" rows="14" readonly></textarea><button onclick="copyConsult()">クリップボードへコピー</button><button onclick="downloadText($('#cout').value,'nova-consult-'+stamp()+'.txt')">テキスト保存</button><button onclick="downloadJson({format:'nova-consult',appVersion:NOVA_VERSION,exportedAt:now(),text:$('#cout').value},'nova-consult-'+stamp()+'.json')">JSON保存</button>`}
function genConsult(){ $('#cout').value=makeConsultText($('#ctype').value,$('#cbody').value) } async function copyConsult(){try{await navigator.clipboard.writeText($('#cout').value);toast('ノヴァへの相談文をコピーしました')}catch{toast('クリップボードが使えません。下の欄を手動で選択してコピーしてください。');$('#cout').focus();$('#cout').select()}}
function showContext(){modal(`<h2>作品・話数を選択</h2><label>作品<select id="mp" onchange="fillEp(this.value)">${state.projects.filter(p=>!p.isArchived).map(p=>`<option value="${p.id}" ${p.id===state.activeContext.projectId?'selected':''}>${esc(p.title)}</option>`)}</select></label><label>話数<select id="me"></select></label><button onclick="selectContext($('#mp').value,$('#me').value);closeModal()">選択</button>`);fillEp($('#mp').value)}
function fillEp(pid){$('#me').innerHTML=state.episodes.filter(e=>e.projectId===pid&&!e.isArchived).map(e=>`<option value="${e.id}" ${e.id===state.activeContext.episodeId?'selected':''}>${esc(e.numberLabel)}</option>`).join('')}
function editApp(id){const a=state.apps.find(x=>x.id===id);modal(`<h2>アプリ設定</h2><label>アプリ名<input id="an" value="${esc(a.name)}"></label><label>URL<input id="au" value="${esc(a.url)}"></label><label><input id="ae" type="checkbox" ${a.enabled?'checked':''}>有効</label><label><input id="at" type="checkbox" ${a.openInNewTab?'checked':''}>新しいタブ</label><label>説明<textarea id="ad">${esc(a.description)}</textarea></label><label>バージョン<input id="av" value="${esc(a.version)}"></label><label>状態<select id="as">${ITEM_STATUSES.map(s=>`<option ${a.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>タグ（カンマ区切りで複数登録）<input id="ag" value="${esc(tagInputValue(a))}"></label><label>メモ<textarea id="am">${esc(a.memo)}</textarea></label><button onclick="Object.assign(state.apps.find(x=>x.id==='${id}'),{name:$('#an').value,title:$('#an').value,url:$('#au').value,enabled:$('#ae').checked,openInNewTab:$('#at').checked,description:$('#ad').value,version:$('#av').value,status:$('#as').value,tags:parseTags($('#ag').value),memo:$('#am').value});touch(state.apps.find(x=>x.id==='${id}'));saveState();closeModal();render()">保存</button>`)}
function editProject(id){const p=id?state.projects.find(x=>x.id===id):project(uid('project'),'新しい作品',state.projects.length+1);modal(`<h2>作品${id?'編集':'追加'}</h2>${['id','title','reading','shortName','englishTitle','genre','summary','themeColor'].map(k=>`<label>${k}<input id="p_${k}" value="${esc(p[k])}" ${k==='id'&&id?'readonly':''}></label>`).join('')}<label>制作状態<select id="p_productionStatus">${PRODUCTION_STATUSES.map(s=>`<option ${p.productionStatus===s?'selected':''}>${s}</option>`).join('')}</select></label><label>状態<select id="p_status">${ITEM_STATUSES.map(s=>`<option ${p.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>タグ（カンマ区切りで複数登録）<input id="p_tags" value="${esc(tagInputValue(p))}"></label><p class="meta">作成日時：${esc(p.createdAt||'自動保存')} / 更新日時：${esc(p.updatedAt||'自動更新')}</p><button onclick="saveProject('${id||''}')">保存</button>`)}
function saveProject(id){let p=id?state.projects.find(x=>x.id===id):{};['id','title','reading','shortName','englishTitle','genre','summary','themeColor'].forEach(k=>p[k]=$('#p_'+k).value);p.productionStatus=$('#p_productionStatus').value;p.status=$('#p_status').value;p.tags=parseTags($('#p_tags').value);touch(p);if(!id){p.sortOrder=state.projects.length+1;p.isArchived=false;state.projects.push(p);state.episodes.push(episode(uid('episode'),p.id,'作品全体',1),episode(uid('episode'),p.id,'未分類',2))}addRecentItem('project',p);saveState();closeModal();render()}
function editEpisode(id){const p=currentProject(),e=id?state.episodes.find(x=>x.id===id):episode(uid('episode'),p.id,'新しい話数',state.episodes.length+1);modal(`<h2>話数${id?'編集':'追加'}</h2>${['id','numberLabel','subtitle','chapter','summary','memo','completionRate','relatedCharactersText','relatedTermsText','relatedWorldsText','relatedScenesText'].map(k=>`<label>${k}<input id="e_${k}" value="${esc(e[k])}" ${k==='id'&&id?'readonly':''}></label>`).join('')}<label>制作状態<select id="e_productionStatus">${PRODUCTION_STATUSES.map(s=>`<option ${e.productionStatus===s?'selected':''}>${s}</option>`).join('')}</select></label><label>状態<select id="e_status">${ITEM_STATUSES.map(s=>`<option ${e.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>タグ（カンマ区切りで複数登録）<input id="e_tags" value="${esc(tagInputValue(e))}"></label><p class="meta">作成日時：${esc(e.createdAt||'自動保存')} / 更新日時：${esc(e.updatedAt||'自動更新')}</p><button onclick="saveEpisode('${id||''}')">保存</button>`)}
function saveEpisode(id){let e=id?state.episodes.find(x=>x.id===id):{projectId:currentProject().id,createdAt:now(),sortOrder:state.episodes.length+1,isArchived:false};['id','numberLabel','subtitle','chapter','summary','memo','completionRate','relatedCharactersText','relatedTermsText','relatedWorldsText','relatedScenesText'].forEach(k=>e[k]=$('#e_'+k).value);e.productionStatus=$('#e_productionStatus').value;e.status=$('#e_status').value;e.tags=parseTags($('#e_tags').value);touch(e);if(!id)state.episodes.push(e);addRecentItem('episode',e);saveState();closeModal();render()}
function findCommonItem(type,targetId){const key=Object.keys(COLLECTION_TYPE_MAP).find(k=>COLLECTION_TYPE_MAP[k]===type);return key?(state[key]||[]).find(x=>x.id===targetId):null}
function isFav(type,targetId){return state.favorites.some(f=>f.type===type&&f.targetId===targetId)||Boolean(findCommonItem(type,targetId)?.favorite)} function toggleFavorite(type,targetId,projectId='',episodeId=''){const i=state.favorites.findIndex(f=>f.type===type&&f.targetId===targetId),item=findCommonItem(type,targetId);if(i>=0){state.favorites.splice(i,1);if(item){item.favorite=false;touch(item)}}else{if(item){item.favorite=true;touch(item)}state.favorites.push({id:uid('favorite'),type,targetId,projectId:projectId||item?.projectId||targetId,episodeId:episodeId||'',title:item?continueTitle(Object.keys(COLLECTION_TYPE_MAP).find(k=>COLLECTION_TYPE_MAP[k]===type)||'',item):targetId,sortOrder:state.favorites.length+1,createdAt:now()})};saveState();render()}function openFavorite(id){const f=state.favorites.find(x=>x.id===id);if(!f)return;if(f.type==='app')openApp(f.targetId);else if(f.type==='project'){selectContext(f.projectId||f.targetId,'');setView('projects')}else if(f.type==='episode'){selectContext(f.projectId,f.episodeId||f.targetId);setView('episodes')}else selectContext(f.projectId,f.episodeId)}
function openRecent(id){const r=state.recentItems.find(x=>x.id===id);if(!r)return;if(r.type==='project')selectContext(r.projectId,'');else if(r.type==='episode')selectContext(r.projectId,r.episodeId);else if(r.appId)openApp(r.appId,r.url)}function delRecent(id){state.recentItems=state.recentItems.filter(r=>r.id!==id);saveState();render()}function duplicateProject(id){let p={...state.projects.find(x=>x.id===id),id:uid('project'),title:state.projects.find(x=>x.id===id).title+' コピー',createdAt:now(),updatedAt:now(),sortOrder:state.projects.length+1};state.projects.push(p);addRecentItem('project',p);state.episodes.push(episode(uid('episode'),p.id,'作品全体',1),episode(uid('episode'),p.id,'未分類',2));saveState();render()}function archiveProject(id){let p=state.projects.find(x=>x.id===id);p.isArchived=!p.isArchived;p.updatedAt=now();saveState();render()}function moveProject(id,d){let p=state.projects.find(x=>x.id===id);p.sortOrder+=d*1.5;state.projects.sort((a,b)=>a.sortOrder-b.sortOrder).forEach((x,i)=>x.sortOrder=i+1);saveState();render()}function duplicateEpisode(id){let e={...state.episodes.find(x=>x.id===id),id:uid('episode'),numberLabel:state.episodes.find(x=>x.id===id).numberLabel+' コピー',createdAt:now(),updatedAt:now(),sortOrder:state.episodes.length+1};state.episodes.push(e);saveState();render()}function archiveEpisode(id){let e=state.episodes.find(x=>x.id===id);e.isArchived=!e.isArchived;e.updatedAt=now();saveState();render()}function moveEpisode(id,d){let e=state.episodes.find(x=>x.id===id);e.sortOrder+=d*1.5;state.episodes.filter(x=>x.projectId===e.projectId).sort((a,b)=>a.sortOrder-b.sortOrder).forEach((x,i)=>x.sortOrder=i+1);saveState();render()}
window.addEventListener('hashchange',render);window.addEventListener('error',e=>{console.error(e);toast('エラーが発生しました。データは保持されています。')});

const STORY_FIELDS={
 scenes:['sceneNumber','title','location','timeOfDay','summary','script','charactersText','termsText','worldsText','memo','status','tags','completionRate'],
 characters:['title','reading','role','profile','personality','speechStyle','appearance','abilities','importantSettings','relationships','episodesText','scenesText','status','tags','memo'],
 worlds:['title','category','description','status','tags','charactersText','episodesText','termsText','memo'],
 terms:['title','reading','description','category','charactersText','episodesText','worldsText','status','tags'],
 timelines:['eraLabel','title','content','sortOrder','charactersText','episodesText','worldsText','status','tags'],
 ideas:['title','content','category','projectText','charactersText','episodesText','ideaStatus','tags']
};
const STORY_LABELS={scenes:'シーン',characters:'キャラクター',worlds:'世界観',terms:'用語',timelines:'年表',ideas:'アイデア'};
const FIELD_LABELS={sceneNumber:'シーン番号',title:'タイトル/名前',location:'場所',timeOfDay:'時間帯',summary:'概要',script:'台本',charactersText:'関連キャラクター',termsText:'関連用語',worldsText:'関連世界観',memo:'制作メモ/メモ',status:'状態',tags:'タグ',completionRate:'完成率',reading:'読み方',role:'役割',profile:'プロフィール',personality:'性格',speechStyle:'口調',appearance:'見た目',abilities:'能力',importantSettings:'重要設定',relationships:'人間関係',episodesText:'登場話・関連話数',category:'分類/カテゴリー',description:'説明',eraLabel:'年月日または時代表記',content:'内容',sortOrder:'並び順',projectText:'関連作品',ideaStatus:'アイデア状態'};
function collectionProjectItems(collection){const p=currentProject();return (state[collection]||[]).filter(x=>!x.isArchived&&(!x.projectId||x.projectId===p?.id));}
function storyTitle(collection,item){return collection==='scenes'?`${item.sceneNumber||''} ${item.title||'無題'}`.trim():collection==='timelines'?`${item.eraLabel||''} ${item.title||'無題'}`.trim():continueTitle(collection,item)||item.title||'無題'}
function storyCollectionView(collection){const p=currentProject(),items=collectionProjectItems(collection).sort((a,b)=> collection==='terms'&&state.termSort==='kana' ? (a.reading||a.title||'').localeCompare(b.reading||b.title||'','ja') : (collection==='scenes'||collection==='timelines'?((+a.sortOrder||0)-(+b.sortOrder||0)):(b.updatedAt||'').localeCompare(a.updatedAt||'')));const extra=collection==='terms'?`<button onclick="state.termSort=state.termSort==='kana'?'updated':'kana';render()">並び：${state.termSort==='kana'?'五十音順':'更新順'}</button>`:'';return `<h1>${esc(STORY_LABELS[collection])}：${esc(p?.title)}</h1><button onclick="editStoryItem('${collection}')">＋追加</button>${extra}<div class="${collection==='timelines'?'timeline-list':''}">${items.map(it=>`<article class="card ${collection==='timelines'?'timeline-item':''}" ${collection==='scenes'?'draggable="true" ondragstart="dragScene(event,\''+it.id+'\')" ondrop="dropScene(event,\''+it.id+'\')" ondragover="event.preventDefault()"':''}><h3>${esc(storyTitle(collection,it))}</h3>${collection==='characters'&&it.importantSettings?`<div class="important">${esc(it.importantSettings)}</div>`:''}<p>${esc(it.summary||it.description||it.content||it.profile||it.memo||'')}</p><p>${itemTagsHtml(it)}<br>${metaLine(it)}</p><button onclick="openStoryDetail('${collection}','${it.id}')">詳細</button><button onclick="editStoryItem('${collection}','${it.id}')">編集</button><button onclick="archiveStoryItem('${collection}','${it.id}')">削除</button><button class="favorite ${isFav(COLLECTION_TYPE_MAP[collection],it.id)?'active':''}" onclick="toggleFavorite('${COLLECTION_TYPE_MAP[collection]}','${it.id}','${it.projectId||''}','${it.episodeId||''}')">${isFav(COLLECTION_TYPE_MAP[collection],it.id)?'★':'☆'}</button></article>`).join('')||'<p>まだありません。</p>'}</div>`}
function openStoryDetail(collection,id){const item=state[collection].find(x=>x.id===id);if(!item)return;const related=relatedCards(item);modal(`<h2>${esc(storyTitle(collection,item))}</h2>${collection==='characters'&&item.importantSettings?`<div class="important"><b>重要設定</b><br>${esc(item.importantSettings)}</div>`:''}<p>${metaLine(item)}<br>お気に入り：${isFav(COLLECTION_TYPE_MAP[collection],id)?'★':'☆'}<br>タグ：${itemTagsHtml(item)}</p>${STORY_FIELDS[collection].filter(f=>!['tags','status'].includes(f)).map(f=>`<section><h3>${esc(FIELD_LABELS[f]||f)}</h3><p>${esc(item[f]??'')}</p></section>`).join('')}<h3>関連リンク</h3>${related}<button onclick="editStoryItem('${collection}','${id}')">編集</button>`)}
function relatedCards(item){const ids=new Set([...(item.relatedIds||[]),...(item.relatedCharacters||[]),...(item.relatedTerms||[]),...(item.relatedWorlds||[]),...(item.relatedEpisodes||[]),...(item.relatedScenes||[])]);let cards=[];CARD_COLLECTIONS.forEach(c=>(state[c]||[]).forEach(x=>{if(ids.has(x.id))cards.push(`<button onclick="closeModal();openCardTarget('${c}','${x.id}')">${esc(typeLabel(COLLECTION_TYPE_MAP[c]))}: ${esc(storyTitle(c,x))}</button>`)}));return cards.join('')||'<p class="meta">関連項目なし</p>'}
function editStoryItem(collection,id=''){const type=COLLECTION_TYPE_MAP[collection],p=currentProject(),e=currentEpisode();const item=id?state[collection].find(x=>x.id===id):normalizeCommonItem({id:uid(type),projectId:p?.id||'',episodeId:collection==='scenes'?e?.id:'',title:'',sortOrder:(state[collection]||[]).length+1,ideaStatus:'未整理'},type);modal(`<h2>${esc(STORY_LABELS[collection])}${id?'編集':'追加'}</h2>${STORY_FIELDS[collection].map(f=>fieldInput(f,item)).join('')}<label>関連ID（カンマ区切り・重複自動除去）<input id="s_relatedIds" value="${esc((item.relatedIds||[]).join(','))}"></label><p class="meta">作成日時：${esc(item.createdAt||'自動保存')} / 更新日時：${esc(item.updatedAt||'自動更新')}</p><button onclick="saveStoryItem('${collection}','${id}')">保存</button>${collection==='ideas'&&id?`<button onclick="adoptIdea('${id}')">採用して項目へ移す</button>`:''}`)}
function fieldInput(f,item){if(f==='status')return `<label>${FIELD_LABELS[f]}<select id="s_${f}">${ITEM_STATUSES.map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`).join('')}</select></label>`;if(f==='ideaStatus')return `<label>${FIELD_LABELS[f]}<select id="s_${f}">${['未整理','検討中','採用','保留','没案'].map(s=>`<option ${item.ideaStatus===s?'selected':''}>${s}</option>`).join('')}</select></label>`;if(f==='tags')return `<label>${FIELD_LABELS[f]}<input id="s_${f}" value="${esc(tagInputValue(item))}"></label>`;let long=['summary','script','memo','profile','personality','appearance','abilities','importantSettings','relationships','description','content'].includes(f);return `<label>${FIELD_LABELS[f]||f}${long?`<textarea id="s_${f}" rows="${f==='script'?8:4}">${esc(item[f]||'')}</textarea>`:`<input id="s_${f}" value="${esc(item[f]||'')}">`}</label>`}
function saveStoryItem(collection,id=''){const type=COLLECTION_TYPE_MAP[collection];let item=id?state[collection].find(x=>x.id===id):normalizeCommonItem({id:uid(type),projectId:currentProject()?.id||'',episodeId:collection==='scenes'?currentEpisode()?.id:'',sortOrder:(state[collection]||[]).length+1},type);const before=JSON.stringify(item);STORY_FIELDS[collection].forEach(f=>{if(f==='tags')item.tags=parseTags($('#s_'+f).value);else item[f]=$('#s_'+f).value});item.title=item.title||item.name||item.sceneNumber||item.eraLabel||'無題';item.relatedIds=parseTags($('#s_relatedIds').value);touch(item);if(!id)state[collection].push(item);recordHistory(item,before);saveState();closeModal();render()}
function recordHistory(item,before){if(!state.settings.saveHistory)return;const prev=JSON.parse(before||'{}');Object.keys(item).forEach(k=>{if(JSON.stringify(prev[k])!==JSON.stringify(item[k])&&!['updatedAt'].includes(k)){state.changeHistory.push({id:uid('history'),type:'history',projectId:item.projectId||'',targetId:item.id,targetType:item.type,field:k,before:prev[k]??'',after:item[k]??'',createdAt:now(),updatedAt:now(),status:'確定',tags:[]})}})}
function archiveStoryItem(collection,id){if(state.settings.confirmOnDelete&&!confirm('完全削除ではなくアーカイブします。よろしいですか？'))return;let item=state[collection].find(x=>x.id===id);item.isArchived=true;touch(item);saveState();render()}
let draggedSceneId='';function dragScene(e,id){draggedSceneId=id;e.dataTransfer.effectAllowed='move'}function dropScene(e,id){e.preventDefault();if(!draggedSceneId||draggedSceneId===id)return;const a=state.scenes.find(x=>x.id===draggedSceneId),b=state.scenes.find(x=>x.id===id);const tmp=a.sortOrder;a.sortOrder=b.sortOrder;b.sortOrder=tmp;touch(a);touch(b);saveState();render()}
function adoptIdea(id){const idea=state.ideas.find(x=>x.id===id);if(!idea)return;const collection=prompt('移動先を入力：characters / worlds / terms / episodes / scenes','characters');if(!['characters','worlds','terms','episodes','scenes'].includes(collection))return;const type=COLLECTION_TYPE_MAP[collection];const item=normalizeCommonItem({id:uid(type),projectId:idea.projectId||currentProject()?.id,episodeId:idea.episodeId||currentEpisode()?.id,title:idea.title,summary:idea.content,description:idea.content,memo:`アイデア「${idea.title}」から採用`,relatedIds:[idea.id]},type);state[collection].push(item);idea.ideaStatus='採用';idea.adoptedTo=[...(idea.adoptedTo||[]),item.id];touch(idea);saveState();closeModal();render();toast('採用先を作成し、元アイデアは履歴として残しました')}
function historyView(){const p=currentProject();const rows=(state.changeHistory||[]).filter(h=>!h.projectId||h.projectId===p?.id).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));return `<h1>変更履歴</h1>${rows.map(h=>`<div class="row"><span>${esc(h.createdAt)} / ${esc(typeLabel(h.targetType))} / ${esc(h.field)}<br><small>前：${esc(h.before)} → 後：${esc(h.after)}</small></span></div>`).join('')||'<p>履歴はまだありません。</p>'}`}

// render after Version 0.5 overrides are registered
saveState(true);

function openProjectDetail(id){const p=state.projects.find(x=>x.id===id);if(!p)return;selectContext(id,state.activeContext.episodeId);const counts={episodes:state.episodes.filter(x=>x.projectId===id).length,scenes:state.scenes.filter(x=>x.projectId===id).length,characters:state.characters.filter(x=>x.projectId===id).length,worlds:state.worlds.filter(x=>x.projectId===id).length,terms:state.terms.filter(x=>x.projectId===id).length,timelines:state.timelines.filter(x=>x.projectId===id).length,ideas:state.ideas.filter(x=>x.projectId===id).length,changeHistory:state.changeHistory.filter(x=>x.projectId===id).length};modal(`<h2>${esc(p.title)}</h2><p><b>説明：</b>${esc(p.summary||'')}</p><p><b>作成日時：</b>${esc(p.createdAt)} / <b>更新日時：</b>${esc(p.updatedAt)}<br><b>状態：</b>${esc(p.status)} / <b>制作状態：</b>${esc(p.productionStatus)} / <b>お気に入り：</b>${isFav('project',p.id)?'★':'☆'}<br><b>タグ：</b>${itemTagsHtml(p)}</p><div class="grid">${[['概要','projects'],['話数','episodes'],['シーン','scenes'],['キャラクター','characters'],['世界観','worlds'],['用語','terms'],['年表','timelines'],['アイデア','ideas'],['変更履歴','history']].map(([label,view])=>`<section><h3>${label}</h3><p>${counts[view]??''}件</p><button onclick="closeModal();setView('${view==='projects'?'projects':view}')">開く</button></section>`).join('')}</div><button onclick="editProject('${id}')">作品情報を編集</button>`)}

// Version 0.5 practical story-workspace helpers
const FILTERABLE_COLLECTIONS=['episodes','scenes','characters','worlds','terms','timelines','ideas'];
function requireProject(collection){return !currentProject()?`<section class="empty-state"><h1>${esc(STORY_LABELS[collection]||'話数')}</h1><p>先に作品を選択してください</p><button class="primary-action" onclick="showContext()">作品を選択</button></section>`:''}
function projectCounts(pid){return {episodes:state.episodes.filter(x=>x.projectId===pid&&!x.isArchived).length,scenes:state.scenes.filter(x=>x.projectId===pid&&!x.isArchived).length,characters:state.characters.filter(x=>x.projectId===pid&&!x.isArchived).length,worlds:state.worlds.filter(x=>x.projectId===pid&&!x.isArchived).length,terms:state.terms.filter(x=>x.projectId===pid&&!x.isArchived).length,timelines:state.timelines.filter(x=>x.projectId===pid&&!x.isArchived).length,ideas:state.ideas.filter(x=>x.projectId===pid&&!x.isArchived).length}}
function collectionLabel(c){return c==='episodes'?'話数':STORY_LABELS[c]}
function projectItems(c){const p=currentProject();return (state[c]||[]).filter(x=>!x.isArchived&&x.projectId===p?.id)}
function filterBar(c){const tags=[...new Set(projectItems(c).flatMap(x=>x.tags||[]))];return `<div class="filters"><label>状態<select id="f_status"><option value="">すべて</option>${ITEM_STATUSES.map(s=>`<option ${state.filters?.[c]?.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>タグ<select id="f_tag"><option value="">すべて</option>${tags.map(t=>`<option ${state.filters?.[c]?.tag===t?'selected':''}>${esc(t)}</option>`).join('')}</select></label><label>お気に入り<select id="f_fav"><option value="">すべて</option><option ${state.filters?.[c]?.fav==='yes'?'selected':''} value="yes">お気に入り</option></select></label><label>並び順<select id="f_sort"><option value="updated">更新順</option><option value="created" ${state.filters?.[c]?.sort==='created'?'selected':''}>作成順</option><option value="name" ${state.filters?.[c]?.sort==='name'?'selected':''}>名前順</option>${c==='terms'?`<option value="kana" ${state.filters?.[c]?.sort==='kana'?'selected':''}>五十音順</option>`:''}</select></label><button onclick="setFilter('${c}')">絞り込み</button></div>`}
function setFilter(c){state.filters=state.filters||{};state.filters[c]={status:$('#f_status').value,tag:$('#f_tag').value,fav:$('#f_fav').value,sort:$('#f_sort').value};render()}
function applyFilters(c,items){const f=state.filters?.[c]||{};let out=items.filter(x=>(!f.status||x.status===f.status)&&(!f.tag||(x.tags||[]).includes(f.tag))&&(!f.fav||isFav(COLLECTION_TYPE_MAP[c],x.id)));const sort=f.sort||'updated';return out.sort((a,b)=>sort==='created'?(b.createdAt||'').localeCompare(a.createdAt||''):sort==='name'?(storyTitle(c,a)).localeCompare(storyTitle(c,b),'ja'):sort==='kana'?((a.reading||storyTitle(c,a)).localeCompare(b.reading||storyTitle(c,b),'ja')):(b.updatedAt||'').localeCompare(a.updatedAt||''))}
function emptyState(c){const label=collectionLabel(c);return `<section class="empty-state"><p>${label}はまだ登録されていません</p><button class="primary-action" onclick="${c==='episodes'?'editEpisode()':`editStoryItem('${c}')`}">最初の${label}を追加</button></section>`}
function homeView(){const p=currentProject(),recent=continueItems().filter(r=>!p||!r.item.projectId||r.item.projectId===p.id).slice(0,5),fav=state.favorites.filter(f=>!p||!f.projectId||f.projectId===p.id).slice(0,5),counts=p?projectCounts(p.id):null;return `<section class="hero"><h1>Nova Studio</h1><p>創る、繋がる、育っていく。</p><h2>ようこそ、物語の記憶へ。</h2><p>現在の作品：${p?esc(p.title):'未選択'} <span class="ver">Version ${NOVA_VERSION}</span></p><button onclick="showContext()">作品を選択</button>${p?`<button onclick="openProjectDetail('${p.id}')">作品専用ダッシュボードを開く</button>`:''}</section>${p?`<section><h2>作品内の件数</h2><div class="stats">${Object.entries(counts).map(([k,v])=>`<div><b>${esc(collectionLabel(k))}</b><span>${v}件</span></div>`).join('')}</div></section>`:''}<section><h2>最近更新した5件</h2>${recent.length?recent.map(r=>`<div class="row"><span>${esc(r.title)} / ${esc(typeLabel(r.type))} / 更新：${esc(r.updatedAt)}</span><button onclick="openContinue('${r.collection}','${r.item.id}')">続きから開く</button></div>`).join(''):'<p>まだ更新された項目はありません</p>'}</section><section><h2>お気に入り5件</h2>${fav.length?fav.map(f=>`<div class="row"><span>★ ${esc(f.title)}</span><button onclick="openFavorite('${f.id}')">開く</button></div>`).join(''):'<p>お気に入りはまだありません。</p>'}</section><h2>制作アプリ</h2><div class="grid">${appCards()}</div>`}
function episodesView(){const p=currentProject();if(!p)return requireProject('episodes');const items=applyFilters('episodes',projectItems('episodes'));return `<h1>話数：${esc(p.title)}</h1><button class="primary-action" onclick="editEpisode()">＋ 話数を追加</button>${filterBar('episodes')}<div>${items.map(e=>`<div class="card"><h3>${esc(e.numberLabel)} ${esc(e.subtitle)}</h3><p>${esc(e.summary)}<br>完成率:${esc(e.completionRate||'未設定')} / ${metaLine(e)}<br>${itemTagsHtml(e)}</p><button onclick="openEpisodeDetail('${e.id}')">詳細</button><button onclick="selectContext('${p.id}','${e.id}')">選択</button><button onclick="editEpisode('${e.id}')">編集</button><button class="favorite ${isFav('episode',e.id)?'active':''}" onclick="toggleFavorite('episode','${e.id}','${p.id}','${e.id}')">${isFav('episode',e.id)?'★':'☆'}</button></div>`).join('')||emptyState('episodes')}</div>`}
function storyCollectionView(collection){const p=currentProject();if(!p)return requireProject(collection);const items=applyFilters(collection,projectItems(collection));return `<h1>${esc(STORY_LABELS[collection])}：${esc(p.title)}</h1><button class="primary-action" onclick="editStoryItem('${collection}')">＋ ${esc(STORY_LABELS[collection])}を追加</button>${filterBar(collection)}<div class="${collection==='timelines'?'timeline-list':''}">${items.map(it=>`<article class="card ${collection==='timelines'?'timeline-item':''}"><h3>${esc(storyTitle(collection,it))}</h3>${collection==='characters'&&it.importantSettings?`<div class="important"><b>重要設定</b><br>${esc(it.importantSettings)}</div>`:''}<p>${esc(it.summary||it.description||it.content||it.profile||it.memo||'')}</p><p>${itemTagsHtml(it)}<br>${metaLine(it)}</p><button onclick="openStoryDetail('${collection}','${it.id}')">詳細</button><button onclick="editStoryItem('${collection}','${it.id}')">編集</button><button onclick="archiveStoryItem('${collection}','${it.id}')">削除</button><button class="favorite ${isFav(COLLECTION_TYPE_MAP[collection],it.id)?'active':''}" onclick="toggleFavorite('${COLLECTION_TYPE_MAP[collection]}','${it.id}','${it.projectId||''}','${it.episodeId||''}')">${isFav(COLLECTION_TYPE_MAP[collection],it.id)?'★':'☆'}</button></article>`).join('')||emptyState(collection)}</div>`}
function relatedSelect(field,label,collection,item){const vals=new Set([...(item[field]||[]),...(item.relatedIds||[]).filter(id=>(state[collection]||[]).some(x=>x.id===id))]);const opts=projectItems(collection).map(x=>`<option value="${x.id}" ${vals.has(x.id)?'selected':''}>${esc(storyTitle(collection,x))}</option>`).join('');return `<label>${label}<select id="s_${field}" multiple>${opts}</select></label><div class="selected-tags">${[...vals].map(id=>`<span class="tag">${esc(storyTitle(collection,(state[collection]||[]).find(x=>x.id===id)||{title:id}))}</span>`).join('')||'<span class="meta">未選択</span>'}</div>`}
function group(title,html){return `<fieldset><legend>${title}</legend>${html}</fieldset>`}
function editStoryItem(collection,id=''){if(!currentProject())return toast('先に作品を選択してください');const type=COLLECTION_TYPE_MAP[collection],p=currentProject(),e=currentEpisode();const item=id?state[collection].find(x=>x.id===id):normalizeCommonItem({id:uid(type),projectId:p.id,episodeId:collection==='scenes'?e?.id:'',title:'',sortOrder:(state[collection]||[]).length+1,ideaStatus:'未整理'},type);const basic=STORY_FIELDS[collection].filter(f=>['sceneNumber','title','reading','role','category','eraLabel','location','timeOfDay','summary','description','content','profile'].includes(f)).map(f=>fieldInput(f,item)).join('');const production=STORY_FIELDS[collection].filter(f=>['script','memo','personality','speechStyle','appearance','abilities','importantSettings','relationships','completionRate'].includes(f)).map(f=>fieldInput(f,item)).join('');const management=STORY_FIELDS[collection].filter(f=>['status','tags','ideaStatus','sortOrder'].includes(f)).map(f=>fieldInput(f,item)).join('');const related=relatedSelect('relatedCharacters','関連キャラクター','characters',item)+relatedSelect('relatedEpisodes','関連話数','episodes',item)+relatedSelect('relatedTerms','関連用語','terms',item)+relatedSelect('relatedWorlds','関連世界観','worlds',item);modal(`<h2>${esc(STORY_LABELS[collection])}${id?'編集':'追加'}</h2><form data-dirty="false" oninput="this.dataset.dirty='true'">${group('基本情報',basic)}${group('関連情報',related)}${group('制作情報',production)}${group('管理情報',management)}<p class="meta">作成日時：${esc(item.createdAt||'自動保存')} / 更新日時：${esc(item.updatedAt||'自動更新')}</p><button type="button" onclick="saveStoryItem('${collection}','${id}')">保存</button></form>`) }
function selectedIds(id){return Array.from(document.querySelectorAll(`#${id} option:checked`)).map(o=>o.value).filter((x,i,a)=>a.indexOf(x)===i)}
function saveStoryItem(collection,id=''){const type=COLLECTION_TYPE_MAP[collection];let item=id?state[collection].find(x=>x.id===id):normalizeCommonItem({id:uid(type),projectId:currentProject()?.id||'',episodeId:collection==='scenes'?currentEpisode()?.id:'',sortOrder:(state[collection]||[]).length+1},type);const before=JSON.stringify(item);STORY_FIELDS[collection].forEach(f=>{const el=$('#s_'+f);if(el)item[f]=f==='tags'?parseTags(el.value):el.value});['relatedCharacters','relatedEpisodes','relatedTerms','relatedWorlds'].forEach(f=>item[f]=selectedIds('s_'+f));item.relatedIds=[...new Set([...item.relatedCharacters,...item.relatedEpisodes,...item.relatedTerms,...item.relatedWorlds])];item.title=item.title||item.name||item.sceneNumber||item.eraLabel||'無題';touch(item);if(!id)state[collection].push(item);recordHistory(item,before);saveState();closeModal();render();toast('保存しました')}
function openEpisodeDetail(id){const e=state.episodes.find(x=>x.id===id);if(!e)return;const scenes=state.scenes.filter(s=>s.episodeId===id&&!s.isArchived).sort((a,b)=>(+a.sortOrder||0)-(+b.sortOrder||0));modal(`<h2>${esc(e.numberLabel)} ${esc(e.subtitle||e.title||'')}</h2><p><b>概要：</b>${esc(e.summary||'')}<br><b>制作メモ：</b>${esc(e.memo||'')}<br><b>完成率：</b>${esc(e.completionRate||'未設定')} / <b>状態：</b>${esc(e.status||'仮設定')}<br>${itemTagsHtml(e)}<br>${metaLine(e)}</p><h3>関連キャラクター</h3>${relatedCards({relatedIds:e.relatedCharacters||[]})}<h3>関連用語</h3>${relatedCards({relatedIds:e.relatedTerms||[]})}<h3>関連世界観</h3>${relatedCards({relatedIds:e.relatedWorlds||[]})}<h3>シーン一覧</h3>${scenes.map(s=>`<div class="row"><span>${esc(storyTitle('scenes',s))}</span><button onclick="openStoryDetail('scenes','${s.id}')">開く</button></div>`).join('')||'<p class="meta">シーンはまだありません。</p>'}<button onclick="selectContext('${e.projectId}','${e.id}');editStoryItem('scenes')">シーンを追加</button><button onclick="editEpisode('${id}')">編集</button><button class="favorite ${isFav('episode',id)?'active':''}" onclick="toggleFavorite('episode','${id}','${e.projectId}','${id}')">お気に入り登録</button><button onclick="editEpisode('${id}')">関連項目を追加</button>`) }
function openStoryDetail(collection,id){const item=state[collection].find(x=>x.id===id);if(!item)return;if(collection==='scenes')return openSceneDetail(id);const fields=collection==='characters'?['title','reading','role','profile','personality','speechStyle','appearance','abilities','importantSettings','relationships','episodesText','scenesText','status','tags','memo']:STORY_FIELDS[collection];modal(`<h2>${esc(storyTitle(collection,item))}</h2>${collection==='characters'&&item.importantSettings?`<div class="important"><b>重要設定</b><br>${esc(item.importantSettings)}</div>`:''}<p>${metaLine(item)}<br>お気に入り：${isFav(COLLECTION_TYPE_MAP[collection],id)?'★':'☆'}<br>タグ：${itemTagsHtml(item)}</p>${fields.filter(f=>!['tags','importantSettings'].includes(f)).map(f=>`<section><h3>${esc(FIELD_LABELS[f]||f)}</h3><p>${esc(f==='tags'?tagText(item):(item[f]??''))}</p></section>`).join('')}<h3>関連リンク</h3>${relatedCards(item)}<button onclick="editStoryItem('${collection}','${id}')">編集</button>`) }
function openSceneDetail(id){const s=state.scenes.find(x=>x.id===id);const scenes=state.scenes.filter(x=>x.episodeId===s.episodeId&&!x.isArchived).sort((a,b)=>(+a.sortOrder||0)-(+b.sortOrder||0));const i=scenes.findIndex(x=>x.id===id),prev=scenes[i-1],next=scenes[i+1];modal(`<h2>${esc(storyTitle('scenes',s))}</h2>${['sceneNumber','title','location','timeOfDay','summary','script','charactersText','termsText','worldsText','memo','completionRate','status'].map(f=>`<section><h3>${esc(FIELD_LABELS[f])}</h3><p>${esc(s[f]||'')}</p></section>`).join('')}<p>${itemTagsHtml(s)}<br>${metaLine(s)}</p><div class="row"><button ${!prev?'disabled':''} onclick="openSceneDetail('${prev?.id||''}')">← 前のシーン</button><button ${!next?'disabled':''} onclick="openSceneDetail('${next?.id||''}')">次のシーン →</button></div><h3>関連リンク</h3>${relatedCards(s)}<button onclick="editStoryItem('scenes','${id}')">編集</button>`) }
function closeModal(){const form=$('#modalBody form[data-dirty="true"]');if(form&&!confirm('未保存内容があります。閉じますか？'))return;$('#modal').classList.add('hidden')}
function backupView(){return `<h1>バックアップ / JSON</h1><button onclick="exportBackup()">完全バックアップJSONを書き出す</button><button onclick="exportCore('all')">共通JSONを書き出す</button><button onclick="exportCore('projects')">作品だけ</button><button onclick="exportCore('episodes')">エピソードだけ</button><button onclick="exportCore('apps')">アプリ設定だけ</button><button onclick="exportCore('favorites')">お気に入りと履歴</button><label class="file">JSONを読み込む<input type="file" accept="application/json,.json" onchange="this.files[0]&&importFile(this.files[0])"></label>`}
function editEpisode(id){const p=currentProject();if(!p)return toast('先に作品を選択してください');const e=id?state.episodes.find(x=>x.id===id):episode(uid('episode'),p.id,'新しい話数',state.episodes.length+1);const basic=['id','numberLabel','subtitle','chapter','summary'].map(k=>`<label>${k}<input id="e_${k}" value="${esc(e[k]||'')}" ${k==='id'&&id?'readonly':''}></label>`).join('');const related=relatedSelect('relatedCharacters','関連キャラクター','characters',e)+relatedSelect('relatedTerms','関連用語','terms',e)+relatedSelect('relatedWorlds','関連世界観','worlds',e);const production=['memo','completionRate'].map(k=>`<label>${k}<textarea id="e_${k}" rows="${k==='memo'?4:2}">${esc(e[k]||'')}</textarea></label>`).join('');const management=`<label>制作状態<select id="e_productionStatus">${PRODUCTION_STATUSES.map(s=>`<option ${e.productionStatus===s?'selected':''}>${s}</option>`).join('')}</select></label><label>状態<select id="e_status">${ITEM_STATUSES.map(s=>`<option ${e.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>タグ（カンマ区切りで複数登録）<input id="e_tags" value="${esc(tagInputValue(e))}"></label>`;modal(`<h2>話数${id?'編集':'追加'}</h2><form data-dirty="false" oninput="this.dataset.dirty='true'">${group('基本情報',basic)}${group('関連情報',related)}${group('制作情報',production)}${group('管理情報',management)}<p class="meta">作成日時：${esc(e.createdAt||'自動保存')} / 更新日時：${esc(e.updatedAt||'自動更新')}</p><button type="button" onclick="saveEpisode('${id||''}')">保存</button></form>`)}
function saveEpisode(id){let e=id?state.episodes.find(x=>x.id===id):{id:$('#e_id').value,projectId:currentProject().id,createdAt:now(),sortOrder:state.episodes.length+1,isArchived:false,type:'episode'};['id','numberLabel','subtitle','chapter','summary','memo','completionRate'].forEach(k=>e[k]=$('#e_'+k).value);e.relatedCharacters=selectedIds('s_relatedCharacters');e.relatedTerms=selectedIds('s_relatedTerms');e.relatedWorlds=selectedIds('s_relatedWorlds');e.relatedIds=[...new Set([...e.relatedCharacters,...e.relatedTerms,...e.relatedWorlds])];e.productionStatus=$('#e_productionStatus').value;e.status=$('#e_status').value;e.tags=parseTags($('#e_tags').value);touch(e);if(!id)state.episodes.push(e);addRecentItem('episode',e);saveState();closeModal();render();toast('保存しました')}
function editProject(id){const p=id?state.projects.find(x=>x.id===id):project(uid('project'),'新しい作品',state.projects.length+1);const basic=['id','title','reading','shortName','englishTitle','genre','summary','themeColor'].map(k=>`<label>${k}<input id="p_${k}" value="${esc(p[k]||'')}" ${k==='id'&&id?'readonly':''}></label>`).join('');const management=`<label>制作状態<select id="p_productionStatus">${PRODUCTION_STATUSES.map(s=>`<option ${p.productionStatus===s?'selected':''}>${s}</option>`).join('')}</select></label><label>状態<select id="p_status">${ITEM_STATUSES.map(s=>`<option ${p.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>タグ（カンマ区切りで複数登録）<input id="p_tags" value="${esc(tagInputValue(p))}"></label>`;modal(`<h2>作品${id?'編集':'追加'}</h2><form data-dirty="false" oninput="this.dataset.dirty='true'">${group('基本情報',basic)}${group('関連情報','<p class="meta">作品が基準になるため、関連データは各一覧から追加します。</p>')}${group('制作情報','<p class="meta">制作状態は管理情報で設定します。</p>')}${group('管理情報',management)}<p class="meta">作成日時：${esc(p.createdAt||'自動保存')} / 更新日時：${esc(p.updatedAt||'自動更新')}</p><button type="button" onclick="saveProject('${id||''}')">保存</button></form>`)}


// Version 0.6 dashboard, tasks, progress, and Universe
const PROGRESS_FIELDS=['setting','script','image','video','music','edit','publish'];
const PROGRESS_LABELS={setting:'設定',script:'台本',image:'画像',video:'動画',music:'音楽',edit:'編集',publish:'公開'};
const UNIVERSE_COLLECTIONS=['projects','episodes','scenes','characters','worlds','terms','timelines','ideas'];
const UNIVERSE_TYPES={projects:'project',episodes:'episode',scenes:'scene',characters:'character',worlds:'world',terms:'term',timelines:'timeline',ideas:'idea'};
Object.assign(TYPE_LABELS,{task:'今日やること'});
function clampPercent(v){v=Number(v);return Number.isFinite(v)?Math.max(0,Math.min(100,Math.round(v))):0}
function ensureV06(){state.tasks=Array.isArray(state.tasks)?state.tasks:[];state.progress=state.progress||{manualAdjustments:{}};state.progress.manualAdjustments=state.progress.manualAdjustments||{};state.lastLocation={projectId:state.activeContext?.projectId||'',view:(location.hash||'#home').slice(1)||'home',episodeId:state.activeContext?.episodeId||'',sceneId:'',characterId:'',openedAt:now(),...(state.lastLocation||{})};state.universeSettings={visibleTypes:{project:true,episode:true,scene:true,character:true,world:true,term:true,timeline:true,idea:true},zoom:1,panX:0,panY:0,limit:80,...(state.universeSettings||{})};state.universeSettings.visibleTypes={project:true,episode:true,scene:true,character:true,world:true,term:true,timeline:true,idea:true,...(state.universeSettings.visibleTypes||{})};}
ensureV06();
function recordLastLocation(extra={}){ensureV06();const p=currentProject(),e=currentEpisode();state.lastLocation={...state.lastLocation,projectId:p?.id||state.lastLocation.projectId||'',view:(location.hash||'#home').slice(1)||'home',episodeId:e?.id||'',openedAt:now(),...extra};saveState()}
const originalSetView=setView;setView=function(v){location.hash=v;recordLastLocation({view:v});render()}
const originalSelectContext=selectContext;selectContext=function(projectId,episodeId){originalSelectContext(projectId,episodeId);recordLastLocation({projectId,episodeId:state.activeContext?.episodeId||''})}
function openLastLocation(){const l=state.lastLocation||{};if(l.projectId)state.activeContext.projectId=l.projectId;if(l.episodeId)state.activeContext.episodeId=l.episodeId;if(l.sceneId){setView('scenes');setTimeout(()=>openSceneDetail(l.sceneId),0)}else if(l.characterId){setView('characters');setTimeout(()=>openStoryDetail('characters',l.characterId),0)}else setView(l.view||'home')}
function itemProgress(item){const p=item.progress||{};return PROGRESS_FIELDS.reduce((sum,k)=>sum+clampPercent(p[k]),0)/PROGRESS_FIELDS.length}
function autoProjectProgress(projectId){const items=[...state.episodes.filter(x=>x.projectId===projectId&&!x.isArchived),...state.scenes.filter(x=>x.projectId===projectId&&!x.isArchived)];const base=items.length?items.reduce((a,x)=>a+itemProgress(x),0)/items.length:itemProgress(state.projects.find(x=>x.id===projectId)||{});const adj=Number(state.progress?.manualAdjustments?.[projectId]||0);return clampPercent(base+adj)}
function progressBars(item){return `<div class="progress-grid">${PROGRESS_FIELDS.map(k=>`<label>${PROGRESS_LABELS[k]}<input type="number" min="0" max="100" id="pr_${k}" value="${clampPercent(item.progress?.[k])}"></label>`).join('')}</div>`}
function saveProgressFor(item){item.progress=item.progress||{};PROGRESS_FIELDS.forEach(k=>item.progress[k]=clampPercent($('#pr_'+k)?.value));touch(item)}
function projectDashboardView(){const p=currentProject();if(!p)return requireProject('projects');return `<h1>作品ダッシュボード：${esc(p.title)}</h1><section><h2>作品全体の進捗</h2><div class="big-progress"><span style="width:${autoProjectProgress(p.id)}%"></span></div><b>${autoProjectProgress(p.id)}%</b><label>手動調整（-100〜100）<input type="number" value="${state.progress.manualAdjustments[p.id]||0}" onchange="state.progress.manualAdjustments['${p.id}']=Number(this.value||0);saveState();render()"></label></section><section><h2>構成</h2><div class="stats">${Object.entries(projectCounts(p.id)).map(([k,v])=>`<div><b>${esc(collectionLabel(k))}</b><span>${v}件</span></div>`).join('')}</div></section>`}
function tasksForProject(){const p=currentProject();return (state.tasks||[]).filter(t=>!p||!t.projectId||t.projectId===p.id).sort((a,b)=>(a.completed-b.completed)||({高:0,中:1,低:2}[a.priority]-{高:0,中:1,低:2}[b.priority])||(a.dueDate||'9999').localeCompare(b.dueDate||'9999'))}
function tasksView(){const open=tasksForProject().filter(t=>!t.completed),done=tasksForProject().filter(t=>t.completed);return `<h1>今日やること</h1><button class="primary-action" onclick="editTask()">＋ 今日やることを追加</button><section><h2>未完了</h2>${open.map(taskRow).join('')||'<p class="meta">今日やることはありません。</p>'}</section><details><summary>完了済み（${done.length}件）</summary>${done.map(taskRow).join('')||'<p class="meta">完了済みはありません。</p>'}</details>`}
function taskRow(t){return `<div class="row"><span><b>${esc(t.title)}</b> <span class="tag">${esc(t.priority)}</span><br><small>${esc(t.content||'')} / 期限:${esc(t.dueDate||'未設定')} / 更新:${esc(t.updatedAt||'')}</small></span><span><button onclick="toggleTask('${t.id}')">${t.completed?'未完了に戻す':'完了'}</button><button onclick="editTask('${t.id}')">編集</button><button class="danger" onclick="deleteTask('${t.id}')">削除</button></span></div>`}
function editTask(id=''){const p=currentProject(),task=id?state.tasks.find(x=>x.id===id):{id:uid('task'),title:'',content:'',projectId:p?.id||'',episodeId:currentEpisode()?.id||'',sceneId:'',priority:'中',dueDate:'',completed:false,createdAt:now(),updatedAt:now()};modal(`<h2>今日やること${id?'編集':'追加'}</h2><form data-dirty="false" oninput="this.dataset.dirty='true'"><label>タイトル<input id="t_title" value="${esc(task.title)}"></label><label>内容<textarea id="t_content">${esc(task.content)}</textarea></label><label>関連作品<select id="t_projectId">${state.projects.map(x=>`<option value="${x.id}" ${task.projectId===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><label>関連話数<select id="t_episodeId"><option value="">なし</option>${state.episodes.filter(x=>x.projectId===(task.projectId||p?.id)).map(x=>`<option value="${x.id}" ${task.episodeId===x.id?'selected':''}>${esc(x.numberLabel||x.title)}</option>`).join('')}</select></label><label>関連シーン<select id="t_sceneId"><option value="">なし</option>${state.scenes.filter(x=>x.projectId===(task.projectId||p?.id)).map(x=>`<option value="${x.id}" ${task.sceneId===x.id?'selected':''}>${esc(storyTitle('scenes',x))}</option>`).join('')}</select></label><label>優先度<select id="t_priority">${['高','中','低'].map(x=>`<option ${task.priority===x?'selected':''}>${x}</option>`).join('')}</select></label><label>期限<input type="date" id="t_dueDate" value="${esc(task.dueDate)}"></label><label><input type="checkbox" id="t_completed" ${task.completed?'checked':''}>完了</label><p class="meta">作成:${esc(task.createdAt)} / 更新:${esc(task.updatedAt)}</p><button type="button" onclick="saveTask('${id}')">保存</button></form>`)}
function saveTask(id=''){let t=id?state.tasks.find(x=>x.id===id):{id:uid('task'),type:'task',createdAt:now()};['title','content','projectId','episodeId','sceneId','priority','dueDate'].forEach(k=>t[k]=$('#t_'+k).value);t.completed=$('#t_completed').checked;touch(t);if(!id)state.tasks.push(t);saveState();closeModal();render()}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(t){t.completed=!t.completed;touch(t);saveState();render()}}
function deleteTask(id){if(confirm('削除しますか？')){state.tasks=state.tasks.filter(x=>x.id!==id);saveState();render()}}
function universeNodes(){const p=currentProject(),q=(state.universeSettings.search||'').toLowerCase();let nodes=UNIVERSE_COLLECTIONS.flatMap(c=>(state[c]||[]).filter(x=>!x.isArchived&&(!p||x.projectId===p.id||x.id===p.id)).map((item,i)=>({id:item.id,collection:c,type:UNIVERSE_TYPES[c],title:continueTitle(c,item)||storyTitle(c,item),item}))).filter(n=>state.universeSettings.visibleTypes[n.type]&&(n.title.toLowerCase().includes(q)||!q));return nodes.slice(0,state.universeSettings.limit||80)}
function universeLinks(nodes){const ids=new Set(nodes.map(n=>n.id)),links=[];nodes.forEach(n=>{(n.item.relatedIds||[]).forEach(id=>ids.has(id)&&links.push([n.id,id]));if(n.collection==='episodes'&&ids.has(n.item.projectId))links.push([n.item.projectId,n.id]);if(n.item.episodeId&&ids.has(n.item.episodeId))links.push([n.item.episodeId,n.id])});return links}
function universeView(){const nodes=universeNodes(),links=universeLinks(nodes),unlinked=nodes.filter(n=>!links.some(l=>l.includes(n.id)));const pos=Object.fromEntries(nodes.map((n,i)=>[n.id,{x:80+(i%5)*180,y:80+Math.floor(i/5)*130}]));return `<h1>Universe</h1><div class="universe-tools"><input id="universeSearch" placeholder="検索" value="${esc(state.universeSettings.search||'')}" oninput="state.universeSettings.search=this.value;saveState();render()">${Object.entries(state.universeSettings.visibleTypes).map(([t,on])=>`<label><input type="checkbox" ${on?'checked':''} onchange="state.universeSettings.visibleTypes['${t}']=this.checked;saveState();render()">${esc(typeLabel(t))}</label>`).join('')}<button onclick="state.universeSettings.zoom=Math.max(.5,state.universeSettings.zoom-.1);saveState();render()">縮小</button><button onclick="state.universeSettings.zoom=Math.min(2,state.universeSettings.zoom+.1);saveState();render()">拡大</button></div><div class="universe" style="touch-action:none"><div class="universe-canvas" style="transform:scale(${state.universeSettings.zoom});transform-origin:0 0">${links.map(([a,b])=>{const A=pos[a],B=pos[b];if(!A||!B)return '';const dx=B.x-A.x,dy=B.y-A.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `<span class="u-line" style="left:${A.x+60}px;top:${A.y+35}px;width:${len}px;transform:rotate(${ang}deg)"></span>`}).join('')}${nodes.map(n=>`<button class="u-card" style="left:${pos[n.id].x}px;top:${pos[n.id].y}px" onclick="openUniverseCard('${n.collection}','${n.id}')"><small>${esc(typeLabel(n.type))}</small>${esc(n.title)}</button>`).join('')}</div></div><section><h2>関連がない項目</h2>${unlinked.map(n=>`<button onclick="openUniverseCard('${n.collection}','${n.id}')">${esc(typeLabel(n.type))}: ${esc(n.title)}</button>`).join('')||'<p class="meta">すべて何らかの関連があります。</p>'}</section>`}
function openUniverseCard(collection,id){recordLastLocation(collection==='scenes'?{sceneId:id}:collection==='characters'?{characterId:id}:{});if(collection==='projects'){selectContext(id,'');setView('projects')}else if(collection==='episodes'){const e=state.episodes.find(x=>x.id===id);selectContext(e.projectId,id);openEpisodeDetail(id)}else openStoryDetail(collection,id)}
const previousRender=render;render=function(){ensureV06();const v=(location.hash||'#home').slice(1);if(v!=='home')recordLastLocation({view:v});if(v==='universe')return shell(universeView());if(v==='tasks')return shell(tasksView());if(v==='progress')return shell(progressView());if(v==='projectDashboard')return shell(projectDashboardView());previousRender()}
const previousShell=shell;shell=function(main){previousShell(main);const nav=document.querySelector('nav');if(nav&&!nav.dataset.v06){nav.dataset.v06='1';nav.querySelector('button[onclick="setView(\'apps\')"]')?.insertAdjacentHTML('afterend',`<button onclick="setView('universe')">🌌 Universe</button>`);const mg=[...nav.querySelectorAll('summary')].find(x=>x.textContent.includes('管理'))?.parentElement;mg?.insertAdjacentHTML('afterbegin',`<button onclick="setView('tasks')">✅ 今日やること</button><button onclick="setView('progress')">📈 進捗</button>`);}}
function progressView(){const p=currentProject();if(!p)return requireProject('projects');const rows=[p,...projectItems('episodes'),...projectItems('scenes')];return `<h1>進捗</h1><section><h2>作品自動進捗: ${autoProjectProgress(p.id)}%</h2><div class="big-progress"><span style="width:${autoProjectProgress(p.id)}%"></span></div></section>${rows.map(x=>`<div class="card"><h3>${esc(x.title||x.numberLabel||storyTitle('scenes',x))}</h3><p>${Math.round(itemProgress(x))}%</p><button onclick="editProgress('${x.type||'project'}','${x.id}')">進捗編集</button></div>`).join('')}`}
function editProgress(type,id){const c=type==='episode'?'episodes':type==='scene'?'scenes':'projects',item=state[c].find(x=>x.id===id);modal(`<h2>進捗編集：${esc(continueTitle(c,item)||storyTitle(c,item))}</h2>${progressBars(item)}<button onclick="saveProgressModal('${c}','${id}')">保存</button>`)}
function saveProgressModal(c,id){const item=state[c].find(x=>x.id===id);saveProgressFor(item);saveState();closeModal();render()}
const previousOpenStoryDetail=openStoryDetail;openStoryDetail=function(collection,id){recordLastLocation(collection==='scenes'?{sceneId:id}:collection==='characters'?{characterId:id}:{});previousOpenStoryDetail(collection,id)}
const previousOpenSceneDetail=openSceneDetail;openSceneDetail=function(id){recordLastLocation({sceneId:id});previousOpenSceneDetail(id)}
const oldHomeView=homeView;homeView=function(){const p=currentProject(),last=state.lastLocation||{},recent=continueItems().filter(r=>!p||!r.item.projectId||r.item.projectId===p.id).slice(0,5),fav=state.favorites.filter(f=>!p||!f.projectId||f.projectId===p.id).slice(0,5),counts=p?projectCounts(p.id):null,tasks=tasksForProject().filter(t=>!t.completed).slice(0,5);return `<section class="hero"><h1>Nova Studio</h1><p>創る、繋がる、育っていく。</p><h2>制作ダッシュボード</h2><p>現在選択中の作品：${p?esc(p.title):'未選択'} <span class="ver">Version ${NOVA_VERSION}</span></p><div class="big-actions"><button onclick="openLastLocation()">続きから</button><button onclick="setView('projectDashboard')">作品ダッシュボード</button><button onclick="setView('universe')">Universe</button><button onclick="editTask()">今日やることを追加</button></div></section><section><h2>前回開いた項目</h2><p>${esc(last.view||'home')} / ${esc(last.openedAt||'未記録')}</p></section>${p?`<section><h2>作品全体の進捗</h2><div class="big-progress"><span style="width:${autoProjectProgress(p.id)}%"></span></div><b>${autoProjectProgress(p.id)}%</b></section><section><h2>作品内の件数</h2><div class="stats">${Object.entries(counts).map(([k,v])=>`<div><b>${esc(collectionLabel(k))}</b><span>${v}件</span></div>`).join('')}<div><b>今日やること</b><span>${tasksForProject().length}件</span></div></div></section>`:`<section class="empty-state"><h2>次の行動</h2><button onclick="editProject()">最初の作品を作成</button></section>`}<section><h2>今日やること</h2>${tasks.map(taskRow).join('')||'<p class="meta">今日やることはありません。</p><button onclick="editTask()">今日やることを追加</button>'}</section><section><h2>最近更新した5件</h2>${recent.map(r=>`<div class="row"><span>${esc(r.title)} / ${esc(typeLabel(r.type))} / 更新：${esc(r.updatedAt)}</span><button onclick="openContinue('${r.collection}','${r.item.id}')">開く</button></div>`).join('')||'<p>まだ更新された項目はありません</p>'}</section><section><h2>お気に入り5件</h2>${fav.map(f=>`<div class="row"><span>★ ${esc(f.title)}</span><button onclick="openFavorite('${f.id}')">開く</button></div>`).join('')||'<p>お気に入りはまだありません。</p>'}</section>${p&&counts.episodes===0?'<section class="empty-state"><button onclick="editEpisode()">最初の話数を追加</button></section>':''}${p&&counts.characters===0?'<section class="empty-state"><button onclick="editStoryItem(\'characters\')">最初のキャラクターを追加</button></section>':''}`}

render();

// Version 0.7 Vidu scene production management
const VIDU_STATUSES=['未着手','プロンプト作成','画像準備','生成中','完成','採用','保留'];
const VIDU_PROGRESS={未着手:0,プロンプト作成:20,画像準備:40,生成中:65,完成:85,採用:100,保留:50};
function defaultViduProduction(){const t=now();return{japanesePrompt:'',englishPrompt:'',negativePrompt:'',referenceImages:[],generatedVideos:[],projectUrl:'',model:'',aspectRatio:'',durationSeconds:'',creditsUsed:'',memo:'',status:'未着手',createdAt:t,updatedAt:t}}
function normalizeViduProduction(v={}){const base=defaultViduProduction(),out={...base,...(v||{})};out.referenceImages=Array.isArray(out.referenceImages)?out.referenceImages:parseLines(out.referenceImages);out.generatedVideos=Array.isArray(out.generatedVideos)?out.generatedVideos:parseLines(out.generatedVideos);out.status=VIDU_STATUSES.includes(out.status)?out.status:'未着手';out.createdAt=out.createdAt||out.updatedAt||now();out.updatedAt=out.updatedAt||out.createdAt;return out}
function ensureV07(){ensureV06();(state.scenes||[]).forEach(s=>{s.vidu=normalizeViduProduction(s.vidu);s.completionRate=sceneCompletionRate(s)})}
function parseLines(v){return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean)}
function viduProgress(v){return VIDU_PROGRESS[normalizeViduProduction(v).status]??0}
function sceneCompletionRate(scene){const baseProgress=scene.progress?PROGRESS_FIELDS.reduce((sum,k)=>sum+clampPercent(scene.progress?.[k]),0)/PROGRESS_FIELDS.length:0;const base=clampPercent(baseProgress||Number.parseInt(scene.completionRate)||0);const vp=viduProgress(scene.vidu);return Math.round(base?((base+vp)/2):vp)}
function viduCompletedVideos(v){return normalizeViduProduction(v).generatedVideos.length}
function viduCard(scene){const v=normalizeViduProduction(scene.vidu);return `<details class="vidu-card" open><summary><span>Vidu制作</span><span class="type-pill">${esc(v.status)}</span><span class="meta">完成動画：${viduCompletedVideos(v)} / 更新：${esc(v.updatedAt||'未記録')}</span></summary><div class="vidu-actions">${v.projectUrl?`<button onclick="openViduUrl('${scene.id}')">Viduを開く</button>`:''}<button onclick="editVidu('${scene.id}')">Viduを編集</button></div><div class="stats"><div><b>完成率</b><span>${viduProgress(v)}%</span></div><div><b>使用モデル</b><span>${esc(v.model||'未設定')}</span></div><div><b>アスペクト比</b><span>${esc(v.aspectRatio||'未設定')}</span></div><div><b>動画秒数</b><span>${esc(v.durationSeconds||'未設定')}</span></div><div><b>クレジット</b><span>${esc(v.creditsUsed||'未設定')}</span></div></div><section><h3>日本語プロンプト</h3><p>${esc(v.japanesePrompt||'未入力')}</p></section><section><h3>英語プロンプト</h3><p>${esc(v.englishPrompt||'未入力')}</p></section><section><h3>ネガティブプロンプト</h3><p>${esc(v.negativePrompt||'未入力')}</p></section><div class="vidu-lists"><section><h3>参照画像一覧</h3>${mediaList(v.referenceImages)}</section><section><h3>生成動画一覧</h3>${mediaList(v.generatedVideos)}</section></div><section><h3>制作メモ</h3><p>${esc(v.memo||'未入力')}</p></section><p class="meta">作成：${esc(v.createdAt)} / 更新：${esc(v.updatedAt)}</p></details>`}
function mediaList(items){return items.length?`<ul class="media-list">${items.map(x=>`<li>${isUrl(x)?`<a href="${esc(x)}" target="_blank" rel="noopener">${esc(x)}</a>`:esc(x)}</li>`).join('')}</ul>`:'<p class="meta">未登録</p>'}
function isUrl(x){return /^https?:\/\//i.test(String(x||''))}
function openViduUrl(sceneId){const s=state.scenes.find(x=>x.id===sceneId),url=s?.vidu?.projectUrl;if(url)window.open(url,'_blank','noopener')}
function editVidu(sceneId){const s=state.scenes.find(x=>x.id===sceneId);if(!s)return;const v=normalizeViduProduction(s.vidu);modal(`<h2>Vidu制作管理：${esc(storyTitle('scenes',s))}</h2><form data-dirty="false" oninput="this.dataset.dirty='true'">${group('プロンプト',`<label>日本語プロンプト<textarea id="v_japanesePrompt" rows="5">${esc(v.japanesePrompt)}</textarea></label><label>英語プロンプト<textarea id="v_englishPrompt" rows="5">${esc(v.englishPrompt)}</textarea></label><label>ネガティブプロンプト<textarea id="v_negativePrompt" rows="3">${esc(v.negativePrompt)}</textarea></label>`)}${group('素材・生成物',`<label>参照画像一覧（1行に1件）<textarea id="v_referenceImages" rows="5">${esc(v.referenceImages.join('\n'))}</textarea></label><label>生成動画一覧（1行に1件）<textarea id="v_generatedVideos" rows="5">${esc(v.generatedVideos.join('\n'))}</textarea></label><label>ViduプロジェクトURL<input id="v_projectUrl" value="${esc(v.projectUrl)}"></label>`)}${group('制作設定',`<label>状態<select id="v_status">${VIDU_STATUSES.map(x=>`<option ${v.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>使用モデル<input id="v_model" value="${esc(v.model)}"></label><label>アスペクト比<input id="v_aspectRatio" value="${esc(v.aspectRatio)}" placeholder="16:9 / 9:16 / 1:1"></label><label>動画秒数<input id="v_durationSeconds" inputmode="numeric" value="${esc(v.durationSeconds)}"></label><label>クレジット使用数<input id="v_creditsUsed" inputmode="decimal" value="${esc(v.creditsUsed)}"></label><label>制作メモ<textarea id="v_memo" rows="5">${esc(v.memo)}</textarea></label>`)}<p class="meta">作成日時：${esc(v.createdAt)} / 更新日時：${esc(v.updatedAt)} / 自動完成率：${viduProgress(v)}%</p><button type="button" onclick="saveVidu('${sceneId}')">保存</button></form>`)}
function saveVidu(sceneId){const s=state.scenes.find(x=>x.id===sceneId);if(!s)return;const before=JSON.stringify(s);const old=normalizeViduProduction(s.vidu);s.vidu={...old,japanesePrompt:$('#v_japanesePrompt').value,englishPrompt:$('#v_englishPrompt').value,negativePrompt:$('#v_negativePrompt').value,referenceImages:parseLines($('#v_referenceImages').value),generatedVideos:parseLines($('#v_generatedVideos').value),projectUrl:$('#v_projectUrl').value,model:$('#v_model').value,aspectRatio:$('#v_aspectRatio').value,durationSeconds:$('#v_durationSeconds').value,creditsUsed:$('#v_creditsUsed').value,memo:$('#v_memo').value,status:$('#v_status').value,createdAt:old.createdAt,updatedAt:now()};s.completionRate=sceneCompletionRate(s);touch(s);recordHistory(s,before);saveState();closeModal();openSceneDetail(sceneId);toast('Vidu制作を保存しました')}
const v07OpenSceneDetail=openSceneDetail;openSceneDetail=function(id){ensureV07();const s=state.scenes.find(x=>x.id===id);if(!s)return v07OpenSceneDetail(id);const scenes=state.scenes.filter(x=>x.episodeId===s.episodeId&&!x.isArchived).sort((a,b)=>(+a.sortOrder||0)-(+b.sortOrder||0));const i=scenes.findIndex(x=>x.id===id),prev=scenes[i-1],next=scenes[i+1];modal(`<h2>${esc(storyTitle('scenes',s))}</h2>${['sceneNumber','title','location','timeOfDay','summary','script','charactersText','termsText','worldsText','memo','completionRate','status'].map(f=>`<section><h3>${esc(FIELD_LABELS[f])}</h3><p>${esc(s[f]||'')}</p></section>`).join('')}${viduCard(s)}<p>${itemTagsHtml(s)}<br>${metaLine(s)}</p><div class="row"><button ${!prev?'disabled':''} onclick="openSceneDetail('${prev?.id||''}')">← 前のシーン</button><button ${!next?'disabled':''} onclick="openSceneDetail('${next?.id||''}')">次のシーン →</button></div><h3>関連リンク</h3>${relatedCards(s)}<button onclick="editStoryItem('scenes','${id}')">編集</button>`)};
const v07SaveStoryItem=saveStoryItem;saveStoryItem=function(collection,id=''){v07SaveStoryItem(collection,id);if(collection==='scenes'){ensureV07();saveState(true)}};
const v07ItemProgress=itemProgress;itemProgress=function(item){const base=v07ItemProgress(item);return item?.type==='scene'||state.scenes?.some(s=>s.id===item?.id)?Math.round((base+viduProgress(item.vidu))/2):base};
const v07SearchableItems=searchableItems;searchableItems=function(){ensureV07();return v07SearchableItems()};
const v07SearchAll=searchAll;searchAll=function(q,show=false){const box=show?$('#searchResults'):null;if(!q){if(box)box.innerHTML='';return}q=q.toLowerCase().trim();let res=searchableItems().filter(({collection,item,type,title})=>[title,item.memo,item.summary,item.description,typeLabel(type),type,item.subtitle,item.chapter,(item.tags||[]).join(' '),item.vidu?.japanesePrompt,item.vidu?.englishPrompt,item.vidu?.negativePrompt,item.vidu?.memo].join(' ').toLowerCase().includes(q));const html=res.map(({collection,item,type,title})=>`<div class="row"><span><b>${esc(typeLabel(type))}</b>：${esc(title)}<br><small>${itemTagsHtml(item)} ${metaLine(item)}</small></span><button onclick="openSearchResult('${collection}','${item.id}')">開く/選択</button></div>`).join('')||'<p>見つかりません。</p>';if(box)box.innerHTML=html;else modal(`<h2>検索結果</h2>${html}`)};
const v07Render=render;render=function(){ensureV07();v07Render()};
ensureV07();saveState(true);
