// Nova Studio ChatGPT bridge: copy/paste and JSON import are intentionally isolated for future API integration.
const CHATGPT_BRIDGE_COLLECTIONS=['projects','episodes','scenes','characters','worlds','terms','timelines','ideas','storyArchiveCards','images','videos','changeHistory','tasks'];
const CHATGPT_BRIDGE_LABELS={projects:'作品',episodes:'話数',scenes:'Scene',characters:'キャラクター',worlds:'世界観',terms:'用語',timelines:'年表',ideas:'アイデア',storyArchiveCards:'Story Archiveカード',images:'画像',videos:'動画',changeHistory:'変更履歴',tasks:'タスク'};
let chatgptPendingPreview=null;
function ensureChatGPTBridge(){state.chatgptBridge=state.chatgptBridge||{};state.chatgptBridge.history=Array.isArray(state.chatgptBridge.history)?state.chatgptBridge.history:[];state.chatgptBridge.backups=Array.isArray(state.chatgptBridge.backups)?state.chatgptBridge.backups:[]}
function chatgptCurrentScene(){const id=state.activeContext?.sceneId||state.lastLocation?.sceneId||nsOpenSceneId;return (state.scenes||[]).find(s=>s.id===id)||null}
function chatgptSceneAssets(s){if(!s)return{images:[],videos:[],audio:[]};const imgs=[...(s.illustrations||[]),...(s.vidu?.referenceImages||[]).map(id=>s.illustrations?.find(a=>a.id===id)||{id,title:id,location:id,type:'Vidu参照画像'})].filter(Boolean);const videos=[...(s.vidu?.generatedVideos||[]),...(s.videoEdit?.exports||[])];return{images:imgs.map(a=>({id:a.id,title:a.title||a.fileName||a.location||a.name,type:a.type||a.format||'',location:a.location||a.url||'',status:a.workStatus||a.adoptionStatus||'',memo:a.memo||''})),videos:videos.map(v=>({id:v.id,title:v.title||v.fileName||v.location,location:v.location||v.url||'',status:v.workStatus||v.adoptionStatus||'',memo:v.memo||''})),audio:(s.audioItems||[]).map(a=>({id:a.id,title:a.title||a.fileName||a.location,type:a.type||'',location:a.location||'',status:a.workStatus||a.adoptionStatus||'',memo:a.memo||''}))}}
function chatgptRelatedCards(s){if(!s)return[];return typeof sceneArchiveCards==='function'?sceneArchiveCards(s):(state.storyArchiveCards||[]).filter(c=>[...(s.relatedIds||[]),...(s.storyArchiveCardIds||[])].includes(c.id))}
function buildChatGPTPayload(question='',mode='json'){ensureChatGPTBridge();const p=currentProject(),e=currentEpisode(),s=chatgptCurrentScene(),cards=chatgptRelatedCards(s),assets=chatgptSceneAssets(s);const payload={format:'nova-chatgpt-context',schemaVersion:'1.0',appVersion:NOVA_VERSION,exportedAt:now(),request:{question,replyJsonFormat:{format:'nova-chatgpt-update',operations:{add:{scenes:[]},update:{scenes:[]},delete:{scenes:[]}},notes:'既存データを上書きせず、変更したい項目だけ operations.add/update/delete に入れてください。'}},context:{project:p||null,episode:e||null,scene:s||null,storyArchiveCards:cards,production:{projectStatus:p?.productionStatus||'',episodeStatus:e?.productionStatus||'',sceneStatus:s?.production?.status||s?.productionStage||'',sceneCompletionRate:s?sceneCompletionRateFull(s):''},assets}};if(mode==='text')return `【Nova Studio → ChatGPT 相談用】\n書き出し日時：${payload.exportedAt}\n\n相談したい内容：\n${question||'（ここに相談内容を書いてください）'}\n\n作品：${p?.title||'未選択'}\n話数：${e?.numberLabel||'未選択'} ${e?.subtitle||''}\nScene：${s?storyTitle('scenes',s):'未選択'}\n制作状況：${payload.context.production.sceneStatus||payload.context.production.episodeStatus||payload.context.production.projectStatus||'未設定'}\n\n関連Story Archiveカード：\n${cards.map(c=>`- ${c.title||c.id} / ${c.category||''}: ${c.body||c.summary||c.memo||''}`).join('\n')||'- なし'}\n\n使用画像：\n${assets.images.map(a=>`- ${a.title||a.id} / ${a.location||''} / ${a.status||''}`).join('\n')||'- なし'}\n\n使用動画：\n${assets.videos.map(a=>`- ${a.title||a.id} / ${a.location||''} / ${a.status||''}`).join('\n')||'- なし'}\n\n使用音声：\n${assets.audio.map(a=>`- ${a.title||a.id} / ${a.location||''} / ${a.status||''}`).join('\n')||'- なし'}\n\n更新用JSONが必要な場合は、format: nova-chatgpt-update と operations.add / operations.update / operations.delete で返してください。`;
return JSON.stringify(payload,null,2)}
async function copyChatGPTContext(){const question=$('#chatgpt_question')?.value||'',mode=$('#chatgpt_mode')?.value||'json',text=buildChatGPTPayload(question,mode);$('#chatgpt_out').value=text;try{await navigator.clipboard.writeText(text);recordChatGPTHistory('copy',{copiedText:text});toast('ChatGPT用コンテキストをコピーしました')}catch(e){$('#chatgpt_out').focus();$('#chatgpt_out').select();recordChatGPTHistory('copy',{copiedText:text,clipboardError:String(e)});toast('クリップボードへ自動コピーできません。手動でコピーしてください')}}
function recordChatGPTHistory(kind,extra={}){ensureChatGPTBridge();const p=currentProject(),e=currentEpisode(),s=chatgptCurrentScene();state.chatgptBridge.history.unshift({id:uid('chatgpt'),kind,createdAt:now(),projectId:p?.id||'',projectTitle:p?.title||'',episodeId:e?.id||'',episodeTitle:e?[e.numberLabel,e.subtitle].filter(Boolean).join(' '):'',sceneId:s?.id||'',sceneTitle:s?storyTitle('scenes',s):'',...extra});state.chatgptBridge.history=state.chatgptBridge.history.slice(0,100);saveState(true)}
function normalizeChatGPTUpdate(raw){const obj=typeof raw==='string'?JSON.parse(raw):raw;if(obj.format==='nova-chatgpt-update'&&obj.operations)return obj.operations;if(obj.operations)return obj.operations;const data=normalizeImportPayload?normalizeImportPayload(obj):obj;return{add:data||{},update:{},delete:{}}}
function previewChatGPTJson(){try{const operations=normalizeChatGPTUpdate($('#chatgpt_json').value);chatgptPendingPreview=buildChatGPTPreview(operations);$('#chatgpt_preview').innerHTML=chatgptPreviewHtml(chatgptPendingPreview)}catch(e){chatgptPendingPreview=null;$('#chatgpt_preview').innerHTML='<p class="empty-note">JSONを解析できません。現在のデータは変更していません。</p>';toast('不正なJSONです')}}
function buildChatGPTPreview(operations){const out={operations,add:[],update:[],delete:[]};CHATGPT_BRIDGE_COLLECTIONS.forEach(c=>{const addItems=Array.isArray(operations.add?.[c])?operations.add[c]:[];addItems.forEach(item=>out.add.push({collection:c,item}));const upItems=Array.isArray(operations.update?.[c])?operations.update[c]:[];upItems.forEach(item=>out.update.push({collection:c,item,current:(state[c]||[]).find(x=>x.id===item.id)||null}));const delItems=Array.isArray(operations.delete?.[c])?operations.delete[c]:[];delItems.forEach(item=>{const id=typeof item==='string'?item:item.id;out.delete.push({collection:c,item:{id},current:(state[c]||[]).find(x=>x.id===id)||null})})});return out}
function chatgptPreviewHtml(p){const rows=(items,type)=>items.map(x=>`<div class="row"><span><b>${esc(CHATGPT_BRIDGE_LABELS[x.collection]||x.collection)}</b>：${esc(x.item.title||x.item.numberLabel||x.current?.title||x.current?.numberLabel||x.item.id||'新規')}<br><small>ID:${esc(x.item.id||'自動採番')} ${type==='update'&&!x.current?' / 新規として追加候補':''} ${type==='delete'&&!x.current?' / 対象なし':''}</small></span></div>`).join('')||'<p class="meta">なし</p>';return `<section class="chatgpt-preview"><h3>追加</h3>${rows(p.add,'add')}<h3>更新</h3>${rows(p.update,'update')}<h3>削除</h3>${rows(p.delete,'delete')}<button class="primary-action" onclick="applyChatGPTJson()">確認して反映</button><button onclick="chatgptPendingPreview=null;$('#chatgpt_preview').innerHTML=''">キャンセル</button></section>`}
function makeChatGPTBackup(){ensureChatGPTBridge();const backup={id:uid('chatgptBackup'),createdAt:now(),data:JSON.parse(JSON.stringify(state))};state.chatgptBridge.backups.unshift({id:backup.id,createdAt:backup.createdAt,note:'ChatGPT JSON読み込み前の自動バックアップ'});state.chatgptBridge.backups=state.chatgptBridge.backups.slice(0,20);try{localStorage.setItem(`${STORAGE_KEY}_chatgpt_backup_${backup.id}`,JSON.stringify(backup))}catch(e){console.warn(e)}return backup.id}
function applyChatGPTJson(){if(!chatgptPendingPreview)return toast('先にプレビューを作成してください');if(!confirm('プレビュー内容を反映します。反映前に自動バックアップを作成します。よろしいですか？'))return;const backupId=makeChatGPTBackup(),p=chatgptPendingPreview;CHATGPT_BRIDGE_COLLECTIONS.forEach(c=>{state[c]=state[c]||[];(p.operations.add?.[c]||[]).forEach(raw=>{let x=COLLECTION_TYPE_MAP[c]?normalizeCommonItem({...raw,id:raw.id||uid(COLLECTION_TYPE_MAP[c])},COLLECTION_TYPE_MAP[c]):{...raw,id:raw.id||uid(c)};state[c].push(x)});(p.operations.update?.[c]||[]).forEach(raw=>{const i=state[c].findIndex(x=>x.id===raw.id);if(i>=0)state[c][i]={...state[c][i],...raw,updatedAt:now()};else state[c].push(COLLECTION_TYPE_MAP[c]?normalizeCommonItem({...raw,id:raw.id||uid(COLLECTION_TYPE_MAP[c])},COLLECTION_TYPE_MAP[c]):{...raw,id:raw.id||uid(c)})});(p.operations.delete?.[c]||[]).forEach(raw=>{const id=typeof raw==='string'?raw:raw.id;state[c]=state[c].filter(x=>x.id!==id)})});recordChatGPTHistory('import',{importedJson:$('#chatgpt_json').value,backupId,summary:{add:p.add.length,update:p.update.length,delete:p.delete.length}});chatgptPendingPreview=null;state=mergeDefaults(state);saveState(true);render();toast('ChatGPT更新JSONを反映しました')}
function chatgptHistoryHtml(){ensureChatGPTBridge();return state.chatgptBridge.history.slice(0,30).map(h=>`<div class="row"><span><b>${h.kind==='copy'?'送信コピー':'JSON読込'}</b> ${esc(h.createdAt)}<br><small>${esc(h.projectTitle||'作品未選択')} / ${esc(h.episodeTitle||'話数未選択')} / ${esc(h.sceneTitle||'Scene未選択')}${h.summary?` / 追加${h.summary.add} 更新${h.summary.update} 削除${h.summary.delete}`:''}</small></span></div>`).join('')||'<p class="meta">連携履歴はまだありません。</p>'}
function chatgptBridgeView(){ensureChatGPTBridge();return `<h1>ChatGPT連携</h1><section><h2>Nova StudioからChatGPTへ</h2><p class="meta">直接同期ではなく、コピー＆貼り付けで安全に相談できます。</p><label>相談したい内容<textarea id="chatgpt_question" rows="5" placeholder="ChatGPTに相談したいことを書いてください"></textarea></label><label>形式<select id="chatgpt_mode"><option value="json">JSON</option><option value="text">文章</option></select></label><button class="primary-action" onclick="copyChatGPTContext()">ChatGPT用にコピー</button><textarea id="chatgpt_out" rows="14" readonly placeholder="コピー内容がここに表示されます"></textarea></section><section><h2>ChatGPTからNova Studioへ</h2><p class="meta">ChatGPTが返した更新用JSONを貼り付け、追加・更新・削除を確認してから反映します。</p><textarea id="chatgpt_json" rows="12" placeholder='{"format":"nova-chatgpt-update","operations":{"add":{},"update":{},"delete":{}}}'></textarea><button onclick="previewChatGPTJson()">JSONを確認</button><div id="chatgpt_preview"></div></section><section><h2>連携履歴</h2>${chatgptHistoryHtml()}</section>`}
const chatgptOldConsultView=consultView;consultView=function(){return chatgptBridgeView()+`<section><h2>従来のノヴァ相談</h2>${chatgptOldConsultView()}</section>`}
const chatgptOldRender=render;render=function(){ensureChatGPTBridge();const v=(location.hash||'#home').slice(1);if(v==='chatgpt')return shell(chatgptBridgeView());return chatgptOldRender()}
const chatgptOldShell=shell;shell=function(main){chatgptOldShell(main);const nav=document.querySelector('nav');if(nav&&!nav.dataset.chatgpt){nav.dataset.chatgpt='1';nav.querySelector('button[onclick="setView(\'consult\')"]')?.insertAdjacentHTML('afterend',`<button onclick="setView('chatgpt')">🤝 ChatGPT連携</button>`)}}
const chatgptOldOpenSceneDetail=openSceneDetail;openSceneDetail=function(id){chatgptOldOpenSceneDetail(id);$('#modalBody .scene-actions')?.insertAdjacentHTML('afterbegin',`<button class="primary-action" onclick="setView('chatgpt');setTimeout(()=>copyChatGPTContext(),0)">ChatGPT用にコピー</button>`)}
ensureChatGPTBridge();saveState(true);render();
