const NOVA_VERSION='0.2.9',SCHEMA_VERSION='2.0',APP_NAME='Nova Studio';
const PRODUCTION_STATUSES=['構想中','設定制作中','台本制作中','絵コンテ制作中','映像制作中','公開中','休止中','完結','保留'];
const ITEM_STATUSES=['確定','仮設定','検討中','保留','要確認'];
const STORY_ARCHIVE_CATEGORIES=['概要','世界観','キャラクター','時系列','用語','場所','背景','アイテム','小物','組織・種族','エピソード','台本','アイデア','伏線','変更履歴','作品設定'];
const STORY_ARCHIVE_STATUSES=['確定','仮設定','検討中','保留'];
const COMMON_ITEM_TYPES={PROJECT:'project',EPISODE:'episode',TASK:'task',CHARACTER:'character',WORLD:'world',TERM:'term',IMAGE:'image',VIDEO:'video',IDEA:'idea',SCENE:'scene',TIMELINE:'timeline',HISTORY:'history',STORY_ARCHIVE_CARD:'storyArchiveCard',APP:'app'};
const COMMON_COLLECTIONS=['projects','episodes','tasks','characters','worlds','terms','images','videos','ideas','scenes','timelines','changeHistory','storyArchiveCards'];
const COLLECTION_TYPE_MAP={projects:COMMON_ITEM_TYPES.PROJECT,episodes:COMMON_ITEM_TYPES.EPISODE,tasks:COMMON_ITEM_TYPES.TASK,characters:COMMON_ITEM_TYPES.CHARACTER,worlds:COMMON_ITEM_TYPES.WORLD,terms:COMMON_ITEM_TYPES.TERM,images:COMMON_ITEM_TYPES.IMAGE,videos:COMMON_ITEM_TYPES.VIDEO,ideas:COMMON_ITEM_TYPES.IDEA,scenes:COMMON_ITEM_TYPES.SCENE,timelines:COMMON_ITEM_TYPES.TIMELINE,changeHistory:COMMON_ITEM_TYPES.HISTORY,storyArchiveCards:COMMON_ITEM_TYPES.STORY_ARCHIVE_CARD,apps:COMMON_ITEM_TYPES.APP};
function commonItemFields(type,title='',time=now()){return{type,title,createdAt:time,updatedAt:time,status:'仮設定',tags:[],favorite:false,memo:'',relatedIds:[]}}
function normalizeCommonItem(item,type){const t=item.createdAt||item.updatedAt||now();return{...commonItemFields(item.type||type,item.title||item.name||item.numberLabel||'',t),...item,type:item.type||type,title:item.title||item.name||item.numberLabel||'',createdAt:t,updatedAt:item.updatedAt||t,status:ITEM_STATUSES.includes(item.status)?item.status:'仮設定',tags:Array.isArray(item.tags)?item.tags:String(item.tags||'').split(',').map(x=>x.trim()).filter(Boolean),favorite:Boolean(item.favorite),memo:item.memo||'',relatedIds:Array.isArray(item.relatedIds)?item.relatedIds:[]}}
const DEFAULT_APPS=[
{...commonItemFields(COMMON_ITEM_TYPES.APP,'ノヴァ物語制作室'),id:'storyArchive',name:'ノヴァ物語制作室',subtitle:'Story Archive',description:'設定、キャラクター、世界観、台本、時系列、アイデア、変更履歴を管理します。',url:'',enabled:true,available:true,openInNewTab:false,version:'',memo:'',sortOrder:1,lastOpenedAt:''},
{...commonItemFields(COMMON_ITEM_TYPES.APP,'AIアニメ制作ダッシュボード'),id:'productionDashboard',name:'AIアニメ制作ダッシュボード',subtitle:'Production Dashboard',description:'各話の制作工程、進捗、作業内容、完成状況を管理します。',url:'',enabled:true,available:true,openInNewTab:false,version:'',memo:'',sortOrder:2,lastOpenedAt:''},
{...commonItemFields(COMMON_ITEM_TYPES.APP,'Viduプロンプト構成ツール'),id:'promptStudio',name:'Viduプロンプト構成ツール',subtitle:'Prompt Studio',description:'Vidu用の日本語・英語プロンプト、キャラクター、画風、場面テンプレートを管理します。',url:'',enabled:true,available:true,openInNewTab:false,version:'',memo:'',sortOrder:3,lastOpenedAt:''},
{...commonItemFields(COMMON_ITEM_TYPES.APP,'歌詞・MIDI制作補助'),id:'musicStudio',name:'歌詞・MIDI制作補助',subtitle:'Music Studio',description:'歌詞のひらがな変換、MIDI確認、音符への歌詞割り付けを行います。',url:'',enabled:true,available:true,openInNewTab:false,version:'',memo:'',sortOrder:4,lastOpenedAt:''},
{...commonItemFields(COMMON_ITEM_TYPES.APP,'Asset Library'),id:'assetLibrary',name:'Asset Library',subtitle:'素材台帳',description:'画像、動画、音声、ロゴ、PSDなどの保存場所を管理します。',url:'',enabled:false,available:false,openInNewTab:false,version:'',memo:'',sortOrder:5,lastOpenedAt:''},
{...commonItemFields(COMMON_ITEM_TYPES.APP,'Voice Studio'),id:'voiceStudio',name:'Voice Studio',subtitle:'音声管理',description:'キャラクターの声、音声モデル、収録素材を管理します。',url:'',enabled:false,available:false,openInNewTab:false,version:'',memo:'',sortOrder:6,lastOpenedAt:''},
{...commonItemFields(COMMON_ITEM_TYPES.APP,'Planner'),id:'planner',name:'Planner',subtitle:'制作予定',description:'今日やること、今週の作業、締切、優先度を管理します。',url:'',enabled:false,available:false,openInNewTab:false,version:'',memo:'',sortOrder:7,lastOpenedAt:''}];
function now(){return new Date().toISOString().slice(0,16).replace('T',' ')}
function uid(prefix){return prefix+'_'+(crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2))}
function project(id,title,sortOrder){let t=now();return{...commonItemFields(COMMON_ITEM_TYPES.PROJECT,title,t),id,title,reading:'',shortName:'',englishTitle:'',genre:'',summary:'',productionStatus:'構想中',status:'仮設定',themeColor:'#22b8c7',tags:[],sortOrder,isArchived:false,createdAt:t,updatedAt:t}}
function episode(id,projectId,numberLabel,sortOrder){let t=now();return{...commonItemFields(COMMON_ITEM_TYPES.EPISODE,numberLabel,t),id,projectId,numberLabel,subtitle:'',chapter:'',summary:'',productionStatus:'構想中',status:'仮設定',tags:[],sortOrder,isArchived:false,createdAt:t,updatedAt:t}}
function initialData(){let t=now();return{appName:APP_NAME,schemaVersion:SCHEMA_VERSION,appVersion:NOVA_VERSION,projects:[project('project_tia_nova','ティア・ノヴァのAIアニメ制作日誌',1),project('project_dream_architect','ドリームアーキテクト',2),project('project_rakurima_tale','ラクリマテイル',3),project('project_toikapu','といかぷ',4)],episodes:[episode('episode_tia_nova_all','project_tia_nova','作品全体',1),episode('episode_tia_nova_unclassified','project_tia_nova','未分類',2),episode('episode_tia_nova_000','project_tia_nova','第0話',3),episode('episode_tia_nova_001','project_tia_nova','第1話',4),episode('episode_dream_all','project_dream_architect','作品全体',1),episode('episode_dream_unclassified','project_dream_architect','未分類',2),episode('episode_rakurima_all','project_rakurima_tale','作品全体',1),episode('episode_rakurima_unclassified','project_rakurima_tale','未分類',2),episode('episode_toikapu_all','project_toikapu','作品全体',1),episode('episode_toikapu_unclassified','project_toikapu','未分類',2)],apps:structuredClone(DEFAULT_APPS),characters:[],worlds:[],terms:[],images:[],videos:[],ideas:[],scenes:[],timelines:[],tasks:[],viduTemplates:[],viduCharacterSettings:[],nova:{consultations:[],recentOpened:[],recommendationState:{}},progress:{manualAdjustments:{}},lastLocation:{projectId:'project_tia_nova',view:'home',episodeId:'episode_tia_nova_all',sceneId:'',characterId:'',openedAt:t},universeSettings:{visibleTypes:{project:true,episode:true,scene:true,character:true,world:true,term:true,timeline:true,idea:true},zoom:1,panX:0,panY:0,limit:80},changeHistory:[],storyArchiveCards:[],activeContext:{projectId:'project_tia_nova',episodeId:'episode_tia_nova_all',updatedAt:t},favorites:[],recentItems:[],settings:{theme:'light',fontSize:'normal',cardSize:'normal',recentLimit:10,favoriteLimit:10,dateFormat:'YYYY-MM-DD HH:mm',defaultOpenInNewTab:false,confirmBeforeOpen:false,saveHistory:true,autoSave:true,confirmOnDelete:true},backupStatus:{lastExportedAt:'',lastImportedAt:''},importCenter:{history:[]},createdAt:t,updatedAt:t}}
