function currentProject(){return state.projects.find(p=>p.id===state.activeContext.projectId)||null}
function currentEpisode(){return state.episodes.find(e=>e.id===state.activeContext.episodeId&&e.projectId===currentProject()?.id)||state.episodes.find(e=>e.projectId===currentProject()?.id)||null}
function dashboardApp(){return state.apps.find(a=>a.id==='productionDashboard')||null}
function buildAppUrl(app){try{const u=new URL(app.url,location.href);const p=currentProject(),e=currentEpisode();if(p?.id)u.searchParams.set('project',p.id);if(e?.id)u.searchParams.set('episode',e.id);u.searchParams.set('source','nova-studio');const ret=location.href;if(ret.length<300)u.searchParams.set('returnUrl',ret);return u.toString()}catch{return ''}}
function openDashboardSettings(){closeModal();setView('settings');setTimeout(()=>document.getElementById('productionDashboardUrl')?.focus(),0)}
function showDashboardUrlMissing(){modal(`<h2>AIアニメ制作ダッシュボード</h2><p class="empty-note">AIアニメ制作ダッシュボードのURLが登録されていません</p><p class="meta">設定画面でURLを登録すると、現在選択中の作品ID・話数IDをURLパラメータとして渡して開けます。</p><button class="primary-action" onclick="openDashboardSettings()">設定画面を開く</button>`)}
function openProductionDashboard(){return openApp('productionDashboard')}
function openApp(appId,urlOverride){const app=state.apps.find(a=>a.id===appId);if(!app||!app.available||!app.enabled)return toast('このアプリは今後追加予定です。');if(!app.url&&!urlOverride){if(appId==='productionDashboard')return showDashboardUrlMissing();return toast('このアプリのURLがまだ登録されていません。設定画面から登録してください。')}const url=urlOverride||buildAppUrl(app);if(!url)return toast('URLを確認してください。');if(state.settings.confirmBeforeOpen&&!confirm(`${app.name}を開きますか？`))return;const t=now(),p=currentProject(),e=currentEpisode();app.lastOpenedAt=t;if(state.settings.saveHistory){const key=[app.id,p?.id,e?.id].join('|');let r=state.recentItems.find(x=>x.key===key);if(!r){r={id:uid('recent'),key,appId:app.id,projectId:p?.id||'',episodeId:e?.id||'',title:app.name,subtitle:'',url,openedAt:t};state.recentItems.unshift(r)}Object.assign(r,{projectName:p?.title||'',episodeLabel:e?.numberLabel||'',url,openedAt:t});state.recentItems.sort((a,b)=>b.openedAt.localeCompare(a.openedAt));state.recentItems=state.recentItems.slice(0,50)}saveState(true);render();(app.openInNewTab||state.settings.defaultOpenInNewTab)?window.open(url,'_blank','noopener'):window.location.href=url}
function selectContext(projectId,episodeId){const ep=state.episodes.find(e=>e.id===episodeId&&e.projectId===projectId)||state.episodes.find(e=>e.projectId===projectId&&e.numberLabel==='作品全体')||state.episodes.find(e=>e.projectId===projectId);state.activeContext={projectId,episodeId:ep?.id||'',updatedAt:now()};saveState();render()}
