const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const plain=value=>JSON.parse(JSON.stringify(value));

function load(){const window={crypto:{randomUUID:(()=>{let i=0;return()=>`quantize-id-${++i}`})()}};window.window=window;window.globalThis=window;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-editor.js'),'utf8'),window);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-selection.js'),'utf8'),window);return window}
function source(){const note=(id,startTick,extra={})=>({id,pitch:60,startTick,durationTicks:240,velocity:80,...extra});return{projectId:'external-quantize',midiData:{ppq:480,timeSignature:{numerator:4,denominator:4},editor:{measureCount:8,view:{quantizeEnabled:true,quantize:'1/16'}},tracks:[{id:'melody',part:'melody',notes:[note('shared',61)]},{id:'drums',part:'drums',channel:10,notes:[note('shared',181,{pitch:36})]},{id:'bass',part:'bass',notes:[note('shared',301,{pitch:43})]},{id:'external-melody',name:'Same',trackType:'midi-melodic',roleAssignment:'melody',notes:[note('shared',115),note('locked',181,{locked:true})]},{id:'external-drums',name:'Same',trackType:'midi-drums',roleAssignment:'drums',channel:10,notes:[note('shared',125,{pitch:38})]},{id:'external-bass',name:'Same',trackType:'midi-melodic',roleAssignment:'bass',notes:[note('shared',301,{pitch:43})]}]}}}
function harness(){const window=load(),core=window.MusicStudioEditor,selection=window.MusicStudioDynamicTrackSelection,session=core.createSession(source()),api={state:{midiEditor:session,midiMultiSelect:false,partialEditSession:null},editorHandleShortcut(){return false},editorApplyQuantize(){return core.quantizeSelectedStarts(session,session.view.quantize)},editorStartNoteDrag(){return true},editorDeleteNote(){return true}};assert.equal(selection.install(api,core,null),true);return{window,core,selection,session,api,track:id=>session.midiData.tracks.find(track=>track.id===id)}}
function select(h,trackId,noteIds=['shared']){assert.equal(h.core.selectTrackById(h.session,trackId),true);h.core.clearNoteSelection(h.session);for(const id of noteIds)h.core.selectNote(h.session,id,{additive:true});h.api.__externalNoteSelectionTrackId=trackId}

test('External Melody Drums and Bass Quantize only their exact Track ID with same names and Note IDs',()=>{for(const id of['external-melody','external-drums','external-bass']){const h=harness(),before=plain(h.session.midiData.tracks);select(h,id);const original=h.track(id).notes.find(note=>note.id==='shared'),noteId=original.id,result=h.api.editorApplyQuantize();assert.equal(result.ok,true);assert.equal(result.changed,true);assert.equal(h.track(id).notes.find(note=>note.id==='shared').startTick,Math.round(original.startTick/120)*120);assert.equal(h.track(id).notes.find(note=>note.id==='shared').id,noteId);for(const track of h.session.midiData.tracks)if(track.id!==id)assert.deepEqual(plain(track),before.find(item=>item.id===track.id),`${id} changed ${track.id}`)}});
test('Track switch Quantize targets only the new Current Exact Track',()=>{const h=harness();select(h,'external-melody');assert.equal(h.api.editorSelectTrack('external-drums'),true);h.core.selectNote(h.session,'shared');h.api.__externalNoteSelectionTrackId='external-drums';const melody=plain(h.track('external-melody').notes);assert.equal(h.api.editorApplyQuantize().changed,true);assert.equal(h.track('external-drums').notes.find(note=>note.id==='shared').startTick,120);assert.deepEqual(plain(h.track('external-melody').notes),melody)});
test('stale External selection provenance is rejected and cleared after a Track change',()=>{const h=harness();select(h,'external-melody');h.core.selectTrackById(h.session,'external-drums');h.session.selectedNoteId='shared';h.session.selectedNoteIds=['shared'];const before=plain(h.session.midiData),undo=h.session.undo.length;assert.equal(h.api.editorApplyQuantize(),false);assert.deepEqual(plain(h.session.midiData),before);assert.equal(h.session.undo.length,undo);assert.deepEqual(Array.from(h.session.selectedNoteIds),[])});
test('External Quantize with no selection keeps the Core no-selection result',()=>{const h=harness();h.core.selectTrackById(h.session,'external-melody');const before=plain(h.session.midiData),result=h.api.editorApplyQuantize();assert.equal(result.ok,false);assert.equal(result.reason,'ノートを選択してください');assert.deepEqual(plain(h.session.midiData),before)});
test('External Quantize matches Core locked-note behavior and preserves note metadata',()=>{const h=harness();select(h,'external-melody',['shared','locked']);const locked=plain(h.track('external-melody').notes.find(note=>note.id==='locked')),open=plain(h.track('external-melody').notes.find(note=>note.id==='shared'));const result=h.api.editorApplyQuantize();assert.equal(result.count,1);assert.deepEqual(plain(h.track('external-melody').notes.find(note=>note.id==='locked')),locked);const changed=h.track('external-melody').notes.find(note=>note.id==='shared');assert.deepEqual([changed.id,changed.pitch,changed.durationTicks,changed.velocity],[open.id,open.pitch,open.durationTicks,open.velocity]);assert.equal(changed.startTick,120)});
test('External Quantize supports representative 1/4 1/8 1/16 and 1/32 Core grid values',()=>{for(const[resolution,step]of Object.entries({'1/4':480,'1/8':240,'1/16':120,'1/32':60})){const h=harness();h.track('external-melody').notes[0].startTick=271;h.session.view.quantize=resolution;select(h,'external-melody');assert.equal(h.api.editorApplyQuantize().changed,true);assert.equal(h.track('external-melody').notes.find(note=>note.id==='shared').startTick,Math.round(271/step)*step)}});
test('External Quantize Undo Redo and Save Reload preserve exact results',()=>{const h=harness();select(h,'external-melody');const original=plain(h.track('external-melody').notes);h.api.editorApplyQuantize();const quantized=plain(h.track('external-melody').notes);h.core.undo(h.session);assert.deepEqual(plain(h.track('external-melody').notes),original);h.core.redo(h.session);assert.deepEqual(plain(h.track('external-melody').notes),quantized);const saved=JSON.stringify(h.session.midiData),reloaded=h.core.createSession({projectId:'reload',midiData:JSON.parse(saved)});assert.equal(JSON.stringify(reloaded.midiData),saved);assert.deepEqual(plain(reloaded.midiData.tracks.find(track=>track.id==='external-melody').notes),quantized)});
test('Core Melody Drums and Bass retain selected-note Quantize behavior',()=>{for(const part of['melody','drums','bass']){const h=harness();h.core.selectPart(h.session,part);h.core.selectNote(h.session,'shared');const other=plain(h.session.midiData.tracks.filter(track=>track.part!==part));const result=h.api.editorApplyQuantize();assert.equal(result.changed,true);assert.equal(h.core.currentTrack(h.session).notes[0].startTick,Math.round(({melody:61,drums:181,bass:301}[part])/120)*120);assert.deepEqual(plain(h.session.midiData.tracks.filter(track=>track.part!==part)),other)}});
test('All MIDI Export remains all-track based with no External Track loss or duplication',()=>{const app=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8'),ids=source().midiData.tracks.map(track=>track.id);assert.match(app,/scope==='all'\|\|track\.part===scope/);assert.equal(new Set(ids).size,ids.length);assert.deepEqual(ids,['melody','drums','bass','external-melody','external-drums','external-bass'])});
