const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value));
function load(){const w={};w.window=w;for(const file of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),w,{filename:file});return{ai:w.MusicStudioAIWorkflow,core:w.MusicStudioEditor,locks:w.MusicStudioMeasureLocks}}
function project(){return{format:'music-studio-project',schemaVersion:'1.0',projectId:'synthetic-ai',revision:7,projectName:'Synthetic',musicalSettings:{bpm:100,timeSignature:{numerator:4,denominator:4},key:'C'},midiData:{version:1,ppq:480,tempo:100,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:960,numerator:3,denominator:4}],tempoMap:[{tick:0,bpm:100},{tick:777,bpm:80}],keySignatureMap:[{tick:0,sharps:0,minor:false}],markers:[{tick:0,text:'A'}],totalTick:7200,editor:{measureCount:5,lockedMeasures:[]},tracks:[{id:'lead',part:'melody',notes:[{id:'a',pitch:60,startTick:1000,durationTicks:120,velocity:90},{id:'b',pitch:64,startTick:1200,durationTicks:120,velocity:90}]},{id:'drums',part:'drums',notes:[]},{id:'bass',part:'bass',notes:[]}]}}}
function setup(){const{ai,core,locks}=load(),p=project(),s=core.createCoordinatedSession(p),w=ai.createWorkspace(p,{createdAt:'2026-10-02T00:00:00Z'});core.selectTrackById(s,'lead');core.setEditRange(s,{startMeasure:2,endMeasure:2});return{ai,core,locks,p,s,w}}
test('workspace is optional serializable state and does not mutate the project',()=>{const{ai,p}=setup(),before=plain(p),w=ai.createWorkspace(p);assert.deepEqual(p,before);assert.equal(ai.validateWorkspace(w).ok,true);assert.deepEqual(plain(ai.parseWorkspace(ai.serializeWorkspace(w),p)),plain(w))});
test('workspace rejects schema revision and project mismatches fail closed',()=>{const{ai,p,w}=setup();for(const bad of [{...w,version:2},{...w,requests:null},{...w,status:'magic'}])assert.equal(ai.validateWorkspace(bad).ok,false);assert.throws(()=>ai.parseWorkspace('{',p),/invalid-workspace-json/);assert.throws(()=>ai.parseWorkspace(ai.serializeWorkspace(w),{...p,revision:8}),/stale-workspace/)});
test('safe context identifies exact Track range notes tempo meter key and markers',()=>{const{ai,core,p,s}=setup(),c=ai.createSafeContext(p,s,core);assert.equal(c.target.trackId,'lead');assert.deepEqual(plain(c.target.range),{startMeasure:2,endMeasure:2,startTick:960,endTick:2400});assert.equal(c.music.tempoMap[1].tick,777);assert.equal(c.music.timeSignatureMap[0].tick,960);assert.equal(c.music.markers[0].text,'A')});
test('AI edit request reuses Partial Edit request snapshots',()=>{const{ai,core,p,s,w}=setup(),r=ai.createEditRequest(w,p,s,core,{instruction:'one semitone up',reason:'test'});assert.equal(r.partialRequest.trackId,'lead');assert.deepEqual(plain(r.partialRequest.targetNoteIds),['a','b']);assert.deepEqual(plain(r.sourceSnapshot.trackNotes),plain(r.partialRequest.notes));assert.equal(w.requests.length,1)});
test('unsafe network-like adapters are rejected',()=>{const{ai}=setup();for(const adapter of [{kind:'remote',generate(){}},{kind:'local',url:'https://example.com',generate(){}},{kind:'synthetic',apiKey:'secret',generate(){}}])assert.throws(()=>ai.localAdapter(adapter),/unsafe-adapter|network-adapter-forbidden/)});
test('deterministic synthetic adapter creates Preview without editing original',async()=>{const{ai,core,p,s,w}=setup(),before=plain(s.midiData),r=ai.createEditRequest(w,p,s,core,{instruction:'up'}),preview=await ai.runLocalAdapter(w,r.requestId,ai.syntheticPitchAdapter(1),core);assert.equal(preview.status,'preview');assert.deepEqual(plain(s.midiData),before);assert.deepEqual(plain(preview.proposal.result.changes.updates.map(n=>n.pitch)),[61,65])});
test('Reject leaves MIDI unchanged and records reason',async()=>{const{ai,core,p,s,w}=setup(),before=plain(s.midiData),r=ai.createEditRequest(w,p,s,core,{instruction:'up'});await ai.runLocalAdapter(w,r.requestId,ai.syntheticPitchAdapter(1),core);ai.rejectEdit(w,r.requestId,'not wanted');assert.deepEqual(plain(s.midiData),before);assert.equal(w.history[0].kind,'edit-rejected')});
test('Apply changes through existing guarded Partial Edit and one Undo restores it',async()=>{const{ai,core,p,s,w}=setup(),r=ai.createEditRequest(w,p,s,core,{instruction:'up'});await ai.runLocalAdapter(w,r.requestId,ai.syntheticPitchAdapter(1),core);ai.applyEdit(w,r.requestId,p,s,core);assert.deepEqual(plain(core.currentTrack(s).notes.map(n=>n.pitch)),[61,65]);core.undo(s);assert.deepEqual(plain(core.currentTrack(s).notes.map(n=>n.pitch)),[60,64]);core.redo(s);assert.deepEqual(plain(core.currentTrack(s).notes.map(n=>n.pitch)),[61,65])});
test('partial adoption applies only selected proposed notes',async()=>{const{ai,core,p,s,w}=setup(),r=ai.createEditRequest(w,p,s,core,{instruction:'up'});await ai.runLocalAdapter(w,r.requestId,ai.syntheticPitchAdapter(2),core);ai.applyEdit(w,r.requestId,p,s,core,{updateIds:['a'],addIds:[],deleteIds:[]});assert.deepEqual(plain(core.currentTrack(s).notes.map(n=>n.pitch)),[62,64]);assert.equal(w.requests[0].decision.partial,true)});
test('stale project revision and Track notes reject Apply',async()=>{for(const mode of ['project','track']){const{ai,core,p,s,w}=setup(),r=ai.createEditRequest(w,p,s,core,{instruction:'up'});await ai.runLocalAdapter(w,r.requestId,ai.syntheticPitchAdapter(),core);if(mode==='project')p.revision++;else core.currentTrack(s).notes[0].velocity=1;assert.throws(()=>ai.applyEdit(w,r.requestId,p,s,core),/stale-project|stale-track/)}});
test('range locks reject proposal atomically through existing guard',async()=>{const{ai,core,locks,p,s,w}=setup();const r=ai.createEditRequest(w,p,s,core,{instruction:'up'});await ai.runLocalAdapter(w,r.requestId,ai.syntheticPitchAdapter(),core);locks.addRangeLock(s,core,{trackId:'lead',startTick:1000,endTick:1100});const before=plain(s);assert.throws(()=>ai.applyEdit(w,r.requestId,p,s,core),/apply-rejected/);assert.deepEqual(plain(s),before)});
test('new song plan is Preview-only until Confirm',()=>{const{ai}=setup(),plan=ai.newSongPlan({title:'New',bpm:72,numerator:6,denominator:8,bars:24,key:'Am',mood:'quiet',genre:'piano',tracks:['melody','bass'],sections:[{label:'A',startMeasure:1,endMeasure:8}]});assert.equal(plan.status,'preview');const made=ai.confirmNewSongPlan(plan,{projectId:'new-id',createdAt:'2026-10-02T00:00:00Z'});assert.equal(made.projectInput.projectId,'new-id');assert.equal(made.midiData.totalTick,34560);assert.equal(made.midiData.tracks.length,2);assert.equal(made.aiOrigin.mode,'local-confirmed')});
test('new song plan validates tempo and clamps no hidden project state',()=>{const{ai}=setup();assert.throws(()=>ai.newSongPlan({bpm:0}),/invalid-bpm/);const plan=ai.newSongPlan({bpm:120,bars:8,tracks:[{id:'voice',role:'vocal',name:'Voice'}]});const made=ai.confirmNewSongPlan(plan);assert.equal(made.midiData.tracks[0].part,null);assert.deepEqual(plain(made.midiData.tracks[0].notes),[])});
for(const kind of ['melody','chord','section','arrangement','continuation','lyrics-structure'])test(`${kind} A/B/C candidates retain preview provenance and decisions`,()=>{const{ai,w}=setup(),set=ai.createCandidateSet(w,kind,{range:[1,4]},[{name:'A'},{name:'B'},{name:'C'}],{adapter:'synthetic-v1',reason:'fixture'});assert.deepEqual(plain(set.candidates.map(c=>c.candidateId)),['A','B','C']);ai.decideCandidate(w,set.setId,'B','adopt',{range:[2,3]});ai.decideCandidate(w,set.setId,'A','reject');assert.equal(w.candidateSets[0].candidates[1].status,'adopted');assert.deepEqual(plain(w.candidateSets[0].adopted[0].selection),{range:[2,3]});assert.equal(w.history.length,2)});
test('candidate validation prevents empty oversized and executable kinds',()=>{const{ai,w}=setup();for(const [kind,values] of [['edit',[{}]],['melody',[]],['melody',Array.from({length:27},()=>({}))]])assert.throws(()=>ai.createCandidateSet(w,kind,{},values),/invalid-/)});
test('workspace persistence survives memory save reopen JSON Backup and Restore as opaque optional data',async()=>{const{ai,p,w}=setup();const set=ai.createCandidateSet(w,'section',{},[{label:'A'}]);ai.decideCandidate(w,set.setId,'A','adopt');const stored={...plain(p),aiWorkspace:plain(w)},repo=new Map();repo.set(p.projectId,plain(stored));const reopened=plain(repo.get(p.projectId)),json=JSON.stringify(reopened),backup=JSON.stringify({projects:[reopened]}),restored=JSON.parse(backup).projects[0];for(const value of [reopened,JSON.parse(json),restored])assert.deepEqual(plain(value.aiWorkspace),plain(w));assert.deepEqual(plain(ai.parseWorkspace(ai.serializeWorkspace(restored.aiWorkspace),restored)),plain(w))});
test('runtime request and proposal objects never contain credential or network fields',async()=>{const{ai,core,p,s,w}=setup(),r=ai.createEditRequest(w,p,s,core,{instruction:'up'});await ai.runLocalAdapter(w,r.requestId,ai.syntheticPitchAdapter(),core);assert.doesNotMatch(JSON.stringify(w),/apiKey|credential|https?:|endpoint|fetch/)});
