'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-recording.js'),'utf8');
const selectionSource=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-selection.js'),'utf8');
const musicStudioSource=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8');
function track(id,extra={}){return{id,name:id,notes:[],...extra}}
function harness(tracks,selectedTrackId){
  const state={midiEditor:{midiData:{tracks},selectedTrackId,playheadTick:240},midiInput:{recording:false,recordingTrackId:null,starting:false,stopping:false,countingIn:false},melodyAudio:{playback:{playing:false}}};
  const core={getTrackById:(list,id)=>list.find(item=>item.id===id)||null,resolveTrackCapabilities:item=>({canRecordMidi:item?.trackType!=='audio'&&item?.trackType!=='unknown'}),resolveCoreTrackSlot:item=>item?.id?.startsWith('core-')?item.id.replace('core-',''):null};
  let startCalls=0,toggleCalls=0,stopCalls=0,playbackCalls=0,shortcutCalls=0;
  const api={__dynamicTrackSelectionInstalled:true,state,resolveCurrentTrackSelection:()=>{const item=core.getTrackById(tracks,state.midiEditor.selectedTrackId),slot=core.resolveCoreTrackSlot(item);return item?{id:item.id,name:item.name,kind:slot?'core':'external',coreSlot:slot,track:item,capabilities:core.resolveTrackCapabilities(item)}:null},editorStartMidiRecording:async()=>{startCalls++;state.midiInput.recording=true;state.midiInput.recordingTrackId=state.midiEditor.selectedTrackId;return{ok:true}},editorToggleMidiRecording:async()=>{toggleCalls++;return{ok:true}},editorStopTransport:()=>{stopCalls++;state.midiInput.recording=false;state.midiInput.countingIn=false;return{ok:true}},editorToggleMelodyPlayback:()=>{playbackCalls++;return{ok:true}},editorHandleShortcut:()=>{shortcutCalls++;return false}};
  const document={querySelector:()=>null};
  const window={MusicStudio:api,MusicStudioEditor:core,document,MutationObserver:class{observe(){}},addEventListener(){},setInterval,clearInterval};window.window=window;window.globalThis=window;
  vm.runInNewContext(source,{window,globalThis:window,setInterval,clearInterval});
  return{api,state,counts:()=>({startCalls,toggleCalls,stopCalls,playbackCalls,shortcutCalls})}
}
function event(key,extra={}){let prevented=false;return{key,code:extra.code||'',target:{closest:()=>null},preventDefault(){prevented=true},get prevented(){return prevented},...extra}}

test('recording adapter actually installs in the Dynamic Selection stack',()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b');assert.equal(h.api.__dynamicTrackRecordingInstalled,true);assert.equal(h.api.__dynamicTrackRecordingVersion,'1.0.1');assert.equal(typeof h.api.resolveRecordingDestination,'function')});
test('selected external melodic recording keeps the exact Track ID with duplicate display names and roles',async()=>{const tracks=[track('core-melody',{trackType:'midi-melodic',roleAssignment:'melody'}),track('external-a',{name:'Same Name',trackType:'midi-melodic',roleAssignment:'strings'}),track('external-b',{name:'Same Name',trackType:'midi-melodic',roleAssignment:'strings'})];const h=harness(tracks,'external-b');const result=await h.api.editorStartMidiRecording();assert.equal(result.ok,true);assert.equal(h.state.midiInput.recordingTrackId,'external-b');assert.equal(h.counts().startCalls,1)});
test('selected external drum recording routes by Track ID rather than Core Drums',async()=>{const h=harness([track('core-drums',{trackType:'midi-drums'}),track('external-drums',{trackType:'midi-drums'})],'external-drums');await h.api.editorStartMidiRecording();assert.equal(h.state.midiInput.recordingTrackId,'external-drums')});
test('external recording toggle starts through routed start and stops through existing Stop transport',async()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b');await h.api.editorToggleMidiRecording();assert.equal(h.state.midiInput.recording,true);assert.equal(h.state.midiInput.recordingTrackId,'external-b');assert.equal(h.counts().startCalls,1);await h.api.editorToggleMidiRecording();assert.equal(h.state.midiInput.recording,false);assert.equal(h.counts().stopCalls,1);assert.equal(h.counts().toggleCalls,0)});
test('Core Melody, Drums, and Bass keep the existing recording toggle path',async()=>{for(const id of ['core-melody','core-drums','core-bass']){const h=harness([track(id,{trackType:id==='core-drums'?'midi-drums':'midi-melodic'})],id);await h.api.editorToggleMidiRecording();assert.equal(h.counts().toggleCalls,1,`${id} should delegate`)}});
test('R shortcut reaches routed recording for both Core and External Tracks',async()=>{for(const id of ['core-melody','external-b']){const h=harness([track(id,{trackType:'midi-melodic'})],id),press=event('r',{code:'KeyR'});assert.equal(h.api.editorHandleShortcut(press),true);await new Promise(resolve=>setTimeout(resolve,0));assert.equal(press.prevented,true);if(id==='external-b'){assert.equal(h.state.midiInput.recordingTrackId,'external-b');assert.equal(h.counts().startCalls,1)}else assert.equal(h.counts().toggleCalls,1)}});
test('Space shortcut reaches current playback adapter and Enter returns playhead to start',()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b'),space=event(' ',{code:'Space'});assert.equal(h.api.editorHandleShortcut(space),true);assert.equal(space.prevented,true);assert.equal(h.counts().playbackCalls,1);const enter=event('Enter',{code:'Enter'});assert.equal(h.api.editorHandleShortcut(enter),true);assert.equal(enter.prevented,true);assert.equal(h.state.midiEditor.playheadTick,0)});
test('transport shortcuts remain blocked while typing composing repeating or modified',()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b');for(const press of [event('r',{code:'KeyR',repeat:true}),event('r',{code:'KeyR',isComposing:true}),event('r',{code:'KeyR',metaKey:true}),event('r',{code:'KeyR',target:{closest:()=>({})}})]){h.api.editorHandleShortcut(press);assert.equal(press.prevented,false)}assert.equal(h.counts().startCalls,0)});
test('recording adapter is explicitly capability-gated by canRecordMidi',async()=>{const h=harness([track('audio',{trackType:'audio'})],'audio'),result=await h.api.editorStartMidiRecording();assert.equal(result.reason,'recording-capability-required');assert.equal(h.counts().startCalls,0);assert.match(source,/canRecordMidi:capabilities\.canRecordMidi===true/)});
test('selection bridge no longer blocks recording but still blocks Correction and Partial Edit',()=>{const blocked=selectionSource.match(/const BLOCKED_EXTERNAL_ACTIONS=\[([\s\S]*?)\];/)?.[1]||'';assert.doesNotMatch(blocked,/editorToggleMidiRecording|editorStartMidiRecording/);assert.match(blocked,/editorApplyCorrection/);assert.match(blocked,/editorRunPartialEdit/)});
test('existing recording engine commits Stop notes through recordingTrackId and addNotesToTrack',()=>{assert.match(musicStudioSource,/targetTrackId=midi\.recordingTrackId/);assert.match(musicStudioSource,/editor\.addNotesToTrack\(state\.midiEditor,trackId,notes\)/)});
test('recording routing does not widen Correction, Partial Edit, roles, schema, or app version',()=>{assert.doesNotMatch(source,/editorApplyCorrection|editorRunPartialEdit|roleAssignment\s*=/);assert.match(musicStudioSource,/APP_VERSION='1\.4\.0'/);assert.match(musicStudioSource,/SCHEMA_VERSION='1\.0'/)});
