'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-recording.js'),'utf8');
const selectionSource=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-selection.js'),'utf8');
const musicStudioSource=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8');
function track(id,extra={}){return{id,name:id,notes:[],...extra}}
function harness(tracks,selectedTrackId){
  const state={midiEditor:{midiData:{tracks},selectedTrackId,playheadTick:240},midiInput:{recording:false,recordingTrackId:null,starting:false,stopping:false,countingIn:false},melodyAudio:{playback:{playing:false}}};
  const core={getTrackById:(list,id)=>list.find(item=>item.id===id)||null,resolveTrackCapabilities:item=>({canRecordMidi:item?.trackType!=='audio'&&item?.trackType!=='unknown'}),resolveCoreTrackSlot:item=>item?.id?.startsWith('core-')?item.id.replace('core-',''):null};
  let startCalls=0,toggleCalls=0,stopCalls=0,playbackCalls=0,shortcutCalls=0;
  const api={__dynamicTrackSelectionInstalled:true,state,resolveCurrentTrackSelection:()=>{const item=core.getTrackById(tracks,state.midiEditor.selectedTrackId),slot=core.resolveCoreTrackSlot(item);return item?{id:item.id,name:item.name,kind:slot?'core':'external',coreSlot:slot,track:item,capabilities:core.resolveTrackCapabilities(item)}:null},editorStartMidiRecording:async()=>{startCalls++;state.midiInput.recording=true;state.midiInput.recordingTrackId=state.midiEditor.selectedTrackId;return{ok:true}},editorToggleMidiRecording:async()=>{toggleCalls++;return{ok:true}},editorStopTransport:()=>{stopCalls++;state.midiInput.recording=false;state.midiInput.countingIn=false;return{ok:true}},editorToggleMelodyPlayback:()=>{playbackCalls++;return{ok:true}},editorHandleShortcut:()=>{shortcutCalls++;return false}};
  const document={querySelector:()=>null};const window={MusicStudio:api,MusicStudioEditor:core,document,MutationObserver:class{observe(){}},addEventListener(){},setInterval,clearInterval};window.window=window;window.globalThis=window;vm.runInNewContext(source,{window,globalThis:window,setInterval,clearInterval});return{api,state,counts:()=>({startCalls,toggleCalls,stopCalls,playbackCalls,shortcutCalls})}
}
function event(key,extra={}){let prevented=false;return{key,code:extra.code||'',target:{closest:()=>null},preventDefault(){prevented=true},get prevented(){return prevented},...extra}}
test('recording adapter actually installs in the Dynamic Selection stack',()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b');assert.equal(h.api.__dynamicTrackRecordingInstalled,true);assert.equal(h.api.__dynamicTrackRecordingVersion,'1.0.2')});
test('selected external melodic recording keeps exact Track ID with duplicate names and roles',async()=>{const tracks=[track('core-melody',{trackType:'midi-melodic',roleAssignment:'melody'}),track('external-a',{name:'Same Name',trackType:'midi-melodic',roleAssignment:'strings'}),track('external-b',{name:'Same Name',trackType:'midi-melodic',roleAssignment:'strings'})];const h=harness(tracks,'external-b');await h.api.editorStartMidiRecording();assert.equal(h.state.midiInput.recordingTrackId,'external-b')});
test('selected external drum recording routes by Track ID',async()=>{const h=harness([track('core-drums',{trackType:'midi-drums'}),track('external-drums',{trackType:'midi-drums'})],'external-drums');await h.api.editorStartMidiRecording();assert.equal(h.state.midiInput.recordingTrackId,'external-drums')});
test('external recording toggle starts routed and stops existing transport',async()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b');await h.api.editorToggleMidiRecording();assert.equal(h.state.midiInput.recording,true);await h.api.editorToggleMidiRecording();assert.equal(h.state.midiInput.recording,false);assert.equal(h.counts().stopCalls,1)});
test('Core Melody Drums Bass keep existing recording toggle',async()=>{for(const id of ['core-melody','core-drums','core-bass']){const h=harness([track(id,{trackType:id==='core-drums'?'midi-drums':'midi-melodic'})],id);await h.api.editorToggleMidiRecording();assert.equal(h.counts().toggleCalls,1)}});
test('R reaches routed recording for Core and External',async()=>{for(const id of ['core-melody','external-b']){const h=harness([track(id,{trackType:'midi-melodic'})],id),press=event('r',{code:'KeyR'});assert.equal(h.api.editorHandleShortcut(press),true);await new Promise(resolve=>setTimeout(resolve,0));if(id==='external-b')assert.equal(h.state.midiInput.recordingTrackId,'external-b');else assert.equal(h.counts().toggleCalls,1)}});
test('External Space uses dynamic playback while Core Space delegates to existing shortcut',()=>{const external=harness([track('external-b',{trackType:'midi-melodic'})],'external-b'),space=event(' ',{code:'Space'});assert.equal(external.api.editorHandleShortcut(space),true);assert.equal(external.counts().playbackCalls,1);assert.equal(external.counts().shortcutCalls,0);const core=harness([track('core-melody',{trackType:'midi-melodic'})],'core-melody'),coreSpace=event(' ',{code:'Space'});core.api.editorHandleShortcut(coreSpace);assert.equal(core.counts().shortcutCalls,1);assert.equal(core.counts().playbackCalls,0)});
test('Enter returns playhead to start',()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b'),enter=event('Enter',{code:'Enter'});assert.equal(h.api.editorHandleShortcut(enter),true);assert.equal(h.state.midiEditor.playheadTick,0)});
test('transport shortcuts remain blocked while typing composing repeating or modified',()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b');for(const press of [event('r',{code:'KeyR',repeat:true}),event('r',{code:'KeyR',isComposing:true}),event('r',{code:'KeyR',metaKey:true}),event('r',{code:'KeyR',target:{closest:()=>({})}})]){h.api.editorHandleShortcut(press);assert.equal(press.prevented,false)}assert.equal(h.counts().startCalls,0)});
test('recording adapter is capability-gated',async()=>{const h=harness([track('audio',{trackType:'audio'})],'audio'),result=await h.api.editorStartMidiRecording();assert.equal(result.reason,'recording-capability-required')});
test('selection bridge allows capability-gated recording and Correction but still blocks Partial Edit',()=>{const blocked=selectionSource.match(/const BLOCKED_EXTERNAL_ACTIONS=\[([\s\S]*?)\];/)?.[1]||'';assert.doesNotMatch(blocked,/editorToggleMidiRecording|editorStartMidiRecording|editorApplyCorrection/);assert.match(blocked,/editorRunPartialEdit/)});
test('existing recording engine commits Stop notes through recordingTrackId',()=>{assert.match(musicStudioSource,/targetTrackId=midi\.recordingTrackId/);assert.match(musicStudioSource,/editor\.addNotesToTrack\(state\.midiEditor,trackId,notes\)/)});
test('routing does not widen Correction Partial Edit roles schema or app version',()=>{assert.doesNotMatch(source,/editorApplyCorrection|editorRunPartialEdit|roleAssignment\s*=/);assert.match(musicStudioSource,/APP_VERSION='1\.4\.0'/);assert.match(musicStudioSource,/SCHEMA_VERSION='1\.0'/)});
