const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const plain=value=>JSON.parse(JSON.stringify(value));

function load(){const window={crypto:{randomUUID:(()=>{let i=0;return()=>`pointer-id-${++i}`})()}};window.window=window;window.globalThis=window;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-editor.js'),'utf8'),window);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-selection.js'),'utf8'),window);return window}
function source(){const note=(id,pitch,extra={})=>({id,pitch,startTick:120,durationTicks:240,velocity:80,...extra});return{projectId:'pointer-edit',midiData:{ppq:480,timeSignature:{numerator:4,denominator:4},editor:{measureCount:4,view:{snapEnabled:true,snap:'1/16'}},tracks:[{id:'melody',part:'melody',notes:[note('core-note',60)]},{id:'drums',part:'drums',notes:[note('core-note',36)]},{id:'bass',part:'bass',notes:[note('core-note',48)]},{id:'ext-a',name:'Same',trackType:'midi-melodic',roleAssignment:'melody',notes:[note('same-note',72),note('locked',75,{locked:true})]},{id:'ext-b',name:'Same',trackType:'midi-melodic',roleAssignment:'melody',notes:[note('same-note',76)]}]}}}
function harness(){const window=load(),core=window.MusicStudioEditor,selection=window.MusicStudioDynamicTrackSelection,session=core.createSession(source());let coreDrag=0,coreResize=0;const api={state:{midiEditor:session,midiMultiSelect:false,partialEditSession:null},editorHandleShortcut(){return false},editorStartNoteDrag(){coreDrag++;return'core-drag'},editorStartNoteResize(){coreResize++;return'core-resize'},editorMoveSelected(dt,dp){core.moveSelected(session,dt,dp);return true},editorResizeSelected(delta){core.resizeSelected(session,delta);return true},editorDeleteNote(){return true}};assert.equal(selection.install(api,core,null),true);const roll={dataset:{totalTicks:'1920',pitchMin:'0',pitchMax:'127'},getBoundingClientRect(){return{width:960,height:1280}},querySelectorAll(){return[]}},noteElement={style:{width:'12.5%'}},target={style:{translate:''},closest(selector){return selector==='.music-piano-roll'?roll:null},setPointerCapture(){}},resize={style:{},closest(selector){return selector==='.music-midi-note'?noteElement:selector==='.music-piano-roll'?roll:null},setPointerCapture(){}};return{window,core,selection,session,api,roll,target,resize,noteElement,track:id=>session.midiData.tracks.find(track=>track.id===id),get coreDrag(){return coreDrag},get coreResize(){return coreResize}}}
function beginMove(h,id='same-note'){return h.api.editorStartNoteDrag({button:0,currentTarget:h.target,clientX:100,clientY:100,pointerId:1,preventDefault(){}},id)}
function beginResize(h,id='same-note'){return h.api.editorStartNoteResize({currentTarget:h.resize,clientX:100,pointerId:2,preventDefault(){},stopPropagation(){}},id)}

test('External move pins exact Track ID and same Note ID without changing other External or Core Tracks',()=>{const h=harness();h.core.selectTrackById(h.session,'ext-a');const other=plain(h.track('ext-b').notes),cores=plain(h.session.midiData.tracks.slice(0,3));assert.equal(beginMove(h),true);h.target.onpointermove({clientX:220,clientY:90});h.target.onpointerup();assert.equal(h.track('ext-a').notes.find(note=>note.id==='same-note').startTick,360);assert.equal(h.track('ext-a').notes.find(note=>note.id==='same-note').pitch,73);assert.deepEqual(plain(h.track('ext-b').notes),other);assert.deepEqual(plain(h.session.midiData.tracks.slice(0,3)),cores);assert.equal(h.track('ext-a').notes.find(note=>note.id==='same-note').id,'same-note')});
test('External resize pins exact Track ID and same Note ID without changing other Tracks',()=>{const h=harness();h.core.selectTrackById(h.session,'ext-a');const other=plain(h.track('ext-b').notes),cores=plain(h.session.midiData.tracks.slice(0,3));assert.equal(beginResize(h),true);h.resize.onpointermove({clientX:220});h.resize.onpointerup();assert.equal(h.track('ext-a').notes.find(note=>note.id==='same-note').durationTicks,480);assert.deepEqual(plain(h.track('ext-b').notes),other);assert.deepEqual(plain(h.session.midiData.tracks.slice(0,3)),cores);assert.equal(h.track('ext-a').notes.find(note=>note.id==='same-note').id,'same-note')});
test('Track switch after pointerdown cancels stale move and clears gesture selection state',()=>{const h=harness();h.core.selectTrackById(h.session,'ext-a');const before=plain(h.session.midiData);beginMove(h);h.target.onpointermove({clientX:220,clientY:90});h.core.selectTrackById(h.session,'ext-b');h.target.onpointerup();assert.deepEqual(plain(h.session.midiData),before);assert.equal(h.api.__externalPointerGesture,null);assert.deepEqual(Array.from(h.session.selectedNoteIds),[])});
test('Selection change after pointerdown rejects stale resize',()=>{const h=harness();h.core.selectTrackById(h.session,'ext-a');const before=plain(h.session.midiData);beginResize(h);h.resize.onpointermove({clientX:220});h.core.clearNoteSelection(h.session);h.core.selectNote(h.session,'locked');h.resize.onpointerup();assert.deepEqual(plain(h.session.midiData),before);assert.equal(h.api.__externalPointerGesture,null);assert.deepEqual(Array.from(h.session.selectedNoteIds),[])});
test('pointercancel leaves MIDI unchanged and gesture state clean for move and resize',()=>{for(const kind of ['move','resize']){const h=harness();h.core.selectTrackById(h.session,'ext-a');const before=plain(h.session.midiData);if(kind==='move'){beginMove(h);h.target.onpointermove({clientX:220,clientY:90});h.target.onpointercancel()}else{beginResize(h);h.resize.onpointermove({clientX:220});h.resize.onpointercancel()}assert.deepEqual(plain(h.session.midiData),before);assert.equal(h.api.__externalPointerGesture,null);assert.deepEqual(Array.from(h.session.selectedNoteIds),[])}});
test('Locked External note rejects move and resize without mutation',()=>{const h=harness();h.core.selectTrackById(h.session,'ext-a');const before=plain(h.session.midiData),undo=h.session.undo.length;assert.equal(beginMove(h,'locked'),false);assert.equal(beginResize(h,'locked'),false);assert.deepEqual(plain(h.session.midiData),before);assert.equal(h.session.undo.length,undo);assert.equal(h.api.__externalPointerGesture??null,null)});
test('External pointer move and resize preserve Undo Redo and Save Reload results',()=>{const h=harness();h.core.selectTrackById(h.session,'ext-a');const original=plain(h.track('ext-a').notes);beginMove(h);h.target.onpointermove({clientX:220,clientY:90});h.target.onpointerup();const moved=plain(h.track('ext-a').notes);h.core.undo(h.session);assert.deepEqual(plain(h.track('ext-a').notes),original);h.core.redo(h.session);assert.deepEqual(plain(h.track('ext-a').notes),moved);beginResize(h);h.resize.onpointermove({clientX:220});h.resize.onpointerup();const edited=plain(h.track('ext-a').notes),saved=JSON.stringify(h.session.midiData),reloaded=h.core.createSession({projectId:'reload',midiData:JSON.parse(saved)});assert.deepEqual(plain(reloaded.midiData.tracks.find(track=>track.id==='ext-a').notes),edited);assert.equal(JSON.stringify(reloaded.midiData),saved)});
test('Core Melody Drums Bass keep the original drag and resize handlers',()=>{for(const part of ['melody','drums','bass']){const h=harness();h.core.selectPart(h.session,part);assert.equal(h.api.editorStartNoteDrag({},'core-note'),'core-drag');assert.equal(h.api.editorStartNoteResize({},'core-note'),'core-resize');assert.equal(h.coreDrag,1);assert.equal(h.coreResize,1)}});
test('All MIDI Export remains all-track based and External Tracks remain unique',()=>{const app=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8');assert.match(app,/scope==='all'\|\|track\.part===scope/);const ids=source().midiData.tracks.map(track=>track.id);assert.equal(new Set(ids).size,ids.length);assert.deepEqual(ids,['melody','drums','bass','ext-a','ext-b'])});
