'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
const hash=async bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}':JSON.stringify(value);
async function fixture(){
 const window={Uint8Array,TextEncoder,Blob,Buffer,console,setTimeout(){},atob:x=>Buffer.from(x,'base64').toString('binary')};window.window=window;
 vm.runInNewContext(fs.readFileSync('music-studio-audio-pipeline.js','utf8'),{window,TextEncoder,Uint8Array,Blob,Buffer,console});
 const inventory={identityComplete:true,models:[{id:'fixture-model',digest:'a'.repeat(64)}],runtimeEvidence:{codec:{backend:'fixture',version:'1'},mappedNative:{complete:true},dynamicNativeGraph:{complete:true},transitiveNativeObservation:{complete:true},nativeClosure:{complete:true},network:{native:'CONTAINED',nativeNetworkVerified:true}}};
 const session='a'.repeat(64),request='b'.repeat(64),input={digest:'c'.repeat(64),byteLength:7},binding={session,request,input};
 const identities={inventoryRevision:inventory,modelIdentity:inventory.models,codecIdentity:inventory.runtimeEvidence.codec,nativeIdentity:Object.fromEntries(['mappedNative','dynamicNativeGraph','transitiveNativeObservation','nativeClosure'].map(key=>[key,inventory.runtimeEvidence[key]])),networkIdentity:inventory.runtimeEvidence.network};
 for(const [key,value] of Object.entries(identities))binding[key]=await hash(Buffer.from(canonical(value)));
 const bytes=Buffer.from('fixture midi');
 const payload={midiBase64:bytes.toString('base64'),processingReceipt:{format:'NOVA_PROCESSING_RECEIPT',version:1,binding,complete:true,status:'VERIFIED',processingEligible:true,publicationEligible:false,nativeClosureComplete:true,networkContainment:'CONTAINED',blockedBy:[],output:{digest:await hash(bytes),byteLength:bytes.length},stages:['decoder','resample','model','inference','stem','encoder','result'].map(stage=>({stage,status:'VERIFIED'}))}};
 return {api:window.MusicStudioAudioPipeline,payload,options:{session,request,input,inventory,sha256:hash}};
}
test('complete bound software receipt accepts output, publication stays false',async()=>{const f=await fixture();assert.equal(await f.api.validateProcessingReceipt(f.payload,f.options),true);assert.equal(f.payload.processingReceipt.publicationEligible,false)});
for(const field of ['session','request','inventoryRevision','modelIdentity','codecIdentity','nativeIdentity','networkIdentity'])test('reject stale processing binding '+field,async()=>{const f=await fixture();f.payload.processingReceipt.binding[field]='f'.repeat(64);await assert.rejects(f.api.validateProcessingReceipt(f.payload,f.options))});
for(const stage of ['decoder','resample','model','inference','stem','encoder','result'])test('reject missing processing stage '+stage,async()=>{const f=await fixture();f.payload.processingReceipt.stages=f.payload.processingReceipt.stages.filter(x=>x.stage!==stage);await assert.rejects(f.api.validateProcessingReceipt(f.payload,f.options))});
for(const field of ['models','codec','mappedNative','network'])test('reject changed processing inventory '+field,async()=>{const f=await fixture();if(field==='models')f.options.inventory.models=[];else f.options.inventory.runtimeEvidence[field]={changed:true};await assert.rejects(f.api.validateProcessingReceipt(f.payload,f.options))});
test('resample not applicable accepted, decoder not applicable rejected',async()=>{const f=await fixture();f.payload.processingReceipt.stages.find(x=>x.stage==='resample').status='NOT_APPLICABLE';assert.equal(await f.api.validateProcessingReceipt(f.payload,f.options),true);f.payload.processingReceipt.stages.find(x=>x.stage==='decoder').status='NOT_APPLICABLE';await assert.rejects(f.api.validateProcessingReceipt(f.payload,f.options))});
for(const mutate of [r=>r.complete=false,r=>r.nativeClosureComplete=false,r=>r.networkContainment='UNVERIFIED',r=>r.publicationEligible=true,r=>r.output.digest='f'.repeat(64),r=>r.output.byteLength=1,r=>r.blockedBy=['native-network'],r=>r.stages.push({...r.stages[0]})])test('partial or tampered processing receipt rejected '+String(mutate),async()=>{const f=await fixture();mutate(f.payload.processingReceipt);await assert.rejects(f.api.validateProcessingReceipt(f.payload,f.options))});
test('missing processing receipt rejected',async()=>{const f=await fixture();delete f.payload.processingReceipt;await assert.rejects(f.api.validateProcessingReceipt(f.payload,f.options))});
