const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const plain=v=>JSON.parse(JSON.stringify(v));
function load(){const w={};w.window=w;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-structure-info.js'),'utf8'),w);return w.MusicStudioStructureInfo}
test('explicit key changes select key and scale family at their exact tick',()=>{const api=load(),d={keySignatureMap:[{tick:960,sharps:-3,minor:true},{tick:0,sharps:0,minor:false}]},before=plain(d);assert.equal(api.keyAtTick(d,959).key.tonic,'C');assert.equal(api.keyAtTick(d,960).key.tonic,'C');assert.equal(api.keyAtTick(d,960).key.scaleFamily,'Minor');assert.equal(api.keyAtTick(d,960).key.scaleVariant,null);assert.deepEqual(plain(d),before)});
test('major/minor spellings retain signed signature extremes',()=>{const api=load();assert.equal(api.keySignatureInfo({sharps:-7,minor:false}).tonic,'Cb');assert.equal(api.keySignatureInfo({sharps:7,minor:false}).tonic,'C#');assert.equal(api.keySignatureInfo({sharps:-7,minor:true}).tonic,'Ab');assert.equal(api.keySignatureInfo({sharps:7,minor:true}).tonic,'A#');assert.equal(api.keySignatureInfo({sharps:0,minor:true}).tonic,'A')});
test('absence or later first key stays unknown and never guesses from notes',()=>{const api=load();assert.equal(api.keyAtTick({tracks:[{notes:[{pitch:60}]}]},0).status,'unknown');assert.equal(api.keyAtTick({keySignature:{tick:960,sharps:0,minor:false}},959).status,'unknown');assert.equal(api.keyAtTick({keySignature:{tick:0,sharps:1,minor:false}},0).key.tonic,'G')});
test('contradictory same-tick keys remain explicit conflicts',()=>{const api=load(),d={keySignatureMap:[{tick:0,sharps:0,minor:false},{tick:0,sharps:1,minor:false}]};assert.equal(api.keyAtTick(d).status,'conflict');d.keySignatureMap[1].sharps=0;assert.equal(api.keyAtTick(d).status,'known')});
test('marker-derived section candidates preserve exact ticks and labels without adoption',()=>{const api=load(),d={totalTick:3000,markers:[{tick:2001,text:'サビ',track:2},{tick:501,text:'Aメロ',track:1}]},before=plain(d),r=api.sectionCandidates(d);assert.deepEqual(plain(r.candidates.map(c=>[c.startTick,c.endTick,c.labels,c.adopted])),[[501,2001,['Aメロ'],false],[2001,3000,['サビ'],false]]);assert.deepEqual(plain(r.unlabelledPrefix),{startTick:0,endTick:501});assert.deepEqual(plain(d),before);assert.equal(d.sections,undefined)});
test('same-tick labels and terminal markers are retained without empty sections',()=>{const api=load(),r=api.sectionCandidates({totalTick:960,markers:[{tick:0,text:'A'},{tick:0,text:'Intro'},{tick:960,text:'End'}]});assert.equal(r.candidates.length,1);assert.deepEqual(plain(r.candidates[0].labels),['A','Intro']);assert.deepEqual(plain(r.terminalMarkers),[{tick:960,text:'End'}])});
test('missing endpoint is left unknown and missing markers do not trigger guessed analysis',()=>{const api=load();assert.equal(api.sectionCandidates({markers:[{tick:120,text:'A'}]}).candidates[0].endTick,null);assert.equal(api.sectionCandidates({sections:[{name:'existing'}]}).status,'unknown')});
for(const d of [{keySignatureMap:{}},{keySignatureMap:[{tick:0,sharps:8,minor:false}]},{keySignatureMap:[{tick:0,sharps:0,minor:'false'}]},{keySignatureMap:[{tick:-1,sharps:0,minor:false}]}])test('invalid key data rejects '+JSON.stringify(d),()=>assert.throws(()=>load().keyAtTick(d)));
for(const d of [{markers:{}},{markers:[{tick:1.5,text:'A'}]},{markers:[{tick:0,text:null}]},{totalTick:10,markers:[{tick:11,text:'A'}]}])test('invalid marker data rejects '+JSON.stringify(d),()=>assert.throws(()=>load().sectionCandidates(d)));
