const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value));
function load(){
  const w={};w.window=w;w.globalThis=w;
  for(const file of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),w,{filename:file});
  return w;
}
function project(id='p'){return{projectId:id,revision:1,musicalSettings:{key:'C'},midiData:{version:1,ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:2}},tracks:[{id:'melody',part:'melody',notes:[]},{id:'drums',part:'drums',notes:[]},{id:'bass',part:'bass',notes:[]}]}}}
test('melody candidate creates a non-mutating exact-range partial-edit preview',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[1],candidate={candidateId:'B',value},before=JSON.stringify(s.midiData),bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,candidate,{project:p});assert.equal(bundle.type,'midi-preview');assert.equal(bundle.targetTrackId,'melody');assert.equal(bundle.result.changes.adds.length,8);assert.equal(JSON.stringify(s.midiData),before);assert.equal(bundle.preview.afterNotes.length,8)});
test('melody materialization updates editable notes but never targets a locked note',()=>{const w=load(),p=project();p.midiData.tracks[0].notes=[{id:'free',pitch:60,startTick:0,durationTicks:240,velocity:90},{id:'locked',pitch:62,startTick:480,durationTicks:240,velocity:90,locked:true}];const s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});assert.deepEqual(plain(bundle.result.changes.updates.map(n=>n.id)),['free']);assert.equal(bundle.result.changes.updates.some(n=>n.id==='locked'),false)});
test('chord candidate previews root motion on Bass and links arrangement roles',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('chord',ctx)[1],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'B',value},{project:p});assert.equal(bundle.targetTrackId,'bass');assert.deepEqual(plain(bundle.result.changes.adds.map(n=>n.pitch)),[36,45,41,43]);assert.equal(bundle.companion.kind,'chord-companion');assert.equal(bundle.companion.arrangement.roles.includes('bass'),true)});
test('lyrics candidate stays metadata-only and links phrase slots to matching Melody candidate',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('lyrics-structure',ctx)[2],before=JSON.stringify(s.midiData),bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'C',value},{project:p});assert.equal(bundle.type,'metadata-preview');assert.equal(bundle.companion.kind,'lyrics-melody-link');assert.equal(bundle.companion.linkedMelodyCandidate,'C');assert.equal(bundle.companion.phraseSlots.length,4);assert.equal(JSON.stringify(s.midiData),before)});
test('candidate apply goes through guarded partial edit path and can be undone',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});const applied=w.MusicStudioAICandidatePreview.applyPreview(s,w.MusicStudioEditor,bundle);assert.equal(applied.ok,true);assert.equal(w.MusicStudioEditor.currentTrack(s).notes.length,8);w.MusicStudioEditor.undo(s);assert.equal(w.MusicStudioEditor.currentTrack(s).notes.length,0)});
test('range lock causes candidate apply to fail closed without mutation',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p);w.MusicStudioMeasureLocks.addRangeLock(s,w.MusicStudioEditor,{trackId:'melody',startTick:0,endTick:3840});const ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p}),before=JSON.stringify(s.midiData);assert.throws(()=>w.MusicStudioAICandidatePreview.applyPreview(s,w.MusicStudioEditor,bundle),/rejected|protected|locked/);assert.equal(JSON.stringify(s.midiData),before)});
test('candidate partial adoption applies only the selected exact measure range',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});const applied=w.MusicStudioAICandidatePreview.applyPreview(s,w.MusicStudioEditor,bundle,{startMeasure:1,endMeasure:1});assert.equal(applied.ok,true);const notes=w.MusicStudioEditor.currentTrack(s).notes;assert.ok(notes.length>0);assert.equal(notes.every(note=>note.startTick<1920),true);});
