const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value));
function load(){const w={};w.window=w;w.globalThis=w;for(const file of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js','music-studio-ai-family-preview.js','music-studio-ai-family-apply.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),w,{filename:file});return w}
function project(){return{projectId:'family-apply',revision:7,musicalSettings:{key:'C'},midiData:{version:1,ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:0,numerator:4,denominator:4},{tick:3840,numerator:3,denominator:4}],tempoMap:[{tick:0,bpm:120,microsecondsPerQuarter:500000,track:0}],editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:2}},tracks:[{id:'melody',part:'melody',notes:[]},{id:'drums',part:'drums',notes:[]},{id:'bass',part:'bass',notes:[]}]}}}
function workspace(w,p,s){const ws=w.MusicStudioAIWorkflow.createWorkspace(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor);for(const kind of w.MusicStudioAIFamilyPreview.KINDS)w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},w.MusicStudioAIComposition.candidateValues(kind,ctx),{adapter:'deterministic-family-v1'});return ws}
test('Family Apply Plan and preflight are non-mutating',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createCoordinatedSession(p),ws=workspace(w,p,s),beforeSession=plain(s),beforeWs=plain(ws),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,w.MusicStudioEditor),pre=w.MusicStudioAIFamilyApply.simulate(plan,ws,p,s,w.MusicStudioEditor);assert.equal(plan.mutates,false);assert.equal(plan.issues.length,0);assert.equal(plan.source.projectRevision,7);assert.equal(plan.unchanged.includes('tempo-map'),true);assert.equal(plan.components.filter(component=>component.previewType==='midi-preview').every(component=>Number.isInteger(component.range.startTick)&&Number.isInteger(component.range.endTick)),true);assert.equal(pre.ok,true);assert.equal(pre.mutates,false);assert.deepEqual(plain(s),beforeSession);assert.deepEqual(plain(ws),beforeWs);assert.ok(w.MusicStudioAIFamilyApply.planRows(plan).length>=5)});
test('successful Family Apply commits Melody and Bass atomically as one Undo Redo unit',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core),undoBefore=s.undo.length,result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,true);assert.equal(result.undoUnits,1);assert.equal(s.undo.length,undoBefore+1);assert.ok(core.getTrackById(s.midiData.tracks,'melody').notes.length>0);assert.equal(core.getTrackById(s.midiData.tracks,'bass').notes.length,4);const after=plain(s.midiData);core.undo(s);assert.equal(core.getTrackById(s.midiData.tracks,'melody').notes.length,0);assert.equal(core.getTrackById(s.midiData.tracks,'bass').notes.length,0);core.redo(s);assert.deepEqual(plain(s.midiData),after);for(const kind of plan.kinds){const set=ws.candidateSets.find(item=>item.kind===kind);assert.equal(set.candidates.find(item=>item.candidateId==='B').status,'adopted')}});
test('protected Bass range fails preflight with zero MIDI workspace or Undo mutation',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s);w.MusicStudioMeasureLocks.addRangeLock(s,core,{trackId:'bass',startTick:0,endTick:3840});const plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core),before=plain(s),beforeWs=plain(ws),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/preflight:chord|protected|lock/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('family mismatch and missing dependency fail closed before Apply',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s);ws.candidateSets.find(set=>set.kind==='chord').candidates[0].value.candidateFamily.id='wrong';let plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core),before=plain(s),beforeWs=plain(ws),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/family-mismatch/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);const ws2=workspace(w,p,s);ws2.candidateSets=ws2.candidateSets.filter(set=>set.kind!=='chord');plan=w.MusicStudioAIFamilyApply.createPlan(ws2,'A',p,s,core,{kinds:['arrangement']});result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws2,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/missing-dependency:arrangement->chord/)});
test('stale revision Track range and candidate fingerprint reject without Undo consumption',()=>{const w=load(),p=project(),core=w.MusicStudioEditor;
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core),before=plain(s);p.revision=8;const r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-project-revision/);assert.deepEqual(plain(s),before);p.revision=7}
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core);s.midiData.tracks=s.midiData.tracks.filter(t=>t.id!=='bass');const undo=s.undo.length,r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-track:chord/);assert.equal(s.undo.length,undo)}
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core);s.editRange={startMeasure:2,endMeasure:2};const r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-range/)}
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core);ws.candidateSets.find(set=>set.kind==='melody').candidates[0].value.summary='changed after plan';const r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-workspace/)}
});
test('partial Family Apply can adopt Melody only without touching Bass',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'C',p,s,core,{kinds:['melody']}),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,true);assert.ok(core.getTrackById(s.midiData.tracks,'melody').notes.length>0);assert.equal(core.getTrackById(s.midiData.tracks,'bass').notes.length,0);assert.equal(ws.candidateSets.find(set=>set.kind==='melody').candidates[2].status,'adopted');assert.equal(ws.candidateSets.find(set=>set.kind==='chord').candidates[2].status,'available')});
test('Family Apply preserves exact meter-change ticks and lock metadata',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),meter=plain(s.midiData.timeSignatureMap),locks=plain(s.midiData.editor.measureLocks||null),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core),r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,true);assert.deepEqual(plain(s.midiData.timeSignatureMap),meter);assert.deepEqual(plain(s.midiData.editor.measureLocks||null),locks)});
