const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

function load(){const window={crypto:{randomUUID:()=>`id-${Math.random()}`}};window.window=window;window.globalThis=window;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-editor.js'),'utf8'),window);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-playback.js'),'utf8'),window);return window}
const plain=value=>JSON.parse(JSON.stringify(value));
function source(){const note=(id,pitch)=>({id,pitch,startTick:0,durationTicks:120,velocity:80});return{projectId:'mute-solo',midiData:{tracks:[{id:'core-melody',part:'melody',name:'Melody',notes:[note('m',60)]},{id:'core-drums',part:'drums',name:'Drums',channel:10,notes:[note('d',36)]},{id:'core-bass',part:'bass',name:'Bass',notes:[note('b',48)]},{id:'external-a',name:'Melody',trackType:'midi-melodic',roleAssignment:'melody',notes:[note('a',72)]},{id:'external-b',name:'Melody',trackType:'midi-melodic',roleAssignment:'melody',notes:[note('b2',74)]}]}}}

test('Core and same-name External Mute remain independent by exact Track ID and survive save reload',()=>{const{MusicStudioEditor:editor,MusicStudioPlayback:playback}=load(),session=editor.createSession(source()),asPlayback=()=>session.midiData.tracks.map(track=>track.part?track:{...track,part:track.roleAssignment==='drums'?'drums':'melody'}),metadataBefore=plain(session.midiData.tracks.map(({id,name,part,roleAssignment,channel,program})=>({id,name,part,roleAssignment,channel,program})));editor.setTrackMuted(session,'external-a',true);assert.equal(session.midiData.tracks.find(track=>track.id==='external-a').muted,true);assert.notEqual(session.midiData.tracks.find(track=>track.id==='external-b').muted,true);assert.notEqual(session.midiData.tracks.find(track=>track.id==='core-melody').muted,true);assert.deepEqual(Array.from(playback.activePlaybackTracks(asPlayback()),track=>track.id),['core-melody','core-drums','core-bass','external-b']);editor.setTrackMuted(session,'core-drums',true);assert.deepEqual(Array.from(playback.activePlaybackTracks(asPlayback()),track=>track.id),['core-melody','core-bass','external-b']);const reloaded=editor.createSession({projectId:'reload',midiData:plain(session.midiData)});assert.equal(reloaded.midiData.tracks.find(track=>track.id==='external-a').muted,true);assert.equal(reloaded.midiData.tracks.find(track=>track.id==='core-drums').muted,true);assert.deepEqual(plain(reloaded.midiData.tracks.map(({id,name,part,roleAssignment,channel,program})=>({id,name,part,roleAssignment,channel,program}))),metadataBefore)});

test('External Solo multiple Solo and Mute plus Solo follow the shared playback contract',()=>{const{MusicStudioEditor:editor,MusicStudioPlayback:playback}=load(),session=editor.createSession(source()),asPlayback=()=>session.midiData.tracks.map(track=>track.part?track:{...track,part:track.roleAssignment==='drums'?'drums':'melody'}),runtime={soloByTrackId:{'external-a':true}};assert.deepEqual(Array.from(playback.activePlaybackTracks(asPlayback(),runtime),track=>track.id),['external-a']);runtime.soloByTrackId['external-b']=true;assert.deepEqual(Array.from(playback.activePlaybackTracks(asPlayback(),runtime),track=>track.id),['external-a','external-b']);editor.setTrackMuted(session,'external-a',true);assert.deepEqual(Array.from(playback.activePlaybackTracks(asPlayback(),runtime),track=>track.id),['external-b']);runtime.soloByTrackId['core-bass']=true;assert.deepEqual(Array.from(playback.activePlaybackTracks(asPlayback(),runtime),track=>track.id),['core-bass','external-b']);assert.equal(session.midiData.tracks.some(track=>Object.hasOwn(track,'solo')),false)});

test('Track switching and UI-style labels cannot redirect Mute or Solo identity',()=>{const{MusicStudioEditor:editor,MusicStudioPlayback:playback}=load(),session=editor.createSession(source()),before=plain(session.midiData);editor.selectTrackById(session,'external-b');assert.equal(editor.currentTrackId(session),'external-b');editor.setTrackMuted(session,'E1 Melody',true);assert.deepEqual(plain(session.midiData),before);const runtime={soloByTrackId:{'E2 Melody':true}};assert.deepEqual(Array.from(playback.activePlaybackTracks(session.midiData.tracks,runtime),track=>track.id),['core-melody','core-drums','core-bass','external-a','external-b']);assert.equal(editor.currentTrackId(session),'external-b')});
