const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
// Transactional IDB model: binary structured cloning, commit, abort and reopen.
// Physical browser persistence is a separate acceptance test.
function idb(){const stores=new Map();let fault=false;const db={close(){},objectStoreNames:{contains:n=>stores.has(n)},createObjectStore(n){stores.set(n,new Map());return{createIndex(){}}},transaction(names,mode){names=Array.isArray(names)?names:[names];const staged=new Map(names.map(n=>[n,new Map(stores.get(n))]));let pending=0,aborted=false,timer;const tx={abort(){if(aborted)return;aborted=true;clearImmediate(timer);setImmediate(()=>tx.onabort?.())},objectStore(n){const map=staged.get(n);function req(op){pending++;const r={};setImmediate(()=>{if(aborted)return;try{r.result=op();r.onsuccess?.()}catch(e){r.error=e;r.onerror?.();tx.abort()}pending--;if(!pending&&!aborted){timer=setImmediate(()=>{if(aborted)return;if(mode==='readwrite')for(const[n,m]of staged)stores.set(n,m);tx.oncomplete?.()})}});return r}return{get:k=>req(()=>structuredClone(map.get(k))),getAll:()=>req(()=>structuredClone([...map.values()])),getKey:k=>req(()=>map.has(k)?k:undefined),put:v=>req(()=>{if(fault)throw Error('QuotaExceededError');map.set(v.projectId||v.id,structuredClone(v))}),add:v=>req(()=>{if(fault)throw Error('QuotaExceededError');if(map.has(v.id))throw Error('ConstraintError');map.set(v.id,structuredClone(v))})}}};return tx}};return{stores,fail(){fault=true},open(){const r={};setImmediate(()=>{r.result=db;r.onupgradeneeded?.();r.onsuccess?.()});return r}}}
function fixture(indexedDB=idb()){let seq=0;const w={console,Date,Math,JSON,Intl,Blob,ArrayBuffer,DataView,Float32Array,Uint8Array,crypto:{subtle:webcrypto.subtle,randomUUID:()=>`long-${++seq}`},indexedDB,location:{hash:'#music-studio'}};w.window=w;vm.runInNewContext(fs.readFileSync('music-studio.js','utf8'),w);const a=w.MusicStudio;return{a,indexedDB}}
function wav(frames=2100000){const b=new ArrayBuffer(44+frames*2),v=new DataView(b),tag=(p,s)=>[...s].forEach((c,i)=>v.setUint8(p+i,c.charCodeAt()));tag(0,'RIFF');v.setUint32(4,b.byteLength-8,true);tag(8,'WAVE');tag(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,8000,true);v.setUint32(28,16000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);tag(36,'data');v.setUint32(40,frames*2,true);const file=new Blob([b],{type:'audio/wav'});file.name='long.wav';return file}
async function setup(){const f=fixture(),a=f.a,repo=a.indexedDbRepository(),p=a.makeProject({projectId:'long-project',projectName:'Long',midiData:{unchanged:true},legacy:{keep:true}});a.setRepository(repo);await repo.put(p);a.state.projects=[p];a.pcmOpen(p.projectId);return{...f,repo,p}}
test('real import route stores >2M samples as Blob and a fresh repository reload verifies every byte',async()=>{const{a,repo,p,indexedDB}=await setup(),file=wav();file.arrayBuffer=()=>{throw Error('whole-file-read-forbidden')};const result=await a.pcmImportFile(file,p.projectId);assert.equal(result.ok,true,result.error);assert.equal(result.project.longWavAssets[0].frames,2100000);assert.deepEqual(JSON.parse(JSON.stringify(result.project.midiData)),{unchanged:true});await repo.close();const fresh=fixture(indexedDB);fresh.a.setRepository(fresh.a.indexedDbRepository());const blob=await fresh.a.pcmLoadLongWav(p.projectId,result.assetId);assert.equal(blob.size,file.size);assert.equal(Buffer.compare(Buffer.from(await blob.arrayBuffer()),Buffer.from(await Blob.prototype.arrayBuffer.call(file))),0)});
test('quota abort preserves metadata and exposes no orphan binary',async()=>{const{a,p,repo,indexedDB}=await setup(),before=JSON.stringify(await repo.get(p.projectId));indexedDB.fail();const r=await a.pcmImportLongFile(wav(100),p.projectId);assert.equal(r.ok,false);assert.match(r.error,/Quota/);assert.equal(JSON.stringify(await repo.get(p.projectId)),before);assert.equal(indexedDB.stores.get('longWavBinaries').size,0)});
test('concurrent project update is rejected without binary writes',async()=>{const{a,p,repo,indexedDB}=await setup();await repo.put({...p,revision:20});const r=await a.pcmImportLongFile(wav(100),p.projectId);assert.equal(r.ok,false);assert.match(r.error,/conflict/);assert.equal(indexedDB.stores.get('longWavBinaries').size,0);assert.equal((await repo.get(p.projectId)).revision,20)});
test('interrupted validation cannot commit',async()=>{const{a,p,indexedDB}=await setup(),file=wav(100),slice=file.slice.bind(file);file.slice=(...args)=>{a.pcmEditor.generation++;return slice(...args)};const r=await a.pcmImportLongFile(file,p.projectId);assert.equal(r.ok,false);assert.match(r.error,/stale/);assert.equal(indexedDB.stores.get('longWavBinaries').size,0)});
test('corrupt or missing binary is rejected; JSON backup cannot claim success',async()=>{const{a,p,indexedDB}=await setup(),r=await a.pcmImportLongFile(wav(100),p.projectId);assert.equal(r.ok,true);const rec=indexedDB.stores.get('longWavBinaries').get(r.assetId);rec.blob=new Blob([new Uint8Array(rec.blob.size)]);await assert.rejects(a.pcmLoadLongWav(p.projectId,r.assetId),/corrupt/);assert.equal(a.exportBackup().ok,false);a.state.settings=a.defaultSettings();a.state.settings.backup.automaticEnabled=true;assert.equal((await a.runAutoBackupCheck()).created,false);const backup=a.backupObject();assert.equal((await a.inspectBackupCompleteness(backup)).fullBackupComplete,false);assert.equal((await a.restoreBackup(backup,{settings:false,projects:true})).ok,false);indexedDB.stores.get('longWavBinaries').delete(r.assetId);await assert.rejects(a.pcmLoadLongWav(p.projectId,r.assetId),/missing/)});
test('memory fallback refuses durable long-audio save',async()=>{const{a}=fixture();a.setRepository(a.memoryRepository());const p=a.makeProject({projectId:'p',projectName:'p'});a.state.projects=[p];a.pcmOpen('p');assert.match((await a.pcmImportLongFile(wav(100),'p')).error,/durable/)});
