const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value));
function load(){const w={};w.window=w;w.globalThis=w;for(const file of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js','music-studio-ai-family-preview.js','music-studio-ai-family-apply.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),w,{filename:file});return w}
function project(){return{projectId:'family-apply',revision:7,musicalSettings:{key:'C'},midiData:{version:1,ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:0,numerator:4,denominator:4},{tick:3840,numerator:3,denominator:4}],tempoMap:[{tick:0,bpm:120,microsecondsPerQuarter:500000,track:0}],editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:2}},tracks:[{id:'melody',part:'melody',notes:[]},{id:'drums',part:'drums',notes:[]},{id:'bass',part:'bass',notes:[]}]}}}
function workspace(w,p,s){const ws=w.MusicStudioAIWorkflow.createWorkspace(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor);for(const kind of w.MusicStudioAIFamilyPreview.KINDS)w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},w.MusicStudioAIComposition.candidateValues(kind,ctx),{adapter:'deterministic-family-v1'});return ws}
test('Lyrics Family metadata Plan narrows anchors and shares one adoption Undo without changing source lines',()=>{const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];p.midiData.editor.editRange={startMeasure:1,endMeasure:4};const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),beforeMidi=plain(s.midiData),beforeWs=plain(ws),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['melody','lyrics-structure'],metadataOnly:true,measureRange:{startMeasure:2,endMeasure:3}}),component=plan.components.find(c=>c.kind==='lyrics-structure');assert.equal(plan.issues.length,0);assert.deepEqual(plain(component.bundle.companion.timeline.slots.map(x=>[x.line,x.startTick,x.endTick])),[[2,1000,1720],[3,1720,2440]]);assert.deepEqual(plain(component.bundle.companion.phraseSlots.map(x=>x.line)),[2,3]);const rows=api.planRows(plan).join('|');assert.match(rows,/Lyrics anchors: 2 \/ M2-3 \/ tick 1000-2440/);assert.doesNotMatch(rows,/Lyrics line [14]:/);assert.equal(api.simulate(plan,ws,p,s,core).ok,true);assert.deepEqual(plain(ws),beforeWs);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,true);assert.deepEqual(plain(s.midiData),beforeMidi);assert.equal(s.undo.length,1);const after=plain(ws);assert.deepEqual(plain(ws.candidateSets.find(set=>set.kind==='lyrics-structure').adopted[0].selection.ticks),[1000,2440]);core.undo(s);assert.deepEqual(plain(ws),beforeWs);core.redo(s);assert.deepEqual(plain(ws),after);assert.deepEqual(plain(ws.candidateSets.map(set=>set.candidates.map(c=>c.value))),beforeWs.candidateSets.map(set=>set.candidates.map(c=>c.value)))});
test('Malformed excluded Lyrics anchor blocks Family MIDI and metadata Apply atomically',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s);ws.candidateSets.find(set=>set.kind==='lyrics-structure').candidates.find(c=>c.candidateId==='B').value.lines[3].stress=[];const before=plain({s,ws}),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['melody','lyrics-structure'],measureRange:{startMeasure:1,endMeasure:1}});assert.match(plan.issues.join('|'),/invalid-lyrics-stress/);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain({s,ws}),before)});
test('Family Apply Plan and preflight are non-mutating',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createCoordinatedSession(p),ws=workspace(w,p,s),beforeSession=plain(s),beforeWs=plain(ws),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,w.MusicStudioEditor),pre=w.MusicStudioAIFamilyApply.simulate(plan,ws,p,s,w.MusicStudioEditor);assert.equal(plan.mutates,false);assert.equal(plan.issues.length,0);assert.equal(plan.source.projectRevision,7);assert.equal(plan.unchanged.includes('tempo-map'),true);assert.equal(plan.components.filter(component=>component.previewType==='midi-preview').every(component=>Number.isInteger(component.range.startTick)&&Number.isInteger(component.range.endTick)),true);assert.equal(pre.ok,true);assert.equal(pre.mutates,false);assert.deepEqual(plain(s),beforeSession);assert.deepEqual(plain(ws),beforeWs);assert.ok(w.MusicStudioAIFamilyApply.planRows(plan).length>=5)});
test('successful Family Apply commits Melody and Bass atomically as one Undo Redo unit',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core),undoBefore=s.undo.length,result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,true);assert.equal(result.undoUnits,1);assert.equal(s.undo.length,undoBefore+1);assert.ok(core.getTrackById(s.midiData.tracks,'melody').notes.length>0);assert.equal(core.getTrackById(s.midiData.tracks,'bass').notes.length,4);const after=plain(s.midiData);core.undo(s);assert.equal(core.getTrackById(s.midiData.tracks,'melody').notes.length,0);assert.equal(core.getTrackById(s.midiData.tracks,'bass').notes.length,0);core.redo(s);assert.deepEqual(plain(s.midiData),after);for(const kind of plan.kinds){const set=ws.candidateSets.find(item=>item.kind===kind);assert.equal(set.candidates.find(item=>item.candidateId==='B').status,'adopted')}});
test('protected Bass range fails preflight with zero MIDI workspace or Undo mutation',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s);w.MusicStudioMeasureLocks.addRangeLock(s,core,{trackId:'bass',startTick:0,endTick:3840});const plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core),before=plain(s),beforeWs=plain(ws),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/preflight:chord|protected|lock/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('family mismatch and missing dependency fail closed before Apply',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s);ws.candidateSets.find(set=>set.kind==='chord').candidates[0].value.candidateFamily.id='wrong';let plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core),before=plain(s),beforeWs=plain(ws),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/family-mismatch/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);const ws2=workspace(w,p,s);ws2.candidateSets=ws2.candidateSets.filter(set=>set.kind!=='chord');plan=w.MusicStudioAIFamilyApply.createPlan(ws2,'A',p,s,core,{kinds:['arrangement']});result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws2,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/missing-dependency:arrangement->chord/)});
test('stale revision Track range and candidate fingerprint reject without Undo consumption',()=>{const w=load(),p=project(),core=w.MusicStudioEditor;
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core),before=plain(s);p.revision=8;const r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-project-revision/);assert.deepEqual(plain(s),before);p.revision=7}
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core);s.midiData.tracks=s.midiData.tracks.filter(t=>t.id!=='bass');const undo=s.undo.length,r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-track:chord/);assert.equal(s.undo.length,undo)}
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core);s.editRange={startMeasure:2,endMeasure:2};const r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-range/)}
  {const s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core);ws.candidateSets.find(set=>set.kind==='melody').candidates[0].value.summary='changed after plan';const r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,false);assert.match(r.errors.join('|'),/stale-workspace/)}
});
test('partial Family Apply can adopt Melody only without touching Bass',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'C',p,s,core,{kinds:['melody']}),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,true);assert.ok(core.getTrackById(s.midiData.tracks,'melody').notes.length>0);assert.equal(core.getTrackById(s.midiData.tracks,'bass').notes.length,0);assert.equal(ws.candidateSets.find(set=>set.kind==='melody').candidates[2].status,'adopted');assert.equal(ws.candidateSets.find(set=>set.kind==='chord').candidates[2].status,'available')});
test('Family Apply preserves exact meter-change ticks and lock metadata',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),meter=plain(s.midiData.timeSignatureMap),locks=plain(s.midiData.editor.measureLocks||null),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core),r=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(r.applied,true);assert.deepEqual(plain(s.midiData.timeSignatureMap),meter);assert.deepEqual(plain(s.midiData.editor.measureLocks||null),locks)});

for(const [label,kinds,metadataOnly] of [
  ['Melody-only',['melody'],false],['Bass-only',['chord'],false],['Section-only',['section'],false],['Melody + Bass',['melody','chord'],false],['metadata-only',['melody','chord','section','arrangement','lyrics-structure'],true]
])test(`Partial Family ${label}: Preview -> Apply -> Undo -> Redo restores MIDI and exact adoption metadata`,()=>{
  const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),beforeMidi=plain(s.midiData),beforeWs=plain(ws),beforeSession=plain(s),api=w.MusicStudioAIFamilyApply;
  const plan=api.createPlan(ws,'B',p,s,core,{kinds,metadataOnly}),preflight=api.simulate(plan,ws,p,s,core);
  assert.equal(preflight.ok,true);assert.deepEqual(plain(s),beforeSession);assert.deepEqual(plain(ws),beforeWs);
  const result=api.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,true);assert.equal(result.undoUnits,1);assert.equal(s.undo.length,1);assert.equal(s.redo.length,0);
  const afterMidi=plain(s.midiData),afterWs=plain(ws);
  if(metadataOnly||kinds.every(k=>!['melody','chord'].includes(k)))assert.deepEqual(afterMidi,beforeMidi);
  if(!kinds.includes('melody'))assert.deepEqual(afterMidi.tracks.find(t=>t.id==='melody'),beforeMidi.tracks.find(t=>t.id==='melody'));
  if(!kinds.includes('chord'))assert.deepEqual(afterMidi.tracks.find(t=>t.id==='bass'),beforeMidi.tracks.find(t=>t.id==='bass'));
  for(const set of ws.candidateSets)assert.equal(set.candidates.find(c=>c.candidateId==='B').status,kinds.includes(set.kind)?'adopted':'available');
  core.undo(s);assert.deepEqual(plain(s.midiData),beforeMidi);assert.deepEqual(plain(ws),beforeWs);assert.equal(s.undo.length,0);assert.equal(s.redo.length,1);
  core.redo(s);assert.deepEqual(plain(s.midiData),afterMidi);assert.deepEqual(plain(ws),afterWs);assert.equal(s.undo.length,1);assert.equal(s.redo.length,0);
});
for(const kinds of [['arrangement'],['lyrics-structure'],['section','arrangement']])test(`unselected dependency for ${kinds.join('+')} is explained and never silently applied`,()=>{
  const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'A',p,s,core,{kinds}),before=plain(s),beforeWs=plain(ws);
  assert.match(api.planRows(plan).join('|'),/dependency-not-selected/);assert.equal(api.simulate(plan,ws,p,s,core).ok,false);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);
});
test('empty component selection cannot fall back to full Apply',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),before=plain(s),beforeWs=plain(ws);assert.throws(()=>w.MusicStudioAIFamilyApply.createPlan(ws,'A',p,s,core,{kinds:[]}),/family-component-selection-required/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('exact partial range clips generated MIDI and survives metadata Undo Redo',()=>{const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),before=plain(ws),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core,{kinds:['melody','chord'],measureRange:{startMeasure:1,endMeasure:1}}),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,true);for(const id of ['melody','bass']){const notes=core.getTrackById(s.midiData.tracks,id).notes;assert.ok(notes.length);assert.equal(notes.every(n=>n.startTick+n.durationTicks<=1000),true)}assert.equal(s.midiData.timeSignatureMap[0].tick,1000);for(const component of plan.components){assert.equal(component.range.endTick,1000);assert.equal(component.range.startMeasure,1);assert.equal(component.range.endMeasure,1);assert.equal(component.changes.adds,core.getTrackById(s.midiData.tracks,component.targetTrackId).notes.length)}const after=plain(ws);core.undo(s);assert.deepEqual(plain(ws),before);core.redo(s);assert.deepEqual(plain(ws),after);assert.equal(s.midiData.timeSignatureMap[0].tick,1000)});
test('failed final Editor commit leaves MIDI metadata and both history stacks unchanged',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core),before=plain(s),beforeWs=plain(ws),locks=w.MusicStudioMeasureLocks,validate=locks.validateEdit;w.MusicStudioMeasureLocks={...locks,validateEdit:(...args)=>{if(args[0].tracks.find(t=>t.id==='melody').notes.length===0&&args[1].tracks.find(t=>t.id==='melody').notes.length>0&&args[1].tracks.find(t=>t.id==='bass').notes.length>0)throw Error('synthetic-final-commit-failure');return validate(...args)}};const result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/synthetic-final-commit-failure/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('nonwritable workspace rejects before MIDI or metadata commit',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core),before=plain(s),beforeWs=plain(ws);Object.defineProperty(ws,'history',{value:ws.history,writable:false,configurable:true,enumerable:true});const result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('Family metadata remains aligned with earlier and later normal Editor history',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s);core.addNote(s,{pitch:60,startTick:0,durationTicks:120,velocity:80});const before=plain(ws),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core,{kinds:['chord']});assert.equal(w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core).applied,true);const adopted=plain(ws);core.addNote(s,{pitch:61,startTick:500,durationTicks:120,velocity:80});core.undo(s);assert.deepEqual(plain(ws),adopted);core.undo(s);assert.deepEqual(plain(ws),before);core.undo(s);assert.deepEqual(plain(ws),before);core.redo(s);assert.deepEqual(plain(ws),before);core.redo(s);assert.deepEqual(plain(ws),adopted);core.redo(s);assert.deepEqual(plain(ws),adopted)});

test('Partial Family respects legacy locks plus additive partial unlock at exact meter tick',()=>{
 const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];p.midiData.editor.lockedMeasures=[1];const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),locks=w.MusicStudioMeasureLocks;
 locks.unlockRange(s,core,{trackId:'melody',startTick:0,endTick:1000});locks.addRangeLock(s,core,{trackId:'melody',startTick:1000,endTick:1720});const ws=workspace(w,p,s),beforeLocks=plain(s.midiData.editor.measureLocks),beforeLegacy=plain(s.midiData.editor.lockedMeasures),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core,{kinds:['melody'],measureRange:{startMeasure:1,endMeasure:1}}),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,true);assert.deepEqual(plain(s.midiData.editor.measureLocks),beforeLocks);assert.deepEqual(plain(s.midiData.editor.lockedMeasures),beforeLegacy);assert.equal(core.currentTrack(s).notes.every(n=>n.startTick+n.durationTicks<=1000),true);const adopted=plain(ws);core.undo(s);assert.deepEqual(plain(s.midiData.editor.measureLocks),beforeLocks);core.redo(s);assert.deepEqual(plain(ws),adopted);assert.deepEqual(plain(s.midiData.editor.measureLocks),beforeLocks);
 const s2=core.createCoordinatedSession(p);locks.addRangeLock(s2,core,{trackId:'melody',startTick:1000,endTick:1720});const ws2=workspace(w,p,s2),blocked=w.MusicStudioAIFamilyApply.createPlan(ws2,'A',p,s2,core,{kinds:['melody'],measureRange:{startMeasure:2,endMeasure:2}}),before=plain(s2),beforeWs=plain(ws2),rejected=w.MusicStudioAIFamilyApply.applyPlan(blocked,ws2,p,s2,core);assert.equal(rejected.applied,false);assert.match(rejected.errors.join('|'),/protected|lock/);assert.deepEqual(plain(s2),before);assert.deepEqual(plain(ws2),beforeWs);
});

for(const [label,kinds,metadataOnly] of [['Section',['section'],false],['metadata Melody',['melody'],true],['metadata Family',['melody','chord','section','arrangement','lyrics-structure'],true]]){
 for(const range of [{},{startMeasure:1},{endMeasure:1},0,{startMeasure:0,endMeasure:1},{startMeasure:1,endMeasure:3},{startMeasure:2,endMeasure:1},{startMeasure:1.5,endMeasure:2}])test(`${label} invalid/outside candidate range ${JSON.stringify(range)} fails closed`,()=>{
  const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),before=plain(s),beforeWs=plain(ws),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds,metadataOnly,measureRange:range});
  assert.equal(api.simulate(plan,ws,p,s,core).ok,false);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.match(plan.issues.join('|'),/selection:/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);
 });
 test(`${label} exact metadata range is displayed and adopted without rewriting candidate`,()=>{
  const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),beforeMidi=plain(s.midiData),beforeWs=plain(ws),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds,metadataOnly,measureRange:{startMeasure:1,endMeasure:1}});
  for(const c of plan.components){assert.equal(c.range.startMeasure,1);assert.equal(c.range.endMeasure,1);assert.equal(c.range.startTick,0);assert.equal(c.range.endTick,1000)}
  assert.match(api.planRows(plan).join('|'),/metadata only.*M1-1.*tick 0-1000/);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,true);assert.deepEqual(plain(s.midiData),beforeMidi);
  for(const kind of kinds){const set=ws.candidateSets.find(set=>set.kind===kind),selection=set.adopted[0].selection;assert.deepEqual(plain(selection.measures),[1,1]);assert.deepEqual(plain(selection.ticks),[0,1000]);assert.deepEqual(plain(set.candidates[1].value),beforeWs.candidateSets.find(set=>set.kind===kind).candidates[1].value)}
  const after=plain(ws);core.undo(s);assert.deepEqual(plain(ws),beforeWs);core.redo(s);assert.deepEqual(plain(ws),after);
 });
}
test('Section timeline uses exact changing-meter ticks and clips partial selection without mutation',()=>{
 const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];p.midiData.editor.editRange={startMeasure:1,endMeasure:4};const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),value=ws.candidateSets.find(set=>set.kind==='section').candidates[1].value,before=plain(value),sessionBefore=plain(s);
 const full=w.MusicStudioAIComposition.sectionTimeline(value,s,core),partial=w.MusicStudioAIComposition.sectionTimeline(value,s,core,{startMeasure:2,endMeasure:3});
 assert.deepEqual(plain(full.segments.map(x=>[x.label,x.startMeasure,x.endMeasure,x.startTick,x.endTick])),[['A',1,2,0,1720],['B',3,3,1720,2440],['Lift',4,4,2440,3160]]);
 assert.deepEqual(plain(partial.segments.map(x=>[x.label,x.startMeasure,x.endMeasure,x.startTick,x.endTick,x.partial])),[['A',2,2,1000,1720,true],['B',3,3,1720,2440,false]]);assert.deepEqual(plain(value),before);assert.deepEqual(plain(s),sessionBefore);
 const plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core,{kinds:['section'],measureRange:{startMeasure:2,endMeasure:3}});assert.match(w.MusicStudioAIFamilyApply.planRows(plan).join('|'),/Section A: M2-2 \/ tick 1000-1720 \/ partial/);assert.equal(w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core).applied,true);assert.deepEqual(plain(s.midiData),sessionBefore.midiData);const after=plain(ws);core.undo(s);core.redo(s);assert.deepEqual(plain(ws),after);assert.deepEqual(plain(ws.candidateSets.find(set=>set.kind==='section').candidates[1].value),before);
});
for(const [name,mutate] of [
 ['overflow',v=>v.plan[0].bars=99],['gap',v=>v.plan.pop()],['fraction',v=>v.plan[0].bars=1.5],['zero',v=>v.plan[0].bars=0],['blank label',v=>v.plan[0].label=''],['empty',v=>v.plan=[]],['missing',v=>delete v.plan],['bad range',v=>v.range.startMeasure=0]
])test(`invalid Section ${name} rejects before metadata MIDI or history changes`,()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),v=ws.candidateSets.find(set=>set.kind==='section').candidates[1].value;mutate(v);const before=plain(s),beforeWs=plain(ws);const plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core,{kinds:['section']}),result=w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core);assert.equal(result.applied,false);assert.match(result.errors.join('|'),/section/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('Section tick resolver failure is non-mutating and fails closed',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),before=plain(s),beforeWs=plain(ws),bad={...core,measureRangeToTicks(){throw Error('synthetic-timeline-failure')}};const plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,bad,{kinds:['section']});assert.equal(w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,bad).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('explicit Project Section Apply appends exact sections with adoption and one Undo Redo unit',()=>{
 const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[{id:'old',label:'Old',startTick:4000,endTick:5000,custom:{keep:true}}];const ws=workspace(w,p,s),before=plain(s),beforeWs=plain(ws),beforeProject=plain(p),api=w.MusicStudioAIFamilyApply;
 const plan=api.createPlan(ws,'B',p,s,core,{kinds:['section'],measureRange:{startMeasure:1,endMeasure:1},applyProjectSections:true});assert.equal(api.simulate(plan,ws,p,s,core).ok,true);assert.equal(core.projectSectionsSnapshot(s),null);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);assert.match(api.planRows(plan).join('|'),/Project Sections: append 1/);assert.match(api.planRows(plan).join('|'),/section: Project Sections（曲構成）/);
 assert.equal(api.applyPlan(plan,ws,p,s,core).applied,true);const state=plain(core.projectSectionsSnapshot(s)),afterWs=plain(ws);assert.equal(state.items.length,2);assert.deepEqual(state.items[0],p.sections[0]);assert.deepEqual([state.items[1].startTick,state.items[1].endTick],[0,1920]);assert.equal(state.items[1].source.familyId,plan.familyId);assert.equal(core.projectSectionsPending(s),true);assert.deepEqual(plain(s.midiData),before.midiData);assert.deepEqual(plain(p),beforeProject);assert.equal(s.undo.length,1);
 core.undo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),{present:true,items:p.sections});assert.deepEqual(plain(ws),beforeWs);assert.equal(core.projectSectionsPending(s),false);core.redo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),state);assert.deepEqual(plain(ws),afterWs);
});
test('default and metadata-only Family Apply never bind or write Project Sections',()=>{for(const metadataOnly of [false,true]){const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s),plan=w.MusicStudioAIFamilyApply.createPlan(ws,'B',p,s,core,{kinds:['section'],metadataOnly}),before=plain(p);assert.equal(w.MusicStudioAIFamilyApply.applyPlan(plan,ws,p,s,core).applied,true);assert.equal(core.projectSectionsSnapshot(s),null);assert.deepEqual(plain(p),before)}});
for(const [name,existing,options] of [
 ['overlap',[{id:'old',startTick:100,endTick:800}],{}],['ambiguous legacy',[{id:'old',startMeasure:3,endMeasure:4}],{}],['invalid collection',{},{}],['id collision',[{id:'will-set',startTick:4000,endTick:5000}],{collide:true}],['no section',[],{kinds:['melody']}],['metadata conflict',[],{metadataOnly:true}]
])test(`Project Section ${name} fails closed with no history binding or mutation`,()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ws=workspace(w,p,s);p.sections=plain(existing);const api=w.MusicStudioAIFamilyApply,opts={kinds:options.kinds||['section'],applyProjectSections:true,metadataOnly:options.metadataOnly===true};if(options.collide){const trial=api.createPlan(ws,'B',p,s,core,opts);p.sections[0].id=trial.projectSections.additions[0].id}const before=plain(s),beforeWs=plain(ws),beforeProject=plain(p),plan=api.createPlan(ws,'B',p,s,core,opts);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);assert.deepEqual(plain(p),beforeProject);assert.equal(core.projectSectionsSnapshot(s),null)});
for(const [name,mutate] of [['delete preserved',plan=>plan.projectSections.after.items.shift()],['change ticks',plan=>plan.projectSections.after.items.at(-1).endTick=99999],['add item',plan=>plan.projectSections.after.items.push({id:'forged',startTick:0,endTick:1})],['selection',plan=>plan.components[0].selection={startMeasure:2,endMeasure:2}]])test(`altered Project Section Plan ${name} rejects before commit`,()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[{id:'old',startTick:4000,endTick:5000}];const ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['section'],applyProjectSections:true}),before=plain(s),beforeWs=plain(ws);mutate(plan);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);assert.equal(core.projectSectionsSnapshot(s),null)});
test('same-revision Project Sections change invalidates preflight',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[];const ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['section'],applyProjectSections:true});p.sections.push({id:'another',startTick:4000,endTick:5000});const before=plain(s),beforeWs=plain(ws);assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('failed Project Section final commit leaves MIDI adoption history and section binding unchanged',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[];const ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['melody','section'],applyProjectSections:true}),before=plain(s),beforeWs=plain(ws);w.MusicStudioMeasureLocks={...w.MusicStudioMeasureLocks,validateEdit(){throw Error('synthetic-section-commit-failure')}};assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);assert.equal(core.projectSectionsSnapshot(s),null)});
test('normal MIDI history before and after Project Section Apply stays aligned',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[];core.addNote(s,{pitch:60,startTick:0,durationTicks:120,velocity:90});const ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['section'],applyProjectSections:true});assert.equal(api.applyPlan(plan,ws,p,s,core).applied,true);const adopted=plain(core.projectSectionsSnapshot(s));core.addNote(s,{pitch:62,startTick:480,durationTicks:120,velocity:90});core.undo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),adopted);core.undo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),{present:true,items:[]});core.undo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),{present:true,items:[]});core.redo(s);core.redo(s);core.redo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),adopted)});
test('Project Section payload cannot be applied with its explicit option disabled',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[];const ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['section'],applyProjectSections:true}),before=plain(s),beforeWs=plain(ws);plan.applyProjectSections=false;assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);assert.equal(core.projectSectionsSnapshot(s),null)});
test('duplicate candidate Set IDs cannot silently apply Section from a different set',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[];const ws=workspace(w,p,s),set=ws.candidateSets.find(set=>set.kind==='section');ws.candidateSets.push(plain(set));const before=plain(s),beforeWs=plain(ws),api=w.MusicStudioAIFamilyApply,plan=api.createPlan(ws,'B',p,s,core,{kinds:['section'],applyProjectSections:true});assert.equal(api.applyPlan(plan,ws,p,s,core).applied,false);assert.match(plan.issues.join('|'),/ambiguous-project-section-candidate/);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs)});
test('successive disjoint Section Applies retain earlier rows and restore each transaction exactly',()=>{
 const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[];const ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply;
 const first=api.createPlan(ws,'B',p,s,core,{kinds:['section'],measureRange:{startMeasure:1,endMeasure:1},applyProjectSections:true});assert.equal(api.applyPlan(first,ws,p,s,core).applied,true);const firstSections=plain(core.projectSectionsSnapshot(s)),firstWs=plain(ws);
 core.setEditRange(s,{startMeasure:2,endMeasure:2});const ctx=w.MusicStudioAIComposition.createContext(p,s,core);for(const kind of w.MusicStudioAIFamilyPreview.KINDS)w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},w.MusicStudioAIComposition.candidateValues(kind,ctx));const beforeSecondWs=plain(ws),second=api.createPlan(ws,'B',p,s,core,{kinds:['section'],applyProjectSections:true});assert.equal(api.applyPlan(second,ws,p,s,core).applied,true);const both=plain(core.projectSectionsSnapshot(s)),secondWs=plain(ws);assert.equal(both.items.length,2);assert.deepEqual(both.items[0],firstSections.items[0]);assert.deepEqual([both.items[1].startTick,both.items[1].endTick],[1920,3840]);
 core.undo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),firstSections);assert.deepEqual(plain(ws),beforeSecondWs);core.undo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),{present:true,items:[]});core.redo(s);core.redo(s);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),both);assert.deepEqual(plain(ws),secondWs);
});
test('failure after a prior Section binding retains original sidecar and both history stacks',()=>{const w=load(),p=project(),core=w.MusicStudioEditor,s=core.createCoordinatedSession(p);p.sections=[];const ws=workspace(w,p,s),api=w.MusicStudioAIFamilyApply,first=api.createPlan(ws,'B',p,s,core,{kinds:['section'],measureRange:{startMeasure:1,endMeasure:1},applyProjectSections:true});assert.equal(api.applyPlan(first,ws,p,s,core).applied,true);const before=plain(s),beforeWs=plain(ws),sections=plain(core.projectSectionsSnapshot(s));const second=api.createPlan(ws,'A',p,s,core,{kinds:['section'],measureRange:{startMeasure:2,endMeasure:2},applyProjectSections:true});w.MusicStudioMeasureLocks={...w.MusicStudioMeasureLocks,validateEdit(){throw Error('synthetic-bound-section-failure')}};assert.equal(api.applyPlan(second,ws,p,s,core).applied,false);assert.deepEqual(plain(s),before);assert.deepEqual(plain(ws),beforeWs);assert.deepEqual(plain(core.projectSectionsSnapshot(s)),sections)});
