const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const plain=v=>JSON.parse(JSON.stringify(v));
function fixture(){const w={};w.window=w;w.globalThis=w;for(const f of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js','music-studio-ai-family-preview.js','music-studio-ai-family-apply.js'])vm.runInNewContext(fs.readFileSync(f,'utf8'),w);const p={projectId:'arrangement',revision:1,midiData:{ppq:480,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:1000,numerator:3,denominator:8}],editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:4}},tracks:[{id:'melody',part:'melody',notes:[]},{id:'bass',part:'bass',notes:[]},{id:'drums',part:'drums',notes:[]}]}},core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,core),ws=w.MusicStudioAIWorkflow.createWorkspace(p);for(const kind of ['melody','lyrics-structure'])w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},w.MusicStudioAIComposition.candidateValues(kind,ctx),{adapter:'local-test'});const value=ws.candidateSets.at(-1).candidates[1].value;return{w,p,core,s,ws,value,C:w.MusicStudioAIComposition,P:w.MusicStudioAICandidatePreview,A:w.MusicStudioAIFamilyApply}}

function inspect(f,selection=null){return f.C.lyricsMelodyReferencePreview(f.value,f.ws,f.s,f.core,selection)}
test('Lyrics resolved Melody phrase events are abstract, exact, partial and nonmutating',()=>{const f=fixture(),before=plain(f.ws),midi=plain(f.s);const p=inspect(f,{startMeasure:2,endMeasure:3});assert.equal(p.lines.length,2);assert.deepEqual(plain(p.lines[0].eventSlots),[5,6,7,8]);assert.deepEqual(plain(p.lines[1].eventSlots),[1,2,3,4]);assert.equal(p.lines[0].startTick,1000);assert.match(f.C.lyricsMelodyReferenceRows(p).join('|'),/allocation unallocated/);assert.deepEqual(plain(f.ws),before);assert.deepEqual(plain(f.s),midi);p.lines[0].events[0].degree=7;assert.deepEqual(plain(f.ws),before)});
for(const [label,change,error] of [
 ['missing Melody',f=>f.ws.candidateSets.shift(),/missing-lyrics-melody-reference/],
 ['ambiguous Melody',f=>f.ws.candidateSets.push(plain(f.ws.candidateSets[0])),/ambiguous-lyrics-melody-reference/],
 ['missing excluded phrase',f=>f.value.lines[0].melodyPhraseSlot=99,/missing-lyrics-melody-phrase/],
 ['duplicate phrase',f=>f.ws.candidateSets[0].candidates[1].value.phrases.push(plain(f.ws.candidateSets[0].candidates[1].value.phrases[0])),/invalid-lyrics-melody-phrase/],
 ['duplicate event',f=>f.ws.candidateSets[0].candidates[1].value.phraseEvents.push(plain(f.ws.candidateSets[0].candidates[1].value.phraseEvents[0])),/invalid-lyrics-melody-event/],
 ['missing event',f=>f.ws.candidateSets[0].candidates[1].value.phrases[0].eventSlots[0]=99,/invalid-lyrics-melody-event-reference/],
 ['ambiguous event membership',f=>f.ws.candidateSets[0].candidates[1].value.phrases[0].eventSlots.push(1),/invalid-lyrics-melody-event-reference/],
 ['event phrase mismatch',f=>f.ws.candidateSets[0].candidates[1].value.phraseEvents[0].phrase=2,/invalid-lyrics-melody-event-reference/],
 ['orphan event',f=>f.ws.candidateSets[0].candidates[1].value.phraseEvents.push({slot:99,phrase:1,degree:1,durationUnits:1}),/unreferenced-lyrics-melody-event/],
 ['range mismatch',f=>f.ws.candidateSets[0].candidates[1].value.range.endTick++,/incompatible-lyrics-melody-reference/],
 ['key mismatch',f=>f.ws.candidateSets[0].candidates[1].value.key='G',/incompatible-lyrics-melody-reference/],
 ['invalid degree',f=>f.ws.candidateSets[0].candidates[1].value.phraseEvents[0].degree=0,/invalid-lyrics-melody-event/],
 ['invalid duration',f=>f.ws.candidateSets[0].candidates[1].value.phraseEvents[0].durationUnits=0,/invalid-lyrics-melody-event/]
])test(`Lyrics reference ${label} fails before any write even in partial inspection`,()=>{const f=fixture();change(f);const before=plain({ws:f.ws,s:f.s,value:f.value});assert.throws(()=>inspect(f,{startMeasure:2,endMeasure:3}),error);assert.deepEqual(plain({ws:f.ws,s:f.s,value:f.value}),before)});
test('Lyrics exact ref resolves older matching family without latest-set fallback',()=>{const f=fixture(),newer=plain(f.ws.candidateSets[0]);newer.candidates.forEach(c=>c.value.candidateFamily.id='different');f.ws.candidateSets.push(newer);assert.equal(inspect(f).candidateId,'B')});
test('Lyrics reference preserves unknown fields and range field ordering',()=>{const f=fixture(),m=f.ws.candidateSets[0].candidates[1].value;m.extra={future:true};m.phraseEvents[0].future='kept';m.range={endTick:m.range.endTick,startTick:m.range.startTick,endMeasure:4,startMeasure:1,future:1};assert.equal(inspect(f).lines[0].events[0].future,'kept')});
test('Lyrics reference empty partial anchor window is empty without moving lines',()=>{const f=fixture();f.value.lines.forEach(l=>l.measureSlot=1);assert.equal(inspect(f,{startMeasure:3,endMeasure:4}).lines.length,0)});

function choices(f,range=null){return f.C.lyricsMelodyReferenceChoices(f.value,f.ws,f.s,f.core,range)}
function explicit(f,choice,list,range=null){return f.C.lyricsMelodyReferencePreview(f.value,f.ws,f.s,f.core,range,{setIndex:choice.setIndex,candidateIndex:choice.candidateIndex,workspaceSignature:list.workspaceSignature})}
test('Explicit runtime occurrence selects either repeated deterministic set ID without changing stored refs',()=>{
 const f=fixture(),copy=plain(f.ws.candidateSets[0]);copy.candidates[1].value.phraseEvents[0].degree=7;copy.candidates[1].value.extra={future:'preserved'};f.ws.candidateSets.push(copy);const before=plain({ws:f.ws,s:f.s});
 const list=choices(f,{startMeasure:1,endMeasure:1});assert.equal(list.choices.length,2);assert.equal(list.choices[0].setId,list.choices[1].setId);assert.throws(()=>inspect(f),/ambiguous/);
 assert.equal(explicit(f,list.choices[0],list,{startMeasure:1,endMeasure:1}).lines[0].events[0].degree,f.ws.candidateSets[0].candidates[1].value.phraseEvents[0].degree);
 const result=explicit(f,list.choices[1],list,{startMeasure:1,endMeasure:1});assert.equal(result.lines[0].events[0].degree,7);assert.deepEqual(plain(result.referenceChoice),{setIndex:2,candidateIndex:1});assert.deepEqual(plain({ws:f.ws,s:f.s}),before);
});
test('Explicit candidate occurrence disambiguates duplicate candidate IDs in one set',()=>{const f=fixture();f.ws.candidateSets[0].candidates.push(plain(f.ws.candidateSets[0].candidates[1]));const list=choices(f);assert.equal(list.choices.length,2);assert.equal(explicit(f,list.choices[1],list).referenceChoice.candidateIndex,3)});
for(const [label,change] of [
 ['workspace field',f=>f.ws.future=1],['candidate contents',f=>f.ws.candidateSets[0].candidates[1].value.phraseEvents[0].degree=7],['reordered sets',f=>f.ws.candidateSets.reverse()],['deleted set',f=>f.ws.candidateSets.shift()],['inserted duplicate',f=>f.ws.candidateSets.push(plain(f.ws.candidateSets[0]))]
])test(`Explicit reference refuses stale ${label} without writes`,()=>{const f=fixture(),list=choices(f);change(f);const before=plain(f.ws);assert.throws(()=>explicit(f,list.choices[0],list),/stale-lyrics-melody-choice/);assert.deepEqual(plain(f.ws),before)});
for(const locator of [null,{}, {setIndex:-1,candidateIndex:1},{setIndex:0,candidateIndex:'1'},{setIndex:0,candidateIndex:99},{setIndex:1,candidateIndex:1},{setIndex:0,candidateIndex:0}])test(`Explicit invalid/nonmatching occurrence ${JSON.stringify(locator)} fails closed`,()=>{const f=fixture();if(locator===null){f.ws.candidateSets.push(plain(f.ws.candidateSets[0]));assert.throws(()=>inspect(f),/ambiguous/);return}assert.throws(()=>f.C.lyricsMelodyReferencePreview(f.value,f.ws,f.s,f.core,null,{...locator,workspaceSignature:JSON.stringify(f.ws)}),/invalid-lyrics-melody-choice/)});
test('Malformed choice stays visible as blocked and cannot bypass phrase validation through selection',()=>{const f=fixture(),copy=plain(f.ws.candidateSets[0]);copy.candidates[1].value.phraseEvents.push({slot:99,phrase:1,degree:1,durationUnits:1});f.ws.candidateSets.push(copy);const before=plain(f.ws),list=choices(f,{startMeasure:2,endMeasure:3});assert.equal(list.choices[0].error,'');assert.match(list.choices[1].error,/unreferenced/);assert.throws(()=>explicit(f,list.choices[1],list,{startMeasure:2,endMeasure:3}),/unreferenced/);assert.equal(explicit(f,list.choices[0],list).lines.length,4);assert.deepEqual(plain(f.ws),before)});
test('Choice listing rejects malformed excluded Lyrics, invalid partial range, missing and malformed sources',()=>{const f=fixture();assert.throws(()=>choices(f,{startMeasure:0,endMeasure:1}),/invalid-lyrics-selection/);f.value.lines[3].stress=[];assert.throws(()=>choices(f,{startMeasure:1,endMeasure:1}),/invalid-lyrics-stress/);const g=fixture();g.ws.candidateSets.shift();assert.throws(()=>choices(g),/missing-lyrics-melody-reference/);assert.throws(()=>g.C.lyricsMelodyReferenceChoices(g.value,{candidateSets:{}},g.s,g.core),/invalid-lyrics-melody-workspace/)});
