const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value));
function load(){const values=new Map(),w={crypto:{randomUUID:(()=>{let n=0;return()=>`ai-integration-${++n}`})()},localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)},location:{hash:'#music-studio'},addEventListener(){},setTimeout,clearTimeout,Intl,Date,Math,JSON,console,TextEncoder};w.window=w;w.globalThis=w;for(const file of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js','music-studio-ai-family-preview.js','music-studio-ai-family-apply.js','music-studio-ai-assistant-ui.js','music-studio-ai-assistant-panel.js','music-studio.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),w,{filename:file});return{window:w,app:w.MusicStudio,core:w.MusicStudioEditor,ai:w.MusicStudioAIWorkflow,composition:w.MusicStudioAIComposition,ui:w.MusicStudioAIAssistantUI,panel:w.MusicStudioAIAssistantPanel}}
function make(app,id='ai-project'){return app.makeProject({projectId:id,projectName:'AI Synthetic',midiData:{version:1,ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},totalTick:3840,editor:{measureCount:2,editRange:{startMeasure:1,endMeasure:2}},tracks:[{id:'melody',part:'melody',name:'Melody',notes:[{id:'n1',pitch:60,startTick:0,durationTicks:480,velocity:90},{id:'n2',pitch:64,startTick:1920,durationTicks:480,velocity:90}]},{id:'drums',part:'drums',notes:[]},{id:'bass',part:'bass',notes:[]}]}})}

test('Lyrics reference UI is read-only, detects stale workspace/MIDI, cancels, and does not persist derived data',async()=>{
 const{window:w,app,core,panel}=load(),p=make(app),s=core.createCoordinatedSession(p),repo=app.memoryRepository();await repo.put(p);app.setRepository(repo);app.state.projects=[p];app.state.midiEditor=s;app.repaintEditor=()=>{};
 const fields={'#aiCandidateKind':'lyrics-structure','#aiFromB':'1','#aiToB':'1'};w.document={querySelector:selector=>({value:fields[selector]||''})};panel.setTab(p.projectId,'candidates');panel.generateFamilyCandidates(p.projectId);panel.generateCandidates(p.projectId);const r=panel._states.get(p.projectId);r.pending=false;const before=plain({ws:r.state.workspace,midi:s.midiData,undo:s.undo});
 panel.inspectLyricsMelody(p.projectId,'B');assert.ok(r.lyricsMelodyPreview);assert.equal(r.pending,false);assert.match(panel.render(p,s),/Melody reference verified/);assert.match(panel.render(p,s),/id="aiToB"[^>]*value="1"/);assert.deepEqual(plain({ws:r.state.workspace,midi:s.midiData,undo:s.undo}),before);
 r.state.workspace.candidateSets.find(set=>set.kind==='melody').candidates[1].value.phrases[0].future=1;assert.match(panel.render(p,s),/参照が変更/);panel.inspectLyricsMelody(p.projectId,'B');assert.match(panel.render(p,s),/Melody reference verified/);s.midiData.tracks[0].notes[0].velocity--;assert.match(panel.render(p,s),/参照が変更/);
 panel.cancelLyricsMelody(p.projectId);assert.equal(r.lyricsMelodyPreview,null);assert.equal(r.pending,false);panel.inspectLyricsMelody(p.projectId,'B');r.pending=true;assert.equal((await app.saveMidiEditor({silent:true})).ok,true);const saved=await repo.get(p.projectId);assert.doesNotMatch(JSON.stringify(saved),/lyrics-melody-reference-preview|workspaceSignature|midiSignature/);assert.equal(r.lyricsMelodyPreview,null);
 const exported=await app.exportProject(p.projectId),backup=app.backupObject();for(const mode of ['json','backup']){const fresh=load(),dest=fresh.app.memoryRepository();fresh.app.setRepository(dest);if(mode==='json')assert.equal((await fresh.app.importText(exported.text)).ok,true);else assert.equal((await fresh.app.restoreBackup(backup,{settings:false,projects:true})).ok,true);assert.doesNotMatch(JSON.stringify(await dest.list()),/lyrics-melody-reference-preview/)}
});
test('Legacy Lyrics render does not resolve/repair missing Melody until explicit inspection',()=>{const{window:w,app,core,panel}=load(),p=make(app),s=core.createCoordinatedSession(p);app.state.projects=[p];app.state.midiEditor=s;w.document={querySelector:selector=>({value:selector==='#aiCandidateKind'?'lyrics-structure':selector.includes('From')?'1':'2'})};panel.generateCandidates(p.projectId);panel.setTab(p.projectId,'candidates');const r=panel._states.get(p.projectId);r.pending=false;const before=plain(r.state.workspace);assert.match(panel.render(p,s),/Melody参照を確認/);assert.equal(r.lyricsMelodyPreview,null);panel.inspectLyricsMelody(p.projectId,'B');assert.match(r.message,/missing-lyrics-melody-reference/);assert.equal(r.pending,false);assert.deepEqual(plain(r.state.workspace),before)});
