const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const plain=v=>JSON.parse(JSON.stringify(v));
function load(){const w={};w.window=w;for(const f of ['music-studio-meter-map.js','music-studio-editor.js','music-studio-measure-locks.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),w);return{core:w.MusicStudioEditor,meter:w.MusicStudioMeterMap,locks:w.MusicStudioMeasureLocks}}
function project(){return{projectId:'synthetic',midiData:{ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:1000,numerator:3,denominator:8},{tick:2200,numerator:6,denominator:8}],tempoMap:[{tick:0,bpm:120},{tick:777,bpm:60}],tracks:[{id:'lead',part:'melody',notes:[{id:'a',pitch:60,startTick:100,durationTicks:100,velocity:90},{id:'b',pitch:64,startTick:3000,durationTicks:100,velocity:90}]}],editor:{measureCount:8,lockedMeasures:[1],parts:{melody:{lockedMeasures:[1]}},trackStates:{lead:{lockedMeasures:[1]}}}}}}
test('A ranges and position are used by internal partial requests and timeline resize',()=>{const{core,meter}=load(),p=project(),raw=plain(p),s=core.createCoordinatedSession(p);assert.deepEqual(p,raw);assert.equal(s.dirty,false);assert.equal(core.measureRangeToTicks({startMeasure:2,endMeasure:2},s.midiData).startTick,1000);assert.equal(core.position({startTick:1000},s.midiData).measure,2);assert.equal(core.createPartialEditRequest(s,{range:{startMeasure:1,endMeasure:3}}).lockedNoteIds[0],'a');core.extendTimelineMeasures(s,1);assert.equal(s.midiData.totalTick,meter.tickAtMeasure(s.midiData,s.midiData.editor.measureCount+1));});
for(const name of ['move','resize','delete','add','recording add','paste','candidate','timeline shrink'])test(`protected ${name} commit rolls back complete session`,()=>{const{core,locks}=load(),s=core.createCoordinatedSession(project());core.selectNote(s,'a');core.copy(s);core.setCandidate(s,'bass','root');locks.addRangeLock(s,core,{trackId:'bass',startTick:0,endTick:4000});if(name==='timeline shrink')locks.addRangeLock(s,core,{trackId:'lead',startTick:10000,endTick:11000});const before=plain(s),r=({move:()=>core.moveSelected(s,1,0),resize:()=>core.resizeSelected(s,1),delete:()=>core.deleteSelected(s),add:()=>core.addNote(s,{startTick:100}), 'recording add':()=>core.addNotesToTrack(s,'lead',[{startTick:100}]),paste:()=>core.paste(s,100),candidate:()=>core.applyCandidate(s,'bass'),'timeline shrink':()=>core.removeTimelineMeasures(s,4)})[name]();assert.equal(r.ok,false);assert.deepEqual(plain(s),before);});
test('exact release and relock preserve legacy aliases and survive reopen Undo Redo',()=>{const{core,locks}=load(),p=project(),s=core.createCoordinatedSession(p),old=plain(s.midiData.editor.trackStates.lead.lockedMeasures);locks.unlockRange(s,core,{trackId:'lead',startTick:100,endTick:200});core.selectNote(s,'a');assert.notEqual(core.moveSelected(s,0,1).ok,false);const changed=plain(s.midiData);core.undo(s);assert.equal(core.currentTrack(s).notes[0].pitch,60);core.redo(s);assert.deepEqual(plain(s.midiData),changed);assert.deepEqual(plain(s.midiData.editor.trackStates.lead.lockedMeasures),old);const reopened=core.createCoordinatedSession({...p,midiData:changed});assert.equal(locks.isProtected(reopened.midiData,core,'lead',core.currentTrack(reopened).notes[0]),false);assert.equal(reopened.dirty,false);});
test('A generated candidates stop exactly at truncated measure ends',()=>{const{core,meter}=load(),s=core.createCoordinatedSession(project());for(const part of ['drums','bass']){const c=core.setCandidate(s,part,'alternate');for(const n of c.notes){const pos=meter.positionAtTick(s.midiData,n.startTick);assert.ok(n.startTick+n.durationTicks<=pos.measureEndTick)}}});
test('nested rejected mutation cannot be swallowed by lock transaction',()=>{const{core,locks}=load(),s=core.createCoordinatedSession(project()),before=plain(s);const r=locks.edit(s,core,copy=>{core.addNote(copy,{startTick:100});return{ok:true}});assert.equal(r.ok,false);assert.deepEqual(plain(s),before)});
test('measure snap and quantize use exact new-bar origins',()=>{const{core}=load(),p=project();p.midiData.editor.lockedMeasures=[];p.midiData.editor.parts.melody.lockedMeasures=[];p.midiData.editor.trackStates.lead.lockedMeasures=[];p.midiData.tracks[0].notes=[{id:'x',pitch:60,startTick:1020,durationTicks:30,velocity:90}];const s=core.createCoordinatedSession(p);assert.equal(core.snapTick(s,1020,'1/16'),1000);assert.equal(core.snapTick(s,950,'measure'),1000);core.selectNote(s,'x');assert.equal(core.quantizeSelectedStarts(s,'1/16').ok,true);assert.equal(core.currentTrack(s).notes[0].startTick,1000)});
test('lock selection and partial unlock use A range while every legacy alias survives',()=>{const{core,locks}=load(),s=core.createCoordinatedSession(project());s.midiData.editor.lockedMeasures=[8];s.midiData.editor.parts.melody.lockedMeasures=[7];const before=plain(s.midiData.editor);core.setSelectedMeasures(s,[2]);assert.deepEqual(plain(s.midiData.editor.lockedMeasures),before.lockedMeasures);assert.deepEqual(plain(s.midiData.editor.parts.melody.lockedMeasures),before.parts.melody.lockedMeasures);core.toggleLockSelected(s);assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:1719,durationTicks:1}),false);core.toggleLockSelected(s);assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:1000,durationTicks:1}),true);assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:999,durationTicks:1}),true)});
