const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const vm=require('node:vm');

const source=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8');
function load(){
  const window={crypto:{randomUUID:(()=>{let n=0;return()=>`night-${++n}`})()},location:{hash:'#music-studio'},addEventListener(){},setTimeout,clearTimeout,Intl,Date,Math,JSON,console};window.window=window;
  vm.runInNewContext(source,{window,globalThis:window},{filename:'music-studio.js'});return{app:window.MusicStudio,window};
}
function formDocument(values){
  const elements={};for(const [name,value] of Object.entries(values))elements[name]={value:String(value)};
  const indicator={dataset:{},textContent:''};return{indicator,document:{querySelector(selector){if(selector==='#musicProjectForm')return{elements};if(selector==='.music-save-state')return indicator;return null}}};
}

test('filename renderer supports every documented token and Japanese text',()=>{const {app}=load();const result=app.renderFileName('{projectName}_{songTitle}_{type}_{date}_{time}_{version}',{projectName:'夜空',songTitle:'星明かり',type:'midi',version:'1.2.3'},{date:'2026-07-20T12:34:56.000Z'});assert.equal(result.ok,true);assert.equal(result.filename,'夜空-星明かり-midi-2026-07-20-12-34-56-1.2.3')});
test('filename renderer replaces unsafe characters and repeated separators',()=>{const {app}=load();assert.equal(app.renderFileName('{projectName}',{projectName:' A / B ::: C '}).filename,'A-B-C')});
test('filename renderer enforces length and fallback',()=>{const {app}=load();assert.equal(app.renderFileName('{songTitle}',{songTitle:''},{maxLength:20,fallback:'代替名'}).filename,'代替名');assert.equal(app.renderFileName('{projectName}',{projectName:'a'.repeat(80)},{maxLength:20}).filename.length,20)});
test('filename renderer rejects unknown tokens',()=>{const {app}=load();const result=app.renderFileName('{projectName}_{secret}',{projectName:'safe'});assert.equal(result.ok,false);assert.match(result.errors[0],/secret/)});
test('MIDI settings API returns a defensive normalized copy',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings({...app.defaultSettings(),midi:{...app.defaultSettings().midi,channel:99,velocity:0,ppq:99999,quantize:'bad'}});const midi=app.getMidiSettings();assert.equal(midi.channel,16);assert.equal(midi.velocity,1);assert.equal(midi.ppq,9600);assert.equal(midi.quantize,'1/16');midi.channel=2;assert.equal(app.getMidiSettings().channel,16)});
test('Logic Pro settings API keeps direct control and auto launch disabled',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings({...app.defaultSettings(),logicPro:{...app.defaultSettings().logicPro,autoLaunch:true,directControl:true,preferMidi:false}});const logic=app.getLogicProSettings();assert.equal(logic.autoLaunch,false);assert.equal(logic.directControl,false);assert.equal(logic.preferMidi,false);assert.equal(logic.method,'file-export')});
test('missing settings create a persisted safe default',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);const settings=await app.loadSettings();assert.equal(settings.projectDefaults.bpm,120);assert.equal((await repo.getSettings()).format,'music-studio-settings')});
test('corrupt stored settings fall back without throwing',async()=>{const {app}=load();const repo=app.memoryRepository();repo.putSettings({format:'broken',projectDefaults:{bpm:'bad'}});app.setRepository(repo);const settings=await app.loadSettings();assert.equal(settings.format,'music-studio-settings');assert.equal(settings.projectDefaults.bpm,120)});
test('partial backup validation warns instead of rejecting the whole envelope',()=>{const {app}=load();const valid=app.makeProject({projectName:'valid'}),invalid={bad:true};const check=app.validateBackup({format:'music-studio-backup',version:1,projects:[valid,invalid]});assert.equal(check.valid,true);assert.equal(check.warnings.length,1)});
test('partial restore adds valid projects and reports invalid projects as skipped',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings(app.defaultSettings());const backup={format:'music-studio-backup',version:1,projects:[app.makeProject({projectName:'valid'}),{bad:true}],settings:app.defaultSettings(),references:[],metadata:{createdAt:new Date().toISOString()}};const result=await app.restoreBackup(backup);assert.equal(result.added,1);assert.equal(result.skipped,1);assert.equal(result.failed,0);assert.equal((await repo.list()).length,1)});
test('settings-only restore does not add or replace projects',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings(app.defaultSettings());const existing=app.makeProject({projectName:'existing',bpm:120});await repo.put(existing);app.state.projects=await repo.list();const backup=app.backupObject();backup.settings.projectDefaults.bpm=77;const result=await app.restoreBackup(backup,{settings:true,projects:false});assert.equal(result.added,0);assert.equal(app.getSettings().projectDefaults.bpm,77);assert.equal((await repo.list())[0].musicalSettings.bpm,120)});
test('projects-only restore leaves current settings unchanged',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings({...app.defaultSettings(),projectDefaults:{...app.defaultSettings().projectDefaults,bpm:111}});app.state.projects=[app.makeProject({projectName:'source'})];const backup=app.backupObject();backup.settings.projectDefaults.bpm=70;const result=await app.restoreBackup(backup,{settings:false,projects:true});assert.equal(result.added,1);assert.equal(app.getSettings().projectDefaults.bpm,111)});
test('backup JSON round trip can be previewed and restored',async()=>{const {app}=load();const sourceRepo=app.memoryRepository();app.setRepository(sourceRepo);await app.persistSettings(app.defaultSettings());app.state.projects=[app.makeProject({projectName:'roundtrip'})];const text=JSON.stringify(app.backupObject());const preview=await app.previewBackupText(text);assert.equal(preview.ok,true);const targetRepo=app.memoryRepository();app.setRepository(targetRepo);const restored=await app.restoreBackup(preview.backup);assert.equal(restored.added,1);assert.equal((await targetRepo.list())[0].projectName,'roundtrip')});
test('automatic backup remains disabled by default',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings(app.defaultSettings());assert.equal((await app.runAutoBackupCheck('2026-07-20T00:00:00.000Z')).reason,'disabled');assert.equal((await repo.listAutoBackups()).length,0)});
test('automatic backup creates only when enabled and due',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);const settings=app.defaultSettings();settings.backup.automaticEnabled=true;await app.persistSettings(settings);app.state.projects=[app.makeProject({projectName:'auto'})];const created=await app.runAutoBackupCheck('2026-07-20T00:00:00.000Z');assert.equal(created.created,true);const early=await app.runAutoBackupCheck('2026-07-20T01:00:00.000Z');assert.equal(early.reason,'not-due');assert.equal((await repo.listAutoBackups()).length,1)});
test('automatic backup avoids unchanged duplicates after the interval',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);const settings=app.defaultSettings();settings.backup.automaticEnabled=true;settings.backup.intervalHours=1;await app.persistSettings(settings);app.state.projects=[app.makeProject({projectName:'auto'})];await app.runAutoBackupCheck('2026-07-20T00:00:00.000Z');const unchanged=await app.runAutoBackupCheck('2026-07-20T02:00:00.000Z');assert.equal(unchanged.reason,'unchanged');assert.equal((await repo.listAutoBackups()).length,1)});
test('automatic backup retention removes only excess automatic records',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);const settings=app.defaultSettings();settings.backup.automaticEnabled=true;settings.backup.intervalHours=1;settings.backup.maxCopies=2;await app.persistSettings(settings);const project=app.makeProject({projectName:'auto'});app.state.projects=[project];for(let index=0;index<3;index++){project.revision=index+1;project.updatedAt=`2026-07-20T0${index}:00:00.000Z`;await app.runAutoBackupCheck(`2026-07-20T0${index*2}:00:00.000Z`)}assert.equal((await repo.listAutoBackups()).length,2);assert.equal((await repo.list()).length,0)});
test('autosave failure preserves dirty input and reports failure',async()=>{const {app,window}=load();const form=formDocument({projectName:'入力保持',songTitle:'',purpose:'',bpm:120,timeSignature:'4/4',key:'',status:'idea',productionNotes:''});window.document=form.document;window.location.hash='#music-studio/project/missing';app.state.settings=app.defaultSettings();app.state.dirty=true;app.state.editGeneration=1;app.setRepository({...app.memoryRepository(),async get(){return null}});const result=await app.saveCurrentProject('missing');assert.equal(result.ok,false);assert.equal(app.state.dirty,true);assert.equal(form.indicator.textContent,'保存に失敗しました')});
test('save completion from an older edit generation cannot clear newer dirty input',async()=>{const {app,window}=load();const project=app.makeProject({projectName:'race'});const form=formDocument({projectName:'first',songTitle:'',purpose:'',bpm:120,timeSignature:'4/4',key:'',status:'idea',productionNotes:''});window.document=form.document;window.location.hash=`#music-studio/project/${project.projectId}`;app.state.settings=app.defaultSettings();app.state.dirty=true;app.state.editGeneration=1;let release;const repo=app.memoryRepository([project]);const originalPut=repo.put;repo.put=async value=>{await new Promise(resolve=>{release=resolve});return originalPut(value)};app.setRepository(repo);const saving=app.saveCurrentProject(project.projectId);await Promise.resolve();app.state.editGeneration=2;app.state.dirty=true;release();const result=await saving;assert.equal(result.stale,true);assert.equal(app.state.dirty,true);assert.equal(form.indicator.textContent,'未保存の変更があります')});
test('repeated edits cancel the previous delayed save timer',()=>{const {app,window}=load();let next=0,cleared=[];window.setTimeout=()=>++next;window.clearTimeout=id=>cleared.push(id);window.location.hash='#music-studio/project/p1';window.document=formDocument({projectName:'timer',songTitle:'',purpose:'',bpm:120,timeSignature:'4/4',key:'',status:'idea',productionNotes:''}).document;app.state.settings=app.defaultSettings();app.markDirty();app.markDirty();assert.equal(next,2);assert.deepEqual(cleared,[1]);assert.equal(app.state.autosaveTimer,2)});
test('Nova Studio home images use existing root assets and hide true misses',()=>{const appSource=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');assert.match(appSource,/img src="\.\/\$\{fileName\}"/);assert.doesNotMatch(appSource,/img src="\.\/assets\/images\/home\/\$\{fileName\}"/);assert.match(appSource,/this\.hidden=true/)});
test('settings UI exposes app stage, filename preview and immutable privacy controls',()=>{const {app}=load();const html=app.settingsView();assert.match(html,/MS-05 Standard MIDI File Type 1書き出し/);assert.match(html,/musicFileNamePreview/);assert.match(html,/\{time\}/);assert.match(html,/name="privacy\.externalTransfer" disabled/)});
test('new project form includes every supported default signature and minor key',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);const settings=app.defaultSettings();settings.projectDefaults.timeSignature='7/8';settings.projectDefaults.key='Am';await app.persistSettings(settings);const html=app.createView();assert.match(html,/<option selected>7\/8<\/option>/);assert.match(html,/<option selected>Am<\/option>/)});
