'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const codec=require('../music-studio-portable-package'),adapter=require('../music-studio-generation-adapter'),fixture=require('../scripts/music-generation-fixture-backend');
function app(){const w={};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../music-studio'),'utf8'),{window:w});return w.MusicStudio}
const a=app();
const valid=b=>b?.format===a.BACKUP_FORMAT&&b.version===1&&Array.isArray(b.projects)&&b.projects.every(p=>a.validateProject(p).valid)&&(!b.settings||a.validateSettings(b.settings).valid);
function state(id='g1'){const p=a.makeProject({projectId:'p',projectName:'synthetic'});p.audioAssets=[{assetId:'audio',size:3,storage:{kind:'external',reference:'offline.wav'}}];p.extension={future:true};const snapshot=JSON.parse(JSON.stringify({format:a.BACKUP_FORMAT,version:1,projects:[p],settings:a.defaultSettings(),extension:{keep:true}}));return{id,snapshot,settings:snapshot.settings,binaries:[{key:'projects[0].audioAssets[0]',bytes:new Uint8Array([1,2,3])}]}}
async function packed(g=state(),scope='complete'){return codec.write(g.snapshot,{generationId:g.id,bindings:new Map(g.binaries.map(b=>[b.key,b.bytes])),validateMetadata:valid,scope,extensions:{compatibility:{future:true}}})}
function use(f,fault){return adapter.create({backend:f.connect(fault),validateMetadata:valid})}
test('complete portable package to separate durable origin reload preserves logical state/settings/bytes',async()=>{const source=fixture.create(),target=fixture.create();try{const g=state();await use(source).restoreGeneration(g);const reopened=await use(source).reloadGeneration(g.id);const text=await packed(reopened);const decoded=await codec.read(text,{validateMetadata:valid});await use(target).restoreGeneration(decoded.generation);const result=await use(target).selectCommittedGeneration(g.id);assert.deepEqual(result.snapshot,g.snapshot);assert.deepEqual(result.settings,g.settings);assert.deepEqual(result.binaries,g.binaries)}finally{source.dispose();target.dispose()}});
for(const mode of ['duplicate','missing','unexpected','size','digest','unsupported','version','unknown-dependency','legacy'])test('reader blocks '+mode+' before writes',async()=>{const p=JSON.parse(await packed());if(mode==='duplicate')p.entries.push(p.entries[0]);if(mode==='missing')p.entries=[];if(mode==='unexpected')p.entries[0].key='unknown';if(mode==='size')p.entries[0].byteLength=4;if(mode==='digest')p.entries[0].bytes[0]=8;if(mode==='unsupported')p.entries[0].contract='future';if(mode==='version')p.version=2;if(mode==='unknown-dependency')p.manifest[0].collection='future';if(mode==='legacy')delete p.snapshot.projects[0].schemaVersion;await assert.rejects(codec.read(p,{validateMetadata:valid}));});
test('metadata-only legacy and unknown extension retention never imply complete',async()=>{const g=state();g.binaries=[];g.snapshot.projects[0].takes=[{future:true}];const p=await packed(g,'metadata-only');const r=await codec.read(p,{validateMetadata:valid});assert.equal(r.complete,false);assert.deepEqual(r.package.compatibility,{future:true});assert.deepEqual(r.generation.snapshot,g.snapshot);});
for(const fault of ['partial-metadata','partial-binary','late-metadata','late-binary','missing-marker','corrupt-newest','byte-mismatch','Cancel','stale','late-failure'])test('durable '+fault+' preserves older generation and retry',async()=>{const f=fixture.create();try{await use(f).restoreGeneration(state('old'));const g=state('new');let why=null;
 const hook=async(phase,dir)=>{if(fault==='partial-metadata'&&phase==='metadata')fs.writeFileSync(dir+'/metadata','{');if(fault==='partial-binary'&&phase==='binary'){const file=fs.readdirSync(dir).find(n=>n.startsWith('binary-'));fs.writeFileSync(dir+'/'+file,'{');}if(fault==='late-metadata'&&phase==='metadata'||fault==='late-binary'&&phase==='binary'||fault==='late-failure'&&phase==='after-commit')throw Error(fault);if(fault==='Cancel'&&phase==='binary')why='Cancel';if(fault==='stale'&&phase==='binary')g.snapshot.extension.changed=true;if(fault==='missing-marker'&&phase==='after-commit')fs.unlinkSync(dir+'/COMMIT');if(fault==='corrupt-newest'&&phase==='after-commit')fs.writeFileSync(dir+'/metadata','{');if(fault==='byte-mismatch'&&phase==='binary'){const file=fs.readdirSync(dir).find(n=>n.startsWith('binary-'));const b=JSON.parse(fs.readFileSync(dir+'/'+file));b.bytes[0]=9;fs.writeFileSync(dir+'/'+file,JSON.stringify(b))}};
 await assert.rejects(use(f,hook).restoreGeneration(g,{reason:()=>why}));const recovery=await use(f).recoverLatestValidGeneration();assert.equal(recovery.generation.id,fault==='late-failure'?'new':'old');assert.deepEqual((await use(f).reloadGeneration('old')).binaries,state().binaries);await use(f).restoreGeneration(state('retry'));assert.equal((await use(f).recoverLatestValidGeneration()).generation.id,'retry');}finally{f.dispose()}});
test('invalid selected generation fails instead of silently substituting',async()=>{const f=fixture.create();try{await use(f).restoreGeneration(state());await assert.rejects(use(f).selectCommittedGeneration('absent'));await assert.rejects(use(f).cleanupIncompleteGeneration('g1'));assert.equal((await use(f).recoverLatestValidGeneration()).generation.id,'g1')}finally{f.dispose()}});
test('superseded operation never commits and newest wins',async()=>{const f=fixture.create();let release;try{let once=true;const ad=use(f,async phase=>{if(phase==='metadata'&&once){once=false;await new Promise(r=>release=r)}});const first=ad.restoreGeneration(state('first'));while(!release)await new Promise(r=>setImmediate(r));await ad.restoreGeneration(state('second'));release();await assert.rejects(first,/superseded/);assert.equal((await ad.recoverLatestValidGeneration()).generation.id,'second')}finally{f.dispose()}});
test('writer Cancel/stale fail before output and clean retry',async()=>{const g=state();await assert.rejects(codec.write(g.snapshot,{generationId:g.id,validateMetadata:valid,reason:()=> 'Cancel'}),/Cancel/);let calls=0;await assert.rejects(codec.write(g.snapshot,{generationId:g.id,validateMetadata:valid,bindings:new Map(g.binaries.map(b=>[b.key,b.bytes])),reason:()=>{if(++calls===3)g.snapshot.extension.changed=true;return null}}),/stale/);assert.equal((await codec.read(await packed(g),{validateMetadata:valid})).complete,true)});
test('normal no-binary metadata package and legacy extensions preserve compatibility',async()=>{const g=state();g.snapshot.projects[0].audioAssets=[];g.snapshot.projects[0].legacy.extensions.future={value:1};g.binaries=[];const parsed=await codec.read(await packed(g,'metadata-only'),{validateMetadata:valid});assert.equal(parsed.package.scope,'metadata-only');assert.deepEqual(parsed.generation.snapshot,g.snapshot)});
test('settings mismatch and duplicate binary identity fail before prepare',async()=>{const f=fixture.create();try{const g=state();g.settings=JSON.parse(JSON.stringify(g.settings));g.settings.projectDefaults.bpm=88;await assert.rejects(use(f).restoreGeneration(g),/settings/);const d=state();d.binaries.push(d.binaries[0]);await assert.rejects(use(f).restoreGeneration(d),/duplicate/);assert.equal((await f.connect().list()).length,0)}finally{f.dispose()}});
test('manifest duplicate/missing, unknown future binary and unknown metadata safety',async()=>{const text=await packed();for(const mutate of [p=>p.manifest.push(p.manifest[0]),p=>p.manifest=[],p=>p.snapshot.projects[0].audioAssets[0].storage.kind='future']){const p=JSON.parse(text);mutate(p);await assert.rejects(codec.read(p,{validateMetadata:valid}))}const p=JSON.parse(text);p.entries[0].futureMetadata={keep:true};assert.deepEqual((await codec.read(p,{validateMetadata:valid})).package.entries[0].futureMetadata,{keep:true})});
