const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value));
function load(){
  const w={};w.window=w;w.globalThis=w;
  for(const file of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),w,{filename:file});
  return w;
}
function project(id='p'){return{projectId:id,revision:1,musicalSettings:{key:'C'},midiData:{version:1,ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:2}},tracks:[{id:'melody',part:'melody',notes:[]},{id:'drums',part:'drums',notes:[]},{id:'bass',part:'bass',notes:[]}]}}}
function lyricsFixture(){const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];p.midiData.editor.editRange={startMeasure:1,endMeasure:4};const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,core),value=w.MusicStudioAIComposition.candidateValues('lyrics-structure',ctx)[1];return{w,p,core,s,value}}
test('Lyrics anchors use exact changing-meter windows and preserve line stress without allocating notes',()=>{const{w,p,core,s,value}=lyricsFixture(),before=plain({p,s,value}),bundle=w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'B',value},{project:p}),t=bundle.companion.timeline;assert.equal(bundle.type,'metadata-preview');assert.equal(t.alignmentPolicy,'measure-anchor-only');assert.deepEqual(plain(t.slots.map(x=>[x.line,x.measureSlot,x.startTick,x.endTick,x.melodySlot])),[[1,1,0,1000,1],[2,2,1000,1720,2],[3,3,1720,2440,1],[4,4,2440,3160,2]]);assert.deepEqual(plain(t.slots[1].stress),plain(value.lines[1].stress));assert.equal(Object.hasOwn(t.slots[1],'noteIds'),false);assert.deepEqual(plain({p,s,value}),before);assert.match(w.MusicStudioAIComposition.lyricsTimelineRows(t).join('|'),/Lyrics line 2: anchor M2 \/ tick 1000-1720.*7 syllables.*Melody B phrase 2/)});
test('Lyrics partial Preview contains only selected anchor lines and keeps original candidate intact',()=>{const{w,p,core,s,value}=lyricsFixture(),before=plain(value),bundle=w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'B',value},{project:p,measureRange:{startMeasure:2,endMeasure:3}});assert.deepEqual(plain(bundle.companion.timeline.slots.map(x=>x.line)),[2,3]);assert.equal(bundle.companion.timeline.range.startTick,1000);assert.equal(bundle.companion.timeline.range.endTick,2440);assert.deepEqual(plain(value),before);assert.deepEqual(plain(bundle.companion.phraseSlots.map(x=>x.line)),[2,3]);assert.equal(s.undo.length,0)});
for(const bars of [1,2])test(`Lyrics keeps distinct same-measure line anchors within ${bars} bars`,()=>{const{w,p,core,s}=lyricsFixture(),ctx=w.MusicStudioAIComposition.createContext(p,s,core);ctx.range={startMeasure:1,endMeasure:bars};const value=w.MusicStudioAIComposition.candidateValues('lyrics-structure',ctx)[0],t=w.MusicStudioAIComposition.lyricsTimeline(value,s,core);assert.equal(t.slots.length,4);assert.deepEqual(plain(t.slots.map(x=>x.line)),[1,2,3,4]);assert.ok(t.slots.every(x=>x.measureSlot<=bars));assert.equal(t.mutates,false)});
test('Lyrics selection without an anchor shows zero instead of moving an outside line',()=>{const{w,p,core,s}=lyricsFixture(),ctx=w.MusicStudioAIComposition.createContext(p,s,core);ctx.range={startMeasure:1,endMeasure:8};const value=w.MusicStudioAIComposition.candidateValues('lyrics-structure',ctx)[2],t=w.MusicStudioAIComposition.lyricsTimeline(value,s,core,{startMeasure:2,endMeasure:2});assert.equal(t.slots.length,0);assert.match(w.MusicStudioAIComposition.lyricsTimelineRows(t)[0],/Lyrics anchors: 0 \/ M2-2 \/ tick 1000-1720/)});
for(const [label,change,error] of [
  ['outside measure',v=>v.lines[3].measureSlot=5,/invalid-lyrics-line/],
  ['fractional measure',v=>v.lines[0].measureSlot=1.5,/invalid-lyrics-line/],
  ['reordered measure',v=>v.lines[3].measureSlot=1,/invalid-lyrics-line/],
  ['duplicate line',v=>v.lines[1].line=1,/invalid-lyrics-line/],
  ['missing phrase',v=>v.lines[1].melodyPhraseSlot=0,/invalid-lyrics-line/],
  ['wrong stress length',v=>v.lines[3].stress.pop(),/invalid-lyrics-stress/],
  ['unknown stress',v=>v.lines[3].stress[0]='unknown',/invalid-lyrics-stress/],
  ['invalid syllables',v=>v.lines[0].syllableCount=0,/invalid-lyrics-stress/],
  ['line count mismatch',v=>v.lineCount=3,/invalid-lyrics-line-count/],
  ['missing lines',v=>delete v.lines,/lyrics-lines-required/],
  ['wrong melody variant',v=>v.linkedMelodyCandidate='A',/lyrics-melody-reference-mismatch/],
  ['wrong melody family',v=>v.melodyCandidateRef.familyId='other',/lyrics-melody-reference-mismatch/]
])test(`Lyrics rejects ${label} even outside the selected window without mutation`,()=>{const{w,p,core,s,value}=lyricsFixture();change(value);const before=plain({p,s,value});assert.throws(()=>w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'B',value},{project:p,measureRange:{startMeasure:2,endMeasure:2}}),error);assert.deepEqual(plain({p,s,value}),before)});
for(const range of [{startMeasure:0,endMeasure:2},{startMeasure:2,endMeasure:5},{startMeasure:3,endMeasure:2},{startMeasure:'2',endMeasure:3}])test(`Lyrics rejects invalid selected interval ${JSON.stringify(range)}`,()=>{const{w,p,core,s,value}=lyricsFixture();assert.throws(()=>w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'B',value},{project:p,measureRange:range}),/invalid-lyrics-selection/);assert.equal(s.undo.length,0)});
test('Lyrics refuses missing or invalid tick conversion without using cached candidate ticks',()=>{const{w,s,value}=lyricsFixture();for(const core of [{},{measureRangeToTicks:()=>({startTick:0,endTick:0})},{measureRangeToTicks:()=>({startTick:0.5,endTick:1000})}])assert.throws(()=>w.MusicStudioAIComposition.lyricsTimeline(value,s,core),/lyrics-timeline-unavailable|invalid-lyrics-ticks/)});
test('melody candidate creates a non-mutating exact-range partial-edit preview',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[1],candidate={candidateId:'B',value},before=JSON.stringify(s.midiData),bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,candidate,{project:p});assert.equal(bundle.type,'midi-preview');assert.equal(bundle.targetTrackId,'melody');assert.equal(bundle.result.changes.adds.length,8);assert.equal(JSON.stringify(s.midiData),before);assert.equal(bundle.preview.afterNotes.length,8)});
test('melody materialization updates editable notes but never targets a locked note',()=>{const w=load(),p=project();p.midiData.tracks[0].notes=[{id:'free',pitch:60,startTick:0,durationTicks:240,velocity:90},{id:'locked',pitch:62,startTick:480,durationTicks:240,velocity:90,locked:true}];const s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});assert.deepEqual(plain(bundle.result.changes.updates.map(n=>n.id)),['free']);assert.equal(bundle.result.changes.updates.some(n=>n.id==='locked'),false)});
test('chord candidate previews root motion on Bass and links arrangement roles',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('chord',ctx)[1],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'B',value},{project:p});assert.equal(bundle.targetTrackId,'bass');assert.deepEqual(plain(bundle.result.changes.adds.map(n=>n.pitch)),[36,45,41,43]);assert.equal(bundle.companion.kind,'chord-companion');assert.equal(bundle.companion.arrangement.roles.includes('bass'),true)});
test('lyrics candidate stays metadata-only and links phrase slots to matching Melody candidate',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('lyrics-structure',ctx)[2],before=JSON.stringify(s.midiData),bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'C',value},{project:p});assert.equal(bundle.type,'metadata-preview');assert.equal(bundle.companion.kind,'lyrics-melody-link');assert.equal(bundle.companion.linkedMelodyCandidate,'C');assert.equal(bundle.companion.phraseSlots.length,4);assert.equal(JSON.stringify(s.midiData),before)});
test('candidate apply goes through guarded partial edit path and can be undone',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});const applied=w.MusicStudioAICandidatePreview.applyPreview(s,w.MusicStudioEditor,bundle);assert.equal(applied.ok,true);assert.equal(w.MusicStudioEditor.currentTrack(s).notes.length,8);w.MusicStudioEditor.undo(s);assert.equal(w.MusicStudioEditor.currentTrack(s).notes.length,0)});
test('range lock causes candidate apply to fail closed without mutation',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p);w.MusicStudioMeasureLocks.addRangeLock(s,w.MusicStudioEditor,{trackId:'melody',startTick:0,endTick:3840});const ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p}),before=JSON.stringify(s.midiData);assert.throws(()=>w.MusicStudioAICandidatePreview.applyPreview(s,w.MusicStudioEditor,bundle),/rejected|protected|locked/);assert.equal(JSON.stringify(s.midiData),before)});
test('candidate partial adoption applies only the selected exact measure range',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});const applied=w.MusicStudioAICandidatePreview.applyPreview(s,w.MusicStudioEditor,bundle,{startMeasure:1,endMeasure:1});assert.equal(applied.ok,true);const notes=w.MusicStudioEditor.currentTrack(s).notes;assert.ok(notes.length>0);assert.equal(notes.every(note=>note.startTick<1920),true);});
test('phrase Preview uses motif rhythm but never mutates the source before Apply',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],before=JSON.stringify(s.midiData),bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});assert.equal(JSON.stringify(s.midiData),before);assert.equal(bundle.companion.kind,'phrase-plan');assert.equal(new Set(bundle.result.changes.adds.map(note=>note.durationTicks)).size>1,true)});
test('continuation Preview retains the observed source fingerprint and uses its phrase degrees',()=>{const w=load(),p=project();p.midiData.tracks[0].notes=[{id:'n1',pitch:60,startTick:0,durationTicks:240,velocity:80},{id:'n2',pitch:62,startTick:480,durationTicks:480,velocity:82},{id:'n3',pitch:64,startTick:960,durationTicks:240,velocity:84}];const s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('continuation',ctx)[1],before=JSON.stringify(s.midiData),bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'B',value},{project:p});assert.equal(value.derivedFromExisting,true);assert.equal(bundle.companion.sourcePhrase.fingerprint,ctx.sourcePhrase.fingerprint);assert.equal(bundle.result.changes.updates.length,3);assert.equal(JSON.stringify(s.midiData),before)});
test('Chord companion links Bass and Arrangement while Melody alignment stays preview-only',()=>{const w=load(),p=project();p.midiData.tracks[0].notes=[{id:'m1',pitch:61,startTick:0,durationTicks:240,velocity:80}];const s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('chord',ctx)[0],before=JSON.stringify(s.midiData),bundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});assert.equal(bundle.companion.bass.familyId,value.candidateFamily.id);assert.equal(bundle.companion.arrangement.familyId,value.candidateFamily.id);assert.equal(bundle.companion.melodyAlignment.mutates,false);assert.equal(bundle.companion.melodyAlignment.slots[0].sourceNoteIds.includes('m1'),true);assert.equal(JSON.stringify(s.midiData),before)});
test('Section Arrangement and Lyrics companions preserve exact same-family dependencies',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),section=w.MusicStudioAIComposition.candidateValues('section',ctx)[2],arrangement=w.MusicStudioAIComposition.candidateValues('arrangement',ctx)[2],lyrics=w.MusicStudioAIComposition.candidateValues('lyrics-structure',ctx)[2],sectionBundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'C',value:section},{project:p}),arrangementBundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'C',value:arrangement},{project:p}),lyricsBundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'C',value:lyrics},{project:p});assert.equal(sectionBundle.companion.arrangementCandidateRef.familyId,section.candidateFamily.id);assert.equal(arrangementBundle.companion.sectionCandidateRef.familyId,arrangement.candidateFamily.id);assert.equal(lyricsBundle.companion.phraseSlots.every(slot=>slot.stress.length===slot.syllableCount),true)});
test('stale Track and stale range reject candidate Apply without mutation',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],trackBundle=w.MusicStudioAICandidatePreview.createPreview(s,w.MusicStudioEditor,{candidateId:'A',value},{project:p});s.midiData.tracks=s.midiData.tracks.filter(track=>track.id!=='melody');const afterTrackRemoval=JSON.stringify(s.midiData);assert.throws(()=>w.MusicStudioAICandidatePreview.applyPreview(s,w.MusicStudioEditor,trackBundle),/rejected|stale|track/);assert.equal(JSON.stringify(s.midiData),afterTrackRemoval);const s2=w.MusicStudioEditor.createSession(p),rangeBundle=w.MusicStudioAICandidatePreview.createPreview(s2,w.MusicStudioEditor,{candidateId:'A',value},{project:p});w.MusicStudioEditor.setEditRange(s2,{startMeasure:2,endMeasure:2});const afterRangeChange=JSON.stringify(s2.midiData);assert.throws(()=>w.MusicStudioAICandidatePreview.applyPreview(s2,w.MusicStudioEditor,rangeBundle),/rejected|stale-range/);assert.equal(JSON.stringify(s2.midiData),afterRangeChange)});

test('partial adoption clips generated notes at the exact truncated A bar end',()=>{const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,core),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0];value.phraseEvents=[{degree:1,durationUnits:3},{degree:3,durationUnits:2}];const bundle=w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'A',value},{project:p}),before=plain(bundle);w.MusicStudioAICandidatePreview.applyPreview(s,core,bundle,{startMeasure:1,endMeasure:1});assert.ok(core.currentTrack(s).notes.length);assert.equal(core.currentTrack(s).notes.every(n=>n.startTick>=0&&n.startTick+n.durationTicks<=1000),true);assert.deepEqual(plain(bundle),before);core.undo(s);assert.equal(core.currentTrack(s).notes.length,0);core.redo(s);assert.equal(core.currentTrack(s).notes[0].durationTicks,1000)});

test('partial adoption cannot change an existing note outside the selected bar',()=>{const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];p.midiData.tracks[0].notes=[{id:'crossing',pitch:62,startTick:900,durationTicks:400,velocity:90}];const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,core),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'A',value},{project:p}),before=plain(s);assert.throws(()=>w.MusicStudioAICandidatePreview.applyPreview(s,core,bundle,{startMeasure:1,endMeasure:1}),/selection-boundary/);assert.deepEqual(plain(s),before)});

test('exact partial adoption coexists with legacy locks new ranges and additive release',()=>{const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];p.midiData.editor.lockedMeasures=[1];const core=w.MusicStudioEditor,locks=w.MusicStudioMeasureLocks,s=core.createCoordinatedSession(p);locks.unlockRange(s,core,{trackId:'melody',startTick:0,endTick:1000});locks.addRangeLock(s,core,{trackId:'melody',startTick:1000,endTick:1720});const before=plain(s.midiData.editor),ctx=w.MusicStudioAIComposition.createContext(p,s,core),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0];value.phraseEvents=[{degree:1,durationUnits:3},{degree:3,durationUnits:2}];const bundle=w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'A',value},{project:p});w.MusicStudioAICandidatePreview.applyPreview(s,core,bundle,{startMeasure:1,endMeasure:1});assert.equal(core.currentTrack(s).notes[0].durationTicks,1000);assert.equal(locks.isProtected(s.midiData,core,'melody',{startTick:999,durationTicks:1}),false);assert.equal(locks.isProtected(s.midiData,core,'melody',{startTick:1000,durationTicks:1}),true);assert.deepEqual(plain(s.midiData.editor.measureLocks),before.measureLocks);assert.deepEqual(plain(s.midiData.editor.lockedMeasures),before.lockedMeasures);assert.deepEqual(plain(s.midiData.timeSignatureMap),p.midiData.timeSignatureMap)});

for(const action of ['delete','extend'])test(`partial adoption rejects crossing-note ${action} before touching Undo`,()=>{const w=load(),p=project();p.midiData.timeSignatureMap=[{tick:1000,numerator:3,denominator:8}];p.midiData.tracks[0].notes=[{id:'edge',pitch:62,startTick:900,durationTicks:action==='delete'?400:50,velocity:90}];const core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,core),value=w.MusicStudioAIComposition.candidateValues('melody',ctx)[0],bundle=w.MusicStudioAICandidatePreview.createPreview(s,core,{candidateId:'A',value},{project:p}),note=bundle.request.notes.find(n=>n.id==='edge');bundle.result=core.createPartialEditResult(bundle.request,action==='delete'?{deleteNoteIds:['edge']}:{updates:[{...plain(note),durationTicks:400}]});bundle.preview=core.createPartialEditPreview(bundle.request,bundle.result);const before=plain(s);assert.throws(()=>w.MusicStudioAICandidatePreview.applyPreview(s,core,bundle,{startMeasure:1,endMeasure:1}),/selection-boundary/);assert.deepEqual(plain(s),before)});
