const {test}=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');const api=require('../music-studio-distribution-identity');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
function fixture(){return {version:1,buildRevision:'fixture',helper:{version:1,pipelineRevision:2,protocolVersion:1,runtimeVersion:'1',sourceDigest:'a'.repeat(64),requirementsDigest:'b'.repeat(64),identityModuleDigest:'c'.repeat(64),dependencyObserverDigest:'f'.repeat(64)},models:[{id:'fixture',revision:'1',digest:'d'.repeat(64),byteLength:3}],dependencies:[{id:'python',version:'3',digest:'e'.repeat(64)}],architectures:['x86_64'],assets:[]}}
const trust=m=>({manifestDigest:hash(Buffer.from(api.canonical(m))),buildRevision:'fixture'});
test('external trust binding, health then strict verified, legacy unverified',async()=>{let m=fixture();let b=await api.bind(m,trust(m),{sha256:hash});m.models[0].id='mutated';let e;b.configure({configureIdentity:x=>e=x});assert.equal(e.models[0].id,'fixture');assert.deepEqual(await b.verify({connectIdentity:async x=>assert.equal(x.expected,e)}),{mode:'STRICT',status:'VERIFIED'});assert.equal(api.legacy().status,'UNVERIFIED')});
for(const [label,change] of [['version',m=>m.version=2],['missing',m=>delete m.helper],['critical',m=>m.critical=true],['duplicate',m=>m.models.push({...m.models[0]})],['digest',m=>m.models[0].digest='x'],['stale',m=>m.buildRevision='old'],['dependency',m=>m.dependencies[0].version=null],['architecture',m=>m.architectures=[]]])test('manifest rejects '+label,async()=>{let m=fixture();change(m);await assert.rejects(api.bind(m,trust(m),{sha256:hash}))});
test('missing trust and wrong digest fail closed',async()=>{let m=fixture();await assert.rejects(api.bind(m,null,{sha256:hash}));await assert.rejects(api.bind(m,{...trust(m),manifestDigest:'0'.repeat(64)},{sha256:hash}),/digest-mismatch/)});
test('Abort, stale during digest, retry',async()=>{let m=fixture();await assert.rejects(api.bind(m,trust(m),{sha256:hash,signal:{aborted:true}}),/Abort/);let stale=false;await assert.rejects(api.bind(m,trust(m),{sha256:async b=>{stale=true;return hash(b)},reason:()=>stale?'stale':null}),/stale/);assert.ok(await api.bind(m,trust(m),{sha256:hash}))});
test('wrong Helper, model, dependency are forwarded without verified result',async()=>{let m=fixture();let b=await api.bind(m,trust(m),{sha256:hash});for(const code of ['wrong-helper','wrong-model','wrong-dependency'])await assert.rejects(b.verify({connectIdentity:async()=>{throw Error(code)}}),new RegExp(code))});
test('actual browser validator rejects model ID/revision/digest/missing/unexpected and dependency',()=>{const vm=require('node:vm'),fs=require('node:fs');const context=vm.createContext({});vm.runInContext(fs.readFileSync('music-studio-audio-pipeline.js','utf8'),context);const pipeline=context.MusicStudioAudioPipeline,m=fixture(),expected={...m.helper,models:m.models,dependencies:m.dependencies,architectures:m.architectures};const health=()=>({ok:true,localOnly:true,version:1,pipelineRevision:2,sourceDigest:m.helper.sourceDigest,runtimeIdentity:{...m.helper,architecture:'x86_64',modelInventory:{status:'VERIFIED',entries:structuredClone(m.models)},dependencyInventory:{status:'VERIFIED',entries:structuredClone(m.dependencies)}}});assert.equal(pipeline.validateIdentity(health(),expected),true);for(const mutate of [h=>h.runtimeIdentity.modelInventory.entries[0].id='wrong',h=>h.runtimeIdentity.modelInventory.entries[0].revision='wrong',h=>h.runtimeIdentity.modelInventory.entries[0].digest='0'.repeat(64),h=>h.runtimeIdentity.modelInventory.entries=[],h=>h.runtimeIdentity.modelInventory.entries.push({...m.models[0],id:'unexpected'}),h=>h.runtimeIdentity.modelInventory.status='STALE',h=>h.runtimeIdentity.dependencyInventory.entries[0].version='wrong',h=>h.runtimeIdentity.dependencyInventory.entries=[],h=>h.runtimeIdentity.dependencyInventory.entries[0].digest='0'.repeat(64)]){let h=health();mutate(h);assert.throws(()=>pipeline.validateIdentity(h,expected))}});
