const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const vm=require('node:vm');

const source=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8');
function load(){
  const values=new Map([['novaStudio_v01','nova-safe'],['aiMusicHelperProject','ai-safe']]);
  const window={crypto:{randomUUID:(()=>{let n=0;return()=>`id-${++n}`})()},localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)},location:{hash:'#music-studio'},addEventListener(){},setTimeout,clearTimeout,Intl,Date,Math,JSON,console};window.window=window;
  vm.runInNewContext(source,{window,globalThis:window},{filename:'music-studio.js'});return{app:window.MusicStudio,values};
}

test('creates complete safe Version 1 settings defaults',()=>{const {app}=load();const s=app.defaultSettings('2026-01-01T00:00:00.000Z');assert.equal(s.format,'music-studio-settings');assert.equal(s.version,1);assert.equal(s.projectDefaults.bpm,120);assert.equal(s.autosave.enabled,true);assert.equal(s.midi.fileType,1);assert.equal(s.privacy.externalTransfer,false);assert.equal(s.experimental.enabled,false)});
test('normalizes dangerous and malformed setting values',()=>{const {app}=load();const s=app.normalizeSettings({projectDefaults:{bpm:999,timeSignature:'bad'},autosave:{intervalSeconds:0},midi:{velocity:999,channel:0},backup:{maxCopies:0},privacy:{externalTransfer:true},experimental:{enabled:true}});assert.equal(s.projectDefaults.bpm,400);assert.equal(s.projectDefaults.timeSignature,'4/4');assert.equal(s.autosave.intervalSeconds,15);assert.equal(s.midi.velocity,127);assert.equal(s.midi.channel,1);assert.equal(s.backup.maxCopies,1);assert.equal(s.privacy.externalTransfer,false);assert.equal(s.experimental.enabled,false)});
test('settings persist independently in repository',async()=>{const {app,values}=load();const repo=app.memoryRepository();app.setRepository(repo);const s=app.normalizeSettings({projectDefaults:{bpm:88}});await app.persistSettings(s);assert.equal((await repo.getSettings()).projectDefaults.bpm,88);assert.equal(values.get('novaStudio_v01'),'nova-safe');assert.equal(values.get('aiMusicHelperProject'),'ai-safe')});
test('settings JSON import fills missing known fields and ignores unknown fields',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings(app.defaultSettings());const incoming={format:'music-studio-settings',version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),appVersion:'1.0.0',projectDefaults:{bpm:96},unknownSecret:'ignored'};const result=await app.importSettingsText(JSON.stringify(incoming));assert.equal(result.ok,true);assert.equal(result.settings.projectDefaults.bpm,96);assert.equal(result.settings.autosave.enabled,true);assert.equal(result.settings.unknownSecret,undefined)});
test('broken, foreign and future settings JSON are rejected without replacement',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings(app.defaultSettings());assert.equal((await app.importSettingsText('{bad')).ok,false);assert.equal((await app.importSettingsText(JSON.stringify({format:'other',version:1}))).ok,false);assert.equal((await app.importSettingsText(JSON.stringify({format:'music-studio-settings',version:2}))).ok,false);assert.equal((await repo.getSettings()).format,'music-studio-settings')});
test('project defaults affect only newly made projects',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);const existing=app.makeProject({projectName:'existing',bpm:120});await repo.put(existing);await app.persistSettings({...app.defaultSettings(),projectDefaults:{...app.defaultSettings().projectDefaults,bpm:92,timeSignature:'7/8',key:'Am',status:'draft'}});const created=app.makeProject({projectName:'new'});assert.equal(created.musicalSettings.bpm,92);assert.deepEqual({...created.musicalSettings.timeSignature},{numerator:7,denominator:8});assert.equal(created.musicalSettings.key,'Am');assert.equal((await repo.get(existing.projectId)).musicalSettings.bpm,120)});
test('backup contains settings, projects and metadata but no binary bodies',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings(app.defaultSettings());const project=app.makeProject({projectName:'backup',fileReferences:[{name:'song.mid',storage:{kind:'external'}}]});project.audioAssets=[{name:'audio.wav',storage:{kind:'external'}}];await repo.put(project);app.state.projects=await repo.list();const backup=app.backupObject();assert.equal(backup.format,'music-studio-backup');assert.equal(backup.version,1);assert.equal(backup.projects.length,1);assert.equal(backup.metadata.binariesIncluded,false);assert.equal(backup.projects[0].audioAssets[0].storage.requiresReselection,true)});
test('backup validator rejects broken, foreign and future backups',()=>{const {app}=load();assert.equal(app.validateBackup(null).valid,false);assert.equal(app.validateBackup({format:'nova-studio-backup',version:1,projects:[]}).valid,false);assert.equal(app.validateBackup({format:'music-studio-backup',version:2,projects:[]}).valid,false)});
test('restore adds duplicate IDs safely and never removes existing projects',async()=>{const {app}=load();const repo=app.memoryRepository();app.setRepository(repo);await app.persistSettings(app.defaultSettings());const existing=app.makeProject({projectName:'existing'});await repo.put(existing);app.state.projects=await repo.list();const backup=app.backupObject();const result=await app.restoreBackup(backup,{settings:false,projects:true});assert.equal(result.added,1);assert.equal((await repo.list()).length,2);assert.equal((await repo.get(existing.projectId)).projectName,'existing')});
test('settings and backup routes are standalone and host-safe',()=>{const {app}=load();for(const route of ['music-studio/settings','music-studio/backup']){const html=app.renderRoute(route,{standalone:true});assert.match(html,/Music Studioホームへ戻る/);assert.equal(app.isMusicRoute(route),true)}assert.match(app.settingsView(),/外部送信/);assert.match(app.backupView(),/既存データを変更せず/)});
