const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const plain=x=>JSON.parse(JSON.stringify(x));
function fixture(){let n=0;const w={crypto:{randomUUID:()=>`lyrics-${++n}`},location:{hash:'#music-studio'},console,Date,Math,JSON,Intl};w.window=w;w.globalThis=w;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8'),w);const app=w.MusicStudio,p=app.makeProject({projectId:'p',projectName:'Lyrics test',syllableAssignments:[{legacy:true}],midiData:{ppq:480,tracks:[{id:'lead',part:'melody',name:'Lead',notes:[{id:'c',pitch:67,startTick:960,durationTicks:480},{id:'a',pitch:60,startTick:0,durationTicks:480},{id:'b',pitch:64,startTick:480,durationTicks:480}]},{id:'other',part:'bass',notes:[{id:'a',pitch:36,startTick:0,durationTicks:1440}]}]},legacy:{extensions:{future:42}}}),input={trackId:'lead',fromNote:1,toNote:3,text:'君と',reading:'き み ~'};return{w,app,p,input}}
test('Explicit reading assigns exact chronological note IDs, melisma and real timing without MIDI mutation',()=>{const{app,p,input}=fixture(),before=JSON.stringify(p),preview=app.lyricsAssignmentPreview(p,input);assert.equal(JSON.stringify(p),before);assert.deepEqual(plain(preview.assignments.map(a=>[a.noteId,a.token,a.syllableIndex,a.extendsPrevious])),[['a','き',0,false],['b','み',1,false],['c','~',1,true]]);const adopted=app.adoptLyricsAssignment(p,preview);assert.deepEqual(plain(adopted.midiData),plain(p.midiData));assert.deepEqual(plain(adopted.legacy),plain(p.legacy));assert.deepEqual(plain(adopted.syllableAssignments[0]),{legacy:true});assert.equal(adopted.revision,2);assert.equal(adopted.syllableAssignments[1].assignments[2].startTick,960)});
for(const [label,change,expected] of [
 ['missing track',f=>f.input.trackId='absent',/track-identity/],['duplicate track',f=>f.p.midiData.tracks.push(plain(f.p.midiData.tracks[0])),/track-identity/],
 ['drums',f=>f.p.midiData.tracks[0].part='drums',/pitched-track/],['duplicate note',f=>f.p.midiData.tracks[0].notes[0].id='a',/invalid-lyrics-note/],
 ['bad timing',f=>f.p.midiData.tracks[0].notes[0].durationTicks=0,/invalid-lyrics-note/],['bad pitch',f=>f.p.midiData.tracks[0].notes[0].pitch=128,/invalid-lyrics-note/],
 ['out of range',f=>f.input.toNote=4,/note-range/],['fraction range',f=>f.input.fromNote=1.5,/note-range/],['blank lyrics',f=>f.input.text=' ',/text-required/],
 ['too few tokens',f=>f.input.reading='き み',/count-mismatch/],['too many tokens',f=>f.input.reading='き み と よ',/count-mismatch/],['orphan extension',f=>f.input.reading='~ み と',/needs-syllable/],
 ['polyphony',f=>f.p.midiData.tracks[0].notes[2].startTick=0,/monophonic/],['overlap outside partial selection',f=>{f.input.fromNote=2;f.input.toNote=2;f.input.reading='み';f.p.midiData.tracks[0].notes[1].durationTicks=700},/monophonic/],
 ['unknown malformed saved field',f=>f.p.syllableAssignments={},/existing-lyrics/]
])test('Reject '+label+' without mutation',()=>{const f=fixture();change(f);const before=JSON.stringify(f.p);assert.throws(()=>f.app.lyricsAssignmentPreview(f.p,f.input),expected);assert.equal(JSON.stringify(f.p),before)});
test('Stale note/project edits and modified previews cannot be adopted',()=>{const{app,p,input}=fixture(),v=app.lyricsAssignmentPreview(p,input);p.midiData.tracks[0].notes[0].pitch++;assert.throws(()=>app.adoptLyricsAssignment(p,v),/stale/);p.midiData.tracks[0].notes[0].pitch--;v.assignments[0].token='tampered';assert.throws(()=>app.adoptLyricsAssignment(p,v),/modified/)});
test('Partial replacement preserves untouched notes and rejects splitting existing melisma',()=>{const{app,p,input}=fixture(),first=app.adoptLyricsAssignment(p,app.lyricsAssignmentPreview(p,input));const replace={...input,fromNote:1,toNote:1,reading:'ぼ',text:'僕'};const next=app.adoptLyricsAssignment(first,app.lyricsAssignmentPreview(first,replace));assert.deepEqual(plain(next.syllableAssignments[1].assignments.map(a=>a.noteId)),['b','c']);assert.equal(next.syllableAssignments[2].assignments[0].token,'ぼ');const split={...replace,fromNote:2,toNote:2};assert.throws(()=>app.adoptLyricsAssignment(first,app.lyricsAssignmentPreview(first,split)),/syllable-boundary/)});
test('Saved mapping detects changed/missing/ambiguous note identity without auto-repair',()=>{const{app,p,input}=fixture(),saved=app.adoptLyricsAssignment(p,app.lyricsAssignmentPreview(p,input));assert.equal(app.lyricsSavedRows(saved)[0].stale,false);saved.midiData.tracks[0].notes[0].pitch++;const before=JSON.stringify(saved);assert.equal(app.lyricsSavedRows(saved)[0].stale,true);assert.equal(JSON.stringify(saved),before);saved.midiData.tracks[0].notes=[];assert.equal(app.lyricsSavedRows(saved)[0].stale,true)});
async function prepare(){const f=fixture(),repo=f.app.memoryRepository([f.p]);f.app.setRepository(repo);f.app.state.projects=[f.p];f.app.lyricsAssignmentView('p');f.app.lyricsEditor.input=f.input;f.app.lyricsEditor.preview=f.app.lyricsAssignmentPreview(f.p,f.input);return{...f,repo}}
test('UI preview/Cancel does not write and changed input invalidates Apply',async()=>{const{w,app,p,input,repo}=await prepare();w.document={querySelector:s=>s==='#musicLyricsForm'?{elements:Object.fromEntries(Object.entries(input).map(([k,v])=>[k,{value:String(v)}]))}:null};app.previewLyricsAssignment({preventDefault(){}},'p');assert.ok(app.lyricsEditor.preview);assert.deepEqual(plain(await repo.get('p')),plain(p));app.changeLyricsAssignment();assert.equal(app.lyricsEditor.preview,null);app.previewLyricsAssignment(null,'p');app.cancelLyricsAssignment();assert.equal(app.lyricsEditor.preview,null);assert.deepEqual(plain(await repo.get('p')),plain(p))});
test('Adopt saves then reopens and survives JSON and Backup restore with original MIDI/legacy preserved',async()=>{const{app,p,repo}=await prepare();const result=await app.saveLyricsAssignment('p');assert.equal(result.ok,true);const saved=await repo.get('p');assert.equal(saved.syllableAssignments[1].assignments.length,3);assert.deepEqual(plain(saved.midiData),plain(p.midiData));assert.equal(app.lyricsEditor.preview,null);assert.match(app.lyricsAssignmentView('p'),/き/);const exported=await app.exportProject('p'),backup=app.backupObject();for(const mode of ['json','backup']){const f=fixture(),dest=f.app.memoryRepository();f.app.setRepository(dest);assert.equal(mode==='json'?(await f.app.importText(exported.text)).ok:(await f.app.restoreBackup(backup,{settings:false,projects:true})).ok,true);const restored=(await dest.list())[0];assert.deepEqual(plain(restored.syllableAssignments),plain(saved.syllableAssignments));assert.deepEqual(plain(restored.midiData),plain(p.midiData));assert.deepEqual(plain(restored.legacy),plain(p.legacy))}});
for(const [label,change] of [['dirty project',f=>f.app.state.dirty=true],['dirty MIDI',f=>f.app.state.midiEditor={projectId:'p',dirty:true}],['recording',f=>f.app.state.midiInput.recording=true],['changed storage',async f=>{const other=plain(f.p);other.productionNotes='concurrent';await f.repo.put(other)}],['unsupported atomic repository',f=>delete f.repo.compareAndPut]])test('Save '+label+' rejects and retains preview/storage',async()=>{const f=await prepare();await change(f);const before=JSON.stringify(await f.repo.get('p')),preview=f.app.lyricsEditor.preview;assert.equal((await f.app.saveLyricsAssignment('p')).ok,false);assert.equal(JSON.stringify(await f.repo.get('p')),before);assert.equal(f.app.lyricsEditor.preview,preview);assert.equal(f.app.lyricsEditor.busy,false)});
test('Repository switch during async read rejects, and atomic storage baseline check rejects concurrent change',async()=>{const f=await prepare(),original=f.repo.get;f.repo.get=async id=>{f.app.setRepository(f.app.memoryRepository());return original(id)};assert.equal((await f.app.saveLyricsAssignment('p')).ok,false);assert.deepEqual(plain(await original('p')),plain(f.p));const x=await prepare(),cas=x.repo.compareAndPut;x.repo.compareAndPut=async(item,baseline,guard)=>{await x.repo.put({...x.p,productionNotes:'newer'});return cas(item,baseline,guard)};assert.equal((await x.app.saveLyricsAssignment('p')).ok,false);assert.equal((await x.repo.get('p')).productionNotes,'newer')});
test('Storage failure retains retryable input/preview and never reports success',async()=>{const f=await prepare();f.repo.compareAndPut=async()=>{throw Error('disk-full')};assert.equal((await f.app.saveLyricsAssignment('p')).ok,false);assert.match(f.app.lyricsEditor.message,/disk-full/);assert.ok(f.app.lyricsEditor.preview);assert.deepEqual(plain(await f.repo.get('p')),plain(f.p))});
test('Lyrics UI escapes user content and marks feature partial rather than whole AI completion',()=>{const{app,p}=fixture();p.projectName='<script>x</script>';app.state.projects=[p];app.lyricsAssignmentView('p');app.lyricsEditor.input={trackId:'lead',fromNote:1,toNote:1,text:'<img src=x onerror=x>',reading:'<b>'};const html=app.lyricsAssignmentView('p');assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));assert.match(html,/AI歌詞生成・アクセント解析は未実装/);assert.equal(app.FEATURES.find(x=>x.id==='lyrics-notes').status,'working')});
// Transaction model stages writes and completes after all requests, enabling abort/commit tests.
function transactionDB(){const stores=new Map(),control={failPut:false,delayComplete:0};return{control,open(){const open={};queueMicrotask(()=>{open.result={objectStoreNames:{contains:n=>stores.has(n)},createObjectStore(n){stores.set(n,new Map());return{createIndex(){}}},close(){},transaction(name){let active=true,pending=0,scheduled=false;const original=stores.get(name),staged=new Map(original),tx={abort(){if(!active)return;active=false;queueMicrotask(()=>tx.onabort?.())},objectStore(){const req=operation=>{const r={};pending++;queueMicrotask(()=>{if(!active)return;try{r.result=operation();r.onsuccess?.()}catch(e){r.error=e;r.onerror?.()}pending--;if(active&&pending===0&&!scheduled){scheduled=true;setTimeout(()=>{if(active){active=false;stores.set(name,staged);tx.oncomplete?.()}},control.delayComplete)}});return r};return{get:id=>req(()=>staged.has(id)?plain(staged.get(id)):undefined),put:item=>req(()=>{if(control.failPut)throw Error('quota-exceeded');staged.set(item.projectId||item.id,plain(item));return item.projectId||item.id}),getAll:()=>req(()=>[...staged.values()].map(plain))}}};return tx}};open.onupgradeneeded?.();open.onsuccess?.()});return open}}}
async function indexedFixture(){const f=fixture(),db=transactionDB();f.w.indexedDB=db;const repo=f.app.indexedDbRepository();await repo.put(f.p);f.app.setRepository(repo);f.app.state.projects=[f.p];f.app.lyricsAssignmentView('p');f.app.lyricsEditor.preview=f.app.lyricsAssignmentPreview(f.p,f.input);return{...f,db,repo}}
test('IndexedDB Apply waits for transaction completion then reopens exact assignment and unchanged MIDI',async()=>{const f=await indexedFixture();f.db.control.delayComplete=20;let complete=false;const promise=f.app.saveLyricsAssignment('p').then(r=>{complete=true;return r});await new Promise(r=>setTimeout(r,5));assert.equal(complete,false);assert.equal(f.app.lyricsEditor.busy,true);assert.equal((await promise).ok,true);const saved=await f.repo.get('p');assert.deepEqual(plain(saved.midiData),plain(f.p.midiData));assert.equal(saved.syllableAssignments[1].assignments[2].extendsPrevious,true)});
test('IndexedDB quota failure aborts whole assignment without changing original and allows retry',async()=>{const f=await indexedFixture();f.db.control.failPut=true;assert.equal((await f.app.saveLyricsAssignment('p')).ok,false);assert.deepEqual(plain(await f.repo.get('p')),plain(f.p));assert.ok(f.app.lyricsEditor.preview);f.db.control.failPut=false;assert.equal((await f.app.saveLyricsAssignment('p')).ok,true)});
test('IndexedDB stale baseline check happens inside readwrite transaction',async()=>{const f=await indexedFixture(),newer={...f.p,productionNotes:'other tab'};await f.repo.put(newer);assert.equal((await f.app.saveLyricsAssignment('p')).ok,false);assert.deepEqual(plain(await f.repo.get('p')),plain(newer))});
test('Cached project mutation before Apply fails closed even when repository baseline is unchanged',async()=>{const f=await prepare();f.app.state.projects[0].productionNotes='unpersisted';assert.equal((await f.app.saveLyricsAssignment('p')).ok,false);assert.equal((await f.repo.get('p')).productionNotes,'')});
test('AI workspace revision is rebound while candidate content remains intact',()=>{const f=fixture();f.w.MusicStudioAIWorkflow={validateWorkspace:()=>({ok:true})};f.p.aiWorkspace={projectId:'p',baseRevision:1,candidateSets:[{future:true}],future:{opaque:true}};const saved=f.app.adoptLyricsAssignment(f.p,f.app.lyricsAssignmentPreview(f.p,f.input));assert.equal(saved.aiWorkspace.baseRevision,2);assert.deepEqual(plain(saved.aiWorkspace.candidateSets),plain(f.p.aiWorkspace.candidateSets));assert.deepEqual(plain(saved.aiWorkspace.future),{opaque:true})});
test('Malformed imported saved assignments render safely and cannot be overwritten as valid bindings',()=>{const f=fixture();f.p.syllableAssignments.push({format:'music-studio-lyrics-note-assignment',version:1,trackId:'lead',text:'<script>x</script>',assignments:[null,{noteId:'a',startTick:'<img src=x>',durationTicks:1}]});f.app.state.projects=[f.p];assert.equal(f.app.lyricsSavedRows(f.p)[0].stale,true);const html=f.app.lyricsAssignmentView('p');assert.ok(html.includes('&lt;img'));assert.doesNotMatch(html,/<img src=x>/);assert.throws(()=>f.app.adoptLyricsAssignment(f.p,f.app.lyricsAssignmentPreview(f.p,f.input)),/invalid-existing-lyrics-record/)});
for(const [label,key] of [['typed drum','trackType'],['role drum','roleAssignment']])test(label+' cannot accept pitched lyrics',()=>{const f=fixture();f.p.midiData.tracks[0][key]=key==='trackType'?'midi-drums':'drums';assert.throws(()=>f.app.lyricsAssignmentPreview(f.p,f.input),/pitched-track/)});
