'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const resource=require('../music-studio-package-resources'),codec=require('../music-studio-portable-package'),runtime=require('../music-studio-runtime-capabilities'),binding=require('../music-studio-binding-prerequisites'),distribution=require('../music-studio-distribution-capabilities');
const limits={maxPackageBytes:20000,maxEntryCount:2,maxSingleBinaryBytes:3,maxMetadataBytes:10000,maxManifestEntries:2,maxObservedBytes:6};
const window={};window.window=window;vm.runInNewContext(fs.readFileSync(require.resolve('../music-studio'),'utf8'),{window});const app=window.MusicStudio;
function snapshot(){const p=app.makeProject({projectId:'p',projectName:'test'});p.audioAssets=[{assetId:'a',size:3,storage:{kind:'external',reference:'offline.wav'}}];return JSON.parse(JSON.stringify({format:app.BACKUP_FORMAT,version:1,projects:[p],settings:app.defaultSettings()}))}
const valid=b=>app.restorePreflight(b).ok,key='projects[0].audioAssets[0]';
async function packed(){return codec.write(snapshot(),{generationId:'g',validateMetadata:valid,bindings:new Map([[key,new Uint8Array([1,2,3])]]),limits})}
for(const name of resource.names)test('unconfigured '+name+' fails closed',()=>{const l={...limits};delete l[name];assert.throws(()=>resource.configure(l),/unconfigured-limit/)});
for(const value of [-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])test('unsafe limit '+value,()=>assert.throws(()=>resource.configure({...limits,maxPackageBytes:value}),/unsafe-size/));
test('safe cumulative overflow',()=>assert.throws(()=>resource.add(Number.MAX_SAFE_INTEGER,1),/size-overflow/));
test('JSON counter exact UTF8 and surrogate escaping',()=>{for(const x of [null,1,-0,1e21,1e-7,[],{},['あ','😀','\ud800','\udc00','\n','\"','\\'],{a:'x',b:[true,false,null]}])assert.equal(resource.jsonBytes(x),Buffer.byteLength(JSON.stringify(x)))});
for(const [name,limit] of [['maxPackageBytes',1],['maxEntryCount',0],['maxSingleBinaryBytes',2],['maxMetadataBytes',1],['maxManifestEntries',0],['maxObservedBytes',2]])test('reader rejects '+name+' before metadata/digest',async()=>{let called=0;await assert.rejects(codec.read(await packed(),{limits:{...limits,[name]:limit},validateMetadata:()=>{called++;return true}}),/over-limit/);assert.equal(called,0)});
test('exact max package/metadata/entry/manifest/single/cumulative boundary',async()=>{const text=await packed(),p=JSON.parse(text),exact={...limits,maxPackageBytes:Buffer.byteLength(text),maxMetadataBytes:resource.jsonBytes(p.snapshot),maxEntryCount:1,maxManifestEntries:1,maxObservedBytes:3};assert.equal((await codec.read(text,{validateMetadata:valid,limits:exact})).complete,true);assert.equal(await codec.write(p.snapshot,{generationId:'g',validateMetadata:valid,bindings:new Map([[key,new Uint8Array([1,2,3])]]),limits:exact}),text)});
for(const mode of ['negative','overflow','size','duplicate'])test('invalid accounting '+mode,async()=>{const p=JSON.parse(await packed());if(mode==='negative')p.entries[0].byteLength=-1;if(mode==='overflow')p.entries[0].byteLength=Number.MAX_SAFE_INTEGER+1;if(mode==='size')p.entries[0].bytes.pop();if(mode==='duplicate')p.entries.push(p.entries[0]);await assert.rejects(codec.read(p,{limits,validateMetadata:valid}),/unsafe-size|size-mismatch|duplicate-accounting/)});
test('object early rejection does not evaluate accessors',async()=>{const p=JSON.parse(await packed());Object.defineProperty(p.snapshot,'bad',{enumerable:true,get(){throw Error('getter-executed')}});await assert.rejects(codec.read(p,{limits,validateMetadata:valid}),/non-json-accessor/)});
test('writer binary overlimit before byte copy/digest/validation',async()=>{let calls=0;const bytes=new Uint8Array(4);await assert.rejects(codec.write(snapshot(),{generationId:'g',validateMetadata:()=>{calls++;return true},bindings:new Map([[key,bytes]]),limits}),/over-limit:single-binary/);assert.equal(calls,0)});
for(const why of ['Abort','Cancel','stale'])test('bounded Cancel/stale and retry '+why,async()=>{const text=await packed();await assert.rejects(codec.read(text,{validateMetadata:valid,limits,reason:()=>why}),new RegExp(why));assert.equal((await codec.read(text,{validateMetadata:valid,limits})).complete,true)});
function environment(){return{indexedDB:{open(){}},crypto:{subtle:{digest(){}}},TextEncoder,Blob,URL:{createObjectURL(){},revokeObjectURL(){}},AudioContext(){},navigator:{}}}
for(const [id,mutate] of [['indexedDB',e=>delete e.indexedDB],['webCrypto',e=>delete e.crypto],['TextEncoder',e=>delete e.TextEncoder]])test('required runtime missing '+id,()=>{const e=environment();mutate(e);assert.equal(runtime.validate(e).ok,false);assert.ok(runtime.validate(e).failures.includes(id))});
test('optional runtime missing preserves package path and reports fallbacks',()=>{const r=runtime.validate(environment(),'package');assert.equal(r.ok,true);assert.equal(r.matrix.find(x=>x.id==='TextDecoder').status,'FALLBACK AVAILABLE');assert.equal(r.matrix.find(x=>x.id==='structuredClone').status,'FALLBACK AVAILABLE');assert.equal(r.matrix.find(x=>x.id==='Worker').requirement,'OPTIONAL')});
test('File API missing fails export only; IndexedDB session fallback never durable',()=>{const e=environment();delete e.Blob;delete e.URL;delete e.indexedDB;assert.equal(runtime.validate(e,'package').ok,true);assert.equal(runtime.validate(e,'fileExport').ok,false);assert.equal(runtime.validate(e,'durableBrowser').ok,false);assert.equal(runtime.validate(e,'session').ok,true)});
test('webkitAudioContext fallback supported',()=>assert.equal(runtime.validate({webkitAudioContext(){}},'playback').ok,true));
test('no estimate or permission makes no capacity assumption',async()=>{assert.equal((await runtime.estimate({})).status,'UNAVAILABLE');assert.equal((await runtime.estimate({navigator:{storage:{estimate:async()=>({quota:1e12,usage:0})}}})).capacityGuaranteed,false);assert.equal(runtime.permission(undefined),'UNAVAILABLE');assert.equal((await runtime.estimate({navigator:{storage:{estimate:async()=>{throw Error('denied')}}}})).status,'UNAVAILABLE')});
test('unsupported profile fails',()=>assert.throws(()=>runtime.validate({},'unknown'),/unsupported-profile/));
for(const bad of [{destructive:true,legacyPreserved:true,sourceVersion:5,targetVersion:5},{legacyPreserved:false,sourceVersion:5,targetVersion:5},{legacyPreserved:true,sourceVersion:5,targetVersion:6}])test('migration guard '+JSON.stringify(bad),()=>assert.throws(()=>binding.migrationGuard(bad)));
test('binding fails before any backend operation when unconfigured/unavailable/identity missing',()=>{let calls=0;assert.throws(()=>binding.create({backend:{prepare(){calls++}},environment:{}}),/binding-preflight/);assert.equal(calls,0)});
test('helper observations missing never imply offline/signing PASS',()=>{assert.equal(distribution.helper({}).offlineReady,false);const h=distribution.helper({pythonReady:true,dependenciesReady:true,modelsVerified:true,sourceIdentityMatches:true,loopbackOnly:true,networkRequired:false});assert.equal(h.softwareReady,true);assert.equal(h.offlineReady,true);assert.equal(h.notarization,'PHYSICAL TEST REQUIRED');assert.equal(distribution.matrix.find(x=>x.id==='PWA').implementation,'UNSUPPORTED')});
test('distribution claims backed by current source packaging',()=>{const launcher=fs.readFileSync('tools/music-audio-pipeline/mac-app/NovaMusicAudioHelper','utf8'),swift=fs.readFileSync('tools/music-native-wrapper/MusicStudioAppConfiguration.swift','utf8'),req=fs.readFileSync('tools/music-audio-pipeline/requirements.txt','utf8'),workflow=fs.readFileSync('.github/workflows/music-audio-helper-macos.yml','utf8');assert.match(launcher,/pip.*install/);assert.match(launcher,/localOnly/);assert.doesNotMatch(launcher,/serverSha256|pipelineRevision/);assert.match(swift,/https:\/\/puitoybox-cloud/);for(const name of ['demucs','basic-pitch','mido','numpy'])assert.ok(req.includes(name));assert.match(workflow,/codesign/);assert.doesNotMatch(workflow,/notarytool submit/)});
for(const why of [null,'Abort','Cancel','stale'])test('incremental bounded digest '+why,async()=>{const hash=require('node:crypto').createHash('sha256');let aborted=false;const request={chunks:(async function*(){yield new Uint8Array([1]);yield new Uint8Array([2,3])})(),declaredSize:3,limits,digester:{update:c=>hash.update(c),finish:()=>hash.digest('hex'),abort(){aborted=true}},reason:()=>why};if(why){await assert.rejects(resource.validateChunks(request),new RegExp(why));assert.equal(aborted,true)}else assert.equal((await resource.validateChunks(request)).observedBytes,3)});
test('incremental early overflow excludes offending chunk from digest',async()=>{let updates=0,aborts=0;await assert.rejects(resource.validateChunks({chunks:[new Uint8Array([1,2,3,4])],declaredSize:3,limits,digester:{update(){updates++},finish(){throw Error('must not run')},abort(){aborts++}}}),/over-limit/);assert.equal(updates,0);assert.equal(aborts,1)});
test('incremental digest unavailable and short size reject',async()=>{await assert.rejects(resource.validateChunks({limits,declaredSize:3,chunks:[]}),/digest-unavailable/);await assert.rejects(resource.validateChunks({limits,declaredSize:3,chunks:[],digester:{update(){},finish(){}}}),/size-mismatch/)});
function guarded(f,extra={}){const repository={},backend=f.connect();backend.metadataRepository=repository;backend.capabilities={immutableSlots:true,guardedCommit:true,atomicMetadataPublication:true,selectedPointer:true,quotaFailureAtomic:true};return binding.create({backend,repository,limits,environment:environment(),validateMetadata:valid,legacyPreserved:true,...extra})}
test('policy-neutral prebinding generation restore/reload with explicit prerequisites',async()=>{const f=require('../scripts/music-generation-fixture-backend').create();try{const ad=guarded(f),g=(await codec.read(await packed(),{limits,validateMetadata:valid})).generation;await ad.restoreGeneration(g);assert.deepEqual((await ad.reloadGeneration('g')).snapshot,g.snapshot);assert.equal(ad.binding,'INJECTED ONLY');assert.equal(ad.prerequisites.productionBinding,'BLOCKED')}finally{f.dispose()}});
for(const why of ['Abort','Cancel','stale'])test('prebinding '+why+' then independent retry',async()=>{const f=require('../scripts/music-generation-fixture-backend').create();try{const ad=guarded(f),g=(await codec.read(await packed(),{limits,validateMetadata:valid})).generation;await assert.rejects(ad.restoreGeneration(g,{reason:()=>why}),new RegExp(why));assert.equal((await f.connect().list()).length,0);await ad.restoreGeneration(g);assert.equal((await ad.reloadGeneration('g')).id,'g')}finally{f.dispose()}});
test('staging overlimit rejects before prepare',async()=>{const f=require('../scripts/music-generation-fixture-backend').create();try{const ad=guarded(f),g=(await codec.read(await packed(),{limits,validateMetadata:valid})).generation;g.binaries[0].bytes=new Uint8Array(4);await assert.rejects(ad.restoreGeneration(g),/over-limit/);assert.equal((await f.connect().list()).length,0)}finally{f.dispose()}});
test('quota failure is rejected; no success or guessed capacity',async()=>{const repository={},backend=Object.fromEntries(['prepare','stageMetadata','stageBinary','read','commit','list','abort','cleanupIncomplete'].map(k=>[k,async()=>{const e=Error('full');e.name='QuotaExceededError';throw e}]));backend.metadataRepository=repository;backend.capabilities={immutableSlots:true,guardedCommit:true,atomicMetadataPublication:true,selectedPointer:true,quotaFailureAtomic:true};const ad=binding.create({backend,repository,limits,environment:environment(),validateMetadata:valid,legacyPreserved:true});await assert.rejects(ad.restoreGeneration((await codec.read(await packed(),{limits,validateMetadata:valid})).generation),/quota-unavailable/)});
test('browser path WebCrypto unavailable fails codec digest deterministically',async()=>{const w={MusicStudioBinaryBoundary:require('../music-studio-binary-boundary'),MusicStudioPackageResources:resource};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../music-studio-portable-package'),'utf8'),{window:w});await assert.rejects(w.MusicStudioPortablePackage.digest(new Uint8Array([1])),/digest-unavailable/)});
test('Audio Helper health validates exact running source, not localOnly alone',()=>{const digest='a'.repeat(64);assert.equal(distribution.health({localOnly:true},digest).ok,false);assert.equal(distribution.health({localOnly:true,pipelineRevision:2,sourceDigest:digest},digest).ok,true);assert.equal(distribution.health({localOnly:true,pipelineRevision:2,sourceDigest:'b'.repeat(64)},digest).ok,false);assert.equal(distribution.health({localOnly:true,pipelineRevision:2,sourceDigest:digest},undefined).ok,false)});
test('Audio Helper caller-supplied model inventory byte verification and failures',async()=>{const bytes=new Uint8Array([1,2,3]),record={identity:'synthetic-model',byteLength:3,digest:await codec.digest(bytes),bytes};assert.equal((await distribution.models([record],{limits})).ok,true);for(const records of [[],[record,record],[{...record,byteLength:2}],[{...record,digest:'0'.repeat(64)}]])await assert.rejects(distribution.models(records,{limits}));await assert.rejects(distribution.models([record],{limits,reason:()=> 'Cancel'}),/Cancel/)});
