const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value));
function load(){const w={};w.window=w;w.globalThis=w;for(const file of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js','music-studio-ai-family-preview.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),w,{filename:file});return w}
function project(){return{projectId:'family',revision:1,musicalSettings:{key:'C'},midiData:{version:1,ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:2}},tracks:[{id:'melody',part:'melody',notes:[{id:'m1',pitch:61,startTick:0,durationTicks:240,velocity:80},{id:'m2',pitch:64,startTick:480,durationTicks:240,velocity:82}]},{id:'drums',part:'drums',notes:[]},{id:'bass',part:'bass',notes:[]}]}}}
function workspace(w,p,s){const ws=w.MusicStudioAIWorkflow.createWorkspace(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor);for(const kind of w.MusicStudioAIFamilyPreview.KINDS)w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},w.MusicStudioAIComposition.candidateValues(kind,ctx),{adapter:'deterministic-composition-v1'});return ws}
test('family preview groups same A/B/C variant across all linked candidate kinds without mutation',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ws=workspace(w,p,s),before=JSON.stringify(s.midiData),preview=w.MusicStudioAIFamilyPreview.createFamilyPreview(ws,'B',s,w.MusicStudioEditor,p);assert.equal(preview.complete,true);assert.equal(preview.familyMismatch,false);assert.ok(preview.familyId);assert.deepEqual(Object.keys(preview.components),['section','arrangement','chord','melody','continuation','lyrics-structure']);assert.equal(preview.components.chord.preview.type,'midi-preview');assert.equal(preview.components.melody.preview.targetTrackId,'melody');assert.equal(preview.components.chord.preview.targetTrackId,'bass');assert.equal(preview.mutates,false);assert.equal(JSON.stringify(s.midiData),before)});
test('family preview exposes section arrangement chord melody alignment and lyrics phrase summary',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ws=workspace(w,p,s),preview=w.MusicStudioAIFamilyPreview.createFamilyPreview(ws,'A',s,w.MusicStudioEditor,p);assert.ok(preview.summary.sectionShape);assert.ok(preview.summary.arrangementTracks.length);assert.equal(preview.summary.chordProgression.length,4);assert.ok(preview.summary.melodyAlignmentReviewCount>=0);assert.equal(preview.summary.lyricsPhraseSlots,4);assert.ok(w.MusicStudioAIFamilyPreview.familyRows(preview).length>=5)});
test('family preview reports missing kinds instead of inventing dependencies',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ws=w.MusicStudioAIWorkflow.createWorkspace(p),ctx=w.MusicStudioAIComposition.createContext(p,s,w.MusicStudioEditor);w.MusicStudioAIWorkflow.createCandidateSet(ws,'melody',{range:ctx.range},w.MusicStudioAIComposition.candidateValues('melody',ctx),{adapter:'deterministic'});const preview=w.MusicStudioAIFamilyPreview.createFamilyPreview(ws,'C',s,w.MusicStudioEditor,p);assert.equal(preview.complete,false);assert.equal(preview.components.melody.preview.type,'midi-preview');assert.equal(preview.missing.includes('chord'),true);assert.equal(preview.missing.includes('lyrics-structure'),true)});
test('family identity mismatch is surfaced fail-visible while source MIDI remains untouched',()=>{const w=load(),p=project(),s=w.MusicStudioEditor.createSession(p),ws=workspace(w,p,s),before=JSON.stringify(s.midiData),chord=w.MusicStudioAIFamilyPreview.latestSet(ws,'chord');chord.candidates[0].value.candidateFamily.id='wrong-family';const preview=w.MusicStudioAIFamilyPreview.createFamilyPreview(ws,'A',s,w.MusicStudioEditor,p);assert.equal(preview.familyMismatch,true);assert.equal(preview.complete,false);assert.equal(preview.familyId,null);assert.equal(JSON.stringify(s.midiData),before)});
