'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-recording.js'),'utf8');
const selectionSource=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-selection.js'),'utf8');
const musicStudioSource=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8');
function track(id,extra={}){return{id,name:id,notes:[],...extra}}
function harness(tracks,selectedTrackId){const state={midiEditor:{midiData:{tracks},selectedTrackId},midiInput:{recording:false,recordingTrackId:null},melodyAudio:{playback:{playing:false}}};const core={getTrackById:(list,id)=>list.find(item=>item.id===id)||null,resolveTrackCapabilities:item=>({canRecordMidi:item?.trackType!=='audio'&&item?.trackType!=='unknown'}),resolveCoreTrackSlot:item=>item?.id?.startsWith('core-')?item.id:null};let startCalls=0,toggleCalls=0,stopCalls=0;const api={state,resolveCurrentTrackSelection:()=>{const item=core.getTrackById(tracks,state.midiEditor.selectedTrackId);return item?{id:item.id,track:item,capabilities:core.resolveTrackCapabilities(item),isCore:!!core.resolveCoreTrackSlot(item)}:null},editorStartMidiRecording:async()=>{startCalls++;state.midiInput.recording=true;state.midiInput.recordingTrackId=state.midiEditor.selectedTrackId;return{ok:true}},editorToggleMidiRecording:async()=>{toggleCalls++;return{ok:true}},editorStopTransport:()=>{stopCalls++;state.midiInput.recording=false;return{ok:true}}};const sandbox={window:{MusicStudio:api,MusicStudioEditor:core,MusicStudioDynamicTrackSelection:{installed:true,renderDynamicTrackSelection(){}}},document:{querySelector:()=>null},MutationObserver:class{observe(){}},setTimeout};sandbox.window.window=sandbox.window;vm.runInNewContext(source,sandbox);return{api,state,counts:()=>({startCalls,toggleCalls,stopCalls})}}
test('selected external melodic recording keeps the exact Track ID with duplicate display names and roles',async()=>{const tracks=[track('core-melody',{trackType:'midi-melodic',roleAssignment:'melody'}),track('external-a',{name:'Same Name',trackType:'midi-melodic',roleAssignment:'strings'}),track('external-b',{name:'Same Name',trackType:'midi-melodic',roleAssignment:'strings'})];const h=harness(tracks,'external-b');const result=await h.api.editorStartMidiRecording();assert.equal(result.ok,true);assert.equal(h.state.midiInput.recordingTrackId,'external-b');assert.equal(h.counts().startCalls,1)});
test('selected external drum recording routes by Track ID rather than Core Drums',async()=>{const h=harness([track('core-drums',{trackType:'midi-drums'}),track('external-drums',{trackType:'midi-drums'})],'external-drums');await h.api.editorStartMidiRecording();assert.equal(h.state.midiInput.recordingTrackId,'external-drums')});
test('external Stop delegates to the existing recording toggle stop path',async()=>{const h=harness([track('external-b',{trackType:'midi-melodic'})],'external-b');await h.api.editorStartMidiRecording();const result=await h.api.editorToggleMidiRecording();assert.equal(result.ok,true);assert.equal(h.counts().toggleCalls,1)});
test('Core Melody, Drums, and Bass keep the existing recording toggle path',async()=>{for(const id of ['core-melody','core-drums','core-bass']){const h=harness([track(id,{trackType:id==='core-drums'?'midi-drums':'midi-melodic'})],id);await h.api.editorToggleMidiRecording();assert.equal(h.counts().toggleCalls,1,`${id} should delegate`)}});
test('recording adapter is explicitly capability-gated by canRecordMidi',()=>{assert.match(source,/canRecordMidi!==true/);assert.match(source,/recording-capability-blocked/)});
test('selection bridge no longer blocks recording but still blocks Correction and Partial Edit',()=>{const blocked=selectionSource.match(/const BLOCKED_EXTERNAL_ACTIONS=\[([\s\S]*?)\];/)?.[1]||'';assert.doesNotMatch(blocked,/editorToggleMidiRecording|editorStartMidiRecording/);assert.match(blocked,/editorApplyCorrection/);assert.match(blocked,/editorRunPartialEdit/)});
test('existing recording engine commits Stop notes through recordingTrackId and addNotesToTrack',()=>{assert.match(musicStudioSource,/targetTrackId=midi\.recordingTrackId/);assert.match(musicStudioSource,/editor\.addNotesToTrack\(state\.midiEditor,trackId,notes\)/)});
test('recording routing does not widen Correction, Partial Edit, roles, schema, or app version',()=>{assert.doesNotMatch(source,/editorApplyCorrection|editorRunPartialEdit|roleAssignment\s*=/);assert.match(musicStudioSource,/APP_VERSION='1\.4\.0'/);assert.match(musicStudioSource,/SCHEMA_VERSION='1\.0'/)});
