'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ingress=require('../music-studio-ingress'),codec=require('../music-studio-portable-package'),flow=require('../music-studio-publication-prebinding');
function app(){const w={MusicStudioIngress:ingress,location:{hash:''},window:null};w.window=w;vm.runInNewContext(fs.readFileSync('music-studio.js','utf8'),{window:w,console});return w.MusicStudio}
const limits={maxPackageBytes:200000,maxEntryCount:2,maxSingleBinaryBytes:3,maxMetadataBytes:100000,maxManifestEntries:2,maxObservedBytes:6};
function fixture(){const a=app(),repository=a.memoryRepository(),backend=require('../scripts/music-generation-fixture-backend').create(),b=backend.connect();let pointer;const prepare=b.prepare,read=b.read,commit=b.commit;b.prepare=(id,identity)=>{b.identities??=new Map();b.identities.set(id,identity);return prepare(id)};b.read=async id=>({...await read(id),repositoryId:b.identities.get(id)?.repositoryId});b.commit=async(id,marker,c)=>{await commit(id,marker,c);pointer={version:1,repositoryId:b.repositoryId,generationId:id,digest:marker.digest}};b.readSelectedPointer=async()=>pointer;b.repositoryId='repo';b.metadataRepository=repository;b.capabilities={immutableSlots:true,guardedCommit:true,atomicMetadataPublication:true,selectedPointer:true,quotaFailureAtomic:true};const options={backend:b,repository,repositoryId:'repo',limits,legacyPreserved:true,validateMetadata:x=>a.restorePreflight(x).ok,environment:{crypto:require('node:crypto').webcrypto,TextEncoder}};return{a,b,backend,options,setPointer:v=>pointer=v}}
async function pack(f,id='g',repositoryId='repo'){const p=JSON.parse(JSON.stringify(f.a.makeProject({projectId:'p',projectName:'synthetic'})));p.audioAssets=[{assetId:'a',size:3,storage:{kind:'external',reference:'fixture'}}];return codec.write({format:f.a.BACKUP_FORMAT,version:1,projects:[p],settings:JSON.parse(JSON.stringify(f.a.defaultSettings()))},{generationId:id,extensions:{bindingIdentity:{version:1,repositoryId,generationId:id}},bindings:new Map([['projects[0].audioAssets[0]',new Uint8Array([1,2,3])]]),limits,validateMetadata:f.options.validateMetadata})}
function file(text,size=Buffer.byteLength(text)){return{size,text:async()=>text}}
for(const [label,size,max] of [['normal',3,4],['exact',3,3]])test('guarded '+label,async()=>assert.equal((await ingress.create().readText(file('abc',size),{maxBytes:max})).text,'abc'));
for(const [label,size,max] of [['over',3,2],['declared smaller',2,4],['declared larger',4,4],['negative',-1,4],['overflow',Number.MAX_SAFE_INTEGER+1,4]])test('guarded '+label,async()=>{let opened=0;const value={size,text:async()=>{opened++;return'abc'}};await assert.rejects(ingress.create().readText(value,{maxBytes:max}));if(label==='over'||label==='negative'||label==='overflow')assert.equal(opened,0)});
for(const why of ['Cancel','stale'])test('ingress '+why+' and retry',async()=>{const g=ingress.create();await assert.rejects(g.readText(file('abc'),{maxBytes:3,reason:()=>why}),new RegExp(why));assert.equal((await g.readText(file('abc'),{maxBytes:3})).text,'abc')});
for(const mode of ['Abort','Cancel','superseded','reader failure'])test('pending stream '+mode+' cancels and releases',async()=>{let release=false,cancel=false,readEntered;const entered=new Promise(r=>readEntered=r),g=ingress.create(),signal=new AbortController();const value={size:3,stream:()=>({getReader:()=>({read(){readEntered();return mode==='reader failure'?Promise.reject(Error('reader-failure')):new Promise(()=>{})},cancel(){cancel=true},releaseLock(){release=true}})})};const promise=g.readText(value,{maxBytes:3,signal:signal.signal});await entered;if(mode==='Abort')signal.abort();if(mode==='Cancel')g.cancel();if(mode==='superseded')await g.readText(file('abc'),{maxBytes:3});await assert.rejects(promise);assert.equal(cancel,true);assert.equal(release,true)});
test('production Project/Backup file normal and legacy imports',async()=>{const a=app();a.setRepository(a.memoryRepository());await a.refresh();const p=a.makeProject({projectId:'p',projectName:'synthetic'}),text=JSON.stringify(p);assert.equal((await a.importFile(file(text))).ok,true);assert.equal((await a.importText(text)).ok,true);const backup=JSON.stringify({format:a.BACKUP_FORMAT,version:1,projects:[p],settings:a.defaultSettings()});assert.equal((await a.previewBackupFile(file(backup))).ok,true);const before=JSON.stringify(a.state.backupPreview);assert.equal((await a.previewBackupFile(file(backup),{maxBytes:1})).ok,false);assert.equal(JSON.stringify(a.state.backupPreview),before)});
test('production import repository switch during read owns no writes',async()=>{const a=app(),r=a.memoryRepository();a.setRepository(r);await a.refresh();const text=JSON.stringify(a.makeProject({projectId:'p',projectName:'synthetic'}));const result=await a.importFile({size:Buffer.byteLength(text),text:async()=>{a.setRepository(a.memoryRepository());return text}});assert.equal(result.ok,false);assert.equal((await r.list()).length,0)});
test('identity flow bounded ingress -> stage -> commit -> selected acknowledgement',async()=>{const f=fixture();try{const ad=flow.create(f.options),result=await ad.importPackage(file(await pack(f)));assert.equal(result.selectedAcknowledged,true);assert.deepEqual(result.identity,{version:1,repositoryId:'repo',generationId:'g'});assert.equal((await ad.reloadSelected('g')).id,'g')}finally{f.backend.dispose()}});
for(const mode of ['wrong repository','wrong generation','digest failure','over limit','Abort','Cancel','stale'])test('publication rejects '+mode+' before prepare; retry',async()=>{const f=fixture();try{const ad=flow.create(f.options);let text=await pack(f);const obj=JSON.parse(text);if(mode==='wrong repository')obj.bindingIdentity.repositoryId='other';if(mode==='wrong generation')obj.bindingIdentity.generationId='other';if(mode==='digest failure')obj.entries[0].digest='0'.repeat(64);text=JSON.stringify(obj);const control={reason:()=>['Cancel','stale'].includes(mode)?mode:null};if(mode==='Abort'){const s=new AbortController();s.abort();control.signal=s.signal}const value=file(text,mode==='over limit'?limits.maxPackageBytes+1:Buffer.byteLength(text));await assert.rejects(ad.importPackage(value,control));assert.equal((await f.b.list()).length,0);assert.equal((await ad.importPackage(file(await pack(f)))).selectedAcknowledged,true)}finally{f.backend.dispose()}});
for(const mode of ['repository','generation','marker'])test('selected pointer rejects '+mode,async()=>{const f=fixture();try{const ad=flow.create(f.options),result=await ad.importPackage(file(await pack(f)));f.setPointer({version:1,repositoryId:mode==='repository'?'other':'repo',generationId:mode==='generation'?'other':'g',digest:mode==='marker'?'0'.repeat(64):result.generation.identity.digest});await assert.rejects(ad.reloadSelected('g'))}finally{f.backend.dispose()}});
test('backend/repository identity mutation blocks publication',()=>{const f=fixture();try{f.b.repositoryId='other';assert.throws(()=>flow.create(f.options),/repository-identity/)}finally{f.backend.dispose()}});
function helper(){const w={MusicStudio:{importExternalSongFile(){},state:{}},window:null};w.window=w;vm.runInNewContext(fs.readFileSync('music-studio-audio-pipeline.js','utf8'),{window:w,Uint8Array,Blob,Buffer,console});return{w,h:w.MusicStudio.audioStemMidiPipeline}}
const expected={version:1,pipelineRevision:2,sourceDigest:'a'.repeat(64),protocolVersion:1,runtimeVersion:'1',requirementsDigest:'b'.repeat(64),identityModuleDigest:'c'.repeat(64)};
function health(){return{ok:true,localOnly:true,host:'127.0.0.1',port:8766,version:1,pipelineRevision:2,sourceDigest:expected.sourceDigest,runtimeIdentity:{version:1,protocolVersion:1,runtimeVersion:'1',requirementsDigest:expected.requirementsDigest,identityModuleDigest:expected.identityModuleDigest,modelInventory:{status:'UNCONFIGURED',entries:[]}}}}
for(const mode of ['correct','revision','digest','protocol','missing','models','unavailable','non-local','Cancel','Abort'])test('offline Helper '+mode+' and retry',async()=>{const{w,h}=helper();h.configureIdentity(expected);const p=health();if(mode==='revision')p.pipelineRevision=3;if(mode==='digest')p.sourceDigest='d'.repeat(64);if(mode==='protocol')p.runtimeIdentity.protocolVersion=2;if(mode==='missing')delete p.runtimeIdentity;w.fetch=async()=>({ok:mode!=='unavailable',json:async()=>p});const options={};if(mode==='models')options.expected={...expected,models:[{identity:'synthetic'}]};if(mode==='non-local')options.endpoint='https://example.invalid';if(mode==='Cancel')options.reason=()=> 'Cancel';if(mode==='Abort'){const s=new AbortController();s.abort();options.signal=s.signal}if(mode==='correct')assert.equal((await h.connectIdentity()).ok,true);else await assert.rejects(h.connectIdentity(options));w.fetch=async()=>({ok:true,json:async()=>health()});assert.equal((await h.connectIdentity()).ok,true)});
test('Helper strict preflight prevents audio upload on identity failure',async()=>{const{w,h}=helper();h.configureIdentity(expected);let calls=[];w.fetch=async url=>{calls.push(url);return{ok:true,json:async()=>({...health(),sourceDigest:'d'.repeat(64)})}};await assert.rejects(h.processAudioLocally({name:'synthetic.wav',size:3}));assert.deepEqual(calls,['http://127.0.0.1:8766/health'])});
