const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const plain=v=>JSON.parse(JSON.stringify(v));
function fixture(){const w={};w.window=w;for(const f of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js','music-studio-ai-family-preview.js','music-studio-ai-family-apply.js'])vm.runInNewContext(fs.readFileSync(f,'utf8'),w);const p={projectId:'continuation',revision:1,midiData:{ppq:480,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:1000,numerator:3,denominator:8}],editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:4}},tracks:[{id:'melody',part:'melody',notes:[{id:'n1',pitch:60,startTick:0,durationTicks:240,velocity:80},{id:'n2',pitch:62,startTick:1000,durationTicks:240,velocity:82},{id:'n3',pitch:64,startTick:1800,durationTicks:240,velocity:84}]},{id:'bass',part:'bass',notes:[]},{id:'drums',part:'drums',notes:[]}]}},core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),C=w.MusicStudioAIComposition,P=w.MusicStudioAICandidatePreview,A=w.MusicStudioAIFamilyApply,ctx=C.createContext(p,s,core),ws=w.MusicStudioAIWorkflow.createWorkspace(p);for(const kind of w.MusicStudioAIFamilyPreview.KINDS)w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},C.candidateValues(kind,ctx),{adapter:'synthetic-test'});const value=ws.candidateSets.find(x=>x.kind==='continuation').candidates[1].value;return{w,p,core,s,C,P,A,ws,value}}
test('Continuation verifies recorded source and exact changing-meter range without writes',()=>{const{p,s,core,P,value,ws}=fixture(),before=plain({p,s,ws,value}),b=P.createPreview(s,core,{candidateId:'B',value},{project:p}),t=b.companion.sourcePreview;assert.deepEqual(plain(t.range),{startMeasure:1,endMeasure:4,startTick:0,endTick:3160});assert.equal(t.noteCount,3);assert.deepEqual(plain(t.notes.map(n=>n.id)),['n1','n2','n3']);assert.match(P.continuationSourceRows(t).join('|'),/recorded fingerprint and intervals verified/);assert.deepEqual(plain({p,s,ws,value}),before)});
for(const[name,edit,error]of[
 ['missing source',v=>delete v.sourcePhrase,/invalid-continuation-source/],['missing track',v=>v.sourcePhrase.trackId='missing',/source-track-required/],['drum source',v=>v.sourcePhrase.trackId='drums',/source-track-required/],['bad count',v=>v.sourcePhrase.noteCount=1.5,/invalid-continuation-source/],['over limit',v=>v.sourcePhrase.noteCount=65,/invalid-continuation-source/],['missing fingerprint',v=>delete v.sourcePhrase.fingerprint,/invalid-continuation-source/],['wrong fingerprint',v=>v.sourcePhrase.fingerprint='other',/stale-continuation-source/],['wrong count',v=>v.sourcePhrase.noteCount=2,/invalid-continuation-source/],['invalid intervals',v=>v.sourcePhrase.intervals[0]=0.5,/invalid-continuation-source/],['changed intervals',v=>v.sourcePhrase.intervals[0]=3,/stale-continuation-source/],['derived flag',v=>v.derivedFromExisting=false,/invalid-continuation-source/],['bad measure',v=>v.range.startMeasure=0,/invalid-continuation-range/],['string measure',v=>v.range.startMeasure='1',/invalid-continuation-range/],['stale ticks',v=>v.range.endTick=4000,/stale-continuation-source-range/]
])test(`Continuation ${name} fails before Preview or Family preflight with no partial writes`,()=>{const{p,s,core,P,A,value,ws}=fixture();edit(value);const before=plain({p,s,ws});assert.throws(()=>P.createPreview(s,core,{value},{project:p}),error);const plan=A.createPlan(ws,'B',p,s,core,{kinds:['continuation'],metadataOnly:true});assert.ok(plan.issues.some(x=>x.startsWith('preview:continuation:')));assert.equal(A.simulate(plan,ws,p,s,core).ok,false);assert.equal(A.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain({p,s,ws}),before)});
for(const[name,edit]of[
 ['pitch',s=>s.midiData.tracks[0].notes[0].pitch=65],['offset',s=>s.midiData.tracks[0].notes[0].startTick=1],['duration',s=>s.midiData.tracks[0].notes[0].durationTicks=120],['count',s=>s.midiData.tracks[0].notes.pop()],['meter',s=>s.midiData.timeSignatureMap[0].numerator=4]
])test(`Continuation refuses ${name} changed after candidate generation`,()=>{const{s,core,P,value}=fixture();edit(s);const before=plain(s);assert.throws(()=>P.createPreview(s,core,{value}),/stale-continuation-source/);assert.deepEqual(plain(s),before)});
for(const[name,edit]of[['id',s=>s.midiData.tracks[0].notes[0].id='different'],['velocity',s=>s.midiData.tracks[0].notes[0].velocity=99],['octave',s=>s.midiData.tracks[0].notes.forEach(n=>n.pitch+=12)],['opaque note field',s=>s.midiData.tracks[0].notes[0].custom={keep:true}]])test(`Continuation runtime source snapshot refuses ${name} changed after Preview`,()=>{const{s,core,P,value}=fixture(),b=P.createPreview(s,core,{value});edit(s);const before=plain(s);assert.throws(()=>P.applyPreview(s,core,b,{startMeasure:2,endMeasure:2}),/stale-continuation-source-preview/);assert.deepEqual(plain(s),before)});
test('Continuation source uses its recorded track when explicit destination differs',()=>{const{s,core,P,value}=fixture();core.selectTrackById(s,'bass');const b=P.createPreview(s,core,{value});assert.equal(b.targetTrackId,'bass');assert.equal(b.companion.sourcePreview.trackId,'melody');assert.equal(P.applyPreview(s,core,b,{startMeasure:2,endMeasure:2}).ok,true);assert.equal(s.midiData.tracks[0].notes.length,3);assert.ok(core.getTrackById(s.midiData.tracks,'bass').notes.length>0)});
test('Continuation selected measure Apply Undo Redo preserves other measures and tracks',()=>{const{s,core,P,value}=fixture(),before=plain(s.midiData),b=P.createPreview(s,core,{value});assert.equal(P.applyPreview(s,core,b,{startMeasure:2,endMeasure:2}).ok,true);const after=plain(s.midiData);assert.deepEqual(after.tracks[0].notes.filter(n=>n.startTick!==1000),before.tracks[0].notes.filter(n=>n.startTick!==1000));assert.deepEqual(after.tracks.slice(1),before.tracks.slice(1));assert.equal(s.undo.length,1);core.undo(s);assert.deepEqual(plain(s.midiData),before);core.redo(s);assert.deepEqual(plain(s.midiData),after);assert.throws(()=>P.applyPreview(s,core,b),/stale-continuation-source/)});
test('Continuation source empty observed window retains existing fallback and limit',()=>{const{s,core,C,P}=fixture();s.midiData.tracks[0].notes=[];let value=C.candidateValues('continuation',C.createContext({},s,core))[0],b=P.createPreview(s,core,{value});assert.equal(b.companion.sourcePreview.noteCount,0);assert.equal(b.companion.sourcePreview.fingerprint,'empty');assert.ok(b.result.changes.adds.length);s.midiData.tracks[0].notes=Array.from({length:65},(_,i)=>({id:`many-${i}`,pitch:60,startTick:i*10,durationTicks:5,velocity:80}));value=C.candidateValues('continuation',C.createContext({},s,core))[0];b=P.createPreview(s,core,{value});assert.equal(b.companion.sourcePreview.noteCount,64);assert.equal(b.companion.sourcePreview.observedNoteLimit,64)});
test('Continuation invalid source notes duplicate track and missing resolver fail closed',()=>{for(const edit of [s=>s.midiData.tracks.push(plain(s.midiData.tracks[0])),s=>s.midiData.tracks[0].notes[0].pitch=128,s=>s.midiData.tracks[0].notes[0].durationTicks=0,s=>s.midiData.tracks[0].notes[1].id='n1']){const{s,core,P,value}=fixture();edit(s);assert.throws(()=>P.createPreview(s,core,{value}),/continuation-source/)}const{s,core,P,value}=fixture();assert.throws(()=>P.continuationSource(value,s,{...core,measureRangeToTicks:null}),/timeline-unavailable/)});
test('Family Preview shows verified Continuation source and conflicting melody components stay refused',()=>{const{w,p,s,core,ws,A}=fixture(),before=plain({s,ws}),b=w.MusicStudioAIFamilyPreview.createFamilyPreview(ws,'B',s,core,p);assert.match(w.MusicStudioAIFamilyPreview.familyRows(b).join('|'),/Continuation source: melody/);assert.throws(()=>A.createPlan(ws,'B',p,s,core,{kinds:['melody','continuation']}),/conflicting-melody-components/);assert.deepEqual(plain({s,ws}),before)});
