const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const plain=value=>JSON.parse(JSON.stringify(value));
function fixture(){return{projectId:'dynamic-playback',midiData:{ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},editor:{measureCount:4,transport:{countInEnabled:true,metronomeEnabled:true}},tracks:[{id:'core-melody',part:'melody',name:'Melody',channel:1,program:0,notes:[{id:'m',pitch:60,startTick:0,durationTicks:480,velocity:90}]},{id:'core-drums',part:'drums',name:'Drums',channel:10,program:null,notes:[{id:'d',pitch:36,startTick:0,durationTicks:120,velocity:100}]},{id:'core-bass',part:'bass',name:'Bass',channel:2,program:32,notes:[{id:'b',pitch:40,startTick:0,durationTicks:960,velocity:80}]},{id:'ext-a',name:'Strings',trackType:'midi-melodic',roleAssignment:'strings',channel:3,program:48,notes:[{id:'a',pitch:72,startTick:0,durationTicks:480,velocity:70}]},{id:'ext-b',name:'Strings',trackType:'midi-melodic',roleAssignment:'strings',channel:4,program:49,notes:[{id:'b2',pitch:74,startTick:480,durationTicks:480,velocity:71}]},{id:'ext-drums',name:'Imported Drums',trackType:'midi-drums',roleAssignment:'unassigned',channel:10,notes:[{id:'ed',pitch:38,startTick:0,durationTicks:120,velocity:95}]}]}}}
function load(selectedId='ext-b'){const window={crypto:{randomUUID:(()=>{let i=0;return()=>`id-${++i}`})()}};window.window=window;window.globalThis=window;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-editor.js'),'utf8'),window);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-playback.js'),'utf8'),window);const core=window.MusicStudioEditor,session=core.createSession(fixture());core.selectTrackById(session,selectedId);let originalToggleCalls=0,stopCalls=0,shortcutCalls=0,scheduledTracks=[];const synth={supported:()=>true,unlock:async()=>true,stopPlayback:()=>{},playTracks:(tracks,timing)=>{scheduledTracks=plain(tracks);const notes=tracks.flatMap(track=>track.notes||[]);return{ok:true,trackCount:tracks.length,noteCount:notes.length,durationMs:10,playbackStart:0,secondsPerTick:.001,timelineDurationSeconds:.01,tempoMap:timing.tempoMap||[],startTick:Number(timing.startTick)||0,endTick:Number(timing.endTick)||1920,scheduledNotes:notes}}};window.MusicStudioAudio={createSynth:()=>synth};window.MusicStudio={state:{midiEditor:session,midiInput:{recording:false,countingIn:false},melodyAudio:{synth:null,playing:false,starting:false,playRequest:0,playbackTimer:null,playbackFrame:null,playbackState:{mutedByTrackId:{},soloByTrackId:{}},transport:null,status:''}},editorToggleMelodyPlayback(){originalToggleCalls++;return{ok:true,source:'core'}},async editorStopTransport(){stopCalls++;this.state.melodyAudio.playing=false;this.state.melodyAudio.starting=false;return{ok:true,playbackStopped:true}},editorHandleShortcut(){shortcutCalls++;return'original-shortcut'}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-selection.js'),'utf8'),window);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-playback.js'),'utf8'),window);return{window,core,session,api:window.MusicStudio,get originalToggleCalls(){return originalToggleCalls},get stopCalls(){return stopCalls},get shortcutCalls(){return shortcutCalls},get scheduledTracks(){return scheduledTracks}}}
test('selected External MIDI Track resolves by exact Track ID without mutating source data',()=>{const env=load('ext-b'),before=JSON.stringify(env.session.midiData),track=env.api.resolveExternalPlaybackTrack();assert.equal(track.id,'ext-b');assert.equal(track.part,'melody');assert.deepEqual(Array.from(track.notes,note=>note.id),['b2']);assert.equal(JSON.stringify(env.session.midiData),before)});
test('External drum MIDI routes to drum playback while retaining exact source Track ID',()=>{const env=load('ext-drums'),track=env.api.resolveExternalPlaybackTrack();assert.equal(track.id,'ext-drums');assert.equal(track.part,'drums');assert.equal(env.session.midiData.tracks.find(item=>item.id==='ext-drums').part,undefined)});
test('External playback schedules only the selected Track and preserves MIDI project data',async()=>{const env=load('ext-b'),before=JSON.stringify(env.session.midiData),result=await env.api.editorToggleMelodyPlayback();assert.equal(result.ok,true);assert.equal(result.noteCount,1);assert.deepEqual(Array.from(env.scheduledTracks,track=>track.id),['ext-b']);assert.deepEqual(Array.from(env.api.state.melodyAudio.transport.activePlaybackTrackIds),['ext-b']);assert.equal(JSON.stringify(env.session.midiData),before);assert.equal(env.originalToggleCalls,0)});
test('multiple External Solo Tracks play together by exact Track ID',async()=>{const env=load('ext-b');env.api.state.melodyAudio.playbackState.soloByTrackId={'ext-a':true,'ext-b':true};const result=await env.api.editorToggleMelodyPlayback();assert.equal(result.ok,true);assert.equal(result.trackCount,2);assert.equal(result.noteCount,2);assert.deepEqual(Array.from(env.scheduledTracks,track=>track.id),['ext-a','ext-b']);assert.deepEqual(Array.from(env.api.state.melodyAudio.transport.activePlaybackTrackIds),['ext-a','ext-b'])});
test('real Selection to Playback install boundary routes Play button Space and Stop by the same External Track ID',async()=>{const env=load('ext-b'),current=env.core.currentTrack(env.session),playButton={onclick:()=>env.api.editorToggleMelodyPlayback()};assert.equal(env.api.__dynamicTrackSelectionInstalled,true);assert.equal(env.api.__dynamicTrackPlaybackInstalled,true);assert.equal(env.api.__dynamicTrackPlaybackVersion,'1.0.2');assert.equal(env.api.resolveCurrentTrackSelection().id,'ext-b');assert.equal(current.id,'ext-b');assert.deepEqual(Array.from(current.notes,note=>note.id),['b2']);const buttonResult=await playButton.onclick();assert.equal(buttonResult.ok,true);assert.equal(buttonResult.noteCount,1);assert.deepEqual(Array.from(env.scheduledTracks,track=>track.id),['ext-b']);assert.equal(env.originalToggleCalls,0);await env.api.editorStopTransport();assert.equal(env.stopCalls,1);let prevented=false;assert.equal(env.api.editorHandleShortcut({code:'Space',key:' ',preventDefault(){prevented=true}}),true);assert.equal(prevented,true);await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(Array.from(env.scheduledTracks,track=>track.id),['ext-b']);assert.equal(env.originalToggleCalls,0);env.api.state.melodyAudio.playing=true;const stopped=await env.api.editorToggleMelodyPlayback();assert.equal(stopped.playbackStopped,true);assert.equal(env.stopCalls,2)});
test('Core Melody Drums Bass playback remains delegated to the existing transport',async()=>{const env=load('core-drums'),result=await env.api.editorToggleMelodyPlayback();assert.equal(result.source,'core');assert.equal(env.originalToggleCalls,1);assert.equal(env.scheduledTracks.length,0);assert.equal(env.stopCalls,0)});
test('Stop while External playback is active uses the exported transport stop API instead of the PR 227 playback gate',async()=>{const env=load('ext-a');env.api.state.melodyAudio.playing=true;const result=await env.api.editorToggleMelodyPlayback();assert.equal(result.playbackStopped,true);assert.equal(env.stopCalls,1);assert.equal(env.originalToggleCalls,0);assert.equal(env.api.state.melodyAudio.playing,false)});
test('Space remains routed while External Delete without a selected note and other gated shortcuts stay blocked',()=>{const env=load('ext-a');let prevented=false;const handled=env.api.editorHandleShortcut({key:' ',preventDefault(){prevented=true}});assert.equal(handled,true);assert.equal(prevented,true);assert.equal(env.shortcutCalls,0);assert.equal(env.api.editorHandleShortcut({key:'Delete'}),false);assert.equal(env.shortcutCalls,0);assert.equal(env.api.editorHandleShortcut({key:'c',metaKey:true}),false);assert.equal(env.shortcutCalls,0)});
test('Dynamic Playback itself does not widen Recording Correction Partial Edit or Track assignment scope',()=>{const playback=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-playback.js'),'utf8'),selection=fs.readFileSync(path.join(__dirname,'..','music-studio-dynamic-track-selection.js'),'utf8');assert.doesNotMatch(playback,/editorToggleMidiRecording\s*=/);assert.doesNotMatch(playback,/editorPreviewCorrection\s*=/);assert.doesNotMatch(playback,/editorStartPartialEdit\s*=/);assert.doesNotMatch(playback,/roleAssignment\s*=/);for(const action of ['editorStartPartialEdit','editorPreviewCorrection'])assert.ok(selection.includes(`'${action}'`));assert.ok(!selection.includes("'editorToggleMidiRecording'"))});
test('Nova Studio host and standalone Music Studio load playback routing after Dynamic Track Selection',()=>{for(const file of ['index.html','music-studio.html']){const html=fs.readFileSync(path.join(__dirname,'..',file),'utf8'),selection=html.indexOf('music-studio-dynamic-track-selection.js'),playback=html.indexOf('music-studio-dynamic-track-playback.js?v=1.0.2');assert.ok(selection>=0);assert.ok(playback>selection)}});
test('Playback routing keeps project schema and app version unchanged',()=>{const app=fs.readFileSync(path.join(__dirname,'..','music-studio.js'),'utf8');assert.match(app,/const SCHEMA_VERSION='1\.0'/);assert.match(app,/const APP_VERSION='1\.4\.0'/)});
test('selected External playback honors global exact-ID Mute Solo state including other Track solos',()=>{const h=load('ext-b'),gate=h.window.MusicStudioDynamicTrackPlayback.externalTrackAudible;assert.equal(gate('ext-b',{}),true);assert.equal(gate('ext-b',{mutedByTrackId:{'ext-b':true}}),false);assert.equal(gate('ext-b',{soloByTrackId:{'ext-a':true}}),false);assert.equal(gate('ext-b',{soloByTrackId:{'ext-a':true,'ext-b':true}}),true);assert.equal(gate('ext-b',{soloByTrackId:{'ext-b':false}}),true)});
