const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const plain=v=>JSON.parse(JSON.stringify(v));
function fixture(){const w={};w.window=w;w.globalThis=w;for(const f of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js','music-studio-ai-candidate-preview.js','music-studio-ai-family-preview.js','music-studio-ai-family-apply.js'])vm.runInNewContext(fs.readFileSync(f,'utf8'),w);const p={projectId:'arrangement',revision:1,midiData:{ppq:480,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:1000,numerator:3,denominator:8}],editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:4}},tracks:[{id:'melody',part:'melody',notes:[]},{id:'bass',part:'bass',notes:[]},{id:'drums',part:'drums',notes:[]}]}},core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),ctx=w.MusicStudioAIComposition.createContext(p,s,core),ws=w.MusicStudioAIWorkflow.createWorkspace(p);for(const kind of ['section','chord','arrangement'])w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},w.MusicStudioAIComposition.candidateValues(kind,ctx),{adapter:'local-test'});const value=ws.candidateSets.at(-1).candidates[1].value;return{w,p,core,s,ws,value,C:w.MusicStudioAIComposition,P:w.MusicStudioAICandidatePreview,A:w.MusicStudioAIFamilyApply}}
test('Arrangement exact changing-meter entry is an anchor and leaves source MIDI and workspace unchanged',()=>{const{p,s,ws,value,core,C,P}=fixture(),before=plain({p,s,ws,value}),b=P.createPreview(s,core,{value,candidateId:'B'},{project:p}),t=b.companion.timeline;assert.equal(b.type,'metadata-preview');assert.equal(t.alignmentPolicy,'measure-entry-anchor-only');assert.deepEqual(plain(t.entryAnchors),[{measureSlot:2,startTick:1000,endTick:1720,tracks:['melody','bass']}]);assert.match(C.arrangementTimelineRows(t).join('|'),/instrument rendering unallocated.*Arrangement entry: M2 \/ tick 1000-1720/);assert.deepEqual(plain({p,s,ws,value}),before)});
for(const [from,to,count] of [[1,1,0],[2,3,1],[3,4,0]])test(`Arrangement partial ${from}-${to} filters the entry without moving it`,()=>{const{value,s,core,C}=fixture(),t=C.arrangementTimeline(value,s,core,{startMeasure:from,endMeasure:to});assert.equal(t.entryAnchors.length,count);if(count)assert.equal(t.entryAnchors[0].measureSlot,2);assert.match(C.arrangementTimelineRows(t)[0],new RegExp(`anchors: ${count} / M${from}-${to}`));assert.equal(s.undo.length,0)});
for(const [name,change,error] of [
 ['outside entry',v=>v.entry=5,/invalid-arrangement-entry/],['fractional entry',v=>v.entry=1.5,/invalid-arrangement-entry/],['string entry',v=>v.entry='2',/invalid-arrangement-entry/],['missing entry',v=>delete v.entry,/invalid-arrangement-entry/],['empty roles',v=>v.tracks=[],/invalid-arrangement-tracks/],['duplicate roles',v=>v.tracks=['melody','melody'],/invalid-arrangement-tracks/],['bad role',v=>v.tracks=[null],/invalid-arrangement-tracks/],['bad Section ref',v=>v.sectionCandidateRef.candidateId='A',/arrangement-reference-mismatch/],['bad Chord family',v=>v.chordCandidateRef.familyId='other',/arrangement-reference-mismatch/],['missing reference',v=>delete v.sectionCandidateRef,/arrangement-reference-mismatch/],['bad range',v=>v.range.startMeasure=0,/invalid-arrangement-range/]
])test(`Arrangement ${name} rejects even when excluded and Family Apply rolls back`,()=>{const{p,s,ws,value,core,C,A}=fixture();change(value);const before=plain({p,s,ws});assert.throws(()=>C.arrangementTimeline(value,s,core,{startMeasure:3,endMeasure:4}),error);const plan=A.createPlan(ws,'B',p,s,core,{kinds:['section','chord','arrangement'],measureRange:{startMeasure:3,endMeasure:4}});assert.equal(A.simulate(plan,ws,p,s,core).ok,false);assert.equal(A.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain({p,s,ws}),before)});
for(const range of [{startMeasure:0,endMeasure:2},{startMeasure:2,endMeasure:5},{startMeasure:3,endMeasure:2},{startMeasure:'2',endMeasure:3}])test(`Arrangement invalid selection ${JSON.stringify(range)} refuses`,()=>{const{value,s,core,C}=fixture();assert.throws(()=>C.arrangementTimeline(value,s,core,range),/invalid-arrangement-selection/)});
test('Arrangement resolver missing failure fractional overflow and inconsistent ticks refuse',()=>{const{value,s,C}=fixture();for(const core of [{},{measureRangeToTicks(){throw Error('resolver-failure')}},{measureRangeToTicks:()=>({startTick:0,endTick:0})},{measureRangeToTicks:()=>({startTick:0.5,endTick:1000})},{measureRangeToTicks:()=>({startTick:0,endTick:Number.MAX_SAFE_INTEGER+1})},{measureRangeToTicks:r=>({startTick:0,endTick:r.startMeasure===2?9000:1000})}])assert.throws(()=>C.arrangementTimeline(value,s,core),/arrangement|resolver-failure/)});
test('Arrangement Family metadata exact partial Plan Preflight atomic Undo Redo excludes derived timeline from storage',()=>{const{p,s,ws,core,A}=fixture(),before=plain({midi:s.midiData,ws}),plan=A.createPlan(ws,'B',p,s,core,{kinds:['section','chord','arrangement'],metadataOnly:true,measureRange:{startMeasure:2,endMeasure:3}});assert.deepEqual(plain(plan.issues),[]);assert.match(A.planRows(plan).join('|'),/Arrangement entry: M2 \/ tick 1000-1720/);assert.equal(A.simulate(plan,ws,p,s,core).ok,true);assert.equal(A.applyPlan(plan,ws,p,s,core).applied,true);assert.deepEqual(plain(s.midiData),before.midi);assert.equal(s.undo.length,1);const after=plain(ws);assert.doesNotMatch(JSON.stringify(ws),/arrangement-entry-timeline-preview|entryAnchors|alignmentPolicy/);core.undo(s);assert.deepEqual(plain(ws),before.ws);core.redo(s);assert.deepEqual(plain(ws),after)});
test('Arrangement stale plan refuses changed source entry without metadata or history mutation',()=>{const{p,s,ws,value,core,A}=fixture(),plan=A.createPlan(ws,'B',p,s,core,{kinds:['section','chord','arrangement'],metadataOnly:true});value.entry=3;const before=plain({p,s,ws});assert.equal(A.applyPlan(plan,ws,p,s,core).applied,false);assert.deepEqual(plain({p,s,ws}),before)});
test('One-bar legacy B entry outside candidate is rejected explicitly without repair',()=>{const{s,core,C}=fixture(),value=C.candidateValues('arrangement',{...C.defaultContext(),range:{startMeasure:1,endMeasure:1}})[1],before=plain(value);assert.throws(()=>C.arrangementTimeline(value,s,core),/invalid-arrangement-entry/);assert.deepEqual(plain(value),before)});
