const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const plain=v=>JSON.parse(JSON.stringify(v));
function fixture(){const w={};w.window=w;w.globalThis=w;for(const f of ['music-studio-meter-map.js','music-studio-measure-locks.js','music-studio-editor.js','music-studio-ai-workflow.js','music-studio-ai-composition.js'])vm.runInNewContext(fs.readFileSync(f,'utf8'),w);const p={projectId:'references',revision:1,midiData:{ppq:480,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:1000,numerator:3,denominator:8}],editor:{measureCount:4,editRange:{startMeasure:1,endMeasure:4}},tracks:[{id:'melody',part:'melody',notes:[]},{id:'bass',part:'bass',notes:[]},{id:'drums',part:'drums',notes:[]}]}},core=w.MusicStudioEditor,s=core.createCoordinatedSession(p),C=w.MusicStudioAIComposition,ctx=C.createContext(p,s,core),ws=w.MusicStudioAIWorkflow.createWorkspace(p);for(const kind of ['section','chord','arrangement'])w.MusicStudioAIWorkflow.createCandidateSet(ws,kind,{range:ctx.range},C.candidateValues(kind,ctx),{adapter:'local-test'});const value=ws.candidateSets.at(-1).candidates[1].value;return{core,s,ws,value,C}}
const inspect=(f,range={startMeasure:3,endMeasure:4})=>f.C.arrangementReferencePreview(f.value,f.ws,f.s,f.core,range);
test('Arrangement identity inspection uses exact stored Section/Chord and preserves excluded entry, source and unknown fields',()=>{const f=fixture();f.ws.future={opaque:true};f.ws.candidateSets[1].candidates[1].value.future='retained';const before=plain({ws:f.ws,s:f.s});const p=inspect(f);assert.equal(p.timeline.entryAnchors.length,0);assert.equal(p.references.length,2);assert.equal(p.references[1].value.future,'retained');assert.equal(p.references[0].section.segments[0].startTick,1720);assert.match(f.C.arrangementReferenceRows(p).join('|'),/harmony not assessed/);p.references[1].value.future='mutated';assert.deepEqual(plain({ws:f.ws,s:f.s}),before);assert.equal(inspect(f,{startMeasure:2,endMeasure:2}).timeline.entryAnchors[0].startTick,1000)});
for(const kind of ['section','chord'])for(const [label,change,error] of [
 ['missing', (f,set)=>f.ws.candidateSets.splice(f.ws.candidateSets.indexOf(set),1),new RegExp('missing-arrangement-'+kind+'-reference')],
 ['duplicate set',(f,set)=>f.ws.candidateSets.push(plain(set)),new RegExp('ambiguous-arrangement-'+kind+'-reference')],
 ['duplicate candidate',(f,set)=>set.candidates.push(plain(set.candidates[1])),new RegExp('ambiguous-arrangement-'+kind+'-reference')],
 ['wrong kind',(f,set)=>set.candidates[1].value.kind='melody',new RegExp('incompatible-arrangement-'+kind+'-reference')],
 ['wrong variant',(f,set)=>set.candidates[1].value.candidateFamily.variant='A',new RegExp('incompatible-arrangement-'+kind+'-reference')],
 ['key conflict',(f,set)=>set.candidates[1].value.key='G',new RegExp('incompatible-arrangement-'+kind+'-reference')],
 ['range conflict',(f,set)=>set.candidates[1].value.range.endTick++,new RegExp('incompatible-arrangement-'+kind+'-reference')],
 ['malformed collection',(f,set)=>set.candidates=null,/invalid-arrangement-reference-candidates/]
])test(`Arrangement ${kind} ${label} fails closed without mutations`,()=>{const f=fixture(),set=f.ws.candidateSets.find(x=>x.kind===kind);change(f,set);const before=plain({ws:f.ws,s:f.s});assert.throws(()=>inspect(f),error);assert.deepEqual(plain({ws:f.ws,s:f.s}),before)});
test('Malformed excluded Section source and invalid Arrangement anchors cannot hide behind partial reference inspection',()=>{const f=fixture();f.ws.candidateSets[0].candidates[1].value.plan[0].bars=0;assert.throws(()=>inspect(f),/invalid-section-part/);const g=fixture();g.value.entry=99;assert.throws(()=>inspect(g),/invalid-arrangement-entry/);assert.throws(()=>inspect(fixture(),{startMeasure:0,endMeasure:1}),/invalid-arrangement-selection/)});
