const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const context={globalThis:{}};context.globalThis=context;vm.createContext(context);
vm.runInContext(fs.readFileSync('music-studio-ai-workflow.js','utf8'),context);
vm.runInContext(fs.readFileSync('music-studio-ai-assistant-ui.js','utf8'),context);
const UI=context.MusicStudioAIAssistantUI,AI=context.MusicStudioAIWorkflow;
function project(){return{projectId:'p1',revision:1,schemaVersion:'1.0',musicalSettings:{},midiData:{ppq:480,tempo:120,timeSignature:{numerator:4,denominator:4},tracks:[{id:'t1',notes:[]}]}}}
test('assistant state is local-only and starts without a request',()=>{const p=project(),s=UI.createState(p);assert.equal(UI.validateState(s),true);assert.equal(s.activeRequestId,null)});
test('new song requires preview before confirm',()=>{const p=project(),s=UI.createState(p);assert.throws(()=>UI.confirmNewSong(s),/preview/);UI.setNewSongDraft(s,{title:'Test',bpm:72,bars:8,key:'C'});const plan=UI.previewNewSong(s);assert.equal(plan.status,'preview');const out=UI.confirmNewSong(s,{projectId:'new-p'});assert.equal(out.projectInput.projectId,'new-p');assert.equal(out.midiData.tempo,72)});
test('A/B/C candidate decisions retain partial selection',()=>{const s=UI.createState(project());const set=UI.createCandidates(s,'chord',{section:'A'},[{chords:['C','G']},{chords:['Am','F']},{chords:['F','G']}]);assert.deepEqual(Array.from(set.candidates,c=>c.candidateId),['A','B','C']);UI.decideCandidate(s,'B','adopt',{measures:[3,4]});assert.equal(s.workspace.candidateSets[0].adopted[0].candidateId,'B');assert.deepEqual(Array.from(s.workspace.candidateSets[0].adopted[0].selection.measures),[3,4])});
test('view model explicitly forbids network',()=>{const p=project(),s=UI.createState(p),core={currentTrackId:()=> 't1',getTrackById:(ts,id)=>ts.find(t=>t.id===id),measureRangeToTicks:()=>({startMeasure:1,endMeasure:1,startTick:0,endTick:1920}),selectedIds:()=>[],resolveCoreTrackRole:()=>null,resolveTrackType:()=> 'midi-melodic'};const session={projectId:'p1',midiData:p.midiData,editRange:{startMeasure:1,endMeasure:1}};const vm=UI.viewModel(s,p,session,core);assert.equal(vm.mode,'local-only');assert.equal(vm.networkAllowed,false);assert.equal(vm.target.trackId,'t1')});
