const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const boundary=require('../music-studio-binary-boundary');
const plain=x=>JSON.parse(JSON.stringify(x));
function load(){const w={console,setTimeout,clearTimeout,Uint8Array,ArrayBuffer};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../music-studio-binary-boundary'),'utf8'),{window:w,Uint8Array,ArrayBuffer,setTimeout,clearTimeout});vm.runInNewContext(fs.readFileSync(require.resolve('../music-studio'),'utf8'),{window:w});const app=w.MusicStudio,repo=app.memoryRepository();app.setRepository(repo);return{app,repo,w}}
function fixture(app){const p=app.makeProject({projectId:'p',projectName:'synthetic'});p.opaque={keep:true};p.audioAssets=[{assetId:'audio',size:3,storage:{kind:'external',reference:'never-fetch.wav'}}];return{format:app.BACKUP_FORMAT,version:app.BACKUP_VERSION,projects:[p],settings:app.defaultSettings(),opaque:{keep:true}}}
const read=()=>({status:'available',bytes:new Uint8Array([1,2,3])});
for(const status of ['available','missing','external','permission-unavailable','reselection-required','unsupported','ambiguous','unverified'])test(`offline resolver ${status} is explicit`,async()=>{const{app}=load(),b=fixture(app),before=plain(b),r=await boundary.resolve(b,{resolver:()=>({...read(),status})});assert.equal(r.dependencies[0].status,status);assert.equal(r.complete,status==='available');assert.deepEqual(plain(b),before)});
for(const source of [{bytes:new Uint8Array([1,2])},{bytes:new Uint8Array([1,2,3]),expectedBytes:new Uint8Array([3,2,1])}])test('byte mismatch blocks closure',async()=>{const{app}=load();const r=await boundary.resolve(fixture(app),{resolver:()=>({status:'available',...source})});assert.equal(r.complete,false);assert.equal(r.dependencies[0].status,'byte-mismatch')});
test('available without observed bytes is unsupported; claims cannot prove completeness',async()=>{const{app}=load(),b=fixture(app);b.metadata={binariesIncluded:true};const r=await boundary.completeness(b,{packageResolver:()=>({status:'available'})});assert.equal(r.binaryComplete,false);assert.equal(r.dependencies[0].status,'unverified');assert.equal((await boundary.completeness(b,{resolver:read})).binaryComplete,false);assert.equal((await boundary.completeness(b,{packageResolver:read})).binaryComplete,true)});
for(const field of ['takes','versions','checkpoints'])test(`future ${field} contract blocks complete but preserves metadata-only`,async()=>{const{app,repo}=load(),b=fixture(app);b.projects[0][field]=[{binary:'unknown'}];assert.equal((await app.restoreBackup(b,{binaryMode:'complete',binaryResolver:read})).ok,false);assert.equal((await repo.list()).length,0);assert.equal((await app.restoreBackup(b)).outcome,'metadata-only');assert.deepEqual(plain((await repo.get('p'))[field]),b.projects[0][field])});
test('inline MIDI is distinct from original imported file; duplicate descriptors deduplicated',()=>{const{app}=load(),b=fixture(app);const source={kind:'external-song-midi',fileName:'synthetic.mid',fileSize:3};b.projects[0].importSource=source;b.projects[0].midiData={importSource:{...source}};assert.equal(boundary.inventory(b).dependencies.length,2);b.projects[0].midiData.importSource.fileName='other.mid';assert.equal(boundary.inventory(b).dependencies[0].status,'ambiguous')});
test('duplicate identity is ambiguous and never sent to resolver',async()=>{const{app}=load(),b=fixture(app);b.projects[0].audioAssets.push({...b.projects[0].audioAssets[0]});let calls=0;const r=await boundary.resolve(b,{resolver:()=>{calls++;return read()}});assert.equal(calls,0);assert.ok(r.dependencies.every(x=>x.status==='ambiguous'))});
for(const [permission,status] of [['granted','available'],['denied','permission-unavailable'],['prompt','reselection-required']])test(`file handle ${permission} never requests permission`,async()=>{const{app}=load(),b=fixture(app),d=boundary.inventory(b).dependencies[0];let reads=0;const resolver=boundary.createResolver(new Map([[d.key,{handle:{queryPermission:async()=>permission,getFile:async()=>{reads++;return{arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer}}}}]]));const r=await boundary.resolve(b,{resolver});assert.equal(r.dependencies[0].status,status);assert.equal(reads,permission==='granted'?1:0)});
test('explicit Blob/File binding reads detached bytes; multiple candidates ambiguous',async()=>{const{app}=load(),b=fixture(app),key=boundary.inventory(b).dependencies[0].key,file=new Blob([new Uint8Array([1,2,3])]);assert.equal((await boundary.resolve(b,{resolver:boundary.createResolver(new Map([[key,{file}]]))})).complete,true);assert.equal((await boundary.resolve(b,{resolver:boundary.createResolver(new Map([[key,[{file},{file}]]]))})).dependencies[0].status,'ambiguous')});
for(const mode of ['Cancel','stale','timeout'])test(`async ${mode} has zero metadata publication and clean retry`,async()=>{const{app,repo}=load(),b=fixture(app);let release;const pending=app.restoreBackup(b,{binaryMode:'complete',binaryResolver:()=>new Promise(r=>release=r)});await Promise.resolve();if(mode==='Cancel')app.cancelBackupRestore();if(mode==='stale')b.opaque.changed=true;if(mode==='timeout'){release({status:'missing'})}else release(read());const r=await pending;assert.equal(r.ok,false);assert.equal((await repo.list()).length,0);assert.equal(await repo.getSettings(),null);assert.equal((await app.restoreBackup(b)).outcome,'metadata-only')});
test('actual resolver timeout fails closed, never hangs',async()=>{const{app}=load();const r=await boundary.resolve(fixture(app),{resolver:()=>new Promise(()=>{}),timeoutMs:5});assert.equal(r.complete,false);assert.equal(r.dependencies[0].status,'unverified')});
test('resolved bytes alone cannot publish through metadata repository',async()=>{const{app,repo}=load();const r=await app.restoreBackup(fixture(app),{binaryMode:'complete',binaryResolver:read});assert.equal(r.ok,false);assert.match(r.message,/atomic-binary/);assert.equal((await repo.list()).length,0)});
for(const fault of ['late-binary','metadata','Cancel','stale','none'])test(`one generation ${fault} stages before commit and retry`,async()=>{const{app,repo}=load(),b=fixture(app);let stored=null;const adapter={metadataRepository:repo,atomicGeneration:true,async restoreGeneration(g,control){const staged={snapshot:plain(g.snapshot),binaries:g.binaries.map(x=>({key:x.key,bytes:new Uint8Array(x.bytes)}))};if(fault==='Cancel')app.cancelBackupRestore();if(fault==='stale')b.opaque.changed=true;if(control.reason())throw Error(control.reason());if(['late-binary','metadata'].includes(fault))throw Error(fault);const committed=await repo.restoreMetadata(g.snapshot.projects,g.settings,control);stored=staged;return committed}};const r=await app.restoreBackup(b,{binaryMode:'complete',binaryResolver:read,generationAdapter:adapter});assert.equal(r.ok,fault==='none');assert.equal((await repo.list()).length,fault==='none'?1:0);assert.equal(stored!==null,fault==='none');if(fault==='none'){assert.equal(r.outcome,'complete');assert.equal((await app.backupObject()).metadata.binariesIncluded,false)}else assert.equal((await app.restoreBackup(b)).ok,true)});
test('private preflight proof prevents forged or altered report commit',async()=>{const{app}=load(),b=fixture(app),r=await boundary.resolve(b,{resolver:read});await assert.rejects(boundary.commit({...r},{adapter:{atomicGeneration:true,restoreGeneration(){throw Error('called')}}}),/preflight/);r.dependencies=[];await assert.rejects(boundary.commit(r),/preflight/)});
for(const fault of ['missing','mismatch','metadata','duplicate','late-failure','Cancel','stale','none'])test(`recovery ${fault} rejects invalid whole generation`,async()=>{const{app}=load(),b=fixture(app),r=await boundary.resolve(b,{resolver:read});let cancelled=false;const generation={snapshot:plain(b),settings:plain(b.settings),binaries:[{key:r.dependencies[0].key,bytes:new Uint8Array([1,2,3])}]};if(fault==='missing')generation.binaries=[];if(fault==='mismatch')generation.binaries[0].bytes[1]=9;if(fault==='metadata')generation.snapshot.opaque.keep=false;if(fault==='duplicate')generation.binaries.push(generation.binaries[0]);const result=await boundary.verifyRecovery(r,async()=>{if(fault==='late-failure')throw Error('late-failure');if(fault==='Cancel')cancelled=true;if(fault==='stale')b.opaque.changed=true;return generation},{reason:()=>cancelled?'cancelled':null});assert.equal(result.accepted,fault==='none')});
test('no-binary legacy complete Restore retains unknown fields',async()=>{const{app,repo}=load(),b=fixture(app);b.projects[0].audioAssets=[];const r=await app.restoreBackup(b,{binaryMode:'complete'});assert.equal(r.outcome,'complete');assert.deepEqual(plain((await repo.get('p')).opaque),{keep:true})});
test('metadata validation and candidate bytes must both pass Backup completeness',async()=>{const{app}=load(),b=fixture(app);assert.equal((await app.inspectBackupCompleteness(b,{packageResolver:read})).fullBackupComplete,true);b.projects[0].midiData={tracks:[{notes:[{note:999,start:0,duration:1}]}]};const r=await app.inspectBackupCompleteness(b,{packageResolver:read});assert.equal(r.fullBackupComplete,false);assert.equal(r.metadata.ok,false)});
test('late second binary read failure never publishes first Project or settings',async()=>{const{app,repo}=load(),b=fixture(app);b.projects.push({...plain(b.projects[0]),projectId:'second'});let calls=0;const r=await app.restoreBackup(b,{binaryMode:'complete',binaryResolver:()=>{if(++calls===2)throw Error('late-reader-failure');return read()}});assert.equal(r.ok,false);assert.equal((await repo.list()).length,0);assert.equal(await repo.getSettings(),null);assert.equal((await app.restoreBackup(b)).added,2)});
test('superseded binary preflight cannot publish after newer metadata Restore',async()=>{const{app,repo}=load(),b=fixture(app);let release;const pending=app.restoreBackup(b,{binaryMode:'complete',binaryResolver:()=>new Promise(r=>release=r)});await Promise.resolve();const newer=fixture(app);newer.projects[0].projectId='newer';assert.equal((await app.restoreBackup(newer)).ok,true);release(read());assert.equal((await pending).ok,false);assert.equal(await repo.has('p'),false);assert.equal(await repo.has('newer'),true)});
test('settings-only complete Restore does not resolve excluded Projects',async()=>{const{app,repo}=load(),b=fixture(app);let reads=0;const r=await app.restoreBackup(b,{binaryMode:'complete',projects:false,binaryResolver:()=>{reads++;return read()}});assert.equal(r.ok,true);assert.equal(reads,0);assert.equal((await repo.list()).length,0);assert.notEqual(await repo.getSettings(),null)});
test('original imported MIDI bytes required even when inline midiData exists',async()=>{const{app,repo}=load(),b=fixture(app);b.projects[0].audioAssets=[];b.projects[0].midiData={tracks:[],importSource:{kind:'standard-midi-file',fileName:'fixture.mid',fileSize:3}};const r=await app.restoreBackup(b,{binaryMode:'complete'});assert.equal(r.outcome,'reselection-required');assert.equal((await repo.list()).length,0);assert.equal((await app.restoreBackup(b)).ok,true)});
test('unknown import source blocks complete coverage and retains metadata',async()=>{const{app,repo}=load(),b=fixture(app);b.projects[0].importSource={kind:'future-source',unknown:true};assert.equal((await app.restoreBackup(b,{binaryMode:'complete',binaryResolver:read})).ok,false);assert.equal((await app.restoreBackup(b)).ok,true);assert.deepEqual(plain((await repo.get('p')).importSource),b.projects[0].importSource)});
test('settings recovery mismatch cannot be hidden by an unchanged raw Backup snapshot',async()=>{const{app}=load(),b=fixture(app),r=await boundary.resolve(b,{resolver:read}),generation={snapshot:plain(b),settings:plain(b.settings),binaries:[{key:r.dependencies[0].key,bytes:new Uint8Array([1,2,3])}]};generation.settings.projectDefaults.bpm=37;assert.equal((await boundary.verifyRecovery(r,async()=>generation)).accepted,false)});
test('metadata-only preflight exposes original file and unsupported future coverage without reads',async()=>{const{app}=load(),b=fixture(app);b.projects[0].importSource={kind:'standard-midi-file',fileName:'legacy.mid',fileSize:3};b.projects[0].takes=[];const r=await app.restoreBackup(b);assert.equal(r.outcome,'metadata-only');assert.equal(r.preflight.binaryDependencies.length,2);assert.equal(r.preflight.binaryContractIssues[0].reason,'unimplemented-production-contract');assert.equal(r.preflight.completeBinaryBackup,false)});
