const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function load(){const w={};w.window=w;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-meter-map.js'),'utf8'),w);return w.MusicStudioMeterMap}
const plain=v=>JSON.parse(JSON.stringify(v));
const data=()=>({ppq:480,timeSignature:{numerator:4,denominator:4},timeSignatureMap:[{tick:0,numerator:4,denominator:4},{tick:960,numerator:3,denominator:4}],tempoMap:[{tick:960,bpm:90}],keySignatureMap:[{tick:960,sharps:2,minor:false}],tracks:[{notes:[{startTick:959,durationTicks:3,pitch:60}]}]});
test('A policy ends a partial old bar at the exact meter event and starts the new bar there',()=>{const api=load(),d=data(),before=plain(d);assert.deepEqual(plain(api.positionAtTick(d,959)),{measure:1,beat:959/480+1,measureStartTick:0,measureEndTick:960,ticksPerBeat:480,ticksPerMeasure:1920,numerator:4,denominator:4});assert.deepEqual(plain(api.positionAtTick(d,960)),{measure:2,beat:1,measureStartTick:960,measureEndTick:2400,ticksPerBeat:480,ticksPerMeasure:1440,numerator:3,denominator:4});assert.equal(api.positionAtTick(d,2400).measure,3);assert.deepEqual(plain(d),before)});
test('measure-to-tick and ranges honor shortened measures rather than shifting the event',()=>{const api=load(),d=data();assert.deepEqual([1,2,3,4].map(m=>api.tickAtMeasure(d,m)),[0,960,2400,3840]);assert.deepEqual(plain(api.rangeToTicks(d,1,2)),{startMeasure:1,endMeasure:2,startTick:0,endTick:2400})});
test('boundary changes do not add an empty measure',()=>{const api=load(),d=data();d.timeSignatureMap[1].tick=1920;assert.equal(api.tickAtMeasure(d,2),1920);assert.equal(api.tickAtMeasure(d,3),3360)});
test('multiple unsorted changes preserve exact fractional-beat boundaries and source order',()=>{const api=load(),d=data();d.timeSignatureMap=[{tick:2401,numerator:6,denominator:8},{tick:960,numerator:3,denominator:4},{tick:0,numerator:4,denominator:4}];const before=plain(d);assert.equal(api.positionAtTick(d,2400).measure,3);assert.equal(api.positionAtTick(d,2401).measure,4);assert.equal(api.tickAtMeasure(d,4),2401);assert.equal(api.positionAtTick(d,2641).beat,2);assert.deepEqual(plain(d),before)});
test('legacy initial signature and missing metadata remain read-only',()=>{const api=load(),d={ppq:960,timeSignature:{numerator:7,denominator:8}},before=plain(d);assert.equal(api.tickAtMeasure(d,2),3360);assert.equal(api.positionAtTick(d,3360).measure,2);assert.deepEqual(plain(d),before);assert.equal(api.tickAtMeasure({},2),1920)});
test('later first event uses the legacy meter only before the event',()=>{const api=load(),d=data();d.timeSignatureMap.shift();assert.equal(api.positionAtTick(d,959).numerator,4);assert.equal(api.positionAtTick(d,960).numerator,3)});
test('equivalent same-tick events can be indexed but contradictory ones are rejected',()=>{const api=load(),d=data();d.timeSignatureMap.push({...d.timeSignatureMap[1]});assert.equal(api.createTimeline(d).segments.length,2);d.timeSignatureMap.push({tick:960,numerator:5,denominator:4});assert.throws(()=>api.createTimeline(d),/conflicting-meter/)});
for(const invalid of [{ppq:0},{timeSignatureMap:{}},{timeSignatureMap:[{tick:1.5,numerator:3,denominator:4}]},{timeSignatureMap:[{tick:-1,numerator:3,denominator:4}]},{timeSignature:{numerator:0,denominator:4}},{timeSignature:{numerator:3,denominator:3}}])test('malformed timing is rejected without repair '+JSON.stringify(invalid),()=>{const api=load(),before=plain(invalid);assert.throws(()=>api.createTimeline(invalid));assert.deepEqual(plain(invalid),before)});
test('tick-to-measure inverse holds at every returned boundary in mixed meter',()=>{const api=load(),d=data();d.timeSignatureMap.push({tick:5001,numerator:5,denominator:8});for(let m=1;m<20;m++){const tick=api.tickAtMeasure(d,m);assert.equal(api.positionAtTick(d,tick).measure,m);assert.equal(api.positionAtTick(d,tick).beat,1)}});
test('fractional nominal bar lengths are not rounded to integer ticks',()=>{const api=load(),d={ppq:24,timeSignature:{numerator:1,denominator:128}};assert.equal(api.tickAtMeasure(d,2),.75);assert.equal(api.positionAtTick(d,3).measure,5)});
