const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function load(){const w={crypto:{randomUUID:(()=>{let n=0;return()=>`new-${++n}`})()},console,setTimeout,clearTimeout};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../music-studio.js'),'utf8'),{window:w});const app=w.MusicStudio,repo=app.memoryRepository();app.setRepository(repo);return{app,repo,w}}
const plain=x=>JSON.parse(JSON.stringify(x));
function backup(app,projects,settings=app.defaultSettings()){return{format:app.BACKUP_FORMAT,version:app.BACKUP_VERSION,projects,settings}}
function project(app,id){return app.makeProject({projectId:id,projectName:id,midiData:{ppq:480,tracks:[{name:'Legacy',notes:[{note:60,start:0,duration:480}]}]}})}
for(const [name,change] of [
 ['MIDI pitch',p=>p.midiData.tracks[0].notes[0].note=128],
 ['muted invalid MIDI',p=>{p.midiData.tracks[0].muted=true;p.midiData.tracks[0].notes[0].duration=0}],
 ['MIDI version',p=>p.midiData.version=999],
 ['MIDI ppq',p=>p.midiData.ppq=0],
 ['MIDI tracks',p=>p.midiData.tracks={}],
 ['MIDI tempo map',p=>p.midiData.tempoMap=[{tick:-1,bpm:120}]],
 ['dependency',p=>p.audioAssets=[{assetId:'a',derivedFromAssetId:'missing'}]],
 ['duplicate identity',p=>p.audioAssets=[{assetId:'a'},{assetId:'a'}]],
 ['asset shape',p=>p.midiAssets={}],
 ['reference shape',p=>p.fileReferences=[{id:'file',storage:{reference:{}}}]],
 ['metadata',p=>p.schemaVersion=999]
])test(`invalid second ${name} publishes neither Projects nor settings`,async()=>{const{app,repo}=load(),old=app.makeProject({projectId:'existing',projectName:'existing'}),settings=app.defaultSettings();settings.projectDefaults.bpm=99;await repo.put(old);await repo.putSettings(settings);const a=project(app,'a'),b=project(app,'b');change(b);const result=await app.restoreBackup(backup(app,[a,b]));assert.equal(result.ok,false);assert.equal(result.added,0);assert.deepEqual(plain(await repo.list()),[plain(old)]);assert.deepEqual(plain(await repo.getSettings()),plain(settings))});
test('atomic metadata Restore preserves legacy and opaque Project MIDI settings fields',async()=>{const{app,repo}=load(),p=project(app,'legacy'),s=app.defaultSettings();p.unknown={keep:true};p.legacy.extensions.extra={keep:true};s.unknown={keep:true};s.general.opaque=42;s.privacy.externalTransfer=true;const before=plain(p),result=await app.restoreBackup(backup(app,[p],s));assert.equal(result.ok,true);assert.equal(result.atomicMetadata,true);const saved=await repo.get(p.projectId);assert.deepEqual(plain(saved.midiData),before.midiData);assert.deepEqual(plain(saved.unknown),before.unknown);assert.deepEqual(plain(saved.legacy),before.legacy);const stored=await repo.getSettings();assert.equal(stored.unknown.keep,true);assert.equal(stored.general.opaque,42);assert.equal(stored.privacy.externalTransfer,false);await app.loadSettings();assert.equal(app.backupObject().settings.unknown.keep,true);assert.deepEqual(plain(p),before)});
test('external metadata remains restorable without claiming binary present or complete',async()=>{const{app,repo}=load(),p=project(app,'dependencies');p.audioAssets=[{assetId:'external',storage:{kind:'external',reference:'offline.wav'}},{assetId:'missing',missing:true},{assetId:'select',storage:{requiresReselection:true}},{assetId:'unsupported',storage:{kind:'future'}}];const result=await app.restoreBackup(backup(app,[p]),{settings:false});assert.equal(result.ok,true);assert.deepEqual(plain(result.preflight.dependencies.map(d=>d.status)),['external','missing','reselection-required','unsupported']);assert.equal(result.preflight.completeBinaryBackup,false);assert.ok(result.preflight.dependencies.every(d=>d.present==='unverified'));assert.deepEqual(plain((await repo.get(p.projectId)).audioAssets),plain(p.audioAssets))});
test('same IDs in input and existing data are additive and never overwrite',async()=>{const{app,repo}=load(),p=project(app,'same');await repo.put(p);const before=plain(await repo.get('same')),result=await app.restoreBackup(backup(app,[p,p]),{settings:false});assert.equal(result.added,2);assert.equal((await repo.list()).length,3);assert.deepEqual(plain(await repo.get('same')),before);assert.equal(new Set((await repo.list()).map(p=>p.projectId)).size,3)});
test('late staging failure retains all old metadata and retry succeeds',async()=>{const{app,repo,w}=load(),p=project(app,'same');await repo.put(p);w.crypto.randomUUID=()=> 'same';const result=await app.restoreBackup(backup(app,[project(app,'first'),p]));assert.equal(result.ok,false);assert.equal(await repo.has('first'),false);assert.equal(await repo.getSettings(),null);let i=0;w.crypto.randomUUID=()=>`retry-${++i}`;assert.equal((await app.restoreBackup(backup(app,[project(app,'first'),p]))).ok,true);assert.equal((await repo.list()).length,3)});
for(const mode of ['Cancel','stale input','stale repository','superseded'])test(`${mode} before publication has zero writes; retry remains usable`,async()=>{const{app,repo}=load(),p=project(app,'a'),value=backup(app,[p]),atomic=repo.restoreMetadata;let release;repo.restoreMetadata=async(...args)=>{await new Promise(resolve=>release=resolve);return atomic(...args)};const pending=app.restoreBackup(value);await Promise.resolve();let newer;
 if(mode==='Cancel')app.cancelBackupRestore();
 if(mode==='stale input')value.projects[0].projectName='changed';
 if(mode==='stale repository')app.setRepository(app.memoryRepository());
 if(mode==='superseded'){repo.restoreMetadata=atomic;newer=app.restoreBackup(backup(app,[project(app,'newer')]),{settings:false})}
 release();const result=await pending;assert.equal(result.ok,false);assert.equal(await repo.has('a'),false);if(newer)assert.equal((await newer).ok,true);repo.restoreMetadata=atomic;app.setRepository(repo);assert.equal((await app.restoreBackup(backup(app,[p]),{settings:false})).ok,true)});
test('pre-aborted signal refuses Restore and leaves existing settings unchanged',async()=>{const{app,repo}=load(),controller=new AbortController();controller.abort();const result=await app.restoreBackup(backup(app,[project(app,'a')]),{signal:controller.signal});assert.equal(result.cancelled,true);assert.equal((await repo.list()).length,0);assert.equal(await repo.getSettings(),null)});
test('custom repository without atomic capability fails before per-project publication',async()=>{const{app,repo}=load();delete repo.restoreMetadata;let writes=0;repo.put=async()=>writes++;assert.equal((await app.restoreBackup(backup(app,[project(app,'a')]))).ok,false);assert.equal(writes,0)});

test('legacy editor-only MIDI restores without manufacturing tracks',async()=>{const{app,repo}=load(),p=project(app,'editor-only');p.midiData={editor:{view:{snapEnabled:false},unknown:{keep:true}}};assert.equal((await app.restoreBackup(backup(app,[p]),{settings:false})).ok,true);assert.deepEqual(plain((await repo.get(p.projectId)).midiData),plain(p.midiData))});

test('refresh failure after commit reports committed metadata rather than false rollback',async()=>{const{app,repo}=load(),p=project(app,'committed');repo.list=async()=>{throw Error('injected-refresh-failure')};const result=await app.restoreBackup(backup(app,[p]),{settings:false});assert.equal(result.ok,true);assert.equal(result.committed,true);assert.equal(result.viewRefreshPending,true);assert.equal(await repo.has(p.projectId),true)});
