const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const plain=value=>JSON.parse(JSON.stringify(value));
const clone=plain;
test('new locks preserve differing legacy alias arrays byte-for-byte instead of rewriting them',()=>{const{core,locks}=load(),p=project();p.midiData.editor.trackStates.lead.lockedMeasures=[3];const s=core.createSession(p),editor=plain(s.midiData.editor);locks.addRangeLock(s,core,{trackId:'lead',startTick:4000,endTick:5000});const after=plain(s.midiData.editor);delete after.measureLocks;assert.deepEqual(after,editor)});
test('stale cached session locks fail before adding Undo history or modifying saved scopes',()=>{const{core,locks}=load(),s=core.createSession(project());s.lockedMeasures=[];const before=plain(s);assert.throws(()=>locks.addRangeLock(s,core,{trackId:'lead',startTick:4000,endTick:5000}));assert.deepEqual(plain(s),before)});
function load(options={}){const w={indexedDB:options.indexedDB,crypto:{randomUUID:(()=>{let i=0;return()=>`lock-test-${++i}`})()},location:{hash:'#music-studio'},addEventListener(){},setTimeout,clearTimeout,console,TextEncoder};w.window=w;const files=['music-studio-editor.js','music-studio.js','music-studio-measure-locks.js'];if(fs.existsSync(path.join(__dirname,'..','music-studio-meter-map.js')))files.unshift('music-studio-meter-map.js');for(const f of files)vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),{window:w,globalThis:w},{filename:f});return{core:w.MusicStudioEditor,locks:w.MusicStudioMeasureLocks,app:w.MusicStudio}}
function project(signature={numerator:4,denominator:4},map=[]){return{projectId:'locks',projectName:'Lock Compatibility',midiData:{ppq:480,tempo:120,timeSignature:signature,timeSignatureMap:map,totalTick:12000,tracks:[{id:'lead',part:'melody',notes:[{id:'inside',pitch:60,startTick:1000,durationTicks:120,velocity:90},{id:'outside',pitch:64,startTick:3000,durationTicks:120,velocity:90}]}],editor:{measureCount:8,lockedMeasures:[1],parts:{melody:{lockedMeasures:[1]}},trackStates:{lead:{lockedMeasures:[1]}}}}}}
test('compatibility session rejects malformed raw locks before existing normalization discards them',()=>{const{core,locks}=load();for(const value of [[1.5],{},['1']]){const p=project();p.midiData.editor.trackStates.lead.lockedMeasures=value;const before=plain(p);assert.throws(()=>locks.createSession(p,core));assert.deepEqual(plain(p),before)}const p=project();delete p.midiData.ppq;delete p.midiData.timeSignature;const s=locks.createSession(p,core);assert.equal(locks.readState(s.midiData,core).tracks.find(t=>t.trackId==='lead').legacyRanges[0].endTick,1920);assert.equal(p.midiData.ppq,undefined)});
test('missing meter dependency and unknown tracks cannot create a partial lock',()=>{const{core,locks}=load(),s=core.createSession(project()),before=plain(s);assert.throws(()=>locks.addMeasureLock(s,core,null,{trackId:'lead',startMeasure:2}));assert.throws(()=>locks.addRangeLock(s,core,{trackId:'missing',startTick:0,endTick:1}));assert.deepEqual(plain(s),before)});
test('empty protected space prevents a real timeline shrink, while extension preserves ranges',()=>{const{core,locks}=load(),s=core.createSession(project());locks.addRangeLock(s,core,{trackId:'lead',startTick:9000,endTick:10000});const before=plain(s);assert.equal(locks.edit(s,core,copy=>core.removeTimelineMeasures(copy,4)).ok,false);assert.deepEqual(plain(s),before);assert.equal(locks.edit(s,core,copy=>core.extendTimelineMeasures(copy,4)).ok,true);assert.deepEqual(plain(locks.readState(s.midiData,core).tracks),plain(locks.readState(before.midiData,core).tracks))});
test('new empty-space locks block candidate replacement while keeping other tracks unchanged',()=>{const{core,locks}=load(),s=core.createSession(project());locks.addRangeLock(s,core,{trackId:'lead',startTick:4000,endTick:5000});const before=plain(s);assert.equal(locks.edit(s,core,copy=>{copy.midiData.tracks[0].notes.push({id:'candidate',pitch:70,startTick:4100,durationTicks:20,velocity:100})}).ok,false);assert.deepEqual(plain(s),before)});
test('IndexedDB save -> actual Editor reopen retains old and explicit new lock ranges',async()=>{const{core,locks,app}=load({indexedDB:fakeIndexedDB()}),repo=app.indexedDbRepository(),p=app.makeProject(project()),s=core.createSession(p);app.setRepository(repo);await repo.put(p);app.state.projects=[p];app.state.midiEditor=s;locks.addRangeLock(s,core,{trackId:'lead',startTick:960,endTick:2400});const expected=plain(locks.readState(s.midiData,core));assert.equal((await app.saveMidiEditor({silent:true})).ok,true);const stored=await repo.get(p.projectId),reopened=core.createSession(stored);assert.equal(stored.schemaVersion,p.schemaVersion);assert.deepEqual(plain(locks.readState(reopened.midiData,core)),expected);assert.equal(locks.isProtected(reopened.midiData,core,'lead',{startTick:1919,durationTicks:1}),true);assert.equal(locks.isProtected(reopened.midiData,core,'lead',{startTick:2399,durationTicks:1}),true);assert.equal(locks.isProtected(reopened.midiData,core,'lead',{startTick:2400,durationTicks:1}),false)});
test('actual JSON project import preserves lock metadata without changing the source',async()=>{const{core,locks,app}=load(),p=app.makeProject(project()),s=core.createSession(p);locks.addRangeLock(s,core,{trackId:'lead',startTick:960,endTick:2400});p.midiData=plain(s.midiData);const before=plain(p);app.setRepository(app.memoryRepository());const imported=await app.importText(JSON.stringify(p));assert.equal(imported.ok,true);assert.deepEqual(plain(locks.readState(core.createSession(imported.project).midiData,core)),plain(locks.readState(p.midiData,core)));assert.deepEqual(plain(p),before)});
test('Backup/Restore preserves exact protection through the existing repository path',async()=>{const{core,locks,app}=load(),p=app.makeProject(project()),s=core.createSession(p);locks.addRangeLock(s,core,{trackId:'lead',startTick:960,endTick:2400});p.midiData=plain(s.midiData);app.state.projects=[p];const backup=plain(app.backupObject()),before=plain(backup),target=app.memoryRepository();app.setRepository(target);app.state.projects=[];const result=await app.restoreBackup(backup,{settings:false,projects:true});assert.equal(result.ok,true);assert.equal(result.added,1);const restored=await target.get(p.projectId);assert.deepEqual(plain(locks.readState(core.createSession(restored).midiData,core)),plain(locks.readState(s.midiData,core)));assert.deepEqual(backup,before)});
for(const [name,signature,map,legacyEnd,newRange] of [
 ['4/4',{numerator:4,denominator:4},[],1920,[1920,3840]],
 ['3/4',{numerator:3,denominator:4},[],1440,[1440,2880]],
 ['6/8',{numerator:6,denominator:8},[],1440,[1440,2880]],
 ['boundary change',{numerator:4,denominator:4},[{tick:0,numerator:4,denominator:4},{tick:1920,numerator:3,denominator:4}],1920,[1920,3360]],
 ['off-bar change',{numerator:4,denominator:4},[{tick:0,numerator:4,denominator:4},{tick:960,numerator:3,denominator:4}],1920,[960,2400]],
 ['multiple changes',{numerator:4,denominator:4},[{tick:0,numerator:4,denominator:4},{tick:960,numerator:3,denominator:4},{tick:2500,numerator:5,denominator:8}],1920,[2500,3700]],
 ['denominator change',{numerator:4,denominator:4},[{tick:0,numerator:4,denominator:4},{tick:960,numerator:6,denominator:8}],1920,[960,2400]]
])test(name+' retains legacy protection and accepts exact new boundaries without moving events',()=>{const {core,locks}=load(),s=core.createSession(project(signature,map)),before=plain(s.midiData);const state=locks.readState(s.midiData,core);assert.deepEqual(plain(state.tracks.find(t=>t.trackId==='lead').legacyRanges),[{startTick:0,endTick:legacyEnd}]);locks.addRangeLock(s,core,{trackId:'lead',startTick:newRange[0],endTick:newRange[1]});const after=locks.readState(s.midiData,core).tracks.find(t=>t.trackId==='lead');assert.deepEqual(plain(after.legacyRanges),[{startTick:0,endTick:legacyEnd}]);assert.deepEqual(plain(after.rangeLocks),[{startTick:newRange[0],endTick:newRange[1]}]);assert.deepEqual(plain(s.midiData.tracks),before.tracks);assert.deepEqual(plain(s.midiData.timeSignatureMap),before.timeSignatureMap);assert.deepEqual(plain(s.midiData.editor.trackStates),before.editor.trackStates);assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:legacyEnd-1,durationTicks:1}),true)});
test('Track-ID states take precedence; core aliases and legacy root retain their existing fallback',()=>{const {core,locks}=load(),p=project();p.midiData.editor.trackStates.lead.lockedMeasures=[3];p.midiData.tracks.push({id:'extra',part:null,notes:[]});const s=core.createSession(p),state=locks.readState(s.midiData,core);assert.deepEqual(plain(state.tracks.find(t=>t.trackId==='lead').legacyRanges),[{startTick:3840,endTick:5760}]);assert.deepEqual(plain(state.tracks.find(t=>t.trackId==='extra').legacyRanges),[]);delete p.midiData.editor.trackStates;assert.equal(locks.readState(core.createSession(p).midiData,core).tracks.find(t=>t.trackId==='lead').legacyRanges[0].endTick,1920);delete p.midiData.editor.parts;assert.equal(locks.readState(core.createSession(p).midiData,core).tracks.find(t=>t.trackId==='lead').legacyRanges[0].endTick,1920)});
test('half-open ranges protect crossing notes and both sides of edits without an extra tick',()=>{const{core,locks}=load(),s=core.createSession(project());for(const [startTick,durationTicks,expected] of [[1919,1,true],[1920,1,false],[0,1,true],[1920,120,false]])assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick,durationTicks}),expected);const before=plain(s),r=locks.edit(s,core,copy=>{core.selectNote(copy,'inside');core.deleteSelected(copy)});assert.equal(r.ok,false);assert.deepEqual(plain(s),before);assert.equal(locks.edit(s,core,copy=>{core.selectNote(copy,'outside');core.updateSelectedNotes(copy,{startTick:1919})}).ok,false);assert.deepEqual(plain(s),before)});
test('existing Editor edits cannot move delete resize or change a protected note',()=>{const{core,locks}=load();for(const change of [{pitch:61},{startTick:1920},{durationTicks:1},{velocity:1}]){const s=core.createSession(project()),before=plain(s);assert.equal(locks.edit(s,core,copy=>{core.selectNote(copy,'inside');core.updateSelectedNotes(copy,change)}).ok,false);assert.deepEqual(plain(s),before)}});
test('unprotected Editor changes commit with real Undo/Redo while lock additions also undo exactly',()=>{const{core,locks}=load(),s=core.createSession(project());locks.addRangeLock(s,core,{trackId:'lead',startTick:4000,endTick:5000});const frozen=plain(s.midiData.editor.measureLocks);assert.equal(locks.edit(s,core,copy=>{core.selectNote(copy,'outside');core.updateSelectedNotes(copy,{pitch:65})}).ok,true);assert.equal(s.midiData.tracks[0].notes.find(n=>n.id==='outside').pitch,65);core.undo(s);assert.deepEqual(plain(s.midiData.editor.measureLocks),frozen);assert.equal(s.midiData.tracks[0].notes.find(n=>n.id==='outside').pitch,64);core.redo(s);assert.deepEqual(plain(s.midiData.editor.measureLocks),frozen);core.undo(s);core.undo(s);assert.equal(s.midiData.editor.measureLocks,undefined);assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:1919,durationTicks:1}),true);core.redo(s);assert.deepEqual(plain(s.midiData.editor.measureLocks),frozen)});
test('explicit new lock survives JSON, Editor reopen, and later meter-map changes',()=>{const{core,locks}=load(),s=core.createSession(project());locks.addRangeLock(s,core,{trackId:'lead',startTick:960,endTick:2400});const p={...project(),midiData:plain(s.midiData)},reopened=core.createSession(plain(p));assert.deepEqual(plain(locks.readState(reopened.midiData,core)),plain(locks.readState(s.midiData,core)));reopened.midiData.timeSignatureMap=[{tick:0,numerator:4,denominator:4},{tick:100,numerator:3,denominator:8}];assert.equal(locks.isProtected(reopened.midiData,core,'lead',{startTick:2399,durationTicks:1}),true);assert.equal(locks.isProtected(reopened.midiData,core,'lead',{startTick:2400,durationTicks:1}),false)});
test('unknown versions stale legacy state and changed scalar timing fail closed without modifying data',()=>{const{core,locks}=load();for(const alter of [s=>s.midiData.editor.measureLocks.version=2,s=>s.midiData.editor.trackStates.lead.lockedMeasures=[],s=>s.midiData.ppq=960,s=>s.midiData.timeSignature.numerator=3,s=>s.midiData.editor.measureLocks.tracks[0].legacyRanges[0].endTick=960]){const s=core.createSession(project());locks.addRangeLock(s,core,{trackId:'lead',startTick:4000,endTick:5000});alter(s);const before=plain(s);assert.throws(()=>locks.readState(s.midiData,core));assert.equal(locks.edit(s,core,copy=>core.addNote(copy,{startTick:6000})).ok,false);assert.deepEqual(plain(s),before)}});
test('invalid ranges ambiguous tracks and malformed legacy locks are rejected',()=>{const{core,locks}=load();for(const range of [{startTick:-1,endTick:1},{startTick:1,endTick:1},{startTick:1,endTick:Infinity}]){const s=core.createSession(project()),before=plain(s);assert.throws(()=>locks.addRangeLock(s,core,{trackId:'lead',...range}));assert.deepEqual(plain(s),before)}const s=core.createSession(project());s.midiData.tracks.push(plain(s.midiData.tracks[0]));assert.throws(()=>locks.readState(s.midiData,core));const s2=core.createSession(project());s2.midiData.editor.trackStates.lead.lockedMeasures=[1.5];assert.throws(()=>locks.readState(s2.midiData,core))});
test('new protected destination and inserted notes are rejected atomically',()=>{const{core,locks}=load(),s=core.createSession(project());locks.addRangeLock(s,core,{trackId:'lead',startTick:4000,endTick:5000});for(const edit of [copy=>core.addNote(copy,{startTick:4000,durationTicks:1}),copy=>{core.selectNote(copy,'outside');core.updateSelectedNotes(copy,{startTick:3999,durationTicks:2})},copy=>core.removeTimelineMeasures(copy,7)]){const before=plain(s);assert.equal(locks.edit(s,core,edit).ok,false);assert.deepEqual(plain(s),before)}});
test('note-level locks remain protected and exceptions/async edits cannot partially commit',()=>{const{core,locks}=load(),s=core.createSession(project());s.midiData.tracks[0].notes[1].locked=true;for(const edit of [copy=>{copy.midiData.tracks[0].notes[1].pitch=70},copy=>{core.addNote(copy,{startTick:6000});throw Error('failed')},async copy=>core.addNote(copy,{startTick:6000})]){const before=plain(s);assert.equal(locks.edit(s,core,edit).ok,false);assert.deepEqual(plain(s),before)}});

function fakeIndexedDB(){
  const databases=new Map();
  const request=operation=>{const result={};queueMicrotask(()=>{try{result.result=operation();result.onsuccess?.()}catch(error){result.error=error;result.onerror?.()}});return result};
  return{open(name){
    const openRequest={};queueMicrotask(()=>{
      let db=databases.get(name),upgraded=false;
      if(!db){
        const stores=new Map();db={objectStoreNames:{contains:key=>stores.has(key)},createObjectStore(key){const records=new Map();stores.set(key,records);return{createIndex(){}}},transaction(key){const records=stores.get(key);return{objectStore(){return{getAll:()=>request(()=>[...records.values()].map(clone)),get:id=>request(()=>records.has(id)?clone(records.get(id)):undefined),getKey:id=>request(()=>records.has(id)?id:undefined),put:value=>request(()=>{const copy=clone(value),id=copy.projectId??copy.id??copy.backupId;records.set(id,copy);return id}),delete:id=>request(()=>records.delete(id))}}}}};databases.set(name,db);upgraded=true
      }
      openRequest.result=db;if(upgraded)openRequest.onupgradeneeded?.();openRequest.onsuccess?.()
    });return openRequest
  }}
}

test('explicit partial release leaves every unselected legacy tick protected and aliases unchanged',()=>{
 const{core,locks}=load(),s=core.createSession(project({numerator:4,denominator:4},[{tick:0,numerator:4,denominator:4},{tick:960,numerator:3,denominator:4}])),before=plain(s.midiData);
 assert.equal(locks.unlockRange(s,core,{trackId:'lead',startTick:0,endTick:960}).changed,true);
 const state=locks.readState(s.midiData,core),target=state.tracks.find(t=>t.trackId==='lead');
 assert.deepEqual(plain(target.legacyRanges),[{startTick:0,endTick:1920}]);assert.deepEqual(plain(target.releaseRanges),[{startTick:0,endTick:960}]);
 for(let tick=0;tick<2400;tick++)assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:tick,durationTicks:1}),tick>=960&&tick<1920);
 for(const key of ['parts','trackStates','lockedMeasures'])assert.deepEqual(plain(s.midiData.editor[key]),before.editor[key]);
 assert.deepEqual(plain(s.midiData.tracks),before.tracks);assert.deepEqual(plain(s.midiData.timeSignatureMap),before.timeSignatureMap);
 const expected=plain(s.midiData);core.undo(s);assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:0,durationTicks:1}),true);core.redo(s);assert.deepEqual(plain(s.midiData),expected);
 const reopened=locks.createSession(plain({midiData:s.midiData}),core);assert.deepEqual(plain(locks.readState(reopened.midiData,core)),plain(state));
});
test('mixed legacy/new locks, overlapping release and relock retain exact half-open tick sets',()=>{
 const{core,locks}=load(),s=core.createSession(project());locks.addRangeLock(s,core,{trackId:'lead',startTick:1800,endTick:2400});
 locks.unlockRange(s,core,{trackId:'lead',startTick:900,endTick:2100});
 for(let tick=0;tick<2500;tick++)assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:tick,durationTicks:1}),tick<900||(tick>=2100&&tick<2400));
 locks.addRangeLock(s,core,{trackId:'lead',startTick:1000,endTick:1100});
 for(let tick=0;tick<2500;tick++)assert.equal(locks.isProtected(s.midiData,core,'lead',{startTick:tick,durationTicks:1}),tick<900||(tick>=1000&&tick<1100)||(tick>=2100&&tick<2400));
 const before=plain(s);assert.equal(locks.unlockRange(s,core,{trackId:'lead',startTick:3000,endTick:4000}).changed,false);assert.deepEqual(plain(s),before);
 assert.equal(locks.edit(s,core,c=>core.addNote(c,{startTick:950,durationTicks:1})).ok,true);
 assert.equal(locks.edit(s,core,c=>core.addNote(c,{startTick:1000,durationTicks:1})).ok,false);
});
test('partial release does not release explicit note locks or other tracks and fails closed on corrupt releases',()=>{
 const{core,locks}=load(),s=core.createSession(project());s.midiData.tracks[0].notes[0].locked=true;
 locks.unlockRange(s,core,{trackId:'lead',startTick:0,endTick:1920});assert.equal(locks.isProtected(s.midiData,core,'lead',s.midiData.tracks[0].notes[0]),true);
 const other=locks.readState(s.midiData,core).tracks.find(t=>t.trackId!=='lead');assert.deepEqual(plain(other.rangeLocks),[]);
 for(const value of [null,{},[{startTick:1,endTick:0}], [{startTick:0,endTick:Infinity}]]){const c=plain(s);c.midiData.editor.measureLocks.tracks.find(t=>t.trackId==='lead').releaseRanges=value;assert.throws(()=>locks.readState(c.midiData,core));}
});
for(const route of ['save','json','backup'])test('partial releases survive actual '+route+' persistence without changing source',async()=>{
 const{core,locks,app}=load({indexedDB:fakeIndexedDB()}),p=app.makeProject(project()),s=core.createSession(p);locks.unlockRange(s,core,{trackId:'lead',startTick:0,endTick:960});p.midiData=plain(s.midiData);const before=plain(p),expected=plain(locks.readState(p.midiData,core));let restored;
 if(route==='save'){const repo=app.indexedDbRepository();app.setRepository(repo);await repo.put(p);app.state.projects=[p];app.state.midiEditor=s;assert.equal((await app.saveMidiEditor({silent:true})).ok,true);restored=await repo.get(p.projectId);}
 if(route==='json'){app.setRepository(app.memoryRepository());const result=await app.importText(JSON.stringify(p));assert.equal(result.ok,true);restored=result.project;}
 if(route==='backup'){const repo=app.memoryRepository();app.setRepository(repo);app.state.projects=[p];const backup=plain(app.backupObject()),original=plain(backup);app.state.projects=[];assert.equal((await app.restoreBackup(backup,{settings:false,projects:true})).ok,true);restored=await repo.get(p.projectId);assert.deepEqual(backup,original);}
 const reopened=locks.createSession(restored,core);assert.deepEqual(plain(locks.readState(reopened.midiData,core)),expected);assert.equal(locks.isProtected(reopened.midiData,core,'lead',{startTick:959,durationTicks:1}),false);assert.equal(locks.isProtected(reopened.midiData,core,'lead',{startTick:960,durationTicks:1}),true);assert.deepEqual(plain(p),before);
});
test('legacy range capture remains scalar even when Editor range API uses A boundaries',()=>{const{core,locks}=load(),s=core.createSession(project()),aCore={...core,measureRangeToTicks:()=>({measureTicks:960})};assert.equal(locks.readState(s.midiData,aCore).tracks.find(t=>t.trackId==='lead').legacyRanges[0].endTick,1920)});
