const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
function load(){const window={TextEncoder,TextDecoder,Uint8Array,ArrayBuffer};window.window=window;for(const name of ['music-studio-midi.js','music-studio-midi-parser.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',name),'utf8'),{window,globalThis:window,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,Blob,unescape,encodeURIComponent},{filename:name});return{writer:window.MusicStudioMidi,parser:window.MusicStudioMidiParser}}
const be16=n=>[n>>8,n&255],be32=n=>[n>>>24,(n>>>16)&255,(n>>>8)&255,n&255];
function vlq(n){let b=n&127,out=[];while(n>>=7)b=(b<<8)|((n&127)|128);for(;;){out.push(b&255);if(b&128)b>>=8;else return out}}
function track(events){return[77,84,114,107,...be32(events.length),...events]}
function smf(format,tracks,division=480,headerExtra=[]){return Uint8Array.from([77,84,104,100,...be32(6+headerExtra.length),...be16(format),...be16(tracks.length),...be16(division),...headerExtra,...tracks.flat()])}
function meta(delta,type,data){return[...vlq(delta),255,type,...vlq(data.length),...data]}
function type0Body(){return[...meta(0,3,[84,121,112,101,32,48]),...meta(0,81,[7,161,32]),...meta(0,88,[4,2,24,8]),0,192,0,0,176,7,100,0,10,64,0,144,60,100,...vlq(480),60,0,...meta(0,47,[])]}
test('MS-05 Type 1 round trip parses PPQ, tempo, signature and ten notes',()=>{const{writer,parser}=load(),made=writer.createMidiFile(writer.createTestMidiData()),parsed=parser.parseMidiFile(made.bytes),s=parser.summarizeMidiFile(parsed);assert.equal(s.midiType,1);assert.equal(s.ppq,480);assert.equal(s.initialBpm,120);assert.equal(s.initialTimeSignature,'4/4');assert.equal(s.noteCount,10);assert.equal(JSON.stringify(s.tracks.filter(t=>t.noteCount).map(t=>t.channels[0])),JSON.stringify([1,2]));assert.match(s.tracks[1].name,/Piano/);assert.match(s.tracks[2].name,/Bass/)})
test('Type 0 parses running status, program and control changes',()=>{const{parser}=load(),parsed=parser.parseMidiFile(smf(0,[track(type0Body())]));assert.equal(parsed.validation.importable,true);assert.equal(parsed.normalized.totalNotes,1);assert.equal(parsed.normalized.tracks[0].notes[0].durationTicks,480);assert.equal(parsed.normalized.tracks[0].programChanges[0].program,0);assert.equal(parsed.normalized.tracks[0].controlChanges.length,2)})
for(const [value,bytes] of [[0,[0]],[1,[1]],[127,[127]],[128,[129,0]],[255,[129,127]],[16383,[255,127]],[16384,[129,128,0]],[0x0fffffff,[255,255,255,127]]])test(`decode VLQ ${value}`,()=>assert.equal(JSON.stringify(load().parser.decodeVariableLengthQuantity(Uint8Array.from(bytes))),JSON.stringify({value,offset:bytes.length,length:bytes.length})));
test('truncated VLQ is rejected',()=>assert.throws(()=>load().parser.decodeVariableLengthQuantity(Uint8Array.from([128])),/途中/));
test('overlong VLQ is rejected',()=>assert.throws(()=>load().parser.decodeVariableLengthQuantity(Uint8Array.from([129,128,128,128,0])),/4バイト/));
test('short and non-MThd headers are rejected',()=>{const p=load().parser;assert.throws(()=>p.parseMidiFile(Uint8Array.from([])),/空/);assert.throws(()=>p.parseMidiFile(Uint8Array.from([1,2,3])),/短/);assert.throws(()=>p.parseMidiFile(Uint8Array.from(new Array(14).fill(0))),/MThd/)})
test('Type 2 and unknown formats are rejected safely',()=>{const p=load().parser,eot=track(meta(0,47,[]));assert.throws(()=>p.parseMidiFile(smf(2,[eot])),/Type 2/);assert.throws(()=>p.parseMidiFile(smf(3,[eot])),/未知/)})
test('SMPTE division is rejected',()=>assert.throws(()=>load().parser.parseMidiFile(smf(0,[track(meta(0,47,[]))],0xe728)),/SMPTE/));
test('Type 0 multiple tracks and zero tracks are rejected',()=>{const p=load().parser,e=track(meta(0,47,[]));assert.throws(()=>p.parseMidiFile(smf(0,[e,e])),/Type 0/);assert.throws(()=>p.parseMidiFile(smf(1,[])),/トラック数が0/)})
test('extended header is accepted with warning',()=>{const p=load().parser,parsed=p.parseMidiFile(smf(0,[track(meta(0,47,[]))],480,[1,2]));assert.ok(parsed.validation.warnings.some(w=>w.code==='extended-header'))})
test('broken MTrk signature and length are rejected',()=>{const p=load().parser,good=smf(0,[track(meta(0,47,[]))]);good[14]=0;assert.throws(()=>p.parseMidiFile(good),/MTrk/);const broken=smf(0,[track(meta(0,47,[]))]);broken[21]=255;assert.throws(()=>p.parseMidiFile(broken),/境界/)})
test('missing End of Track allows preview but blocks import',()=>{const p=load().parser,parsed=p.parseMidiFile(smf(0,[track([0,144,60,100,0,128,60,0])]));assert.equal(parsed.validation.ok,true);assert.equal(parsed.validation.importable,false);assert.ok(parsed.validation.warnings.some(w=>w.code==='missing-eot'))})
test('data after End of Track is warned',()=>{const p=load().parser,parsed=p.parseMidiFile(smf(0,[track([...meta(0,47,[]),0])]));assert.ok(parsed.validation.warnings.some(w=>w.code==='after-eot'))})
test('running status without status is rejected',()=>assert.throws(()=>load().parser.parseMidiFile(smf(0,[track([0,60,100,...meta(0,47,[])])])),/Running Status/));
test('meta clears running status',()=>assert.throws(()=>load().parser.parseMidiFile(smf(0,[track([0,144,60,100,...meta(0,1,[65]),0,62,100,...meta(0,47,[])])])),/Running Status/));
test('SysEx clears running status and is summarized',()=>{const p=load().parser,parsed=p.parseMidiFile(smf(0,[track([0,240,2,1,247,...meta(0,47,[])])]));assert.equal(parsed.normalized.unsupportedEventsSummary[0].type,'SysEx')})
test('Japanese track name, lyric and marker decode',()=>{const p=load().parser,e=new TextEncoder(),parsed=p.parseMidiFile(smf(0,[track([...meta(0,3,[...e.encode('ピアノ🎹')]),...meta(0,5,[...e.encode('歌詞')]),...meta(0,6,[...e.encode('Aメロ')]),...meta(0,47,[])])]));assert.equal(parsed.normalized.tracks[0].name,'ピアノ🎹');assert.equal(parsed.normalized.lyrics[0].text,'歌詞');assert.equal(parsed.normalized.markers[0].text,'Aメロ')})
test('invalid UTF-8 uses replacement and warning',()=>{const p=load().parser,parsed=p.parseMidiFile(smf(0,[track([...meta(0,3,[255]),...meta(0,47,[])])]));assert.ok(parsed.validation.warnings.some(w=>w.code==='text-encoding'))})
test('tempo and time signature changes are mapped',()=>{const p=load().parser,body=[...meta(0,81,[7,161,32]),...meta(480,81,[6,239,145]),...meta(0,88,[3,2,24,8]),...meta(480,88,[6,3,24,8]),...meta(0,47,[])],n=p.parseMidiFile(smf(0,[track(body)])).normalized;assert.equal(n.tempoMap.length,2);assert.ok(Math.abs(n.tempoMap[1].bpm-132)<.01);assert.equal(n.timeSignatureMap[1].display,'6/8');assert.ok(n.estimatedDurationSeconds>0)})
test('missing tempo and signature get explicit defaults',()=>{const n=load().parser.parseMidiFile(smf(0,[track(meta(0,47,[]))])).normalized;assert.equal(n.tempo,120);assert.equal(`${n.timeSignature.numerator}/${n.timeSignature.denominator}`,'4/4');assert.equal(n.tempoMap[0].defaulted,true)})
test('invalid tempo and signature produce warnings',()=>{const p=load().parser,parsed=p.parseMidiFile(smf(0,[track([...meta(0,81,[0,0,0]),...meta(0,88,[4,9,24,8]),...meta(0,47,[])])]));assert.ok(parsed.validation.warnings.filter(w=>w.code==='invalid-meta').length>=2)})
test('chords, repeated pitches and velocity-zero note-off assemble',()=>{const p=load().parser,body=[0,144,60,90,0,144,64,100,...vlq(240),128,60,12,0,64,0,0,144,60,80,...vlq(120),128,60,1,...meta(0,47,[])],notes=p.parseMidiFile(smf(0,[track(body)])).normalized.tracks[0].notes;assert.equal(notes.length,3);assert.equal(notes.map(n=>n.durationTicks).join(','),'240,240,120')})
test('orphan and unfinished notes remain warnings and are not invented',()=>{const p=load().parser,n=p.parseMidiFile(smf(0,[track([0,128,61,0,0,144,60,100,...meta(0,47,[])])])).normalized;assert.equal(n.totalNotes,0);assert.ok(n.warnings.some(w=>w.code==='orphan-note-off'));assert.ok(n.warnings.some(w=>w.code==='unfinished-note'))})
test('channel 10 is a drum candidate and pitch bend is held',()=>{const p=load().parser,t=p.parseMidiFile(smf(0,[track([0,201,0,0,233,0,64,...meta(0,47,[])])])).normalized.tracks[0];assert.equal(t.drumCandidate,true);assert.equal(t.pitchBends[0].signedValue,0)})
test('conversion never embeds source bytes or paths',()=>{const{writer,parser}=load(),made=writer.createMidiFile(writer.createTestMidiData()),parsed=parser.parseMidiFile(made.bytes),data=parser.convertParsedMidiToProjectData(parsed,{fileName:'roundtrip.mid',fileSize:made.bytes.length,mimeType:'audio/midi'}),json=JSON.stringify(data);assert.equal(data.sourceFormat,1);assert.equal(data.tracks.reduce((n,t)=>n+t.notes.length,0),10);assert.equal(json.includes('ArrayBuffer'),false);assert.equal(json.includes('/Users/'),false);assert.equal(data.importSource.fileName,'roundtrip.mid')})
test('converted project data re-exports with MS-05 key information',()=>{const{writer,parser}=load(),first=writer.createMidiFile(writer.createTestMidiData()),data=parser.convertParsedMidiToProjectData(parser.parseMidiFile(first.bytes),{fileName:'first.mid'}),second=writer.createMidiFile(data),again=parser.parseMidiFile(second.bytes).normalized;assert.equal(again.ppq,480);assert.equal(again.tempo,120);assert.equal(`${again.timeSignature.numerator}/${again.timeSignature.denominator}`,'4/4');assert.equal(again.totalNotes,10);assert.equal(again.tracks.filter(t=>t.noteCount).length,2)})
test('preflight uses content later, not extension or MIME alone',()=>{const p=load().parser;assert.equal(p.preflightMidiFile({name:'song.bin',size:20,type:'text/plain'}).ok,true);assert.equal(p.preflightMidiFile({name:'empty.mid',size:0,type:'audio/midi'}).ok,false);assert.equal(p.preflightMidiFile(null).cancelled,true)})
test('large files reject before parsing',()=>assert.throws(()=>load().parser.parseMidiFile(new Uint8Array(load().parser.MAX_FILE_SIZE+1)),/16 MB/));
test('parses thousands of events within practical time',()=>{const p=load().parser,events=[];for(let i=0;i<5000;i++)events.push(0,144,60,90,0,128,60,0);events.push(...meta(0,47,[]));const bytes=smf(0,[track(events)]),start=Date.now(),parsed=p.parseMidiFile(bytes);assert.equal(parsed.normalized.totalNotes,5000);assert.ok(Date.now()-start<1500)})
