const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

function load(){const window={crypto:{randomUUID:(()=>{let value=0;return()=>`length-note-${++value}`})()}};window.window=window;window.globalThis=window;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','music-studio-editor.js'),'utf8'),window);return window.MusicStudioEditor}
const plain=value=>JSON.parse(JSON.stringify(value));
function project(){return{projectId:'external-length',schemaVersion:'1.0',midiData:{ppq:480,timeSignature:{numerator:4,denominator:4},editor:{measureCount:4},tracks:[
  {id:'core-melody',part:'melody',name:'Melody',notes:[{id:'shared',pitch:60,startTick:0,durationTicks:240,velocity:80,meta:{track:'core'}}]},
  {id:'core-drums',part:'drums',name:'Drums',channel:10,notes:[{id:'drum',pitch:36,startTick:0,durationTicks:120,velocity:100}]},
  {id:'core-bass',part:'bass',name:'Bass',channel:2,notes:[{id:'bass',pitch:40,startTick:0,durationTicks:480,velocity:75}]},
  {id:'external-a',name:'Melody',trackType:'midi-melodic',roleAssignment:'piano',custom:'a',notes:[{id:'shared',pitch:64,startTick:0,durationTicks:333,velocity:91,meta:{keep:'a'}},{id:'range',pitch:67,startTick:1920,durationTicks:222,velocity:72,extra:'keep'},{id:'locked',pitch:69,startTick:1920,durationTicks:111,velocity:73,locked:true},{id:'outside',pitch:71,startTick:3840,durationTicks:444,velocity:74}]},
  {id:'external-b',name:'Melody',trackType:'midi-melodic',roleAssignment:'piano',custom:'b',notes:[{id:'shared',pitch:76,startTick:0,durationTicks:555,velocity:92,meta:{keep:'b'}}]}
]}}}
function track(session,id){return session.midiData.tracks.find(item=>item.id===id)}

test('External Note Length Preview Apply Cancel pin exact Track ID and keep other Tracks isolated',()=>{const core=load(),session=core.createSession(project()),before=plain(session.midiData.tracks);core.selectTrackById(session,'external-a');let result=core.previewNoteLength(session,{target:'all',length:'1/4'},core.createEditorContext(session));assert.equal(result.ok,true);assert.equal(result.preview.targetTrackId,'external-a');assert.deepEqual(plain(session.midiData.tracks),before);core.cancelNoteLength(session);assert.equal(session.noteLengthPreview,null);assert.deepEqual(plain(session.midiData.tracks),before);result=core.previewNoteLength(session,{target:'all',length:'1/4'},core.createEditorContext(session));core.applyNoteLength(session,core.createEditorContext(session));assert.deepEqual(Array.from(track(session,'external-a').notes,note=>note.durationTicks),[480,480,111,480]);for(const id of['core-melody','external-b'])assert.deepEqual(plain(track(session,id)),before.find(item=>item.id===id))});

test('same Note ID duplicate names roles and Core External collision remain independent',()=>{const core=load(),session=core.createSession(project()),coreBefore=plain(track(session,'core-melody')),bBefore=plain(track(session,'external-b'));core.selectTrackById(session,'external-a');core.selectNote(session,'shared');core.previewNoteLength(session,{target:'selected',length:'1/8'},core.createEditorContext(session));core.applyNoteLength(session,core.createEditorContext(session));assert.equal(track(session,'external-a').notes.find(note=>note.id==='shared').durationTicks,240);assert.deepEqual(plain(track(session,'external-b')),bBefore);assert.deepEqual(plain(track(session,'core-melody')),coreBefore)});

test('stale Preview Context and selected-note changes are rejected atomically',()=>{const core=load(),session=core.createSession(project());core.selectTrackById(session,'external-a');core.selectNote(session,'shared');const contextA=core.createEditorContext(session),created=core.previewNoteLength(session,{target:'selected',length:'1/8'},contextA),preview=plain(created.preview);core.selectNote(session,'range',{toggle:true});const beforeSelection=plain(session.midiData),undo=session.undo.length;let result=core.applyNoteLength(session,core.createEditorContext(session));assert.equal(result.ok,false);assert.ok(result.errors.includes('stale-selection'));assert.deepEqual(plain(session.midiData),beforeSelection);assert.equal(session.undo.length,undo);core.selectTrackById(session,'external-b');const beforeTrack=plain(session.midiData);session.noteLengthPreview=preview;result=core.applyNoteLength(session,contextA);assert.equal(result.ok,false);assert.deepEqual(plain(session.midiData),beforeTrack);session.noteLengthPreview=preview;result=core.applyNoteLength(session,core.createEditorContext(session));assert.equal(result.ok,false);assert.ok(result.errors.includes('stale-preview'));assert.deepEqual(plain(session.midiData),beforeTrack)});

test('all selected and measures change duration only and preserve locked notes and metadata',()=>{const core=load();for(const target of['all','selected','measures']){const session=core.createSession(project());core.selectTrackById(session,'external-a');if(target==='selected')core.selectNote(session,'shared');const before=plain(track(session,'external-a').notes),input={target,length:'1/16',measureFrom:2,measureTo:2},result=core.previewNoteLength(session,input,core.createEditorContext(session));assert.equal(result.ok,true);core.applyNoteLength(session,core.createEditorContext(session));const expected=new Set(target==='all'?['shared','range','outside']:target==='selected'?['shared']:['range']);for(const note of track(session,'external-a').notes){const previous=before.find(item=>item.id===note.id);assert.equal(note.durationTicks,expected.has(note.id)?120:previous.durationTicks);for(const field of['id','pitch','startTick','velocity','locked','meta','extra'])assert.equal(JSON.stringify(note[field]),JSON.stringify(previous[field]))}}});

test('External Note Length is one Undo Redo unit',()=>{const core=load(),session=core.createSession(project()),other=plain(track(session,'external-b'));core.selectTrackById(session,'external-a');core.previewNoteLength(session,{target:'all',length:'1/8'},core.createEditorContext(session));core.applyNoteLength(session,core.createEditorContext(session));core.undo(session);assert.equal(track(session,'external-a').notes[0].durationTicks,333);core.redo(session);assert.equal(track(session,'external-a').notes[0].durationTicks,240);assert.deepEqual(plain(track(session,'external-b')),other)});

test('Core Melody keeps Note Length while Core Drums and Bass remain rejected',()=>{const core=load(),session=core.createSession(project());core.selectTrackById(session,'core-melody');let result=core.previewNoteLength(session,{target:'all',length:'1/8'},core.createEditorContext(session));assert.equal(result.ok,true);core.applyNoteLength(session,core.createEditorContext(session));assert.equal(track(session,'core-melody').notes[0].durationTicks,240);for(const id of['core-drums','core-bass']){core.selectTrackById(session,id);result=core.previewNoteLength(session,{target:'all',length:'1/8'},core.createEditorContext(session));assert.equal(result.ok,false)}});
