const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.join(__dirname,'..'),deps=process.env.MUSIC_LOCK_DEPENDENCY_DIR||base,plain=v=>JSON.parse(JSON.stringify(v));
function load(){const w={};w.window=w;for(const [dir,file] of [[deps,'music-studio-meter-map.js'],[deps,'music-studio-measure-locks.js'],[base,'music-studio-editor.js']])vm.runInNewContext(fs.readFileSync(path.join(dir,file),'utf8'),w,{filename:file});return{core:w.MusicStudioEditor,locks:w.MusicStudioMeasureLocks,meter:w.MusicStudioMeterMap}}
function project(signature={numerator:4,denominator:4},map=[]){return{projectId:'synthetic',midiData:{ppq:480,tempo:120,timeSignature:signature,timeSignatureMap:map,tempoMap:[{tick:0,bpm:120}],keySignatureMap:[{tick:960,sharps:2,minor:false}],markers:[{tick:960,text:'A'}],totalTick:9600,editor:{measureCount:5,lockedMeasures:[1]},tracks:[{id:'melody',part:'melody',notes:[{id:'protected',pitch:60,startTick:960,durationTicks:120,velocity:90},{id:'free',pitch:64,startTick:2200,durationTicks:120,velocity:90}]}]}}}
function setup(){const api=load(),session=api.locks.createSession(project({numerator:4,denominator:4},[{tick:960,numerator:3,denominator:4}]),api.core);api.core.selectNote(session,'protected');return{...api,session}}
const edits={move:(c,s)=>c.moveSelected(s,1,1),resize:(c,s)=>c.resizeSelected(s,1),delete:(c,s)=>c.deleteSelected(s),velocity:(c,s)=>c.setSelectedVelocity(s,100),update:(c,s)=>c.updateNote(s,'protected',{pitch:61}),add:(c,s)=>c.addNote(s,{id:'new',startTick:100,durationTicks:20}),batch:(c,s)=>c.addNotes(s,[{id:'new',startTick:100,durationTicks:20}]),record:(c,s)=>c.addNotesToTrack(s,'melody',[{id:'recorded',startTick:100,durationTicks:20}]),paste:(c,s)=>c.paste(s,100),transpose:(c,s)=>c.applyTranspose(s),length:(c,s)=>c.applyNoteLength(s),correction:(c,s)=>c.applyCorrection(s)};
for(const [name,edit] of Object.entries(edits))test('internal commit rejects protected '+name+' atomically',()=>{const {core:c,session:s}=setup();if(name==='paste')c.copy(s);if(name==='transpose')c.previewTranspose(s,{fromKey:'C',toKey:'D'});if(name==='length')c.previewNoteLength(s,{length:'1/4'});if(name==='correction')c.previewCorrection(s,{key:'D',scale:'Major',quantize:'1/4',strength:100});const before=plain(s);const result=edit(c,s);assert.equal(result.ok,false);assert.deepEqual(plain(s),before);assert.equal(c.editFailureCount(s),1)});
test('destination protection rejects an unlocked source move',()=>{const {core:c,session:s}=setup();c.selectNote(s,'free');const before=plain(s);assert.equal(c.moveSelected(s,-1000).ok,false);assert.deepEqual(plain(s),before)});
test('a mixed recording batch cannot commit only the unprotected member',()=>{const {core:c,session:s}=setup(),before=plain(s);assert.equal(c.addNotesToTrack(s,'melody',[{id:'safe',startTick:3000,durationTicks:120},{id:'unsafe',startTick:100,durationTicks:120}]).ok,false);assert.deepEqual(plain(s),before)});
test('ignored nested rejection aborts the outer lock transaction',()=>{const {core:c,locks:l,session:s}=setup(),before=plain(s);const result=l.edit(s,c,work=>{c.moveSelected(work,1);c.selectNote(work,'free');c.moveSelected(work,10);return work});assert.equal(result.ok,false);assert.deepEqual(plain(s),before)});
test('allowed edits Undo/Redo preserve exact legacy and release protection',()=>{const {core:c,locks:l,meter:m,session:s}=setup(),legacy=plain(s.midiData.editor.lockedMeasures);l.unlockMeasures(s,c,m,{trackId:'melody',startMeasure:1});assert.equal(l.isProtected(s.midiData,c,'melody',{startTick:959,durationTicks:1}),false);assert.equal(l.isProtected(s.midiData,c,'melody',{startTick:960,durationTicks:1}),true);c.selectNote(s,'free');c.moveSelected(s,10);assert.equal(c.currentTrack(s).notes.find(n=>n.id==='free').startTick,2210);c.undo(s);assert.equal(c.currentTrack(s).notes.find(n=>n.id==='free').startTick,2200);c.redo(s);assert.equal(c.currentTrack(s).notes.find(n=>n.id==='free').startTick,2210);const reopened=l.createSession({projectId:'synthetic',midiData:plain(s.midiData)},c);assert.deepEqual(plain(reopened.midiData.editor.lockedMeasures),legacy);assert.deepEqual(plain(l.protectedRanges(reopened.midiData,c,'melody')),[{startTick:960,endTick:1920}]);c.selectNote(reopened,'protected');assert.equal(c.deleteSelected(reopened).ok,false)});
for(const [name,signature,map] of [['4/4',{numerator:4,denominator:4},[]],['3/4',{numerator:3,denominator:4},[]],['6/8',{numerator:6,denominator:8},[]],['boundary',{numerator:4,denominator:4},[{tick:1920,numerator:3,denominator:4}]],['offbar',{numerator:4,denominator:4},[{tick:960,numerator:3,denominator:4}]],['multiple',{numerator:4,denominator:4},[{tick:960,numerator:3,denominator:4},{tick:2500,numerator:5,denominator:8}]],['denominator',{numerator:4,denominator:4},[{tick:960,numerator:6,denominator:8}]]])test('guard preserves scalar legacy ticks and exact A release '+name,()=>{const {core:c,locks:l,meter:m}=load(),p=project(signature,map),original=plain(p),s=l.createSession(p,c),normalized=plain(s.midiData),bar=480*4/signature.denominator*signature.numerator;assert.deepEqual(plain(l.protectedRanges(s.midiData,c,'melody')),[{startTick:0,endTick:bar}]);const span=m.rangeToTicks(s.midiData,1,1);l.unlockRange(s,c,{trackId:'melody',startTick:span.startTick,endTick:Math.min(span.endTick,bar)});for(let tick=0;tick<bar+1;tick++)assert.equal(l.isProtected(s.midiData,c,'melody',{startTick:tick,durationTicks:1}),tick>=Math.min(span.endTick,bar)&&tick<bar);assert.deepEqual(plain(p),original);for(const field of ['timeSignatureMap','tempoMap','keySignatureMap','markers'])assert.deepEqual(plain(s.midiData[field]),normalized[field])});
test('empty protected space cannot be truncated by timeline resize',()=>{const {core:c,locks:l}=load(),p=project();p.midiData.tracks[0].notes=[];p.midiData.editor.lockedMeasures=[5];const s=l.createSession(p,c),before=plain(s);assert.equal(c.removeTimelineMeasures(s,1).ok,false);assert.deepEqual(plain(s),before)});
test('explicit note flag lock/unlock remains usable without releasing range protection',()=>{const {core:c,locks:l,session:s}=setup();c.lockSelectedNotes(s);assert.equal(c.currentTrack(s).notes[0].locked,true);c.unlockSelectedNotes(s);assert.equal(c.currentTrack(s).notes[0].locked,false);assert.equal(l.isProtected(s.midiData,c,'melody',c.currentTrack(s).notes[0]),true);assert.equal(c.moveSelected(s,1).ok,false)});
test('legacy numbered lock toggle cannot mutate captured range state',()=>{const {core:c,session:s}=setup();c.setSelectedMeasures(s,[1]);const before=plain(s);assert.equal(c.toggleLockSelected(s).ok,false);assert.deepEqual(plain(s),before)});
test('saved additive locks fail closed when required dependency is absent',()=>{const {core:c,locks:l,session:s}=setup();l.unlockRange(s,c,{trackId:'melody',startTick:0,endTick:960});const w={};w.window=w;vm.runInNewContext(fs.readFileSync(path.join(base,'music-studio-editor.js'),'utf8'),w);assert.throws(()=>w.MusicStudioEditor.createSession({midiData:plain(s.midiData)}),/missing-lock-dependency/)});
test('malformed legacy locks are not normalized away before validation',()=>{const {core:c}=load(),p=project();p.midiData.editor.lockedMeasures=[1,1.5];assert.throws(()=>c.createSession(p),/unrecoverable-legacy-locks/)});

test('new ranges, partial release and legacy ranges jointly guard candidate commit',()=>{const {core:c,locks:l,session:s}=setup();l.unlockRange(s,c,{trackId:'melody',startTick:0,endTick:960});l.addRangeLock(s,c,{trackId:'melody',startTick:3000,endTick:3100});s.candidates.melody={part:'melody',notes:[{id:'candidate',pitch:65,startTick:3000,durationTicks:60,velocity:80}]};const before=plain(s);assert.equal(c.applyCandidate(s,'melody').ok,false);assert.deepEqual(plain(s),before)});
test('partial edit commit cannot enter exact new range protection',()=>{const {core:c,locks:l,session:s}=setup();l.addRangeLock(s,c,{trackId:'melody',startTick:2200,endTick:2320});c.setEditRange(s,{startMeasure:2,endMeasure:2});const request=c.createPartialEditRequest(s),note=request.notes.find(n=>n.id==='free'),result=c.createPartialEditResult(request,{updates:[{...note,pitch:65}]}),preview=c.createPartialEditPreview(request,result),before=plain(s);assert.equal(c.applyPartialEditPreview(s,request,result,preview).ok,false);assert.deepEqual(plain(s),before)});
test('quantize into a range lock is rejected atomically',()=>{const {core:c,locks:l,session:s}=setup();l.addRangeLock(s,c,{trackId:'melody',startTick:2160,endTick:2200});c.selectNote(s,'free');const before=plain(s);assert.equal(c.quantizeSelectedStarts(s,'1/8').ok,false);assert.deepEqual(plain(s),before)});
function externalSetup(){const {core:c,locks:l,meter:m}=load(),p=project();p.midiData.editor.lockedMeasures=[];p.midiData.tracks.push({id:'external',roleAssignment:'unassigned',trackType:'midi-melodic',name:'External',notes:[{id:'outside',pitch:60,startTick:2201,durationTicks:120,velocity:80}]});const s=l.createSession(p,c);c.selectTrackById(s,'external');l.addRangeLock(s,c,{trackId:'external',startTick:2200,endTick:2400});return{core:c,locks:l,meter:m,session:s}}
test('scoped repair apply uses the same internal guard for new range locks',()=>{const {core:c,session:s}=externalSetup(),track=c.currentTrack(s),repair={ok:true,trackId:track.id,sourceSignature:JSON.stringify(track.notes),measureFrom:2,measureTo:2,afterNotes:plain(track.notes).map(n=>({...n,startTick:2202})),changes:[]},before=plain(s);assert.equal(c.applyScopedMidiRepair(s,repair).ok,false);assert.deepEqual(plain(s),before)});
test('generated cleanup commit cannot quantize a protected external note',()=>{const {core:c,session:s}=externalSetup();assert.equal(c.previewGeneratedMidiCleanup(s,{quantize:'1/4'}).ok,true);const before=plain(s);assert.equal(c.applyGeneratedMidiCleanup(s).ok,false);assert.deepEqual(plain(s),before)});
